### ISSUE TITLE
Unable to auto cast druide travel form

### ISSUE THREAD

**Issue by BourgeoisM** [xod-wow/LiteMount#10]
On my druid i'm not able to use litemount to auto cast travel form.
If i stay still it cast random mount from what i've set.
I restored advanced otpion and restarted game without any changes.

Each time i'm pressing the macro when i'm moving or jumping it says in error message :
You can't mount there

I noticed that i also have a shaman problem not turning in ghost form when running/inside.
I use the trick to put the /cast ghost wolf on the in combat, and when unavailable otpions.

Here is the report.
[report.txt](https://github.com/xod-wow/LiteMount/files/5469173/report.txt)

**Comment by BourgeoisM** [comment]
Here is something interesting : I have a profile that i set long time ago for gathering
And on this profile Travel form works perfectly ! 
Here the report with the gathering profile :  
[report-2.txt](https://github.com/xod-wow/LiteMount/files/5469184/report-2.txt)

**Comment by mbattersby** [comment]
You have Travel Form and Mount Form both set to priority 0, disabled for the Default profile. LiteMount will never summon them if you have the priority set to 0.

Your second character, Handantsama-Dalaran, uses the "recolte" profile which does not have them set to priority 0. That is why it works there.

**Comment by mbattersby** [comment]
I'm not sure about your Ghost Wolf problem. Can you send your report from the Shaman after you have activated it and it didn't work?

**Comment by mbattersby** [comment]
Didn't hear back, I assume this is working. Closing.

**Comment by BourgeoisM** [comment]
Sorry i forgot to reply.
With the reset and the inclusion of ghost wolf in mounts it works perfectly.
I just have some random time were it does not remove ghost wolf form when walking or in combat, but i think i'll got through a complete wtf removal and it may solve everything.
