### ISSUE TITLE
[Feature Request] Flags for Multi-Seater (2/3)

### ISSUE THREAD

**Issue by PanoramicPanda** [xod-wow/LiteMount#100]
It'd be really nice to have a flag for multi-seater mounts that I could combine with Flying/Ground mount. Granted, I think flying are only 2 (besides Hivemind).

**Comment by mbattersby** [comment]
Hi there,

You don't need any code feature for this, you can just create a group (mine is called PASSENGER) for multi-seat mounts and use the group in rules. That's exactly what I do.

Unfortunately there's no information about whether a mount is multi-seat in the game so no way to automatically flag them.

There is a list of current passenger mounts here: https://wowpedia.fandom.com/wiki/Category:World_of_Warcraft_passenger_mounts

Happy adventuring, X.

**Comment by mbattersby** [comment]
See also this FAQ answer:

https://github.com/xod-wow/LiteMount/wiki/Passenger-Mounts-When-Grouped

**Comment by PanoramicPanda** [comment]
Yeah, I meant to come back and close this after I discovered the custom group stuff late last night. I made 2-seater flight and 3-seater ground groups. Also used some macros + click casting w/middle click to bind all the hotkeys to my portrait to save bar/button space ;)
