### ISSUE TITLE
Incorrect map id in Sanctum of domination

### ISSUE THREAD

**Issue by Unplayed** [xod-wow/LiteMount#101]
Addon shows that is 2450, but it is 1998-2002, and rule is not working.
![изображение](https://user-images.githubusercontent.com/43932588/187955983-a19274e7-c13e-49cb-87dd-c69ace52cd5e.png)
How I can correct this or enter map id (or range of ids or just list of ids)?

**Comment by mbattersby** [comment]
Hi Unplayed,

That 2450 is not a map ID (which would be used by the Map condition) but an instance ID (used by the Instance condition that you have selected).

I made a rule for Sanctum of Domination using the instance (2450) like in your screenshot and tried it out. The rule worked fine.

I'm not sure what's causing your rule not to work as you want, but it's not this. If you can't figure it out feel free to log a full bug report - https://github.com/xod-wow/LiteMount/wiki/Report-Bug - and I'll see if I can help you.

Happy adventuring, X.
