### ISSUE TITLE
Wondering about adding a few conditions to swimming & falling

### ISSUE THREAD

**Issue by Jaladhjin** [xod-wow/LiteMount#103]
Hello!

I was wondering about adding a few conditions into the Advanced section.

The first being if swimming in addition to casting a swimming mount like Sea Turtle or Fathom Dweller to also cast Water Walking/Path of Frost type things so I can get up above the water to mount normally.

Also while swimming specifically it'd also be nice to cast Water Breathing from a Shaman or Unending Breath from a Warlock.

Hmm what else there were 2 things trying to remember them

Ah yes can I add using Engineering items like the Parachute or Glider into my Falling criteria?

I'm not sure the Engineering Parachute/Glider have Spell IDs do they? If they do I assume I'd just add them into the IF [falling] section huh I'll maybe check on Wowhead to see if they have Spell IDs.

In macros it's just /use 15

Lastly if I've been afk a bit I've noticed when I hit my LiteMount macro it says "You must be standing to do that" so is there some logic we could add that would stand me up so I just have to press the macro again?

Think that's about it for the moment! 😁👍

**Comment by mbattersby** [comment]
Hi!

You can do pretty much all of those things with [Advanced Options](https://github.com/xod-wow/LiteMount/wiki/Advanced-Options). There is no way to do them from the UI rules, and I don't think that's likely to come (at least not any time soon, Dragonflight support is going to be a lot of work).

For water walking or path of frost you can use the __PreCast__ action.

For the engineering items you can use the __Use__ action.

I don't think there is any way to stand up automatically, unfortunately. If you find a macro way to do it you can try putting into a __Script__ action, but even if you can I suspect it will not be able to be done in one keypress.

Happy adventuring, X.

**Comment by mbattersby** [comment]
[Crusader Aura](https://github.com/xod-wow/LiteMount/wiki/Crusader-Aura) has an example of using __PreCast__.

For the engineering items you can use non-equipped items by name, and equipped items will need the inventory slot ID (like 15).

Happy adventuring, X.

**Comment by mbattersby** [comment]
You could try

/run DoEmote("STAND")

**Comment by Jaladhjin** [comment]
Hey thanks very much for the advice!

Sooo the problem with PreCast & the Crusader Aura options is it doesn't apply specifically to the condition Swimming it does it at all times.

Is there a way to get a bit more granular & if swimming then use all the water walking / water breathing abilities?

And using the engineering items only if falling similar to Slowfall & all the Rocfeather Kite & what not type items y'know.

The PreCast is too general & just does it every time the macro's clicked.

**Comment by mbattersby** [comment]
You can apply all of the normal conditions to PreCast. Everything from Adanced Options works.

E..g

PreCast [swimming] ...
