### ISSUE TITLE
No Mounts in Mount view

### ISSUE THREAD

**Issue by sdrowan123** [xod-wow/LiteMount#104]
What happens?
In the mount view, no mounts appear. My hotkey does not summon any mounts. The grey bar for where mounts should be is there, no portrait or title for any and no priority for any. Cannot change priority for blanks. I've double checked to make sure my filter is normal, reset the filter, tried multiple filters, nothing worked. I've changed profile, and reverted, no dice. Additionally, it does not work on any of my characters. I've tried installing an old version of the addon which previously worked but it did not work either.

What did you expect to happen instead?
See mounts and summon mounts.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
I stopped playing before 9.1, it worked during Shadowlands launch.

Please do not modify anything below this line.

--- General ---

date: Thu Sep 29 22:07:42 2022
version: 9.2.24
locale: enUS
current profile: Default

--- Player ---

name: Tostadas-WyrmrestAccord
class: DEMONHUNTER
level: 60
race: NightElf
faction: Alliance
spec: 2 581 Vengeance

--- Location ---

map: Oribos (1670)
mapPath: Oribos (1670) -> The Shadowlands (1550) -> Cosmic (946)
instance: The Shadowlands (2222)
zoneText: Oribos
subZoneText: Ring of Fates
IsFlyableArea(): false

--- Debugging Output ---

VersionUpgrade: 4
 - migrating global.flagChanges
   - into profile: Tostadas
   - into profile: Default
   - into profile: Tortilla
   - into profile: Hogort
   - into profile: Beorf
   - into profile: Yerkov
 - migrating global.customFlags
   - into profile: Tostadas

--- Options DB ---

L312YXXXr2pOn2i6QR(6JeYswYIIkwbA7WV0RrtoIeHabuaa612pO)O9H9BW)yBw55KzwZmngcOBb1UY
ry2XmvxvwzvzwzLNtoyjT8YLZF1BV42Y)E(BV9MVB3p8x)3)H)6F(FC77UD3D3)d)1N9QxDZTVwB2nx)
Tx(M)0UBV7YBUE5f5L7xo)pCXv7((D)R)NB036pkF11putp)IlE11V)U)5tQ))Yl)N)ZBwVT8))KEVp)
97(BpT34B2TU7MBV(j9oV8M7U)IxFXDpPx6SDxD1LRV)DRpP36tE7LV7szH663CXhwv)YDxF)fV6QDF7
L39wT1VCNSY(DyvEZE)IRU4DxC7Lprr6MBE3fpnn2NFZBU527FsVYzYYY3(KEJV6YRU46D3902j)v729
0gLxktK)1)9vxDXt6T(93EX1V6Tx(02B(xE6ATZV4Q7Ee7u(l7U97U5V9u6z5L((BV5BV8QDF5U)XDFi
3gN)729Tx8(REapfX3EANdr7(G(dIMEcxarJoPvF0StBOhT7dyBhnCBZ5Qb8bTGR6JtA0wpwNWoTsFDI
nz8lpPXi(UpK1N3Qh0CRwRFslSOHN2OkA3PSJQ3lUVPt17FcRf(Lf7J3C1nRxCvX04BV6I38jLv5DflL
x0o321mw(IV5p(ILZ)3wo)p)SN)LLhUxmUAAs95QVu(S00S8F1VWN9S)0x)nFXl)0ZTw012mMFGUSTpN
AMkF5N98)YY5)7W89iJ6ZV8Az791VcczZY5F6f3D)UIvXxE51V5138U7KUs(pzf5TYY65V9IxFZ)LSi)
A5Z7htlN)crR(2B3D9Rf5PTv6GZkEeK3)lU7QDAJg47(ID)93RFq3Y5)X7FZf3(A5d)YD7((LxmKTb4Z
U523i)ZnYgKZV59xjTxumnwpC5BE79V9MRKXAOr6LF)7V(13EX3jTzOtMkF57VsmwU82lUR89sp(5xC1
v3Ho75Lx9AzkTNBm1hMzGVPtVZ393F1vV)17E95FVyFZvY(804YQmS5(U0u5P2PPXUMLZkkHU((g9BBY
P5E9Zg7hBW3oLtj9DBZZJdd4nAYODLobFu5v1NA7NgYL23pnpLrxmm1QdAEEsMLN5BeknVn3ajQS9PXg
OriqTJjr5FMkUDu0AhZOt67LDmAZsnIazYZK2(HXw2hdZZ9A7BZP(PjV30xORDuwUld6qBtRk35Hr0)L
odnkp3oQJDEknd9tAiHPB5960EOFQzqhYUUuFIYAACGJyFt2F1rm1N7GQvgP(gVz60STBSdtLuAAmpY1
S(gvA7NNPy3p3MY(yn6JGkMdnPS2SY0C0NM6tzXyO1AERo6dPUo8DIOHpzEQv7aTryonNYPoSio1XzN8
cJ8HoS4ppo179ouNJnC9Dip2yBPAsUwPvFAEAe9vra1pzyOxvW9JtUOOcq)4m2OPD7yAk5Q)OtHuuuRT
6qoo3pOkNCZqhwXtJn5ox11IP040exWepDDyd0qkphZkxkvHzymNdvf2MjprZdzVDl3rlE5WSs8(aLql
AE5fZ0KCEoJfNCBI7weVktCFZ0mwFLheJa0U5oQtlTd9xEAWmXfJHjV)Ww4MXzv9PntxANh7NudQ(uxs
LTIqQ6EXGTBK2oPjihL1yFfj35Fj8Vm3KBJxigjFLjJ95sV0bR4HMjOJ6MgOlHgzUK8xyW1nyolw9qlv
2Vs)ktLT(6yn0ngVQkWDnj2m5vnlurdIf3UwUdrgZUo)nN8HcEh66Au5yueCmxKTrCLumOHFOoXpNkJY
(kyjj(X6vbtCELhsO5I7eDG0pdZ9C5zSkpcLGmHM5mppd5FEGUVMKL9Y)w2lntnrxp2OjnoJLP(bSVzC
Ea7cMZdyNVS3dsqXWLEwgNtqFK7HdczPS8EW4ziLyFjE1vPQp3nHDJddn9CjVDaRLIwDcEWlQeAJ1b3K
631BI4KnPrFjBuBW(0sR4E3M5bT9IppSTxe7E(cLOhgHYP4PDvToAWjqYeaoVymgQzISEJbywcMz0uEW
eww9s0PU8cCa6AhAmPfVPmaDDupcpNdZ0dHSlAMwcImYLuzQmL8NAnTb2(lNdM5PmD9J2s3iCw0zhfLA
TTR5HEUuiJTQSZPHbCsr5KoiqA7ORezaufzU4qdTtmd4cLeq3i25m1oJf(YoVrB6L4dCFDJSXbgenJT9
dC4hPHGCqf2tu2)3JDXD4nh7BDTn(kXVoSckVFMwg9ynVObWSuC6Krpn1WXt8GL54vwkGwucWXotQJr6
mlUWvnGCYvBJj0du8fZxm3KtJP3PItsU5EehUiNKsdfXcTNoWNBySpJyWlsgpLTPh2LtWov98rJjrvoJ
Tktuy6zeqddm4LYPIyfvSzWsqzFc8quM1ERWtIYnZJD7hPp0HbUwuAMDEDM()AsTCzx29yRSDn0T6e29
nid5aFXbiQsZNXIM63UHBf4AC5qOo)SE0TYPr0NGCmEVPkzSlsyy4ffd7zBfcASYjp4W5ojOrD5Re9iw
FMBMrOoffnddtIAOJ6NE0)LnydyDzgRMIfmoPt1yWytIEJhxkEOnNPZHcBaRJjAmlcyIbOjBS0VS4Yel
74gtL23BhCiwFn9yPCAI(uKtL7TtO7cxdZMblp7qCmW1(YrEy3xFEiBUffnQTYXi5kDhANCuoDYkFRDS
2mo3wcuFGNQwEbmBgffjp0Rdwg6Qj9xihVJptCtaBeztBR50PBMb8pKWEJjgVFrdLTJ(7qGvIMN(TeT8
eMbTYDUuXq6kgNQexlIcxIGcgvZIxbk1nntUnUUhCAkNzNkTAW2MPs)iodiBBJKU28rlBoB68xdHI3nc
Xt8Cnax6JyVgJnsCEop5rj7HC10BclmLZdWBvjQg(EdzOlALWSY86yYnP0zs5gdyJG0)TmgP5oZj4imk
KXl17rVJBmu6meSuRCxTbOngXux7mmbfZdCuYSeZedNq(mDQwuvUK1bFs5bB)JCuYO3z44AXad7KBhBT
lFuoUwN4m4jXNCpSNubdU87OjJefCpSeLJNMCnMTOIJ0LTvJ8SA5axOFBBGtD5GgUfquC4C8IWBHy1K4
b5DYzz60Euc5HNJlDgUuuQNHU3Zaef3jPrSRRPbkUYolCINSHVX7Dyi1kg3Xls3c92HyLpdB9A67r4)L
rcIOS7sFqKleZV4JIxcx2aI14UIlbR3vPzu6iyfLPixelDJwrBnJf4beuss2l2KDHQ3fESwxcDsFOroX
KhOo1anUMEhU(psnDrDXO1KOaX8QjH(OOUW0Vr8LR796kxGT8D9LaYWcR0vWKAGxLr1GtEFPcB5Klg0T
ekI29IZmFLQl6l)CLbtDzoYP7nPlhZ2Ml6kRDS3ShBhDhOZMyHDxI3eliCE5(zX2IoJZwitfhyJMQb2u
fNS4uu5YXj7Sag8u5whOBLZPD7MeIdrI90SPMXzAYYrld1qo(bEAK)Rb7KKD42n)69lL2btOCjakmDLj
j8jlwh88IEr9KmjdbL0kBYXEMsiTUkdHW1ZmgODbnif3djQYyMc64Yq5IxnCnI3Os88pWiBBAqeiTYon
ZEu6Rwtl6ASS1kyDm0Wt2k(tXrrYwvi9dtZ8I3DypBrOGgx2eMyutjE0V8ET4(bLjMDTgE0VeuRF9NUU
EUGlRdTMCzXyGiEglsOVqsxBsNXmHjxv0sx0eTpKOgTtCN5aucQMr011WJlLlIqVAzXEghVkNmL9EZnj
NmjZwM9R2jhQAXvp1066SoFOSlVpHlMj3NL3iAC23moZBAk3vTd3JiBoJkYn1vsOGTUObjs2FcB9(b6l
wMiEk8smuRmTnujd3pquPtEFHDGIVig60CdVvSesuQN3Vs22BXMZqDlkxe7Q2UzBIY0Rib2meTtN8Y9R
8eJAh4vmu4(WPXwECRevwJjEmMJIQj6oC21OfHQSld(BfBSU4sO4G6mdCU0xTMcXCUKzY1Mfp2wYJs9(
z3Tn(AvenZOlAm1ztDmNrs3zp1Xytlzs1v1HIZwDB641MAAZDmOZMw8K4IfM7TJYHuEQhy60sdzEzNUE
4XORpgiMFIUUMjVrZ2AksA7qXrkMunJmBp5bg1rrhrxaT2DXsDSlgGYGyrCgvA4ejUpO1ortUv9GVTfh
NkNQoBrH0YSg3YJoMZjEbPr6WrIkgwmIRYb32mBgaJ0nyjfg6tY91S8dnYSPjhrJXrflUVtwih8EdcD)
is2zjgpDYpkJofW(KLQ(PPzF2p5AnFRWa3GBBagTiglxfh3HqUvhUEP8pvc2e1xzlLAtm8nEGGS9cN7j
Mr42af1fV9ytlXxOKzuvaN0C9B9eoKGARspXR0107Ulqahj9JS1qOjZZnrpbjFS17PqHc1DhVn004etn
QCEIURQCBl3pbZ)N4dEi6l0dIzmZCWydUUt5O(wZIIjoxTz81qEl3PsOzANuCzzjWINYkQlCnJzMUVso
U6nPo307DM3T8eX5YnlWNXSawUQKonX1a1UqUQb80kE(7g8jkp9s3Nb5HRvsyPO)L4RWbksOqm7vY2yU
7vVMGjyw0x8ykzno5DvSsIZK6yMrkUwzkf1Ck6c2SlytE7A5GY3OOZGPzl3nibNnnz6hxRuY(phbp)uJ
4afjW1Mwx0Wo480S7Oyo7IMFAjUFOyYZW0kdecyx8esHnXedwUnT(q5m(zVVOVk9GRve8edkpXmOOxih
Retn9WPMCnaE7SYfYjwkT8E4DD5KDTu0fY(Nr7ehlBkfvgfJMuBC4MVcWaNsz62ODEGz5xBhKTuMUu12
XWz6N4r5f1M(zL0utDvlHZyAG7K1BCR9BbMn2QboPKJSX3vUMR(DLCL156f63ltZPsWd(2fCSOSXNhEj
Xbq32IICYxcMXYZSeHwKflgZtBlKJIKXZhkbBRluZiwyjySwoKZZyty5w6mLIT8acTRy61K4Q9ZJyuHd
mrMYIpw6kPgHBAf3smj55rOnZ6nf11WjgGDjh2m(VoEVY2w7cs0xGyO5H2J9DL9cn(QCNjumtZI9aLy6
0DUoBcUcKGsvYkRLZblYY(mtRtbWy0S5UeVkB5obis1wes19FSs8G3F3938UpteTIqjFW7V8RU59xF)N
D5v3V72NF5D3xEJp5RF(Z)0p5LF6VtMsN)IV(L)NXhCwTySYrCfdYkee5Fo)p)fFL(Up73)np7fA38NE
25F(F4l(MYJ)UV48ND2ZzN98V(zVS8Hp7)O8))PVaFZkexJ2hFKYJdsqMlV6Ql(yve3G4ebmkhrCcAhY
lVO8MO8e4nHATLnGBbVjupJnmG)d5nrPF3N3eAxSpVjwxEI8Mq9fzyKqEtSEmVjwnEtu6Jd5nXkT7T5E
hoB8b5nXQ7NyDHeNqvF7tCc7f3K4e2eWIwLW5LaXjkFgioXzgXjSMrSemSnEmeNWgRrFeq88FqItWM3Y
RRqIt4X8CiXjkpbItuEceNqvvTTwoaQjoH9Imw1hI4ewZ0NaXjOaIu4SjXjwFqIteyHXRgQZOdyoH1oo
6kZjSo3Ur4exXaZjujpfx1Diete9JXCc)gKK4eRlhrCcDwThXjyFM5g)zB7oioXQAS3yzptjorPpkPku
B1b0Mq)ShK2e6CAFAtSEsAtGdklpawtSEmRjmP2mf4LfobRj029HznbvOXiqZdL0e4lFastycNkVG0eL
pYrpLKMyDHrzOpOKMWEZjFOGRbL0eRNI0eLrAIPYgKMq7RhI0e2NX16CJbC8EKMqL1m3bbstSsstOTHc
)HKMy1inX6IrAI1hbPjkFfinbfaVdsj(eZFk5mr5ZaNjkpDiNjOgHwx7ZzIvJZeCoJ(YZRe5mHQAuotS
ACMaIFpFbew26XCMyDjs0kpS0I3uFtGdX6sfvcoIZeR4fGC3B(oEqotOFYbCMGt4PK)uRPnsC2LmK06y
Q(bNjwxiNjkAXKXShWzIYtoNjCCMRy5cOmH1)i)vbwSgBjjJjolsJh44aNAmi6wd3fJVeKyuAxLidaiF
jwxc(sqwlSUuXtG9imr5doKWeRgHj0HoXu0h8LWi7rCNaqxckY0QD0oTHjBjilHNfQGfdeyx8LeblqFI
sZazjkcHswIv7oHuSgTXb2J8E3b(OKsgRlet(YdkPewnqo1gzSLWVqvnzg4LYiBj0X7i2sq2gznZoKop
tNCZek4GTeG9dQ6AYGyYU0haAFDXUBO2zdeBC)gKKSe6lOqSUAx4CDXY7X6sWwcMAdmnX6pzlXQrWjDG
SGsjJzlFgOlXA9n)W1rvTHX7hNUevSPbeMWuA0oFKNlP8LGIyOYWnAD(s4up2rzZPlbUh76cbZw1jpiB
jw5wn3PWESLyTk)hGmjLVdKLqLcpjgGSewVHOH4HLonC8Ra3BEMcsoWCFG5)EeLO8LoncCwl48KWt(0P
OjbVTVolmWpjDh0Uq5jH29ZJ(bdy6R5bD1OjHnbD3r63bAsGHEKHU2qB1r6ThWduEFK(ivpO8KyTIxpG
MeRlbnjQZ0fxFDMs45JKmLqBUYnxQQcN(uGt02a8IyDPMVliBUOz9wCOkxjwnUsOtelpBEMDpIRewF07
pHTCGSeyuz)s2sqnM3DhYwcKJmD4v4ESMLSzQ(Mi3HLh6TyLqUgnrd6VocSjzlX6sf5MaDj4Bcv0H8Lq
L1gCNmWxIY3b(sWEatCqubmDNHLiOlH1x4QqjE(oOlH9ITCCGQd0LqFpJpMK9cLwz8BZYcFfzjaVQkZA
nPUQWyuy7aYsS(WKLO8aONXAfnvazjwxoKSeRy7oDw)ZiBjO2IXPnJZHpKTeANPSLO089zlH1vWxYqJD
EIYwcRVC71jgkMH1pOlX6cPlH1zyVX(0LyvnCN8nQXwdBBj1HKQsLNa5PPGbFhkFjuP5i(sqyjXaX41r
wx1Ev5lb1xMjbVwLsujDymUSQ0Mq7adddYwIYtOGj05rRnJoGUe6iQ0LqfhLUeRlKUeuN4M27XwckyUP
DVRFZMcdXV9GKL4SfswIvAJZWNu2sSIDyO7rYWSXMHLR0LW6n31iJKqzvbBgpGh8NR8ToJoiJjwxc(K4
mE24qrWyIkcq4mMGSOqNEZ80Fct1QQqNy1caktqnuh7egylOybuAC3jOmbMXn8EcJkLjwxmktyTZcMGj
DsRufDidmu2NXewNvXyckyStpGXeL2de9mDg3rFaJj0Vvr5t)mNYeojoaFkkcP5aKKOyDXOmX6sf7mCk
tawLu6vqzIvyi2BoZ2JYeuBKCjdd5wuMWHUKaBUwX2cYyc9foGXeQG0Xt3jJjkpb2wOcNrjkWDRY4RqH
PT)actyQHO3WH0JgZpnctaGqxxcM3PtpFjaruCiHjGUQ1suHsycDszKOaGxI(yG3Byu5lrrkuMkz9M(e
QMO1Lkwqtcrq53wAv6sy9g3g1WyEjm)6BO8La9hl)RGMebRiCC01UR36oC2qhdy6a(sSUeeHiOlrWVcY
xcvEAgnEyyNyXCQBQnyLyuTOLwlGhwLhuUtyYNBusvmH2duMyvvN9PO5mcM5Hygo5cnTftDrY9WtoPja
1kmHNhn200f9gu6GVD6uBpstO9FVLnrgrl5mHkfDz3ayGxAeKMGJzdvN8gFGZeRlKZeMGnr9u23wad39
5mr5dOBcLXe23GdwnA2mzj5x7gyRbDajmHoNATBpoY7(FiHjq77Qi6aK79ymb6QKTvOfcfymHQEMmtoR
KP0EQdcSrJQSbUDWulNXebNWaHj0Uy2sc34beMW6nZxx21wEqDwGmC3n4lH1xy3MXpru)j63X0)rEZSA
0Lq7bJUebHiaBjwxmEzQd9yI65mda2zlb46Zk3aZWQICKo15YSDqgVw9GDJ2n5QkOlr5PdPlr5ZCgfq6
suEc0LqLBJgYKJBLNIPCVDjMeimX6YECgYswVXaBsyI1LGWeKY3MW5EQ7ndaELLGXedg6kbHjaBhGgXU
9UX69O8c3Kw9gJjCEs4uHElcteSdgmMqfBR6boKXeL278SHmMGZZzQCTYGILxHnQzx2ujbfvSor1YSAL
gbWUqRnIYdzEHzsyct2MSUaJEW(cNXeodZbJjGuy3jfmMqN7AvVODBdNOGYeQ8O0AV8eOmHnrr35KRFl
ktW69P8KvVpr9bbsty9gdUZto5gKMOL3oKCMWAg26CaPjwxQinbyqxP92ngjJwwxmgKODXESMO8WmHUI
uRyDjOnbl2wRV6mbJUH9cqQ1RuTzlfLo1qyTgATIU2hTihDMtGAlADPQK(aFjwx8kMyZFCe2KKc)8ZlH
95IGIEo)fL43oG7FIFve0v2d(vrO80HO7xEJdr3)SFfr3VkhV)QHUV7a7KG7)loK()ObY3HV396FWp7b
Lp53cO375I1XVNjY(0G3))HHSxfmEl2FgrSpc4n5q2haavvfRBbuFGLYVIa1BjORcO(d(1nWEZjFOGv(
pvG6d4594SDGz(4bC(aR3arZhj48oqK)sJn)d(7zW6YPXMpIXi)G)EgSIx4JCS53ci(JrD)KGNFeM5BG
uUdqUJbEKbzhu7nGY2rW2bU(uWohGnVfeZgWYoCYb8WbcWgWMbUVbCVbiVooUBIE7gq0EeWSpwixRayD
dyvRWh1aImYstu(42e4KWI6e33ll8Aq5pcvu)I2o00oQOhtndhuuhZ2JWenUUCChahtuNOfBGjQtoc)I
fbJlCCsdqrdUcffsUHzMtsGkS(nirRUAQdjAWIchs0QFppmgA6KViqe1HuoiTqaiA11N3aquhaxNIcvW
R6aI64YfeGjaEXV3vv2SobGObyWoGObqqBaiAqjdNVgorsC0YCoQ8thp0O82nQx4C8iQsvh)1TWdTI5r
gBeFs4HgWV2AK17e4HwD3FGhQjv9EFfhuPp44H6jVi4V2gWH65NiaU8uWH6Sn5KWHwHIRrkLGjfoAOvq
x8yGd9WQhFDjaWpG52jnWPad1X72t2sW4iN4gpkSqd0(DWq9KCvHfQNyOGirbwOvuy5uGHgKzjsn4jrd
ni(0XWH6eDyd0qDCY2am0G3c)4XcnYIPXdMaj0GKlbR186j3PvQtbVkOqdw54qHgWJMcOq9Is)iKqJCR
VfsObpConsOohLIKxgyHgqz8Jgl0k87dSq98RLCSqDmLpQ6Xlp5Ge7yHgie6qHgWP(GvpouBpmuObdYs
Jw5JhO56aLwbfQNT2abYak06K)FisOo0PoMhvK4XPeMZYMOsdpjoObEPoqObBhIAu1HSi5iHgGUxbfQZ
lQakuhXuNfsbLBCGqdmudKqDEyKCyXc2QSfqOomPbqOoGwoN)COMc46yDjSxHdFCzJBjhoGK0abnWoDl
apDaiRRo9zBspn4ARjVrmujhxIkvVDQZaVD9dcbQUFeAzhi5TGa1HxmGanqApQB89a2tfIGQCocOoC2N
aa0ag6ab0aG1aqwhaucF5Pq)0l((nq)ScyAha0KdfFGbQJtUJ43Jed0kidWaEmgOjht50dJbAYXH0Paq
GbQZErNXdjhd0GDfvGGASoWXana5Tceuh24GelBccQttghfuvImLHLMJnWbn4QrakHbe6bLnU2dgoO1L
Ts4gyYQFzJmahHdQZGaNzcDbBHoeduJbUbgOjqaTZwcwG8bGa1)bviGaTIcuo6Ib8B(VHlXpHnoaObt1
ojcOrPXCAiqDkTeOdxrD0OMXnaJdiqDYSg830R1SGTSbeOEbAeW)gei3qDnWCVIysoZGdCYCiqRq69ye
qto(Uoz7QOdRdaQJCRJsBG)zqYWhlaOoxYSsVi4nTdaQZm5TW)mOINJ)zav4w4Fg4A6)8bTf6NvK(DVs
g36lTlCUH6ejma)m4wGd(5dwW447yIQCev3VEX1EYQZSJr(mQiGG3Tb0NoEKBb9zqk5nG(0l1KdaivB)
gqFgmU2PHFuIoec0hpYN)cxE2omOEDAVhKO4VEaFKIiQ)hrHpwfWNmKTvCE9jxq2r6e)PIz7zl)wfZ2F
8fKDCjQF1qVnI353OW3wUKZzBaERhz5)pd82YY9VaG3Ur5wxHDBulMFmJDRL32FHXUDRISoyl5VDRX6i
eKF6LyTN22FXHXnkX6NikUrAy)iafx9CrlP3)gbfxVEIpjEUBvgXBGSB8RuGJXRdGx1payEH5grjB897
yelRkDyVaPJkY2VxF8dTEosfYHvoCfviCSKJlt5GkhWwwtmUjN)SwPpBGuUDLdxHFT)7jp3ACmU0bxmF
4kh2PVXqqxxR(Npji2oMavLvD1Vcho(foDtFieUXovNOio9q8RHfjOVQCW3aA8Qke)WshUIbTpQAhoiB
Id24gGK7SumUOFu7WXpnb21DDyY9KDEem5owY(D4cuYdwPCam5W66GskVc4CfL8ZyxzbuAaZD0p36rvG
h1Ryu5WvLb(jGj3rwRc6uVYH9SSwvc9Bu4WbFg3cNCVWHRi2WEf1CV3SK1B0XPJDxvTMhLcCDcPPeziL
hWC7Gd5PkzdGYZg7i3OYHJl8x9lKZpFqLhCVVIp(oE4oM3h9lT(6svX)6yUcWYpBPI46NaT8GjfrT)Ec
4Yn2zSvXdx9NGJnblhMJ)Cw7WbQtoMWNU2HDy8CQpeGLhfDXJbS8nQDyhEPkK(DE58WGLxHly7rPK0tm
9JdSC)xGuh18aIUaT8amTizPvvoSJB3PalVUYyFuLoCW3MJblVkRZEve7OLhvd5gLoSdsEKqXNkA5oyG
o)Id0YdQ1ealECLd7GcwHwUtj5aT8GsarLg)WGLxvMXoS5rLFf1t9Pbl3lT6QFfCDWYD4h(rJvUdGYPl
B4OeH3cRChpchQ8kaSdSYD4e)rJvEfi4ow5vabSXp16rr09JVSHJke0WLli9Gtjkhl(0tgS8GaaoE4oB
Dsby5ocGTpY6g2b6ZbSo5OLh5X2blp5GJvv7VoSD1WLBawUbA5vyPh)jykqg0XjkW51Hhxh)ER7StyQR
jZdQCy9fGEiWVmkmzhjDhCDJX3dDXwTj)TM5N1AC86W6g2Hr)eyMhCkPn(7lZgvnSrYLQQgokjDhY8OC
GDmZ3JA)thu2(Nc0Chx8Tan3qg)imZdOzFILm8MGMhKP1anp5aJNCkA4OMhiQFeQ5bG9Ne28Ou4FyuZJ
FSom(BwdA(KhXAuS2WYXkPDhvChV4aX89kA954Op32(Pu2WXFbdmO53SSHnYY4WwgLnStCInGlVQ6oRX
lNSCO6NoH9bmhj8Y(XCWRi6QFMjoc08GCEBHAERXGPtJAEamTdAEvbm7GM7CrTIr0v)8UyOMhWYEAuZh
nsY9bqn34lSd)8XLnSZIYnGmpxvyZd(V6thbzE8hETGeSXpDub9tnyRDcex9dLv2RJuIyEWx6TGmpidz
fDc3aZ8G25orPdqZFQfnCWW69(zwxLBhZCNc0BHzUZd7OKHdgwSbK5o9g)avmSZI3tHzUtG4nRy4OySE
YOMB)m4DCfdx9RX3X4Mh)oFfvRIHB(E)siEeU5oc)BaBEukoo3tdyZRR7Bd386F32zIu9IFWHV)XdC(V
GyL74Jx(Fl)V

**Comment by mbattersby** [comment]
I have no idea what might be causing that. Perhaps some other addon is interfering? I assume the mount journal shows all the mounts correctly?

**Comment by mbattersby** [comment]
I think it has somehow triggered a profile upgrade fault. That is my best guess, though I don't know what fault. If you run

/console scripterrors 1
/reload

I think you will see it shows up some errors.

You can probably fix it by removing the LiteMount.lua somewhere inside your SavedVariables folder. Or you can try doing:

/run LiteMountDB = nil
/reload

**Comment by sdrowan123** [comment]
It started working by installing a version from a few years ago and reinstalling the new version. very strange!
