### ISSUE TITLE
I can't get this addon to load. 

### ISSUE THREAD

**Issue by als30334** [xod-wow/LiteMount#105]
I keep getting

183x SharedXML\Mixin.lua:28: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@SharedXML\Mixin.lua"]:28: in function `Mixin'
[string "@LiteMount\Options-Options.lua"]:153: in function `VersionUpgrade4'
[string "@LiteMount\Options-Options.lua"]:301: in function `VersionUpgrade'
[string "@LiteMount\Options-Options.lua"]:326: in function `Initialize'
[string "@LiteMount\Core.lua"]:40: in function `Initialize'
[string "@LiteMount\Core.lua"]:90: in function `?'
[string "@LiteMount\AutoEventFrame.lua"]:20: in function <LiteMount\AutoEventFrame.lua:18>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

I update my addons every day before I log in.

**Comment by mbattersby** [comment]
Are you just returning to playing WoW or running LiteMount after not having done so couple of years? Or did you somehow copy back your wow WTF folder from a really old copy?

If it's not that it looks like your WTF options for LiteMount got corrupted somehow.  The only thing I can think of to suggest is to reset the options by deleting the LiteMount.lua file inside the WTF folder, or running

```
/run LiteMountOptionsDB = nil
/reload
```

**Comment by mbattersby** [comment]
Closing, no info provided.
