### ISSUE TITLE
10.0.0 better as 10.0.3 ..

### ISSUE THREAD

**Issue by Robcor0007** [xod-wow/LiteMount#108]
I have updated to 10.0.3 and the addon have problems.
I have a druid and i want Travelform when i'm, on moving.
When i don't move i want a Flightmount (in DF a dragon)

test it on Beta Server
With 10.0.0 all is fine (beta fine - Rateail server nothing happens)
with 10.0.3 nothing happend. no travelform or mount (this happend on Retails Server too)

see attachement bug logs from beta and retail server
[Retail Server with version 10.0.0.txt](https://github.com/xod-wow/LiteMount/files/9869455/Retail.Server.with.version.10.0.0.txt)
[Beta Server with version 10.0.0.txt](https://github.com/xod-wow/LiteMount/files/9869458/Beta.Server.with.version.10.0.0.txt)

**Comment by Robcor0007** [comment]
i test it with 
/click LM_B1 LeftButton     in my macro

results:
with version 10.0.0 on retail all is fine
with version 10.0.3 on retail noting happens...

with version 10.0.0 on beta server - all ok
with version 10.0.3 on beta server - /click LM_B1   it only take travelform - no dragonmount more...

**Comment by mbattersby** [comment]
There is  a Blizzard bug. Two combinations work for macro:

Set `/console ActionButtonUseKeyDown 1` then use `/click LM_B1 LeftButton`

or

Set `/console ActionButtonUseKeyDown 0` then use `/click LM_B1`

Only Blizzard can fix it.

**Comment by Robcor0007** [comment]
ok thx
