### ISSUE TITLE
[Feature request] Multi-person mount action in rules

### ISSUE THREAD

**Issue by ZehelFenris** [xod-wow/LiteMount#109]
Add "Multi-person" as an option under Flag or somewhere else in actions for mounts that can have more than one player on them.

![unknown](https://user-images.githubusercontent.com/43239740/198129440-b4834dfe-b551-4d4f-ae07-acbcadc9b000.png)

**Comment by mbattersby** [comment]
Best thing to do is create a PASSENGER group then use that. Only takes a minute.

The game does not flag the passenger mounts differently in any way so there's no automated way to do it.
