### ISSUE TITLE
LM needs out-of-combat priming before it works in-combat

### ISSUE THREAD

**Issue by durandal42** [xod-wow/LiteMount#110]
If the first time I activate LiteMount (via a "/click LM_B1 LeftButton" macro) in a session is while I am in combat, it doesn't do anything until I exit combat. (I use "LiteMount : Macro : Combat" settings to cast Divine Steed if I attempt to mount while in combat, and this worked pre-10.0.)

If I've activated LiteMount out of combat even once during a session, it works fine.

**Comment by mbattersby** [comment]
Thanks for the report. 

This is part of the Blizzard SecureActionButton issues. I can't fix it so I'll just keep an eye on whether Blizzard fixes it, or if not then I'll take the combat functionality out when DF launches.

**Comment by mbattersby** [comment]
Turns out I broke this attempting to fix the other thing, so even though everything else is still broken I fixed this.
