### ISSUE TITLE
Oculus item mounts

### ISSUE THREAD

**Issue by ZehelFenris** [xod-wow/LiteMount#115]
Would it be possible to have the 3 items in oculus that makes you ride an drake get added as mounts like we have Magic Broom?

[https://www.wowhead.com/item=37860/ruby-essence](https://www.wowhead.com/item=37860/ruby-essence)
[https://www.wowhead.com/item=37815/emerald-essence](https://www.wowhead.com/item=37815/emerald-essence)
[https://www.wowhead.com/item=37859/amber-essence](https://www.wowhead.com/item=37859/amber-essence)

**Comment by mbattersby** [comment]
I think those are really vehicles not mounts, so I'm not going to put them in.

You can do this yourself in the advanced options action list though if you want to:

```
Use [instance:578] 37860, 37815, 37859
```

See: https://github.com/xod-wow/LiteMount/wiki/Advanced-Options


Or you can put appropriate /use commands in your unavailable macro. See https://github.com/xod-wow/LiteMount/wiki/Unavailable-Macro

Happy adventuring, X.
