### ISSUE TITLE
New Profiles don't retain current settings

### ISSUE THREAD

**Issue by sweetjukes** [xod-wow/LiteMount#116]
What happens?
When I create a New Profile and select "Current Settings", no settings are actually carried over to the new profile.

What did you expect to happen instead?
All current settings for mounts, rules, etc. should move over to the new profile.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
TBH i don't know, sorry. I just made a new character for evoker and saw this happen.

Please do not modify anything below this line.

--- General ---

date: Wed Nov 16 13:43:46 2022
build: 10.0.2 | 46658 | Nov 14 2022 | 100002
version: 10.0.6
locale: enUS
current profile: Default

--- Player ---

name: Xetera-Tichondrius
class: EVOKER
level: 60
race: Dracthyr
faction: Horde
spec: 1 1467 Devastation

--- Location ---

map: Oribos (1671)
mapPath: Oribos (1671) -> The Shadowlands (1550) -> Cosmic (946)
instance: The Shadowlands (2222)
zoneText: Oribos
subZoneText: Ring of Transference
IsFlyableArea(): false

--- Debugging Output ---

 - PriorityRandom n=94, t=0.800, c=0.210
 - setting action to mount Mechanized Lumber Extractor
PreClick ok time 24.094399988651
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 240 mounts
 - trying Flying Mount
 - found 94 mounts.
 - PriorityRandom n=94, t=0.800, c=0.328
 - setting action to mount Mechanized Lumber Extractor
PreClick ok time 23.263400003314
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 240 mounts
 - trying Flying Mount
 - found 94 mounts.
 - PriorityRandom n=94, t=0.800, c=0.250
 - setting action to mount Mechanized Lumber Extractor
PreClick ok time 21.721499994397
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.099999994039536
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 240 mounts
 - trying Flying Mount
 - found 94 mounts.
 - PriorityRandom n=94, t=0.800, c=0.738
 - setting action to mount Scrapforged Mechaspider
PreClick ok time 22.654200002551
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 240 mounts
 - trying Flying Mount
 - found 94 mounts.
 - PriorityRandom n=94, t=0.800, c=0.568
 - setting action to mount Mecha-Mogul Mk2
PreClick ok time 23.15870000422
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED

--- Options DB ---

nU16YX1XX5hM8JKuHkzUFX)tIuKwqsWS4skz7ugfoe7HaB4IDrT7ckbvP2N909m9xphzt5iswfoCU0tF
)2m4k7vV9Qv3C30b(NVC(x(LTZNV(loF9B3CZD73T(WMhpYZ84X53TB6ttB2o9(TZF)0nh2F1x1g(57V
)9tN0rUz)UpS52Fy(WXn73D1LvEKXcw9FDZ0XtNV(9pEy3MD3E(6dpE8ocm)9G(ZVUtxT6ppFA(W0Ndd
)hoyA1xm)4p)7DTV(P7F4Zt7FUv)MPJFC(0V3vVA(Jp()87CX0YF4W(pSz783o)0X)jsLvVy(dtpU93M
PmwWNLpmM(3G0hl43GAhl4ZtG680kUD7(3pTLjNJpE)973989pU7etEx6J1GXD1L52N(C9QlJxDzixZ0
ivl9FDjBWt)NqWtRjeI5cni9VQX7OpT0CoNVyd0gc842qLM3sWjhRzAxoth6PCd6(ukxTTZ0zdTpz4Lc
0Cj(e9LqKGenU15Yg6qY031C0yBJ6IHI13(0xdog8maIjRJgnX4q1gzsXXNrnLlmIAOjJXON3gJf(mdp
gLZLkt58z6srdtTm67ngBSFoUAWYmaRt2PVdeFTgBu1PpN13MDhpnT7M5gR2E1QVDA7M7xV)atJM4vR(
kYoJw75RxDZ8UPdB2ZyPjqI0BMoSLf6F)(D0AMp8et)0eVy6WhVFpVLxoT5WmnkrNRwD3069FXRN29R2
GJ(ZvRE7DKYvBb)02PDRpYm9ep((d3EhT0NrQn7)P5dNVE)hoF9jE1Vy6(DZRB4sMXL72VD)9mDqhxIi
JvN2F4(JN2)iHGF1H5FQDAwRnr43HP5Dmbw5Z4vtNMxa3vZNo1COq(Cy0RsB45ekWQ)xoD6UdBMOHdel
xXUgNYqgbZKw96B72j1F(b6G78o(G5n8YF881)X9hwtR4vthoS5iZJ(U5pnV981(guje)DBxpreYFGN5
2PBEQJBV9Pg(sNYBN72IkgFX06gEF4H5DeUujf8vF)(BF8F94DmZ(1tBNyUIZZYM)68H5t3XIGdN2CSP
8sW8RoS)JZ0A)MJBNzMVRqc(vpqcVJ9d6lpsc)UkJleiS8Tt)Y0NMpE3ZeK4hMj)rRj4sY(5tnqqY8xV
D62hjt8TBzv)mDswZ)PHOgElVC)H3Vz9A(CFZ80nes9V9872SDD)ePJj8V3Gts0pUCMC8FAZnNV(hN(4
CJDraCfjZp9499n9I93Vz30jbplSAW8dpU9M7(vQoVCZbo0XFAhtRei(6MYiHgFlj4xV)EMT49M)5Yl2
y2f6YRhV)Qllm1rA3RNynKLEPBUOHJo6Z7zhBVMmKoS50gXSl5no4njKy3cwz0O4cXZ(W4bn5iPe3xQP
4CQPFTVaN3fQJL2hKK9KNW2NKRYO4IQunfXff5Mjowzqp0shs(eHm9nLsMyFuVnLLZVTGWy0(ATLuX1x
Bkfkkq7Oh5IYj4mr0bJSWQVgbHqcyGtY2tLAsq(sSi7ohsDkQu8EH28MsimwzfuSv9p7Tgbub6VJblyW
sUdGsidow1y9UXN(Xs74CWxD5X8chjylUoaccRd(7d8SoVSqMI7RZMiF2oz308c0D5Si6jzOC6m17uQV
VWOny7Jfs9dmKnYpfOsHdfXqSsE56GQen4uPr99Tu9ExAmOvrLSs9f7yE3y0(Nu81QOLrICJmTpbs1hd
witRjbRywHOAXbklJD5uQUd0uQe6BpzSwHrMcqjLitJypq0COF8jYgdmsNjlmYQjvnkmfdNu2iuej5nD
afkWUm7tcVJ03mz5iZXIhNUtK8PqfmmAAbpCzInkF6Jc0ZkxIjsXRGjxLZHSfQIvzGWYbPdNcHyCqLkA
qmK(NbhmHilvNO32(mnwqhtJcbfZ9ZoryMaLAPLPKTlEZkBjRNSWQcWXfZkCGuTcrhJjXANP1OEkcQqC
k4lS65a9GwhKLDOVkealMxmygeyreKKdmXXrB(oOOe3sg94hcQus3trj3QIhQYQ4XRuQvOHhHBqxUICf
BFQGelLhmp2LOAfQQ3xNvyILmuDyQeP9zY2IctBFpKvJ3n2UGOrkV2bzUyqRIjcftE0d5fJMhR1ngf0F
2bwk5ixeduwZYrzxiAf0VwaoBPK7d6wIQOVge3VmLkwbvdmIi6lcxv1ycU6deolunPG61dTtiKYseUkZ
YyzYlTQTm0vTAeL8YPHHhrUigOtdoejnmNEKUX8D8iwRQHhniui6P13gn5fnpMKfdn6pIElLnES6glfb
5TUIAxLhbH9qrHpm1(v0zcuzuLXk96kfYU95GcqSFIBy7lGuoqKwEWbxDqHImNuOKCaARSJFuy8b)t0T
y1KQIDc1XQby32yCOr0phsncXBjG7myLgrHiga3VnVfSSic4tWmoWo4GsQ4J)0r4YGM0pJAac7isiVwO
azcsIgEs5hvkgQfK(brdIxtB0cd5OV0pakqN4VH83Brkp88dQfUI5p1GzqvNCo40JQctbknVeyseYweR
shYUI8cocL7fDP2ktkwxgZJbPQofbZWwf1sZGJIAlrFsXGgGN2vCSR04ZbFr2KXiMawYnSrbFEyyM1mX
GtbcqYNetrqeQM9k4eXHCnoeBUSnpgSOiYa7Il2KOTMHtjEqH)XCQbHQUqihXiCxv9QfCvlc4tzk2hL8
(xrg3KoUzSR4yPrfbZJb7iizGzgBpmMEXkrg3ypKDhSaO)apXo1tnVNQEKqrWbpKKahr84TpoiK0h5Gu
I(y5mFSJ1khaf9SoolXbJLI8l6FKBJ6yL1Xkvnby1Xqfj75ldDYa0K4DHSsPCTtJfmibXwYhPeG9JTja
lrUzgYcrx2srJerCdylyclocuncebmpEb1GqCsBEKrvdVa8xKS(6cmqcJWT)kmGqzmAC8jswKcPHSISI
SVnVOqtUUIded8dPbB8N1Gd5Eq17KgdUyxaSflcPineto2bRvceXsCjsxo6wWdHCKQ7vYXv6vMaj4Wcr
cA7bbsj(MaPIjgqD1uCmHumrWlO6X8XHEI4BQ9jm0noTk2AcocJLYcRZWqtwlixleK9KnobuNlhxc5rz
IMbJrsXGrm4vorYM(8KYZi9YKkWt2HfSCQzsAkJr28iTbYNIjRBseYnOkwDglYLGYvbClluYi7uK2exF
nkhkdxLmMMgWSGpDLKsuGXt2uYcswnBjIxdfJCmBKeiDOuZgOY6Pch8mutadlsdaSKMTKlKvR6L3)4qf
Dekhbuxivxxye)rap5EfrIiLLbplzhaTowGdGYb)l8UCJfiJskaAfpwVnmwqaODDXGrDxlCSwbIrzHiO
aXmGGJ3wEqylaMSaTeH2GOmolubPcHwGwlwksDKlbybNRJIC2el2LMgBqcY1yDsoBK3yrCqgQ5bqvZWK
OVLO61tJ5ldijw3jk3seVNY2rtERQDoIGvDSG84ZYacY5ACEXtaJHALFruBfX51WSjXGRDXelgvYijGw
23exswofBPmwPmp5O1OiLMWLPQLBXDrdiL2kbk1h)481yijjHHAgY12(f3iKUTiHcJwqYBAb9Rwm20GT
LDJJno22Gzcza741owqrHBuvETcnWuZILU4WexnX6IyFOHjSAaIQBiVwjDBcxm7uVo88cSSEunfLGmAi
tBbJZvBuAQcZwQOy1Bh5UyiNaFKNhigFvuJfGiXgJOQBjEd8xekzWD5TjR15wmVMpOv7idx9huAjBr4p
XZ3vt7ZG2nzYH8WQtZvi7rNU4nTG325s1mSvZEpUzlYDTBOPirsj39EnHyZsmr43EKWh51YMHxCdeO8(
HLqqYNMGichqbSfTZ22HxfuAPpKrYbT5f2djJHeIxqhQXsYQ1Gu1UwxnAfXrdQynIwx02FC8jcOs(2R6
NIcjVR(rzd0zvu6xwjNUPqQEnBrgxqgTuKFnn4cWaYKju00brUm4cfdYATcksP3lYngX6OLbx3qBAKrH
b1PAjt2Ssa(X5lYYCeoO8bl6JedEHa57(0kanvDQynm01KkEiDvKMcjRHh6rjBCfhw3aQ(XcuLnKlhz8
J8iObbdIwQ4jjg17OG4WbveexaQ0yqzEshXR8NrUKLbQIguWJM1rlWNw)2HBCqYctGfxCl0wO0EHWmfh
9hqRKphgTG2AbkK1IwOGWObaMrR25(aldQoG5vwgZVy)1XOGeYfiJO6xrTIbTTq0UuvmAPOUrpYuHHf6
1yA5yiAbLAWcqHCzPIXCJ1kAMuDqWnhDOP0ybPbWwCeWoQM0BRHY8eX81kZTKBUoNH8xAGFSaYfZynAs
tgudSQeWAUWHlfcewPKicfFu5U01)0hq2KKkqgzWXFghFIS19ODnKQFuRoXH2S3QzbrbPSIgIorLRKrN
LlJ7sZIyZueSsEH7hKTjzq1jbsFf9cVvjNWTjprOFm(KQW2Un4(jG(r38zfgNvCa1HKvdr2FGdnEumGE
kKdUWI0heiWTxuCSZbt0qeIKVsjtALnzGmiqSaK0wfD5MBKieIMkC6rjR25f85ear5gM86nWqEALTxXL
kq8xVnoOjnZd10K4LOkcQKz3ijdelMkPcIvkFKIsOIJmwQcYlJ(fz8OHsmsls1q7HBOZlfXfHFAUFpJC
vqIEmJc(z1AYzLs4iNyalqkHajwUMNxfLVZYx9QWOkk1GXWHd7LsYeghFmIgYhl1IchvNkIgpt2SEu43
4YwOOGIHCSAxKBp49ubCcxMYY1ceg5JZUnrANzj3Sqqvci2j6XHxl6Kbj84KmJ2UJuFOAqkOmiw0J08m
QV2iUTacrqcWmuLZpnUqFY2v1hr3uK3NuG9DHl31QSyUyebrPkVQAooUWcDurgtXFWcAp3fCMAggfCJ9
TyoqFjPPovheAb99HOyTrfusyleOiZpN(IhOOl4sN48r1Y8cOFsbCfbnCToaGwCOpPP5Hy8Kbru1oWDO
ekvnoHgmMjB4Uq1Cz(tqzM1I6eb4hBUwgynCitj2OX11o4qkQ22xPmczXA0I9g7zeYx(QL6Zt6ua)yun
paANuzRyKofvrXcuTmwQmk3vbKoKxVEypAgEJ(W842Hz3P1bqf5Q3bhAowfseaSxmRCQC6Z9rP8f1xtq
wYCRvnxyqHwawRE3AjywgrrBwKjc7yeMAo84rWvwWOj8qs(DWnoyHfvRchK9tfQ3n9Of85oa4sSK5XJQ
tGkCUqAhYNuMdjTCaenMxQqquvxOgISErbOuSQjP3kLhUMy)r9Pz)rDWemwX)CIQ)QlcyFedrufMtf0O
t2rDC44zrT3WYYQAUSokYHR6bZHblcaA0OcK0A4pkHTJ7CZZxOfsYJmxGPTXmQKi4uRC9cPiRurjHl(x
aa3)czxrw3CawPQ0emYOOtGzygL9Hh6jta93)zOrHO3BS(kAgeRWkSyRZVOcByMvR4H6qsfuopzhaf(a
UvZanKqvw)YwEIKmzqn85kEQ5keLq0rGjXqwBtPEhcm9JE9Gx4AVbscLWXifUgPCkLN1FNR8yeWftSkN
lKI8WXvnIbJWXdjFHLxlhDrtGtkazDK1GCo9omAP2dDbN(QxSAHwS)snB9Qw7HdT9IYkry5KT9YUEa9d
hIIYjcImnq1e8ZnWONUqjCl38dev005ahIenOV)fkCh(cxiSN48OZuKadkVvQCnr2zdHrGBvIOTVGyPW
txbo75whMvYqs(UPAUGJwhiQqEzTaJ2AHXHbHaO4TLXvAGRDIFSkIVrtqtSWI3ihZFqz2KNr0vxYNck2
k7qxzYuQIHXsfzsWRL1uIi0ErFWhT8z6ha3e)oKOclr6R8RNsmU1xtTxV48wWEX9Nfow5KF1Ct1mf9A7
R5hDO6Ig4gzVGyToN6LdpANwZVLKClAAvXXRMXRT2IZ3DOMP3lubrsJzPAhw2jEq4xi1WjnUvFVMEePW
PTBYPxWe)YXSYNC5sDq51obqcjCP28Xlc0cIE3GQWCkjTiHSMfol6L9Z3yGvpvKDqICZ3hLzPIpCJvF1
bUiE2hTUrnC8j2jzj1EBWOVsvIPappJxHvRYr4KHqgb(87fd(a1lqI7MvubRMknzgisAtrFXxCdvHdfd
URm(LNmMhVHndsgOfqSn4PRwD4X(l69sN8E5)Un3V50k(DW)Qdt7wF(6V(NFyE9M(BM)Vm9rAtx6)hw7
F(lIE(rT)4H2Jn)n7VHF20N(8pr)pSD62NF30UBLtUxG2BVA1BE3LxT6)GpbP5F)DJ1c(TCmc8V)XtN2
V7lVHrq8M))U5Ppn)dZ3T5MTZNV4fBo2EJYNV()E3E(XBtO4F78fpF)dp92Pd3oF6433M(IV8Hh2(0By
gY5lAKgTJ73V(pC8UnF40Z2T)4JV)(zAdRF2h2(e)7UZFJO03D5Zo))(YV7V8)3wwFy6297oSz9VAJV4
nF5R(tx(MV5fFZLV6ZbbD)0o(Iv)4389NVy19thojy838sA1ds681NV(F581R2U)N4Fzf2U9zT339Mtt
NMPp)R8Bt)LB3C7D8VbcVA7M18OVC70d9TU6H5TBpFnPQrdtrNs8p4Bb2ZFW26z(JehNqpS)4mHopD(6
x0OVZx)6TpEpdwsf4dZtNApv9vF8P723Fr6NM778DhNjqfz4v4iy9tOyTkG)U2VquhMpU)a9Z1QqC(tm
zS5dNVwi8(ouP8fF9LV48fTFTQoFXvNK)E1)3d

**Comment by mbattersby** [comment]
Should be fixed in 10.0.7, thanks.
