### ISSUE TITLE
Batch disable mounts

### ISSUE THREAD

**Issue by rursache** [xod-wow/LiteMount#124]
Hello, 

I just discovered this addon. I have 500+ mounts but i only want to use one flying, one ground, one aquatic and one DF. 
Currently it seems i need to uncheck all but those mounts to get what i want?
Is there a "unselect all" option so i can manually pick the 4 mounts i want?

Thanks!

**Comment by azuraji** [comment]
At the very top of the Priority column you select 0 to override all mounts, then you can select the mounts you actually want individually.

![image](https://user-images.githubusercontent.com/72912613/206563647-541386ef-11b4-45c6-b166-6a68e07491ad.png)

**Comment by rursache** [comment]
Oh, got it. A bit confusing but i guess it makes sense?
Thanks!
