### ISSUE TITLE
Short hangup on multiple triggers of the hotkey per second

### ISSUE THREAD

**Issue by FREEZEball** [xod-wow/LiteMount#125]
Small bug or even just an annoyance, but my mount keybind ("shift+scrollwheel up/down") and my mouse that allows for no-inertia wheel scroll (Logitech MX Master 3) trigger the mount action multiple times per second, which hangs WoW for whatever time the wheel is rolled for. Maybe it is possible add "a cooldown" for triggers?

If it matters, I have precasting Water Walking in my Advanced Options 
```
LeaveVehicle
Dismount [nofalling]
PreCast "/*Water Walking name in my localisation here*/"
CopyTargetsMount
ApplyRules
//the rest is default
```

**Comment by FREEZEball** [comment]
Quick add, it also shifts me in then out of Travel Form on druids, I'd say if I scroll for more than 0.5 sec. Default Blizz button bind (or rather, Bartender bind) would only shift me out with longer scroll (I think it is more than 1.5 sec - which is it never did before I started testing LiteMount). Maybe an option to limit amount of triggers on keybind to user set limitation could help my (admittedly, very specific) case.

**Comment by mbattersby** [comment]
Yeah don't do that.

Sorry, hammering the activation is not something I have any interest in supporting.
