### ISSUE TITLE
Ruby Life Pools cant Mount

### ISSUE THREAD

**Issue by AgentHawk** [xod-wow/LiteMount#128]
Hey

i like your addon but i have the problem in Ruby. I think he trys to Mount the dragon but its not allowed...so a litte bit strange

**Comment by mbattersby** [comment]
Can you please reproduce the problem then submit the bug report data:

https://github.com/xod-wow/LiteMount/wiki/Report-Bug

Thanks.

**Comment by mbattersby** [comment]
I tried out Ruby Life Pools, it's working fine for me.

**Comment by mbattersby** [comment]
Works for me, no response. Closing.
