### ISSUE TITLE
Only ground mounts summoned in Nokhud Offensive

### ISSUE THREAD

**Issue by azuraji** [xod-wow/LiteMount#132]
In the Nokhud Offensive dungeon, I only want Dragonriding mounts to be summoned but instead only ground mounts are summoned. Is there some way to implement a rule to override this behavior?

**Comment by mbattersby** [comment]
Summoning Dragonriding mounts in Nokhud is the default. I use it almost every day so it's definitely working.

I think you have probably added a rule or changed the priorities to disable it. You'll need to find what it is and remove it. You can try starting with a new profile if you can't figure out anything else.

**Comment by mbattersby** [comment]
Closing due to no response.

**Comment by azuraji** [comment]
Apologies for the late reply. Unfortunately it didn't help. Also I'm having the same issue in the zone **The Primalist Future**. Only ground mounts are summoned, although Dragonriding is allowed.

**Comment by mbattersby** [comment]
I have no idea what could be causing your issue.

Please confirm that it happens with LiteMount as the only addon, and paste the bug report.

https://github.com/xod-wow/LiteMount/wiki/Report-Bug

**Comment by mbattersby** [comment]
Closing due to no information.
