### ISSUE TITLE
Dragonriding mounts resetting to default customization

### ISSUE THREAD

**Issue by stuffs07** [xod-wow/LiteMount#133]
When I customize one of my dragonriding mounts only one stays with the accepted customization all others revert back to the original/basic mog. (ex. when i changed renewed proto and highland to yellow skins, the renewed stays yellow and the highland goes back to blue/basic mog)

**Comment by mbattersby** [comment]
LiteMount doesn't (at least intentionally or as far as I know) touch any of the Dragonriding stuff.

I'm not sure what's causing your issue but I don't think it's LiteMount. Can you test without any addons and then with just LiteMount to see if the behaviour is caused by LiteMount? Thanks.

**Comment by mbattersby** [comment]
Closing, not LiteMount related as far as I know.
