### ISSUE TITLE
Feature Request: use gliders (or similar items) in bags when falling and trying to mount-up

### ISSUE THREAD

**Issue by Rezy942** [xod-wow/LiteMount#135]
Hello,

I see in the addon guide there is an option to use certain gliders
![image](https://user-images.githubusercontent.com/122007087/217986959-1ffddfee-088a-4cbc-9cfa-1a0688e138ef.png)

I just tried this in-game, and addon would not use my "Goblin Glider Kit" when I was falling
Is this possible to implement? For this glider and any other similar ones in game.

Would be neat not having to use a keybind just for a glider... :')
ty for amazing addon!

p.s. maybe there is a way to do it via coding or macros etc but im not very tech savvy, and this kind of thing would be neat to add as a default feature when people load up the addon imo :)

**Comment by mbattersby** [comment]
Hi Rezy942,

I had this as a default once, but it made a lot of people very angry to automatically consume an item (rather than just causing a cooldown on an item), so I'm afraid I can't make it the default.

You can add it yourself very easily by using the Advanced Options if you want to.  Normally it looks like this:

```
LeaveVehicle
Dismount [nofalling]
CopyTargetsMount
ApplyRules
Limit [mod:shift,nosubmerged,flyable] RUN,~FLY
Limit [mod:shift,nosubmerged,dragonridable] RUN,~DRAGONRIDING
Limit [mod:shift,submerged] -SWIM
SmartMount
IF [falling]
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  # Last resort dismount even if falling
  Dismount
END
Macro
```

And you would need to add a line for the goblin glider so it looks like this:

```
LeaveVehicle
Dismount [nofalling]
CopyTargetsMount
ApplyRules
Limit [mod:shift,nosubmerged,flyable] RUN,~FLY
Limit [mod:shift,nosubmerged,dragonridable] RUN,~DRAGONRIDING
Limit [mod:shift,submerged] -SWIM
SmartMount
IF [falling]
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  Use Goblin Glider Kit
  # Last resort dismount even if falling
  Dismount
END
Macro
```

**Comment by Rezy942** [comment]
Ah, makes sense about complainers. They could just as easily remove that line ;)
Thank you for the explanation, I will do this!! Looks easy enough

**Comment by mbattersby** [comment]
It's true. Afraid to say I usually pick the option that gives me the least grief. :)
