### ISSUE TITLE
Can't use the LiteMount hotkey to dismount dragonriding when I'm in combat.

### ISSUE THREAD

**Issue by gotex007** [xod-wow/LiteMount#139]
If I get into combat I can't use the LiteMount hotkey to dismount my dragon. It's been like this the whole expansion and I'm really hoping it can be fixed.

**Comment by mbattersby** [comment]
It's working fine for me. You probably have a custom combat macro that you need to fix or disable.

![image](https://user-images.githubusercontent.com/1300207/221742099-31ed0827-6fbb-42d7-83a5-a6ad99ccdf25.png)

**Comment by gotex007** [comment]
Huh. You're right. I guess it just was never an issue prior to dragonriding because I could just use my normal bar and that would dismount me. My bad.
