### ISSUE TITLE
BFA ground mounts

### ISSUE THREAD

**Issue by RetroFrito** [xod-wow/LiteMount#140]
What happens? Ground mounts are activated in BFA areas

What did you expect to happen instead? Only flying mounts

Did it work in a previous version of LiteMount? If so, what was the last version that worked? Addon version did not change

Side note: Prior to today's patch, I had not unlocked flight in the BFA zones. Today it was given to me with the new patch, and ground mounts are summoned along with flying mounts.

Please do not modify anything below this line.

--- General ---

date: Tue Mar 21 21:43:42 2023
build: 10.0.7 | 48676 | Mar 20 2023 | 100007
version: 10.0.11
locale: enUS
current profile: Default

--- Player ---

name: Fritobandito-AeriePeak
class: HUNTER
level: 65
race: Worgen
faction: Alliance
spec: 1 253 Beast Mastery

--- Location ---

map: Trueshot Lodge (739)
mapPath: Trueshot Lodge (739) -> Highmountain (650) -> Broken Isles (619) -> Azeroth (947) -> Cosmic (946)
instance: Broken Isles (1220)
zoneText: Trueshot Lodge
subZoneText: 
IsFlyableArea(): true

--- Debugging Output ---

Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 17 rules for button 1
Dispatching rule Mount [class:HUNTER] Hunter
 - filters: Hunter
 - setting action to mount Sky Golem
 - found matching rule 15
PreClick ok time 23.550300002098
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 17 rules for button 1
Dispatching rule Mount [class:HUNTER] Hunter
 - filters: Hunter
 - setting action to mount Sky Golem
 - found matching rule 15
PreClick ok time 24.299499988556
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event PLAYER_TALENT_UPDATE
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event BAG_UPDATE_DELAYED
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event PLAYER_TALENT_UPDATE
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event BAG_UPDATE_DELAYED
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event PLAYER_TALENT_UPDATE
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event BAG_UPDATE_DELAYED
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 17 rules for button 1
Dispatching rule LimitExclude [flyable] RUN
 - new filter: -RUN
Dispatching rule Mount [class:HUNTER] Hunter
 - filters: -RUN Hunter
 - setting action to mount Turbo-Charged Flying Machine
 - found matching rule 15
PreClick ok time 24.611999988556
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.

--- Options DB ---

nY1wts1ns6FlZt7dR3y19l8ghd2GbAi6UTDS7gtfCO7dDxlvxfB1vpZW8a)23mLYVuhWESzc7HdsPsLz
Q8Uu5n2nxU5IRUD(i)NNVC8WUD3F8WNUA5ZV9)4ZV9Xlh3sF9ML5p0G7W(3V9MFz549BpSFZz1nN2CXp
9W9N2U)DZB3T8PV118JBV5MLtFZG)I)(29F4txt)FFRR4IB3UB3YU5BU9BDfpBz3UdxF4MB(MPQF6HR)
0v3E4JFRW)dmtWYQBwo(nVMJBpD4DZ7VM(JV118FnF32BMpn)Tc)tw(7F66LR2E38PV5d9xTCA5BDdiW
VzhXe745V)H7U7W(V)Wd7pDp93pZ5Do7MZO)jLmLm9f9VoxM)dAqFOuRTVCgJnhBFgSrB)RsjhOP90FX
48H0MZY06I1yIgL(BjFYZ4JM35RvxBr1s2XyNrAnyRzMmpZ6d(i9NvcZ(AXyBllxiCh5nZxcUqBmxS6m
DuLmghnzM3PAYl7u2XiXXdwcHg2ZeHy6RM28m9PVHuJLPpFBv2CQHugb2KYPyWA133uIusH(NUyX46F6
t1q022mI)Z9nRTbfcpmOKqPtwHsJQBSL1BzbmtC0bq1iSL1w6yTMR0xmNBn5gXedDacD6oBtGciPg)fl
at5uJBAuEiyiCq)towZTZk5KTFgtQamYy2nBeM1wCmhWKE1N7hXXAkYcoEJj5cln4Lv82MYINjR2zuX2
ORcRpu4)nxcMgkswNR2KrSKL1my8gY8G(CxCWBSL)7HSiokKoOPleyrltYeSbgfTtRgkI(UOJeNPo1qA
urMD5925J2oj4mwttKYJ6QEMaToOH6BktfFniNFXalZdDPRV9fVVHUSL4NAxbJ1p4ZmA1zxHL3n5u1B7
N58xDdPQZ57k3mh4z2JMUyJSqGrCWxzEQjhC(sruaTgdZVeW0HyuS6cUQfkZKARRlWykSR)WgibrCy8M
sFJt5qkbfudBwY0aBceBNOnZPiRRvAIUCk01HtHyZUUzT01Ei1YsTJl6i31rB1KCwzW2jUywv7MOSBdB
xcY(F8SqHWBSzwvyZ(yYcYUAtEEzSq054dZAxCkMOzyv6nmM49TsAVTdWt)ooeVy7(7pnV)QLM)plfDB
E327U(WXnNz2CXtNV)0YX9F(TVGItC9H7UNXi5n7IFE31BPWgxC1Y(5JBpWCwoqbioC8gY97H3ZEIpSN
bNTsV4YBPrp7WhU9HR)8BF97F)Y(73(3wy2Wqi7P3TCCEhnZtoUmFxZp(Zo841yN4uBBtF4o(aN2PNmF
8d3D4arA)W82JlSKHCUrB0Xd3)DF(TTnCA32BU90cH4xsXSUV5vIdWS8XJpql8YJZ3X(cD0YoSJaF(48
1noXkJ8K5BybHnKizX0XdFyHw2f3E44YxW6XAqyXx96lF2tp)LV(jp9V8xylDAzVH2AcUzco210fxUS7
WnhF4(p)2Z3((tFjEmF92q6CmXC2HJNU94YEM6yTIl(VzKUB(y7GMa4Ix9lKeF3UT8j5NF7poF8427zH
Zlx(BleJWE6Tu8SlE2mLqv)a61h3EZ29ZNAkcwlPC)NIgwd1XYRxqIQ)5TZ0mFpfA)Qd39U7)9o2SbY3
Yf)WYU7p8WoE2DehejV7x86hoTBUXpbv49lBpSB5eaJmARYe)aV3pB(osnHvOiD6lo)H3rzg9YTVNd2F
4WowtJ9BlhdZ0wE64brxAz(4jrP8FsPuE62gWwoXVD7xM7K(VYQU7zOPKCMV5lpHDPiH659Zml)tpS)M
D08pFpTf8KUvhBp)(DKPeFm5jXeZ1xU9489njC9pxc3mTn0b1zl7oDlV77)3UN1F3E83vatoziyN)N)V
0XWXgBre63F78DVJZQJzzH7P1E(YhztLRzNPuWUlE9hjZo(4)rKeBHs6(gwtiW2it7MV6duAU303AAJk
SjGCmr5)D18CF0aND7XT7fR(tmexC6Wr2oTTKL7(4U1t(tZxZGSC8Jl7pXIf2)WtooVS)qJbOGf)w3on
6N8ADhLh9wwCD(Y1hE4DN(DLjrkUp5FGmp4tRFE)1lhFhLo9NAwGe9onF6eiPN(poqwN90c)4XdVNkB4
flF6()0QpiViVF(HD)zfCma7Fvngdi(dkRya0FqLedG(dkEynD)VOEHbi)HLiScS)OQcgG9VSqGbi)H5
(pa73pDFD(Xrz7CedtFEhNO)BiTeII3kr8OmHD989Oudtrj6mpApPEo2QgBFK)RPi5zIK27rVd1bOsnd
5GrsvMII3YrJGSunfVmVrkFObzq30EklwFYM6q6OuIJsIW2u25gaegJ2HLSmlojPNuOOiTtEu6)oHMr(
WmGvFncgjAuAswEQutcXxIfz1uQtDoQu4ar9fBA1zaiRGJBjAZFg9wJGkkdz3yqHoLAhWODeuOKALbRg
R3n(0duvqfz9ugX8IWjq5J1rqqKIUAkxkGJfzdZ7DWOeDQrPyIGZ7fKtfmjkbevkBolhCQCOdiLwSTpw
i13euqbssJt2toqOI4qIHLOb7knQVVKQ37sJbTkPKvMVyhZ7gJ2)Kk1Pk6B9A)At7tGvLm7TTdQKFike
LmjFESkNY1csPJmrQKsTkDSAzz8AsbO5sCSrmsK8xzijdpitPOFImLsBgvas4uSMszPyxwZuM2rQdIwI
umPTvJRirj9rkR8oK5yXRN4Ou)qfIrAAHKqHXniJc2ZQSJzDXRHjl9eOrrIvBOOYdJvDAeIXbdRKbjB6
FgCWeJSKDIYC7Z0aGoLgfgkM77n3Abbl1cjK6tsh69VsqrjPU4cb4xJLeoWPwHNL6ZzcOsSFu56OUFPb
KcdwP6NYkxpyq7qFwyf(SF1GzWQf0kdP9lY8DuvPcHm62poYsjDnfLXRkDOkZIVrPaAEmQKyzqxMC6eu
KdxNQkgpDESirhluv30oRioL67fMuWE1KTdCA7RzDtuCGoLQ1e6qO9Opj(zzcr4xYZFiVA08aw3yuW9u
D4IaLC4lhcApfOitJdwH6RfqYuPvMqAqZrf75GYOI1q1aJjc0iCKrLpJqcbIMfMMuu96M2zesvjchPzz
mYUYgfbo5n3ngu4yA2acCzHCIOjr)nocMYXiqeuhINWmFwPJb6fPydYoDgRv1aLgu4iQIFXk0ZfNNvrc
mGJ(vnimmGe5kyDf1(lpIL7HAeVxQzUOrXnIQmGeYXkCitRzf9JmiicWkmDiJ418Gdz(G)encsDtYKOb
POBwQd5iKEwOTjDjJXpRKGvZNtQWPVpO7NDKlnSHG0iYPrRSAZBHelI0giCghuh8JzjnBH7CeTm4j5tP
tTyW8au4s0eKSv8KLHq2C5SihgIf087S1(8CJMG9E0lDQIcxkELAqMgZp4ByrXFQXbHjb5dXP7A1V6Oe
HQ4(2jwVoKTg5RCKqGxuQ0o81zaXHuqZwINw4QHjDB9Ijnf6xcwLIb4CIxvzSQ04ZSkwKfzmI)Dl5R2O
Op7gFQzZbFhSHS8zjO63XXXACCSn6uFuTpgDTUHQvlsuwZWJfpOi0yXd8CAdAOkYjnIewvxEsxhBJs5y
k6cvBfPTtQ4MXQIdqJkbMhdkAOvr(0wEym9kirA7ynKzhmaO)hIp7u348AQ6wkhzrc79frhZiyiV8XgH
8fJfJe)L7Ejc9WWkBafyTo2lX)c3uvrPlHRpPbzDaPE(dRogRi5qVworUFvkyviH2ADCQgmdwaXpIuUZ
(XYe16e5LzCwiMGwkuvnoq2kHWQTaL0GJawgVIUq8pYyz16l66HtIK1xxrbIdPaLFryGHYy044tenMIS
HeMS4Ip45ffAY1vCqyqEqzGahX1Gt7nUfSip4Qvb0w0iIeaoJUTdrRegcTr3YTU2TsgapkuXZsIWe9jQ
jmMGxkeiOTgX3ixNTGPIbX7jkjdbRjczHNV8m3adPXNWq340sHRPeYKTGDJVXO10WqPwlWxRMKDLn2mu
3mhHc5BzIMHmss6GPr4voLK0B07COPRN0Z(KDyml7AMoyLXiZFK)a5EXK1fjN3YDsyBNXiNI(nPXFzSq
Dd3DfVpu56O6PmCAYeAAqOf8PRmOo5eGmUW8XOMihj1HksoMnsEMouVAdvzDxHREssHB9HSIewHs(dL(
yxFNksKi(IVeTfkzburjjicJ4pc6jhTiseP2yv(lzhivm4Zo9(vi6dEA4v5gyqgLo)HPx16rAtwuqVCx
zyrrDrIhw(wJZJ5hcy)yW8GRwHkekoLwXwIBF5scBMGf7yrjTO3aYAGltyLyRtGCMeRwfsWKsHqiRmLS
JgIa9LI5f5yHmDZd8RgMje2MSffB0ev8FAaAzGu1wXHDLsMcraSXQ2BkcT1ba5XNIicxl8g9(6T6113i
wBrZRWPHGtIfi5(o4xnAxyi3IjiWOIPYaszEQgEJstWhK3u160420bAs7fbLmKFS)5XQqEF4WUTErwrA
7YXwy0JtMuwX(QnKnnKAz3yBJJLnKLzuVrXaBhgGII34qDiRQ25vGUAZeUjwxfxeDCH1cqeFd5hlPltK
IKVhXnrBEHeZjKCMZ6rjx(SjRPKztA6heU8JLH4EPS6kK8LmoYGiLHvwgd6k8oupli2TXiMcwsIvWjvj
dzU3vLSs4e0hZVMCrerp6ce3mgKurKOsjesqBIn54wvkv39USxYgVTOvs8USRMHzD27bhshD(bGfSr5r
stM1uc0prkIK7nBE1MkUfIaveXjoGiQa1AtH4fD22YdkLaD6msNGrKajDAJZkE(osJLeA2ojO1ELxnbO
ghnWvDencPnFySkHNkMmkrG(0ReaI6gO9QOSVajNFQWPEn9sgRieyWH6LBpSgHcmKFzn)rTzh1Qf2YmS
wbz1Oal)0leNPgCjhKDokrHeMOWwYrN6kXQw6msLZYCeUT8blKXYt7W2cCvKglqjjuHwN21hwxtmdjDv
KndDwd32uCpuJjvJI1nWQFaGQSOD7b1iqbivbebP4Ejg1BgHKWb9iarJC8TxygJkaqkjEvanY(Smiv0r
dE0SoQg4Jk3dhH9xHbdlxemuxOeLXPjLHVvzg5RavzVibOmhSGeYAzou8A0NaZOV(C7LLbv3YmKLX8yr
1H7g0wtYkPGJiQGxT5aABKiubvmguuOjzMPY4aApBA9yiecLeXkuHO46dHRbROzsfobVC0MMsdasdKTA
lGDuf(Y5JgTatTuE(rd1fmK7sdMoGu2K3cfJj6urocvDawXf(BP4Iszl8nFGdE8CT2Opth(t5Dx1GLeB
ief3(02N419SPxnZQqRXbOYNKb5OWMKK9bBCBhGIuf9ARIi3eArsf0xDY)KhsEQOeWo8Nc1GhH1MEYSQ
LUzLYdYGHY7dD8tEzwy044Zo5qHaZiYyoGMer2mO5(u0zu8f9jYlRDfv40XfGTIxBXohAq(0RzM1q7q)
cHSt8TUk7a5gfftIU7znERgqZpS1SQZ9mu)QuUVcMOIkLtFw0Q6S4k4i3PA6OoO9XnhexFexNdSvir)Q
u6DdQUZHXsTapZSCzmpczgW9hXXzcdJvi3ikWoYPwsdoeq)Pz7heOIoqfh(CphL0mDQba3qeb)bcRqSv
0lBMQemOP0IBaJY0VMgQY4YhPmM1APOqTiL8CbH8cGwSuD7sQcezPPLrvOa9f9DP2U0crCY(l7JY9ntt
T0Rg(6197QzCddCgROUpJhHQ1Rrcpbso2ufnPGkpSQXrdAzBv0Ke6tuZqtDRt1YlnSnyE9DpHPDJNDBq
urkzCJsuLyi5nQmPcQFJ1aG1RhxaaRUIQlsijDgPIKMRUqJSO3LrutfJKZOh7C5f6xG8jnCuPgDMGcHY
WdoN(MWEu4WQMYlCFX2TsUd0XiARjFzFIwjHiKkxqVmc2yrwfXZAW)KbbwyLrCaPTCJs6YHalJ7yKuld
OJybChhnIvCk6hxHjbOv3lTrEJgNmEJ2nx0iC1i7aYTnYFIjXo7WxJPmibGEFc6BqNT3r4c9yLJT6aTQ
nEIwJmpN)h8y6qwHnpMiCdLbCFd4mTqKRmAYCdRDq7pmyEAQ6AKGptPLbKJtBOSvxDB2JsrWdOLpm7ZZ
EwRdCIeDDWDSttdK5dnjghszBOkkpL5M0HkVs(K0jqyZXf1YQvUrUx6BhH9Co2m5O0HhrtWyRoLuHKMs
Ve3Sp7pVVbSXQO3ZVTL8aPcbWLelUvOQ(ejznGgN1WQSRiFssrcQ6bTqsgoXuHQcezyWQCc5fnRROVpF
e1sBlJR0iTkDEOeNck9srOZdExoqPiTIJq8k7BmCsVZtYnQWq2XJNUuvXOhTNQHvyO70E1QVsF2muCos
PviQBYdYVnnPVb9aJzOpNq6i(Qbhivhk3GLtIkfL)xv1D1BxUcpcSZt4N1Pp6bYrfknt(1d04ApCu28E
IST1Ru3Z32PyMxg9Ohpkc(XTGSLkLrpL1NIb3MjeXsFztw)6w1I8o4RT1kiaPTZxtcuo5xbvhu5hKGWk
yRibaAjfzrjvlWwes4jU6xXlIfXukAerdYOT6Wv7V63wdX6yWi4ys3WpkMlSQcmuAnN7szqNzLIqqEYi
hNoumLKURAXdvTuihAnh3Kci9KFEm8NYVtfB7EwLKgXV1c99(3wdvcVkrdiYtgevJshNtR64DA4ngLNq
1NG0iizpAHM8BQHby8BsIK5WOKrRyuA0oQqIvegLI4dPsvdUgz5sFuwNcIv9NFrdRIVTXp6NgSYYQuqe
XQbQ889sP6jIgV8BKPjFS4TcYciyis(frOvYJcsEOwuV4MrlTDOJ0T3aJCSxIi2oRt6wLOJ41icDbM81
ZLShT2G7Ys)tQy4Wi5NYOkiZips9UKgxmMx7)U8dGPHvQAFnpb4FJRpCyjHQsc43Ff398KkHWJLWp64M
3IdZqcpk1wfg9vrIFuvuexgy7fXjQkKUoA4TxTvipjstwk6dcQ1rEnhbyQrIe9kkT4Lw0qkeFj8IDyK2
3FBj51wpgIRuas6GRYs3cEQI630F6l0Hhu(Cr84v46zfrEwQyIfniVpdEWUTMrcxBE88VS4fB2kUeXY1
77s(92XyIBaFurAudOO2UoKaiRpn8CQ3XhNyYiziTrpKlT(Y4sVAFDAZfhFyh(560)n78YT3T90t)hxT
7b(T1))8(DFA(D7w(RF(TN)ZNrBZMlEf)WNPzUB(JpIsG67U)H3D3YXBwUMG5UtpQvuH)lbJQ3o(DcM(
U)V3F1JIumZKaphAkmGh)gIEeLsJabF8ghqC1U57V)r)6Jp)8N)6Zjq(v(h(a)G)tFnmp5PV61N9SF(S
lFkd3twU7W(BP55F6h5Fh89Yx)9VOJVDhU6d8piSVcMx94F8P)v(NeYnlTFVtF9U94lF2lo75)4ZUSTB
ZNU9d75F1qKC181aF(R)XFMX15hU5b(xCK93SxV(mMyE1H9FGph)6PV4zp(vp(S)k)B7z(Uz(xDJ)Rb5
np(Lp(jpNH5nZ7MVEldu43q0N)Zp)jm5E8HTTFPmFnaQ47zIKZ(NiMFjj7(p)czT93iSFZ5p)PxWsP3C
C7Y9NKFkThp8WhLNz)q2X)sA7VF2j0L4j8cUNqgft416oHYEN2GhtZeY(DcTAGNR)(7N49fshw)V3WPj
C1Dt4D6oTrstCAJeNVnsSJ)(lpRdJRT8(fjpH43tOC1j8m0M0ODm10RQOr889VYd1B1xBY27LEQ)J)UD
yZuA)T2pHabt4voYJ0722eUESgsAo55j7Vi(1YGvsQEIhnWAxO5AzwV5In6OPvYurppMPni3bwyNDyh7
yV)2T)n8KpaWQnYVN880gj7nEUEQrt4n21qrRo3VGJK3(AJW6MtxUP9(4)cYsEpetWnFta0UP2juDQav
wiSwU2tRvO6TbAAJKhnGp3Hk1Le9FXatOxiD5f7X4Y1sG(1WoT(isPg9GupnKI(Nq6knWBfamHwgnT(O
TFhnt4XzXyO3q6PMwl)WqNghORuyuLn5YFNwPPX)OAAEjUCftQAFsMOFbJmKM9NtgdFVRvtRfWYR6IP7
2JZFcDhCAdU4O2CbvFxyeVxOlecGfX97pVVN5Uny7zqdAu28w(NtBKxxEFNcDHw)PVYBvV2VjuU00gCL
19VkD4T9NAhts9Fap8x9h9(040K90092D5g5nP3ewCYFn2Z0fF9FkdtiLaigtG37geC7sM2i)mGMwjG7
xrrB7ep2D7u(vunHsONWJly6RTc64ONMPWAYKgr60F87t4fGWJ0FkODnKvo(VCTvNurX0ALt4YwUIJg)
4QQIBx42VjKj8w7)cPS8mJGoqlSD7)0lWV4MVaX6E1sC9lWRIe51toT2Ar3u1oT)CNM6XSoS76Fy38nF
)TZ7VPNhv)vQrbXU4xF(R2CX)EhU3)Ta0V9hu9vh(4NUCMsU609TaOBE3MEWYn))

**Comment by HyperMan19680** [comment]
I have the same issue, and I think its cause the addon has not been updated yet to reflect this change.

**Comment by mbattersby** [comment]
This is almost certainly due to the BfA flying unlock changes. With luck it is fixed in 10.0.12.

**Comment by mbattersby** [comment]
Thanks for letting me know.
