### ISSUE TITLE
[filter=] syntax no longer supported in action lists (was: Error messages in chatbox since last update (10.0.12))

### ISSUE THREAD

**Issue by sthdevilish** [xod-wow/LiteMount#141]
I'm getting these when mounting using the LiteMount keybind, no lua errors, just these error messages (they also appear on screen each time):

LiteMount: Bad condition 'filter=VASHJIR' in action list.
LiteMount: Bad condition 'filter=AQ' in action list.
LiteMount: Bad condition 'filter=NAGRAND' in action list.
LiteMount: Bad condition 'filter=SURAMAR' in action list.
LiteMount: Bad condition 'filter=230987' in action list.
LiteMount: Bad condition 'filter=230987' in action list.
LiteMount: Bad condition 'filter=MONK' in action list.
LiteMount: Bad condition 'filter=RUN' in action list.
LiteMount: Bad condition 'filter=WALK' in action list.
LiteMount: Bad condition 'filter=FLOAT' in action list.

**Comment by mbattersby** [comment]
Hi,

This was a deliberate change in 10.0.12, where a really old (pre-BfA I think) compatibility syntax` in action lists was removed to keep the number of things I have to maintain down.

To fix the problem you'll have to edit your advanced action lists and change to the "new" format for the relevant lines, which is to move the [filter=XXX] to just an XXX on the end.

E.g.,

> SmartMount [filter=NAZJATAR]
to
> SmartMount NAZJATAR

and
> SmartMount [filter=BIGMOUNTS][map:1234]
to
> SmartMount [map:1234]  BIGMOUNTS

**Comment by sthdevilish** [comment]
Thanks, this worked :) I am indeed using this addon from a long time. In fact I don't even remember why did I need these filters (some of them are propably obsolete now) :-D

Keep up the good work!

**Comment by mbattersby** [comment]
Thanks for the update, glad it's working!

I'll leave this open for a little while in case anyone else comes to say the same thing, and close it off later.

Happy adventuring, X.

**Comment by sthdevilish** [comment]
Actually it would be great if these settings were stored per account, not
per character, as I'm about to copy/paste it on every one of my 20
characters :-D Think I mentioned it a while ago.

śr., 29 mar 2023 o 14:17 mbattersby ***@***.***> napisał(a):

**Comment by mbattersby** [comment]
Which settings?

The action lists are part of the profile settings. They can't be shared any further, that's the point of the profiles to allow you to have different configurations.
