### ISSUE TITLE
Otto Mount Bug

### ISSUE THREAD

**Issue by Geminiocean** [xod-wow/LiteMount#142]
What happens?
When summoning Otto it auto triggers the Aquatic Shades toy which applies the  Cooler Than You buff. 

What did you expect to happen instead?
Otto should not be auto applying the buff or toy as he doensn't when summoned regularly.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
This is my first version if litemount.

Please do not modify anything below this line.

--- General ---

date: Sat Mar 25 19:36:46 2023
build: 10.0.7 | 48676 | Mar 20 2023 | 100007
version: 10.0.12
locale: enUS
current profile: Sryn

--- Player ---

name: Sryn-Windrunner
class: HUNTER
level: 70
race: Worgen
faction: Alliance
spec: 1 253 Beast Mastery

--- Location ---

map: The Azure Span (2024)
mapPath: The Azure Span (2024) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: 10.0 Dragon Isles (2444)
zoneText: The Azure Span
subZoneText: Iskaara
IsFlyableArea(): false

--- Debugging Output ---

VersionUpgrade: 4
VersionUpgrade: 5
VersionUpgrade: 6
VersionUpgrade: 7
 - checking profile: Default
 - checking profile: Sryn
VersionUpgrade: 8
 - checking profile: Default
 - checking profile: Sryn
VersionUpgrade: 9
 - checking profile: Default
 - checking profile: Sryn
Initializing LiteMount v10.0.12, debugging enabled.
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PostClick handler called on LM_B2 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PostClick handler called on LM_B3 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PostClick handler called on LM_B4 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 5.7419999837875
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)

--- Options DB ---

DYz3U6rUXv7BNeeKpu8NUj5X2XabgqiWYFjN1qYZOzgbOrkqsZb(eDTNQixRQOE7T2wJLMb7wS5pflwS
yrYNEFLU(RxV8h(Lx)r7NV8J)93)Lx9V)Lx9)823)JF83E)7FZm5F4dV)NE7p)F)Mp(P3(H3F9IX1N1S
(d)9p)lV91FF5wZ)p)Up83E97S3)PF7x)1p8()Wh(T3)5pP)7xuAN9w56fP(65UyfAL8HMS()LZ(qsxV
4WQPB1)lF77)0NF97)H3mRo56L)hV(tF(nFu7j)53((F(h)WV(PRxKpA6lsY)p5lV6V(lV5lV6p9Hp(3
E7p(JVrZ1F5nV(h(LV8Q)L)WV8239JF5vF4N(YRY1A9FvlL(dwQ)4hF9p)bn3)NF6DAdn7t)VF8d)0BF
3B(ZV5V)PVL2BM43uB9Y)4B(Px)BVBVYM1etwF8xn90)1hF7h(4B)8Bx9W0zrYv9N6)LRNhJ1JwQhZhl
JsQTsuAhPtKvPNZZhZJAASYqUKRJiRRelTQuwz9mvpsRCQdb9cEVKoICw9gTVQPYPkmRcDEkhRulPZgA
)zgQrQR8M6N98kVNN1UxPlXRCwYqM1oDvqghLXb7ihIltO4QzZje((rhLUvpx9OEVuqFRi9AnY5G94KG
mCuscQQQ(3iriNNdxpvZ92QU61gtunFl54XsK1L4xlJClEpuo1upVQGk0I5XzR3zpg6gRVVYw6CmoYOW
5sbvEU1GrGkLOXn9q21dRmEKQPvA1ZvJuBc(jQ1CUGbKJrodtN(HWwvtTSkYOuYNrIjxuAENVNI3NJux
pEmAdyVPd(cED5KD1YrnXr3XzjufWilpgWGCwQS3RrLQdzqRCE2R4jjLGDWzLwUApwWKeT7xxsYPoXJ6
0S0GoDiNdXRtmB6Sjq5OwM41z1Cqw1zTZ5TTYj0OwTd1u7Ox8bCynCwhT41qIYnv3IhlhOYBUQZ65WPH
0gJqGWK2A3vhQsG(mQhhr)1fdv1SESM5mmDICg2YZhpJmSK0Jwh)eDrvYqTm6QoA9sDmF90jTtoDpC1k
DRzAIm7Pj0Npooh0)N29p8E9H3EO)PVh9VrrKM3PJ(xkSMrpXg53sSXEAhJTQJo4Gz((vvnAhNI36Xi2
5PxMU3VhUC4MYWZyVpOzt9GUlZn1Lt1RC640nWSx3IcblS6WDsNtqB2B0eY6KO2hsBpN4rDovjhPUe0r
plHGaH)OCc3SMKGoS64V22sTf5nhPYUFltnQ6VhJc1gNFL2gyH4p6Ump01a8ICGbER2HRzRNIzddHtM0
U3b9JPMiCfHQkZOtRgQfVrxDe1w5G(rBinDEv6aAC1zEose9y9TvUUvI6jvMG97rSwQTebxanZLtSoFZ
LJO6HwCMZLCEmg(eunr0JA6Ks4bqxPggMMkbYK(h6YsouZ5iRmwHuU7taBXA5fAiznMpph2u1rX7kAoP
ICqhYAz26amccvRMqVU2461wIHsp6GWKqT3qKeZCcJZ(iuKu9LO5MjCOZzwjS02aLRDwTJALXLQ1kplm
NcSxoQu5pFFIASdg2GwNhH0rhzj10g9USklrFcpAD0rKylYk9jkveTsrNAaXovhDgdJ2f8470jiRUDsd
iy96XrPVAkD5s4xAMZZ49r)M(UTh91b5Cc1ls2B1bNZOHnEs1Lk3Dm9nZO1uVLrabfyunZ5P3bGBUQhT
K9A0RI50ZYJ506s)y1QZJk9ozLIrq2HmnlFZ1kOmIGzcj1zT41Elhp6bZrFh2ez8yV6M3hXO6rmQLBPw
Ky3B(ZOQ2keSvB0JLLi0zM2HEotvFTk1jnxjC4U8Q5rIrfOHyctHrAWO2vlCjk1rK1dxaBrIWaDa9ZS4
141B5m05Wstxob2)6FOB6S7g3kZWBsytEO1(Qq6Omxn0kE0qmCXJUGfGtw4rPiVOb0vwhrBb3ljnQayZ
Pongrohro9XFoPZQvgByX3nrtxhzRumE2Xigv1DqfvqcPQHoxIIbR6t1jtmwGzGjDPQXruzBkHTMG7OH
dbMoEtU46F6CLTY39YtFeNPYytcG)OQgGrnQHEK6r8iJOuxzJrmLWy)89WGw9CDecg1hAyn0p8OMHHGg
Qe7IwIBLIvB3xruZqw8MnuTyviBehlZ1oYB6a6qr37mcewLpyMy1eDsX1bMLHRIQ6nutDHR3RssJkw5G
6IIUCOVdLe3nY8rorxY(oHhNiEk1(MTM6V7CxgcJAF)9(MjnxzrJXTnBlqX4TKdj0riOdtgPt5ZteEJo
Tk5rvmo9X(ZumzgTQ9ESsUg8WjJFq9VinVuyax3Is3JhMXuOXSqfxI2B6uwUNaB76qdjn610K0ZqszyS
AOLH4HHaD2fF)XHhjNQ2Pns7OjiqZm3V6SQAERsF9QQcnGnncDfn6pU3NKV1zR8WCon4bCOblWDuQkIA
SaeQE1tlxksTBsE)7mfv6iYqMvvMUASsLJmGuvdao3BKkmSPe3qV(0Ogf6Wl0Ml2XMCfA4sKyl6wB1fg
x19bSvE44388Vsu3Tukk0j3OtUYWgSnkSP3wsOfkXwP8GzR80fWzoU6b8GPuFQ4iq0T4D0I63NAEYfU1
zJyw6PU7)ZiR9Os9zlz2QA0uCnG0XWpCkTAhrgAXJ(eAonFM6WfwU2F(G7F00mrHwQi1dETSL6sBy64s
iHi0NEQV1O49624JMNUHkYW3QMDqDuO8JJqJhQeTF0xr8eJghTNLhkl1EhJB14uoTcHHajxQ(SO0zO2A
5OzpIIfkZg3XHo0MIm0JmeE3qFW6nBzDRXqiJLEeEapZfZkGR5lQJStVuqjQoFGFI57He2oz4z5uH75s
JEMhVZmVHe4NkRwmUY3zZ9fQotIrmQrT8IIzzvcjpmp7C1BrWuHKQWOJLAVrvErN2J8MZBVVTvTCnXcp
hi74yyyfhQuYnB7NIT652TjD)95wbXJplum6cJQrJtRNVNk8wQe5SZwQfXnj7IcwqPWOevhCP2wRc)ch
SQuPdEGuXGB3U5ZoNfV6scTPBmIcRIqo1HBoyzVFvPh9tEC7QM2pT8HuPz8HqN1h8SqMVVgLc9PUUiWW
FS4cax3TQTv37(iNwiQONw8imTALlcwZChZj1PaLarDm7Hq6N3XyK4CzlVjuzJdMxnEd4Hs38vMARb3M
IQn5EBt6ezowL8P6wTIbZ2b9BvQjQK11gXiOU2vNrKOUUPDNFYpM1gMiQwRmIMJXaRZw0L(42m19PKYr
TwIm4wl(j(W9jOlr6AinNW)YXHF5iQkME4o0judVM4wYRUFF1iP46Niau6DXQ(EKAZt1x5t3Xhhc1PyO
US9btZfnwzoAQb5N8(cEQ2QCMPg7qIIqZ3PJUGnpPajozF7eMrIUBzlN949SqJWFdpAtDwsNJq6EE9Jh
WpijTQOjMLvUxtDAMRIR8iAp3tJlHOrrSvvCzbDdC5iVWWu37eDZPn65zKHZOY2AcopAWvmTHgFreF38
j1n3sXO(lf(6kdAts8i8vxhCFZUnGz3shU66ICdU6ie3SWW95Rt7yyNQl)MVWLDSPRhT9U04JzEgf68n
QJS8gUQKiqdUrnDYn9Lz5LHiw4zePZIokBocG8w19AITNvkCYLgVo1rwufr0CnoNqJwlmzyCl8ELVErN
BM1VcA7XQFpgTkpqOwNEueEI(66XfUG(5G1Ug6U7t7ix5KJcpxDngwXDvEuPVwRAddkUi9PDrRR82hCD
v1)ndqt3vmAkDZF(zlv8PznAUn0GDPqjCG30PNrXxYN6XelLO(r9nCQ7403KedZXw1cH(OEj4YBdFh1s
j5vVPRIhpJ(mBQbpWkZuGkTJyN6QFmg17G34Y0NphwgUBcBUjs1clf2sQvfDjv10X8yDQfJUs37hgRZ2
feVAm7mx9vWC3BAaY0rI1DwLYUbNeYAMtt1erquwS4mecRwLqjXmC4N2H5E03F(zkCAUkvLr9VFAPmts
Hf1V0iDC4KXNCm4L(OtcWRv3supB3VJpuYDhmVocSmNUdsiWvB)QR3x8L)vpz(9dP1kgETa15wDoPvJU
NOo3SMn(ZLK32dOK5ojo3Lvm7moy7HUievjdgnSUYmpp9rJx8I5yeMFARtCeu1NtrGAtbfG5FIrn1Rdp
axyvB(IX26SHzAM04bRQE95zi3I7)sfF8O2Lp3cQLloxOp8zuJWovxz7mwf90DRwPB1kVqJPOYW20njG
931hBEcWRlbhddEDp6SNodzicdq7QjoQzpcb0MZrXUnqXmJBSEOnNIQLo54WcoGlyQ7Wq8Oz5GL((seS
8krB)TWxtLvVDIzmwztuBrDIXs1Lbhl1Dsx2e1EKx61q3Ib1LAOM0bIQH9LkyZYB82Mqgr5WZ4PKLior
uLvjnYr7WvqP5)uq5MtvJzih64m20UPiyK2NNoepdU30HeBVptRAZsf6eDKYV4Jgv0f1pN4Rv7RpL9JW
PY7lBwPLiNOtP7VZnesEXBXP5PBGj8ZYZWP67A0Ykwju3YhwbP3Krm9hINff9z0(WvtIEcM3OohDfUMX
rp29zCmTdmmA4o4x)nxgTLyWKQjkjmqD9XHmZkfrHOt5lrDs1ODAHRulzYrsj7NMRgWa0n2TUXvXuReA
ek(w6uR7H7rmXDKQtutXkIygLU0T7gWw9mQwSL4tolBEXNj0a64SVsTW7qYMgZiV1WDHgqDzuo8u5kM2
jCfrJYTjD2Cae60aFEgejVJXZEoN4vVzt63oBw)2ksDEUywqM0xMe3O0j6Uh1MFGQ(fFy6aEIj6k1uUo
k0TIQJX5Oo3vkfGO3Qtgwn6iZ7Z3MwqXBCWepCzQ73C5CTygv1bd118F1djL7bWiucp6aqnpms2vmqaM
pAB)JJlzEyCQLHhlRD5sCIFXpW0429TEaEp3sQXLb1efgZRT((ziPWA0CFZr1ZQ7OSWETTN9069QYhBP
1okXMl9fu9vgWLn4d1N4NFIQsHEsNQYBTs81eNhkXMDYMoDBHg09ACpEZSc73ACjbho3kZRIcZaSdRc9
jgkZuuPHwJtgTfk9JeiXPZ2jgYfy1PWJiRCZscp1vD9PSFLoQBn0zm7B6S3jjYobkKb7KmAE)A)O3Xyr
1rgqNx295TmAr7kpy4if)a3nMlp8QY7x(g7Sc5AiUcO6mH2NDpeRiyRIFaB2vNSQY5YsDwNCvvv7dvT6
vNN9GXaxZ79KcHs2dAC0Ci4SDvT6ssMhMw3bds3Qt3VvYezRywRqPF6odTAfvv)03ZqJHFpna8LL48NP
N7e7vdsKHQtJzY0hD(OTDXaWxOfx9QdQ79WrmuCmDvZApcUcNvASVTYQoTIN6UfajNF6x4Ln)8WRupSA
DNsqROBqT7l3WdzqJWaRvRgICpP2fQX(V6uBzPAX)nF6Pi1(ZGh6)61l)P396F(p8lV(9)8Bie425NPV
4V8))fxV8FBby9Za)Sj4a(z5YHFwUi8ZwI3HFwU(UHFwUEc4NT6)g8ZOr7RgfWpBTeGF2EpGFMzaoLb8
ZwQpc)mQ0v3JWpV60ZWMmXB5ZxMDKhGF2E9JWpB54r4NNfEb)SC5WppFCb)SC9cc)S94n4NNs3c(517N
Wplo8Ztn(c(z(yjY6s8b8Z89qLc4NT3dTiHFw8z0OVddY7Wplxpb8ZqpKD9WkJFd4NTQOTKEa)S9eGF2
QQ7Wplo8ZiRqtFh(z((SRs6RhFo4NT)fGFwUC4NHQGXwTGFwUC4NrVM7oEb)SCDh(zRm3HFE19RRE3D4
NTAhWpJ6CnGc4NLlh(zR6b8ZYfHFw2HFMNrMLZB0ppB9NH(5PA43h9Zwoa9ZY1)e0plxo9Z8rF2Y3p9Z
YD6NHMEvIB0pV6Pj0Nb9ZMa8m0pB14I(55a26UUqN2No9i9ZYfPFwqIn2t7yWf0pZ3VQkeZICr6NXa65
PxgOuw0pd5y4DYLDfOFEQpVr)mQ8oRrMZVt6NfN(z0j917AU)8mvnK(zM6sKb9ZqqWerq)mKe0Hj9Zm1
wK3CKkNk)i9ZMaUOFwUi9ZRg9RPF2(h3PFg1o8nFN(5v37aoki9ZtD(3d9ZIt)SC50plo9Zmr0JFg6NL
Rxq6Nnrc0pBPMYC9KNJ(zMtCgal6NzImWYf9ZZux0pdvcKPG(zCywmNWH)D4NrgODu67c(55G3aXkq4N
5Jynsa)SL1f8ZmXqNh9pyra4NzoXwb6JqpclVBWpBDoa)8S0l4NHY5KgzCPAa)8kNpa)mFFIASdygq4N
zgyQl4NxcvluJ09doDEMkKG7WpBzaWpBTlGFwwMxOca8ZYfHF2EnGF2s8g8Z89OPUd)8SPwWpB593p8Z
Ytb)m6HqSa8ZY13n8ZwJ9pa(5TJZ7o9ZwtTOF2QPB0pl4rpAUhOF2EpOFMz9mEKJGTulsS7npYjOFMVh
Hm0Ohls)mup0Z5n6NLPD9J0pptDr)SvRph9ZmRhUztlsCjGph9ZmNy87r6NLLpNVj9ZOjX8xq)S8pG(z
RsVt)mBk0aG(ziFW)cPFwUa9ZYLt)mZPp(ZzD3PFMVphLcMcG(zMHsubCcWI(zwmuzG(zMkIWb0pZkl0
2LTMag(ps)mZjx)Br)mtT7LNojEw6NznGIb6N5JWlXZr)8SpEJ(5zQl6NThb9ZY1tq)me8hOFgLcUQVt
)SSgXhRSc6NzvbpkG(z5zPFMLHRIEJ(5LK8i9ZwQG(zwdNXJCIUK9Tc)Ds)mRbFr7Vn9Zw1c6NNJxl6N
rfGGoi9ZY1tq)SLiOFEwbl6NLLQz1QK(zlX70pJsHbCq)SCDN(zlJlAYSKb9ZZgAr)889pd9ZY8XCpep
yTa6NT3JRlEwvl6NNQIf9ZYtr)mA1Vn9Zwf8i9ZuuG58Zr)SCDN(zRnb9ZRAkDMIkDezitD6J0pZmGz3
G(5Pgyr)8uSEG(zwOdVqypo4ok57dfCjsS5dV1TQcdR3GFwUEc4NrHodnWPBG(i8ZYxb)CagdHFwU(k4
NDada7Zw3)5yF2k(3j7ZyyHn6D2NfuTJidODVZ(8ufUqkqC2NLRxq2NHEVgfAPHEc2NHkUqHnJ1sUZ(S
1Oph7ZMud2NfN9ziu5s0(y6AGMcyFMLhkRBSpdfeI2GSplqfhQTVn7ZmdyweyFM1BpYq4Bd9bW(mZ6wJ
XXiUlLeyFwwwbCf)NJ9z(EiH3zFEMQWd3HSpdj4BZ(mYl9V)9Y(mZlwxbSpB5bSpl(9go7Kl0NThZUxh
G(m1hWvbqF2YWD0NLRNf9zz(ybbtr0NzdSuDa9z(EOAbKCmRD2uTiQjjTvmAFMzwb7Z89BPYfgQy1ca)
SvPa(zMt63Qrpyb8ZeZf5YPFMzyvRFV0pBcWI(zw(TsTStj9ZYLt)mkvAvR3OF2YjOF2e3NK(zYP4mdD
kbK(5LkMX)q6NzExfJ0pl(v6jxe(5zNzWDPa4NLR)bWpBz9o8ZId)S9Ea)8SwxWpdLrLMEfSnjc)S4Wp
pLQf8ZMSa4NzTwIm09UD4pKJrG(zKv4H5jPFMOgbb8mseJrps)SL2D6NzQnVr7lrH0pBpcSNS8c6NThb
9ZlX(iouHhOFEwQf9ZZgR570b0pBTWI(5zIps)mZzpEpwZDr)mtegHG(5zNPgNpGFssG(zbzDl1Sxx)(
OFEQSw0pZYJnba6NTU9)e0pBfdy6znrZ3npOF26xps)8SPs8i8Fo6NTxd6NTAh0pBpoCV(K(zXVdtRuB
WpJ74uUicgZc1p3ZkNfUUovzo3S6RTU(6ZyE529VX(S81x97c9zRUIB5L3x8C4yDnSY16aX4EJwSpJbj
yNVD5Zo7Z8J3yv(6iwdJGAHpidldB4phx5D8PnSbcnPFwwttk(aNx8bw3Jifsrfo9a8Z2JdEnd8g1Thb
N2t9YaMd8k5LvtTQja)mRtKtq)S4iplx7)w3b39V4aNpBNfLaYxX2bqphspT2adWZhjX1e(z5AdEwY(S
CT)DaTXgDG(m)SuNQKQ3rbqaYfbXEQtD2YdYni5Z27bBewVcetmFm4Sa0xm72RZmqMgi(oNatxYYeg1a
aE2KfhutY78Szlj)kRVrV9SwB8kwiEiY12VJg2WOEJttII7SfwaqBp6aqdMtMQ4h4FEQRw8pphRw4xoF
CWDiqONxP6hAcaC3evq)I1aLSFfrlaONLQr3035FwGnGVsyHh41J8pZkL90f2EIt98u)f)6AbaqBz15F
k4FMmzAPd(NTEsWre5mAM6I)zRbC(NjjYtf060WMc4cvy7rqaTS8aGPlaW5zZUiG2Epy1s2rLJ05pRkh
aAY02SBTaGEQ2Eea65WIFbKaK)PS2sOvbjHYC6U)l8gN7SnaOjk1YYUThXDruIdaOjRZZ2A9TiibR(43
IllLQFmtb9ZX3EqcO)lxoPyR(mVi3D(Mba0SAp8UkpZDaaTarTtD1bDi5FtbRwFdJpqk6ulZ77gyKZQJ
UYYEmoGTZPwMSNNa8ZYY4HXxVr)82NuZn6NNMbo9Z8djAwbm4AqHOCTb)Cz7wDVd)SL1bNgU)v4GpPck
FRkiGt(o8ZYLd)mgM85Po5Cpf7ZGgZzd5FmjBSpV4XMYbMefF7cBu4IVYv26lfra38ta)SSJ8mrGDz4u
4zzM8XSG(5Y(LL64pNB7NeZn8N3WfL4ppZ5c)5zRUWFE2bwOspvFj)I1a(ZZ8UG0DkHbuZGYxwVyFXo)
Ze9xRu4BAsUii52tbj1B8sw9MAJO3saI(guQ4l9yAl1Pz1gt0BFtje5xlVG(5LMN0pdszLLjY61BFK54
31cYtX(m6)KdWdNtS4dvbF8YtD9IIAQvHhzqDU4SpdbHoVwSpllBvSIwFSp)JZzDq1j7ZcK0v1JpocOh
8anD0NbQ9wH2GYhOplxBSft4)NDF)74HF9dwQRv)e)lMWQuG(SSSv5GJtYpzFgY3P7Xo(6Qx8wVAv(9I
Sd)CIqiS(isKRD2NXNdJvNo7Ze89L6J7FaFHzYY2HFDaG95PoD9T7i7F6jeNC5AN9zY5Vvk8Hfpv6zEu
oG9ztufgfZZZ(SviW(88X6XgcxOT2GFE)ZDdWppvb(hcczMEwz(x6d)uVMdCRVLQ1ahsmGNL4DBjgFmR
K0B5IWrpRj)82b7ZY0hfFC7JV05jGuuBpguuV9RKJeG3EkE(rSr4PxQ4GOAUUQt)Cqrn55wUEbHFE1LF
a(zRkpC2xXxN5QqN82cUd)SGMNH6VGpFPE5VrLa8ZwIo8Z7FMPoX0BFChBFMQG9zRLWhuRjFF93Uk0o7
FgU(xPlHFgADwm8vhph0wFwYwhaivloOYc(4DN6Sc95fOpt0OLlIgTazc2wb6Zen6z74Fb58drWkg(qL
KN(xt1F4D)4F67G651FV()o

**Comment by mbattersby** [comment]
This isn't a bug, it's a deliberate behavior that will continue to be the case.
