### ISSUE TITLE
Running Wild Not Being Used

### ISSUE THREAD

**Issue by Littlenemo** [xod-wow/LiteMount#144]
Running Wild not being cast once character trains Journeyman Riding. I have it set to priority 4, and no other ground mounts besides the Chauffer, which is priority 1. Summons Chauffer every time after training to 100% ground speed.

**Comment by mbattersby** [comment]
Hmm that's weird, it's hard to imagine how the riding skill would make any difference.

Can you please trigger the error and paste the bug report info:
https://github.com/xod-wow/LiteMount/wiki/Report-Bug

Thanks.

**Comment by mbattersby** [comment]
If you are able can you also send me the output of
```
/dump IsSpellKnown(33388)
````
and
```
/dump IsSpellKnown(33391)
```

**Comment by mbattersby** [comment]
I think what probably happened is you learned Expert Riding as well. Seems like you forget the previous riding spell when you learn a new one.

An overall fix for this will be in the next release.
