### ISSUE TITLE
Mummified Raptor Skull doesn't exist

### ISSUE THREAD

**Issue by PreYem** [xod-wow/LiteMount#146]
Hello, I couldn't find King's Rest mount in the list to add to my ground mount list (Mummified Raptor Skull); perhaps it's a bug that it's not on the list

**Comment by mbattersby** [comment]
The mount learned from that item is not called Mummified Raptor Skull, but Tomb Stalker.

https://www.wowhead.com/spell=266058/tomb-stalker

**Comment by mbattersby** [comment]
![image](https://user-images.githubusercontent.com/1300207/230514884-72d3296f-e947-49ab-bb63-2923b086844c.png)
