### ISSUE TITLE
New mounts are automatically disabled in "Mounts" tab

### ISSUE THREAD

**Issue by Rezy942** [xod-wow/LiteMount#149]
Hello,

Any way to prevent new mounts to be shown as "0" priority?
![image](https://user-images.githubusercontent.com/122007087/234392225-630298c2-f66a-4860-b363-448011e7b51f.png)

This setting is disabled, yet still new mounts are shown as 0:
![image](https://user-images.githubusercontent.com/122007087/234392353-8130a34f-858f-4657-be68-71b1339900d7.png)

Please help me out incase its not a bug, thanks!

**Comment by mbattersby** [comment]
That's not what that option means by "new", it's referring to mounts newly added to the game by blizzard.

Mounts you don't know yet are in the list and you can set the priorities. They are down the bottom. You must have set this to 0 previously, or had that option ticked when the mount was added back in Shadowlands.

**Comment by Rezy942** [comment]
I see, thanks. That wording is quite confusing imo.
I will keep an eye out but im 100% sure i never set that mount to 0.
All my unused mounts are set to priority 1. As soon as i learned it, it became 0.
There is no way out of 800+ mounts that single one was set to 0. Something else is the cause.
Will let you know if i find out the cause.

**Comment by mbattersby** [comment]
What wording would you use for the option? I agree it's not clear but I nothing else I tried was either. I think to some degree people see what they want to see, and don't really read it. It does specifically say "added" and not "learned".

Let me know if you find any bug with the priority setting. Obviously I can't rule out a bug, but occams razor says it's more likely you misclicked one mount without noticing than you have a bug nobody else has had in nearly 11 years. :)

**Comment by Rezy942** [comment]
No youre probably right but i will keep an eye out.
Reg. tooltip im still quite confused on what it does.
If i get it right - newly added mounts (like via patch?) are automatically set to 0 priority as disabled?
Or something else? Not sure... :)

A lot of addons put a hover tooltip with a bit more info to describe the options for confusing options like this (confusing as in can mean different things initially and not exactly direct)
Perhaps something liek that can be done for this tooltip? (and any others newbies like me might be confused about)

Thank you

**Comment by Rezy942** [comment]
I think saying "Automatically disable new mounts added to the game by Blizzard" or something similar makes more sense, as otherwise it makes the user think this option refers to mounts newly learned by the player that may have exists in the game for a long time. This is what made me believe newly learned mounts are set to 0, when it wasnt the case.

You can leave it as is as now i understand, but most players will not go to the lengths I did to find out. They just ignore the option.
