### ISSUE TITLE
Dismounting in combat causes druid to change into travel form.

### ISSUE THREAD

**Issue by NoShotz** [xod-wow/LiteMount#151]
What happens?
When I try to dismount via the macro while in combat as a druid, it changes me into my travel form instead of dismounting, for reference I don't even have the macro : combat enabled.

What did you expect to happen instead?
To just dismount my currently mounted mount.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
Unknown, only started playing my druid with this addon yesterday.

Please do not modify anything below this line.

--- General ---

date: Sun May 21 21:41:52 2023
build: 10.1.0 | 49570 | May 11 2023 | 100100 |  |  
version: 10.1.0-1
locale: enUS
current profile: Default

--- Player ---

name: Threaviann-Dalaran
class: DRUID
level: 65
race: NightElf
faction: Alliance
spec: 1 102 Balance

--- Location ---

map: The Azure Span (2024)
mapPath: The Azure Span (2024) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: The Azure Span
subZoneText: 
IsFlyableArea(): false

--- Debugging Output ---

Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 1 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 43 mounts
 - trying Dragon Riding Mount
 - found 5 mounts.
 - PriorityRandom n=5, t=1.667, c=0.207
 - setting action to mount Highland Drake
PreClick ok time 19.07800000906
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 1 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 43 mounts
 - trying Dragon Riding Mount
 - found 5 mounts.
 - PriorityRandom n=5, t=1.667, c=1.220
 - setting action to mount Windborne Velocidrake
PreClick ok time 19.104600012302
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 1 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 43 mounts
 - trying Dragon Riding Mount
 - found 5 mounts.
 - PriorityRandom n=5, t=1.667, c=0.744
 - setting action to mount Renewed Proto-Drake
PreClick ok time 19.516299962997
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 1 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 43 mounts
 - trying Dragon Riding Mount
 - found 5 mounts.
 - PriorityRandom n=5, t=1.667, c=0.021
 - setting action to mount Highland Drake
PreClick ok time 19.299300014973
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
Changed to travel form in combat.
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Refreshing status of all mounts.
 - saving current form Moonkin Form()
 - saving current form Moonkin Form()
 - saving current form Moonkin Form()
 - saving current form Moonkin Form()

--- Options DB ---

nU12Yr6TX5hhFvsHZh8DRKCKvzjkxIB0fjvyXrKZUCIgoJZWHRYQl4ZE(AG(RXVtjfNvBjIfOrJUB0NX
pVZF37V72hEA3f5NF9UtpU)Y1dV829)tVD)xT74Ul7ona48PpC4J)4(lVC48P7UPF317U99pDz)UpDy3
Pt)dH(2h3)tV(X)0PD)0X9pE3xi7(MZV805R)6)WTcq)IDhU84UN39)hQcG)3UC(dhoU)VS)ZV87Zt3(
v7)WUxp(7Zgla(TO01Q)2eNToG4Jhp)t7okKYlV(8ZNp9LNF90vH0UjwATE5UBQP(D3e8PA3F3n(aghA
DpMllWuBbatcZIbnzvavUNl9XSyufteXoR(bOEmBmMsozCfOVHfRv98KDjqfZ9ws21aBLSBEC5yRIFwg
q3DcMdc(cHEyarO6lPYKo7TAOooBSEelcWd5EWH18yw54aERJ1tbLHIfznFtWvQ4DJtlKBUaGaZgD5SC
ycThI(KGySHIZfKZxqHRNfIQlqasOoj(qp5fwkmGPus1HeAW2Y0c3KCEb3y6Ipj4lk4ih9U2ywielcpj
hUpaHyBG6URiIDzLq3fdTbrxCErylIIk4l3KRhY(4efyCSpKk4F39Lyuq31FlBKdNE56UtpSFOA4U72)
0UxUU)c0k)lho9Xhp)8lIK5UBF3rm7UhE7(FC3XJ7)SGACDIP)4(Rp9h2D5T7F3d7EC)ZyfrXaQVxUcv
8tpkYfizGc)(3U)2N2945F5iSnEzW(P7U17(NDqd(YUpEgh638YX9tD63U)loU7HFET0xE4koGJJfVz3
Ll7UE4taLgV4ZvWo)RhF8v4vripCO)Oyn829N)WB3Fvo)V50d7UCA3vWT3a9P4D3(xEfy89hUSBqqbWP
FbyZFE)PNo8i2WF(8XJN)fSuk7hih2CN(JVD)3U)J7E4Ztm)(pFzaaW27pF5JpbbOONvCkt)Jho94Hh2
nPkyFD7n7pEfU(EDEKaV)WR)eW13E4da6)65ZhFzGpiC(3Gz9X9qi8L7(eUueZgCTE77E5jXCx2D9UB)
Z4g5LjP8nN(WRtPriwL9V)cUEE7(V7S4kcAo5kjkmZ()BCChoDA3dh3pTJbTT7x)p3DDsRqpxUE8VD))
l6yEd9LpT7VbLI3UhaC7d7pT7YHZcHNWb)3DFIZfAU3kJNK5xE(0)1R7fXeeizLIE3V(6fHWgoWKfW93
xd28r5(5zbGh)0(txbqcTksN)Ll73)05JpoGUOO5MZ)8tVI989F4d7p9curedL596zCTAKe8mmVrF9zr
3jjQ(pdv8JpkQC7398VS7Z)DE2hU1Pdwm8zXH6Ff88LdxpmnFGHMtCBn8NMk5(yimMJdxpkathwXECyS
J)6Qc5p3LRjUr8tVk9jab4lSVaDojUFHdHXq4sj7NqcFNTOUUZNxqMSdTnXeChwMqgkfxEoB0xQ65pai
TMvzGgIfmHfo6AgsNKhCgfuAMoXea7X(KsGFYERqEs89RKNIPYiU0GpA5MIiXz9yuRfJkBgDTuAbzNmV
3PaiEwvuLgHa4Kkjx6MilfA1jUAPkNeHGIH1W4cuLtI9qDTUkNsis4ebjvGg6iqAJCSkMeEFcMV075GU
5quJLLqOfvFauPE4ICiyYHjGzFscca5yQmpKu1P)uXkcqQ3ni4wq1IAzhpvmBCULEmgkRj9gPunMV5xR
hwZohc3fDv1tdkjlhlKvJ5KN3U9sCjku9TqVR6MJDfmUwrkUYuPsP0s6insOOeNOsm4yNAViX)NucsEi
tzAWvvzkIV2DgovdRs1PchOzQlhG6GtnNB0egbFfjQBIDvmvZTODHRAdLuVUwwPiMbXaYSI8Qj6eoxDL
4Q9(IGu73uZehqiq3hPCEXVgzarZCykqlSOKVrEnSSaysP5At)58Sr(tmvREdYO5I4oFoQq9KYYVxIE4
ejrGCQx55msLKUcb7NnUoBNNYFyDL)6rNRAm9I)8lTzLt0m)4KvYPn9Uf(8uhmJ1NOQxZfND6RBSsX2t
Z47UrhMQS6KuZ)uMlLPNZqTlH0jYPputbtwUU2KQHL6M)6GxLMTkvHeMuXE3v3cPoe2uXWA2jH2Bb3Iq
mnlpvBZijwVrukVJWbP6MzRlydRzPKOgOWvRhqgvPPMFZDSYjiLEsZDeoW2sw1beSREPfMwnm6oAxbon
txAqBHbhsGMv(h6Sr7qNmcuBY0LAvNteezv4d)6H1KkhJvtQDauNujcOjvvoVIWkrlyy1aJSimF1OJf6
vP4aYjDM7DZwnuvvhOP2vdYOKwF1ejknH)qVxSEgfuMbHp0mBX6kcFK6uYHzM8Q6vQhnwbqsbzN(MXE2
WamVciv9kxNQsafNo5sOVyqvLa6BA(fdiv90M41ZPawnbz3ioL5eTeUB5IYKoZZrlCurEWriDQ(sorH)
yDpLyzMbbWzErD0NglHEqu1LyKUI8zl2IFfpnaYMUhDjnXLimnuYwYvIPZawWY6dgit22N904hLpppRK
u15cYYA9fFt34YqlKiTjGdLGDQ94MRsg2c0DtnFdmXn44CLBquvQgqAz7XSgtwItYYkxTSPh7xTPrwaA
GRsoXegKD1w7QSgwnXIUjNtnf8WXTZqFnSgAj2rNhILSoSLm9Bb0YAizGQVUMSzh)IMYB2KQSwPllzsv
OjIh660NS4wWHnJk2nFEPq3Zmeq6MQUq33zY8qf3T2vEbA2iW6AYjbc7l3A7P1YBGuV)6CpWSJga4p0p
DW8Jl7PBhPELHcwv2dxZmYOS91bXuhZnNgm2lPk5xWQhaIY2xNLMWQhziOkDLwVVGSVG0U)PvNGvMNyS
T0etu)r2fZTT3x3QZgUOiWRZI0OJRTPiRaVmSCmeiVSaqVHqyREEH3nYJnNgl0H3gI4EdJXyHWUzZ(B2
(P)IIp2xkgmfGeY7iTWqBnBEnKjAIOCmrkVQgmwx1THxS8IWOOraqrBpfuDcKbfzrzYn7IOTzrhbabND
SlPSgrsU81qE1CyJmGxPO6An)yqFQgJGj6WIXeg7HruHCtXuZXy)GsQuW6YuwiTDlVuzsRBz6)p7cwTY
9IMBfu15PbFFLT0Ws)26aGvJP4vBDySAAjyfZ9YLDlzKMaIqJ0bDPOP6almVLHrVy39f)YUwpvzDnQo7
mSmeUACvBx6foQCPzPjZ8lq(luW5P(gSEzPcApOhRxPduHsllkLz3I0mxKNEfadnUEoBz1bXo1rQ5Qtt
6mWYyhOQANkD7drLEaIzKYkitqwsK3QOw2VQo77SfiiXbwOjeePvSif9WPlJkb9gVXFf)cP9fabIQa96
i7kSaqNfka02R7JmfkpRZhJ6P1MY2M24TTVHUws44AY6IT2GRMXx(1KSyqpvarru(1MkS(NqIPqWgzRh
WKcL0k0DvlTvoWj20bmRgetkywTYHVA9Ab2U1f6nlZcdHRnUxaT0znlrRjwJ7fZyjWdfjwLTS86wlRaA
7laQRHM9SzL7cr1pH(4k(7MniI57udP1MMsi4apf3m7uhqeXXffQjb18TnhQUoCd7mIIEHIUUv1M0jps
uwtkqMrX15xx7IjbgxD8Se2GkvUbnF9gmznjyqv6THikm7jFzjbRHffKxBBjxRSoeCl7xa0waS8ZvnvJ
6gq3CyAEKX2kNb2ugrHGjc4GlTITlvEc3qQhJX6kfwlmNTGpgTsUDS)pdyxuG1bxSngdSunVIWTY6YRL
wWQBta1TO8LMAJXXDo1QWdbM6IbjytVrry)RGgmpqPwTUbRm4yKr0L7CLFdzqKScCRH3WfUPDAo(d1OM
J1ytRlxv9QxP9TGF2DwbuvkdV9HnxtnEQ1vYuo)gmexyGkWmHs4a0RAAdqZlqvFizEaG(vNvGqzv6iHa
vPEGj6IJfXgtvM8HGifsOpWBtz9jsZTc7DpUlSwV3DjQNND0VEMTqzSEATlL9AiEr3ggncGHOt4SAMKq
HusSv50OLmQGvM7mYMWs4UzuGd(WTSnT2K07EASlW6vK1ZkSvHWMKLJpFcCeWABGWKve7HHoV18MRabP
61AntxCXKNYyb)khMX1MxXAPtftRFrI6OAOcVwm3NCVRrKJiijloff34dlSgxaq7HI1cribworzEq4uP
Wc7s9fLZ2JUaPDYUoyym(01CwfaOWenH1kVv6ksWFBnB1MLbmruggNlcdsfxsL0u1bPyZBwuBG3ygDuQ
YALGgT3tsOA1kH48SzdU17ei9RwN08Hlq2wRZn1z8azsYb1gVUqvZwhgSErbuzLEaqz1QWKZKXj2W3Y2
5y8gK8XguXyiOeWWcwvlfLCrNI4qlLfaLfY2Ce0MQxShAQYMmc3q0M1dNItbdYf3rpDj6hZ55dca3iQD
S0RgREKuZs7uf1dh1BShzEZrp1reRFMiI0fZjaikSAYpQtBYvWpiVHW9oZPPBHD8XeZbwkTHnrXj9ZDc
GK5UL4P3Y2C1Wfb2Srnr6uWZaXIknFFebwIHO18k4)HAuq5x1JGJVyNE7XDNkKHvP65T6wvILuF0Wu3T
rpSTjG5KUASWAKLRJ16QFmgdzW8JBro3wNVBz1XNDajUVjfovglpsGU9CirlUO16FjFF6FRZkEgiDPLY
0ekYZcpgco2Vcg2wr400FGXp3dQunycI5KDOc5xOuPzrKUktZAnVZek6xqt4U5dHnXGK3hRkhcfdxu8p
IMUkpM9StE)OYIeMdBR3raAPQUTK7VQvuLxH8otaPktqxXMn328WpzZmiV9zC0JThPJUesdMrJSsEeft
vVRQCLuXPNlMT4hwVmcHmBe(OrOwPf8Ka)zQI2J3WpnOXXd(tdajvIo3V4XDPlOQLJhhAkawnVfzRph6
DrR7JoxK1jVEzRS9Q(ivE)MsRmxlPWYMIjk3zXksFevRROZBXwSuOgf5P4pALPliLoaK8NNG6TiTOeTM
OmkywU)v0kPmZ0GDbwytj7wyvViRwny2hQ2Dtzbv1kSx)TknlfFRQ(fCcww5nAnQy1KnXxGASIyQDlnB
A3ijXYC(RR(h749lcNOQcYBqopFr9KLEcMUSYmKmDLHjfhKkKiGjFxZQ9kFizv2mUeFPLbHsv6iJYWVC
UbtvC8TQfLfMus3EkkKJo)2cw5xKqsd6LzKpwR4xHhvLFRiIImjkO2WilTuOS4FtOA98c6QE94B8lujq
37JpgKQjEMaI0hnNEv2N7bkvnrpvuKQ6zzdcHU501DT0jGFm7JcQ638oc0QjXhLxsnAL6e73umWuNcUL
NqOjYOpYNlXCi8eBVDAKFkashZjBH7jThcd1l1axE0nMCKZ8fj0nZ2oYEgkQQZjLcOdgXsrnsqL1oM5d
9jwfQNg97GKO3YdKbZKQmTSqyl7giTAhVA1coXA8mdQpGuTuqDN(vnylZF7(N36IHSItPyOUDqHf1TXL
PYDYlr6xSFIiiTEDLsGUxNOhHMODOFfES13EqRR)vh6lKMJbHJCtdMnAx6(LheKzU2R0Kgknuok2EEfR
qtHvR3dmta9ZEDi(qsbkSzrdDHxTY8cn0ehngh0zVjLQ(0KkqQglVBEZsUBnrOZx3RMZ0sxkdOViBgtU
1CMsd)YJKYg96P6t9Ls3MgfRHLg(VN3bY3XJMRtRZmZtn17CovTE7AVbJW(w7JQB6RgZkvCzT85hwrQP
TkcBPhFpWVZa5qzzw9mNmtQdkir7lbcrINSFfeGkPf3OBc0WqXOGfM(JNV(l)iQNhQY9UUZc5eyJbhF2
lmPzj)ifRqTCtf4l3AkfQFWYYFLVTdfxr(4Sd)pXfTQM6suZ5SioP6OWAzaYoq3mK9SLDszrZHsxtNRd
VZuLwqifzwfbsNqzSVMvwt3uOKMvNwGsrASPHHY9U9UDSSXbKkL68wtvqLALnXzmxkIgVtuyT0yeLuQN
vPDOeI0A5GNwYJlkEpeOWDaltp3ZVzkeFIr3fvE2eVwM1Mp68wZ4b7RqkyF5GscyQbEQYUtkzsnjSW6J
LAebIhgkZ2go)(3NglQ4Ohs8j(6LcZ7mzTRt2FJIRUL0RMOGmY8e5mN6bwzSSEBD6L5PxBupfQV6E6Tn
9DKMhr6OFuiLYCOy66YMKbFOZrjrb79r92N8H(R8qykCAw6RcVlOOvScgQuvhz)Ya9Yh7yBD(wFKdD7t
Ml6TBAgCvkbNP8Jc71wxi1bO7xE0sAb443umcyYpjHe0oOElC0WKYtubBujgdvyp(M(BiHIvlPAxN9Bg
LcRsyOZWEhbpfmsDAvtcC1zAc6VWg3n7Q24SUE3TxE9O(Xwp)F3(ThE(W1B3F9T7)3F(8J)XhUE54)XB
3)(l7(0(J7V8hEbJF90Jx2929F3UNF(81NKRLBNFA3Np(4p8)b(EC8vSF5WJYVbraPF1p8UV(7V5h(MV
6BU5RNi4373NIRF)PJF(7o)PdN(44x8i5)U7)5p

**Comment by mbattersby** [comment]
This happens for me too :(

**Comment by NoShotz** [comment]
Can confirm it is fixed.

**Comment by mbattersby** [comment]
Excellent, thanks for logging the bug and confirming the fix.
