### ISSUE TITLE
Fits through doors vs doesn't fit

### ISSUE THREAD

**Issue by OIK2** [xod-wow/LiteMount#155]
I have thought about this logic, and could see it being useful.  If I am in town, select a mount that fits through doors, if I am in the wild, select from the whole list.  I know that I would still need to dismount to enter if coming from out of town, but I seem to get the largest dragons each time I am trying to do business in town.

**Comment by mbattersby** [comment]
As far as I know there's no way to find out how big a mount is automatically, or anything about it's 3D model.

What you can do is make a group for SMALL mounts and use that group in a rule using the Resting condition.
