### ISSUE TITLE
How can I set one binding to open the Dragon Flight Acrobatic Mount, and another binding in same zones to open ground mounts?

### ISSUE THREAD

**Issue by TheEndlessStaircase** [xod-wow/LiteMount#156]
Sorry if this is obvious, but I can not work it out. In the Dragon Flight Zones the mount button always opens the new acrobatic mount.. but I would also like to have one of the second binding open my ground mounts... if this possible?

**Comment by mbattersby** [comment]
You need to do this with a rule.

Go into the rules settings, from the drop-down select the appropriate key binding, create a new rule with no conditions and the action as Limit Mounts and the parameter as Type > Ground.

![image](https://github.com/xod-wow/LiteMount/assets/1300207/49647fd4-3934-4080-a37d-1ce2ec88319a)
