### ISSUE TITLE
TWW - Handle new mount types for expanded skyriding

### ISSUE THREAD

**Issue by mbattersby** [xod-wow/LiteMount#159]
Yeah this is more complicated than it looked. There are 5 new categories of mount type ID, these are my best guesses so far at what they are. I don't know what capabilities they have.

424 -- Flying (and eventually Dragonriding) Drakes and others
426 -- Copies of the Dragonriding mounts for the Azeroth flying competition
428 -- Flying (and eventually Dragonriding) Proto-drakes and others
429 -- Flying (and eventually Dragonriding) Rocs and Pterrordax
430 -- Literally only "Temp" which I guess is Blizzard testing something

I have no idea why 424/248/429 are separate or if they should be treated differently. I think 426 and for now 430 can probably be excluded as irrelevant to LiteMount usage, but I can't say for sure.

_Originally posted by @mbattersby in https://github.com/xod-wow/LiteMount/issues/157#issuecomment-1632094126_

**Comment by justinkb** [comment]
Type (ID) filtering is affected by this in an annoying way in that you can no longer filter out those newly classified mounts at all, might wanna do a quick fix for that too

**Comment by mbattersby** [comment]
I have no idea what you're talking about, they filter just fine they are all part of Flying in the filtering and working just fine.

**Comment by justinkb** [comment]
For me, the "Type (ID)" filtering doesn't work for them. If I unselect all
the options there, meaning nothing should show up, those drake's,
protodrakes and ravens and stuff still do show up. Is that not happening
for you?

**Comment by mbattersby** [comment]
OK I'm an idiot, I forgot to put out a new release with the fixes. Thanks for the prompting.

**Comment by justinkb** [comment]
doh! I hadn't actually looked at the repo itself to see you had made those changes already

**Comment by mbattersby** [comment]
Seems to be ok now, Blizzard keep changing it but I'm tracking on beta.
