### ISSUE TITLE
[BUG] Advanced Rule "level:" doesn't work at all

### ISSUE THREAD

**Issue by Raydor** [xod-wow/LiteMount#160]
What happens?
When using "level:" advanced condition in the Rules section, after clicking Okay it resets to "Max Level" condition.

What did you expect to happen instead?
I want it to stay with the rule "level:1/9" I set, because I want a condition to only happen for level 1-9 (or less than 10 which doesn't exists). An alternative would be in my case to add a Rule for "Known spell"/"Riding known", because I want to cast mechano-hog mount (the mount you can cast at level 1) for when before learning Apprentice Riding.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
I don't know.

Please do not modify anything below this line.

--- General ---

date: Thu Aug 10 03:14:02 2023
build: 10.1.5 | 50791 | Aug  4 2023 | 100105 |  |  
version: 10.1.5-3
locale: enUS
current profile: Default

--- Player ---

name: Smoolepala-Sanguino
class: PALADIN
level: 70
race: BloodElf
faction: Horde
spec: 1 65 Holy

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: 
IsFlyableArea(): false

--- Debugging Output ---

 - filters: 
 - filtered list contains 50 mounts
 - trying Dragon Riding Mount
 - found 5 mounts.
 - PriorityRandom n=5, t=0.500, c=0.199
 - setting action to mount Cliffside Wylderdrake
PreClick ok time 18.977200001478
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 0 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 50 mounts
 - trying Dragon Riding Mount
 - found 5 mounts.
 - PriorityRandom n=5, t=0.500, c=0.412
 - setting action to mount Cliffside Wylderdrake
PreClick ok time 18.765199996531
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 0 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 50 mounts
 - trying Dragon Riding Mount
 - found 5 mounts.
 - PriorityRandom n=5, t=0.500, c=0.012
 - setting action to mount Cliffside Wylderdrake
PreClick ok time 19.064899995923
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Setting flag FLY for spell Ardenweald Wilderling (353856).
Setting flag FLY for spell Ashenvale Chimaera (288495).
Setting flag FLY for spell Awakened Mindborer (316637).
Setting flag RUN for spell Battle-Bound Warhound (344228).
Setting flag RUN for spell Big Battle Bear (51412).
Setting flag FLY for spell Black Serpent of N'Zoth (305182).
Setting flag FLY for spell Blazing Hippogryph (74856).
Setting mount Chauffeured Mechano-Hog (179244) to priority 1
Setting mount Cindermane Charger (171847) to priority 1
Setting mount Crimson Tidestallion (300153) to priority 1
Setting mount Chauffeured Mechano-Hog (179244) to priority 0
Setting flag RUN for spell Dreamlight Runestag (312759).
Setting flag FLY for spell Elysian Aquilon (353875).
Setting flag RUN for spell Enchanted Shadeleaf Runestag (332246).
Setting flag FLY for spell Ensorcelled Everwyrm (307932).
Setting flag RUN for spell Eternal Phalynx of Courage (334406).
Setting flag RUN for spell Eternal Phalynx of Purity (334403).
Setting flag RUN for spell Frostwolf War Wolf (164222).
Setting flag RUN for spell Gravestone Battle Gargon (333021).
Setting flag RUN for spell Inferno Armoredon (406637).
Setting mount Junkheap Drifter (297157) to priority 1
Setting mount Junkheap Drifter (297157) to priority 2
Setting mount Junkheap Drifter (297157) to priority 1
Setting flag RUN for spell Kor'kron Annihilator (93644).
Setting flag FLY for spell Mail Muncher (315987).
Setting mount Mollie (298367) to priority 1
Setting mount Mollie (298367) to priority 2
Setting mount Mollie (298367) to priority 3
Setting flag RUN for spell Phalynx of Courage (334391).
Setting flag FLY for spell Prestigious Bronze Courser (222202).
Setting flag FLY for spell Sandstone Drake (93326).
Setting flag RUN for spell Sapphire Vorquin (394218).
Setting flag FLY for spell Scourgebound Vanquisher (414334).
Setting flag FLY for spell Scrapforged Mechaspider (299159).
Setting flag FLY for spell Sharkbait (254813).
Setting flag FLY for spell Shimmermist Runner (332252).
Setting flag FLY for spell Sinfall Gravewing (353872).
Setting flag RUN for spell Swift Albino Raptor (279569).
Setting flag FLY for spell Swift Purple Wind Rider (32297).
Setting flag FLY for spell Tangled Dreamweaver (359843).
Setting flag RUN for spell Swift Shorestrider (101573).
Setting flag RUN for spell Thalassian Charger (34767).
Setting flag RUN for spell Thalassian Warhorse (34769).
Setting flag RUN for spell Traveler's Tundra Mammoth (61447).
Setting flag FLY for spell Uncorrupted Voidwing (302143).
Setting flag FLY for spell Wildseed Cradle (334352).
Setting flag RUN for spell Wandering Ancient (348162).
Setting flag FLY for spell Witherbark Direwing (279868).
Setting flag FLY for spell Wonderwing 2.0 (290328).
Setting flag RUN for spell X-995 Mechanocat (294143).
Setting mount Chauffeured Mechano-Hog (179244) to priority 1
Setting mount Chauffeured Mechano-Hog (179244) to priority 2
Setting mount Chauffeured Mechano-Hog (179244) to priority 3
Setting mount Chauffeured Mechano-Hog (179244) to priority 4
Setting mount Chauffeured Mechano-Hog (179244) to priority 3
Setting mount Chauffeured Mechano-Hog (179244) to priority 2
Setting mount Chauffeured Mechano-Hog (179244) to priority 1

--- Options DB ---

9P1AV55nY1FrbG3V0V129sd6w3IO2cuuScwjw2raALw4yx09l(3Epd55m85v7MAhe)a(soC4C9md59X7
)3V)UF6NF4Z2)E3F61xF(X)8dp)W3E)39T3F3dV8PV(0lVUMYRV8XN(0)5JF(xE61xU)DZ7V7dp(JF9t
)2xE4hF(XpC))W9Fb)9U)8NF9Jp98J)Zp(x(L))O3D)Mh)4dF951s(0ZV(Jp88F7T4Px(LV8Wl)0JgXE
xQukyLF(Hp96lF79F)V8mg(6MU2rry85F61V(Yx(3(8tV(5N(YtBseB5qQC)7c4ZuPvNRplHroM3JAtO
U(mpZX(EWqVgB4FTvfgP0A00SeN91OPCQmptDpyUxc59uBXsnUN5yInBt)EiwpZS4B6ytPCdmZErTwOU
hnhBDU)RjuoJYdWOnsJ1YATY(dJOB2l3YPzxNFCU3S3mp3N5sSmhnDMQbYOLqHZCm5Vog1bjuV02hUXi
NJBztomkBEBnZj)CgdCc1Cm0oF2pFYdABUKz2OL0OVj2O01GZqmNoFMptLhL8m1p)ofuL4iTjqPUfoPz
RpgKRtMCIh(90IT5SM2IXskNjXt9oniaxYn3eeBoYee7jwJL4ESsBVFGdc99(v6H9qDUbPuEV)56mLOf
1OgQBsyJM36KzoNANbJoxrdsihgXZVNCPZy)zD2N0me2ebUOCtN6CTeLME2YtjFiNetZjTtxRk5cGSR9
6B(R1gf(vigl0GUeK4ppd03bh)YMtAW1uI3uOtX7m0MbNM0jR1du4aRu(ZjyzeOR9qUZ9ClrHBW1aPED
KDLFkYDF27(pxin7q4YpZvs9Ul7SJoJRe6Z5HJOZCz4YdifAuiwQ1Zb2zdiBCLiD3mwMUBWxprsTMWE0
AFloR99zSboBFUtZbesyDBL(E6nzO0obbl5OhnlL4x14Mbt1ABw9J6M02M042nR8qnZb6nBNuPKtl3aA
zt2303xg0pEdQrruVr)87B5ZSxBbF3jdd1uJmcwZEI2HLYcWhUbCAhsDmMYyPu7CWuhXCkoXvu0LzL(5
(zrBXrVm5PewDrMXy0LDJDizSPzOtFgJMrAdmNzfppj(CosHdFqR2Ejkt1AU12R34PgL85wPFz0(zUPZ
Osq0tYEcPbOrwPl)R4sfVTJ4bzoe3hNiFGshc2V6uNrPTZmDgMb5lHPwvCmySOSdfWZ88d70SVP7dcSA
QkKANJzcIk9PrC90zqEIXVwipbRPOSaP(c2sEkwlBHYRMuMf7W3LW)c5PuCnZTgToNZ2zqEI6WNKbaqc
8C3fjKNWFcNZu5mtHGiMgU7x)KHpllkBVModUzLYmZiaRzM5ppv8ySMl8phfzd6rEOlDL62g8WFNZhD6
H5wACMjnthtT7yIDxooDMJhoZirR20tUWzVpWitjTbXtbnZqzN4OwKSF97rjXQupz6(6H7isjZWUkEI5
CngvXHI1v6eEovS)e4AfqmuiULmCmixBqLeAgCcCqFW9yFQJ1O88RzIQcjlhJZmBNF)CSLdL9PNfuEei
AskiB6P8yawYMKwGVh05nficqe1CeDZFAtTMPd2tGgltEuw)mpvhp616Phns8ZuvTAHHPwRACwffX2ND
xSupdspre2o48x3H7K7oUobcZCK5VpkU9Tn125tTvjLnynQaGvJhUQEzv0ATRqw2GJJgwqdJfpTfcyVp
lWW2J5vsZyGJc4M0AygNcnpSX3h21Quwvm1QlH6N1Vzq4GfolVCwZLzYKlZ1AIl)ovRc(dTLGLQc)zRz
6BPeuG67fbfTsmAlV77jXGMQJqJhedEu8SvmHisYop7fdWebaHbXcnyk61mNNz6gaYVZOQahMhhBXsiD
wLa0oNhTkQS6qa5caSZ5ZY2ct4ygd0WerfP10AcufJ0wuBVO7rWNVSBQshveMjUNhjNYfcpNlR3TrlkI
rlMNhddMAaPQR9YHcJZOvNyukTgv4mrcVTfBj2vEiGGGO8wtLw8i6w9WUkJlGROq1ZssGyqvve4Gn4r7
PCMLHNZetGHNSTnF2aQgGjXCp1EnDrYWW(a(BIiLb)r7iJsfjJtHdnvEwinPn7iiebGt6sChQrwnugzm
RhdjbUX(uaqdjVe6zJGnHdWGUViMy7kpCS69gdSR80(peSl5tvfzB5WeISqnCSpjSeJhvG7wRsJdyD54
oMn3IOfPnPjAI(VZK9aFrtqmqaOq3xfv4OgMX2ka)yL7f03Y2caCKmmkds4EhvMtuNpfwHEIvYzmD7W0
uab2BC4uQnGNO(DiRvDSqdiZLETh2InuMSGpNoqAXUQeJqQXnW8Z4PcqfvDsrfxFTEAzhNQjjaAHk)eY
eAzBkqsEevEZiOG5m1uqoY(cTOjJiahpwMpOukWaR2IshcqVFykqeEXzmhlNjq4wam9LbR(QyPr2(ofF
b0ltxct22wv)CSUqlQxDOnRbvfIr2fl4poUWvCxTJOqzyvvCrUT5qd5XLvj8OaYbJC3b4i)eOMBHGUnQ
xGFC)qFpcDlQOxTgDyBTzqj59(CTiA9iHe2bGxYrco9UAbYoptOF(09TfKRyiLjqhJz9AnRXJGVCwu0f
X5ZGjxeNDthbADejIQ1m5Iqf)bQmZdwcOPQ9Y6SE9jEY7CbWojuiWBQFw1(qn75tprBPlKIIny5ZqYfV
ZblUIU2MKyEe2hbiX0T4G6zzhXAxvQaLC8mHHlHzGsJU84yhSlt9YMjYUkVHcoIAXShesHacP18vrtpe
gIrmw)on46nbQlfZQwna7wnfATdPdTYNLP0HTUhveHvcN5woZLmMn1WHZpgQezpsreOtrecSHWhm6sKN
raaMYlLyyp737xiRsuMv3JmLoHPNQGlzMLYUN4l3kgIAPfeuKEMOWwl6ODP91SlhCJ(Q)T2uPygH7tht
jMEgzlYk5R1a3dbYhcidyH4ebaJmk7AQ1Zupuv(sfMzb7JkJhydOr9Is88dfEHsWApk7)UGKy0C6Zukw
7330VoAQr)qR49PFgk0ibgdkAkKvkUMnHYzz8OoqYJP)jTPbhOm3fSzuwKv3KtgkyATK3ixjvLflaz4O
ZhQJpgvvHotVLkZzu(92u3RcoevgcPB81E9bDxlq8newTwq1phHpF33jg2ZOjvW9QQ)ixIseBKFqTkuG
0ycH7zuLM3AjZUKUSi(LaebTUc2J0LQswuhumDOA(mH9EbLISMnbWjCQqeHDvvAIvXOs16khgL1kUyfU
HctaGkeKkYtCa7LSlRoGzhh2wTqXgDRmliAUlSb6UafbOstP4HtkfSwf4mkVTS25Z(5tUfi6KxEck5i6
hC(vPRsWGXFmk2T7LGb0bu0BDgxOYSwFVv4HvK)iNj3k73vgLzBEwenDl9HuTOyCv4BX7XfiLSmTPQIG
ZcaLrlw6kcPDzmIkgLy69BaKsygqLLPZCPbnQKtrsXM2ANj0oeZndw9wC95S53FvpYdgcEP2merK0T(c
G5d7bTgY5NqH1RxiKHuiQ7BarHur(iJDKMiz1HHvabLOOugoc6iBRSDvkEDX9MkKCBpgxtvf0TqZZdnC
ZoMM5Uo)WCI0cWa8BieJYeuWLNs7iSHuzutpXxmxekCZKxxVsWA5SVfjpaVuxqWSj1AMBgVoN8iUscZp
nid1drjFNYz1OueZtMMiujTYrS280lzzYUYLHksDte4z7oAOe76eIWeozPl0v1UXmcOlAQEkLQz1Hwur
qxnWWsUx0eulUGRUUAKvYRl482F2Z6wUrrbf5aN97NWQ6GcXqqo1grLNay2Iu0DgkyDRfKbGYt3ZQDYf
sbeDvNru7SQ8v(eta)xQHGSPmj7wAzy(36JvxguKKCKAjRMeXuWrFZjd)UkqoGQoPqFsb46A)y4C7k(I
NtLashfqzlJP6UmqmRoanZYki7fi15n7Nkasnl5jTm4xMtv1cDljnTYT7FJbDlDMU3mHVuBJxgt2VZOU
ApfSjgUdxLxXMfUG7eeeoEKsv31H1eDsvd8NuimG4SRW8R8acQCxGfmzJNaBoAkrHbyz)Pbr4ysOdDiK
ZKb9lFZCw6kX9uTRXuzkRfQ5oRJIUN46SDEdgQ4qiEyP4io9y4gkbhLxsBVr0l1HsTF0tXdwEeUO99uH
DpDFiPARAQUeJQ6OMJkEJCVT2MROKT(flEpmnnZT23U3fZ3wYX6UTzHTsrrsqY5PdYFEmDznGWjIXDTy
D8aH0scnQvApLtPGEcirCG1LoHQHzWbZ5xMpwvrmQgY92KLyvT3aqKL5vrxg0IvNUmNnBd2r0LXQXLvU
htE)LNRBkBXQoW88bidkXNTudqfvuaKIAYS4lZZ96TRLAlZHfVYnA521T2BMNcx9WB)gmuP3BoXGayJy
XqRqRmmmIIO(Mct(5fwTFiA9OG8KjQBKlMDSPRnxkarCkVleD6FVUU79uHArVOddv5bNv9ibiBLthCyj
bwTeImdwcrKscLYCQ(DaOMjpubLRzi0utfNaiOSfAExmSuofxexUSdKcj9kKqe3CP5mlL2aiAHslRHkI
xADvuSfbSFOQs1Lc8URScDPWCwuBdxuTZ9ki)P02ZlSTwNNzoKWQQs(SgHq3TQEwjlqHYZmpsETvkT66
9Aup2dr(jGvlfxUYyilrWEZSxmI)yc0dBzvDKJavDYhGUK0Wmy9KarLIZOQC57rkSqEBbEkDjDJcmAxE
PI3p7npmrGhlJP2hfKQ1FKiZej)IuCpHEJgHRYcOiUmiwvlcA(yyP1d7cMyCiT6cmczAeeQt6x83Gqdq
CKX0SWc9TDQFojkT)qTFd)mHIauvQUNv62toSlTRwqX9NmxwxILDvp9JWFVKAP7ny2VPiJrU2igvWkoi
7pThVsCt0I)izsOg4a5UMIwnt6XqyNtfbBwRhdv30q3FWQjbBMQJOLuIz4p0X0VPkC0DGowcC6ZynNTr
cmfqpO88lCp1vIpdRAwJQWcl1dLAgulQjtj9uBCq827pjqHMWvdY4hLKF9zlSgQkHS6pDHHLTE6ZCbq0
3PWnwuQydg6w6HO6AFmkY9jOEezaDyQkZhv2lWXAZ6Rg)qrQn1Xr5pPUDYkJwtTEOQ8macabjF4HmRiw
7MdAD9KFSyRBtxe7zM8Y4KxOLPKpaga9vEXOAMIQBXk3PFMRa9pv53idLYWddib7RMv7ywn)t5sM69UU
EhNCcgSiUVv)DM6VgbRXtucxR6f(KmG4KRAqSKPCRRUFw9NMlQ5NyrsNxg2kqTaBHIc2hftfUvrwJPOb
q2BTOz8DsqRuH22tao9HNgqxZRHiua0Y6b6z2PAWzxpANPEvB2TdnjXTSFKn7dpCw0Fyk2Up1eAYpd22
mIYOL92TkdDavkO7L1QcR6QmjDqajLoyMppfILF2AWsNDEfd1zXJRwdpPIEm7YdiKyRrlOS4MeGz1pw7
zdsB1AJONxvNQz63)NPu4zbe1bvhMuPdHP69CzJf1geqad0ddH30XQbR(tEihmAQTTk(Y9395V(mFr47
)3D)HN(tp9LF7)7p98x)WJF79)3p)4)ZJp)3L)JF79)J)8dF9JF8XV(5h)W3E))YJ)0p)WlV(D)tV(P9
tp)V1RIF9a057o)Vy73DV(8h(HRB4APyWF3Zp8jq)x(0(NO1M9k2)H)(F))67(HV)389V73F)DFhM(74
RPb)4p8F8on2(QRWy)U)W)fhJVVSBgJxx2nRLfpC782gC)AmWQc0BzGnIMBgJ9k925TlF82nB31L3WOR
x3ZTJTalE7zCJJ4MTyF5I3meZiD7XENJ)TKZau)goz1FUBpzBCT3mVD2IBpSlCKVrrTQK62Dy)(dERIk
)xD(3xk5Bw76YWVLtwoq3oT9R14nC3QHPVrOui5Ui82x99TRDhn(xX(yFlF3Ya73aYTB2Ud73mV9ZK)V
sk2FRk2Aw9TBW(PP8RWr7BH(gAS7))BeWYG9IjX(AoEZ8wp8YRKt)9()Vd

**Comment by mbattersby** [comment]
Thanks, I'll have a look at this soon.

But also you don't need to make a rule like that. Since that is the only mount you know, the chauffer will automatically be summoned by default.

**Comment by mbattersby** [comment]
This is not really a bug. The simplified rules interface already supports "level" but only for the case of no arguments, meaning max level. When you hand-enter an advanced option using "level" and it goes to display it, that's the only thing it knows how to extract from "level:1/9" so that's what it shows.

Even though it's not a bug I can make the display for "level" a bit nicer, so I will. But if you go to edit it again, it'll come up under Level with the only drop-down option being "Max Level", and you'd have to select advanced and re-enter it. I'm ok with that.

For people who want to really use the advanced mechanisms, The raw action lists are fully available under Advanced Options. It's ok that Rules only supports a limited subset.

**Comment by mbattersby** [comment]
And, as I mentioned before, a rule for Chauffer before knowing riding is pointless because that's how LiteMount behaves automatically.

**Comment by Raydor** [comment]
I have seen your change, now it appears correctly with "Level : 1 - 9":
![image](https://github.com/xod-wow/LiteMount/assets/2204071/0af1bc9d-4f35-48fd-9816-e3f9e05de886)

> But also you don't need to make a rule like that. Since that is the only mount you [edit] can use, the chauffer will automatically be summoned by default.

The thing about this and why I reported is that yes, I could put Chauffer and it will be casted because its the only mount I know (if im lower than level 10), but after learning Apprentice Riding, it will also be casted randomly alongside other mounts that are faster, thats why I want to have all my favourite mounts enabled (including the chauffer) and automatically exclude this mount after learning Apprentice Riding, so after that it doesn't get casted at some times and I don't have to be disabling chauffer on every alter after reaching lvl 10.


> And, as I mentioned before, a rule for Chauffer before knowing riding is pointless because that's how LiteMount behaves automatically.

Im not sure if LiteMount behaves like that automatically (ignoring Chauffer if its enabled with priority 1 alongside other mounts after level 10). If this is the case, then it would be nice that it gets explained somewhere for this mount.

Ty for your fix! 👍

**Comment by mbattersby** [comment]
> but after learning Apprentice Riding, it will also be casted randomly alongside other mounts that are faster

No, LiteMount is aware that the mount is slow and won't use it if faster mounts are usable. Doesn't matter the priority, it is never used if you know a better mount (by default). Same way it won't use a ground mount if you can fly, and won't use a flying mount if you can dragonride. This the base "use the best mount for the situation" logic of LiteMount.

Happy adventuring, X.
