### ISSUE TITLE
Kalimdor Cup error

### ISSUE THREAD

**Issue by leemitchell25** [xod-wow/LiteMount#161]
Hi.

The [dragonriding] condition isn't working for Kalimdor Cup races.

My Advanced Options ...

# dragonriding abilities
IF [dragonriding]
   IF [mod:alt]
      Spell Bronze Timelock
      Stop
   END 
   IF [flying]
      Spell [mod:shift] Whirling Surge
      Script [mod:ctrl] "/use Aerial Halt(Dragonriding)"
      Script "/use Surge Forward(Dragonriding)"
      Stop
   END
END
LeaveVehicle
CancelForm [nofalling]
Dismount [nofalling]
CopyTargetsMount
ApplyRules
# Force ground mount if in a flyable zone
Limit [mod:shift,nosubmerged,flyable] RUN,~FLY
# Force interactable Ground mount if in Nagrand
Limit [mod:shift,nosubmerged,noflyable,map:550] 164222/165803
# Force ground mount if in a dragonriding zone
Limit [mod:shift,nosubmerged,dragonridable] RUN,~FLY, ~DRAGONRIDING
# Force waterwalking mount if submerged
Limit [mod:shift,submerged] Limit ~RUN,~FLY,~DRAGONRIDING
# favorite, faction, racial, class or profession mount
Limit FAVORITES/{FACTION}/{RACE}/{CLASS}
Limit [profession:Alchemy] +93326
Limit [profession:Blacksmithing] +213209
Limit [profession:Engineering] +55531/60424/44151
Limit [profession:Herbalism] +223814
Limit [profession:Jewelcrafting] +120043
Limit [profession:Leatherworking] +213339
Limit [profession:Tailoring] +169952/61309
Limit [covenant:Kyrian] +180764/180765/186482/186485
Limit [covenant:Necrolord] +182076/181821/186487/186488
Limit [covenant:Night Fae] +180413/180722/186493/186494
Limit [covenant:Venthyr] +183715/182332/186476/186478
Mount [mod:shift] RUN
Mount [nosubmerged,dragonridable] DRAGONRIDING
Mount [nosubmerged,flyable] FLY
Mount [nosubmerged,noflyable] RUN
Mount [submerged] SWIM
Mount 
IF [falling]
  # Flap, Travel Form
  Spell 164862
  Mount DRUID
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  # Goblin GliderTinkered Cloak / Kit
  Use [noequipped:169223] 15
  Use 109076
  # Last resort dismount even if falling
  Dismount
END
Macro`

After I enter the race, I'm mounted on a dragon automatically by the game. I use space to 'soar' and the litemount button to surge forward. So I start the race by 'soaring' and then hit the litemount button to surge forward and dismount and fall to my death. :S

I was able to use [aura:Riders of Azeroth Drake] instead of [dragonriding] to successfully use the litemount button as I intended but it would be nice if the [dragonriding] conditional checked for this as well.

Thanks in advance! :D

**Comment by leemitchell25** [comment]
-- UPDATE --

I just used the 'I'd like to pick my mount for the cup races.' feature and it changed the aura.

These are the auras I found:

Riders of Azeroth Velocidrake; Riders of Azeroth Drake;  Riders of Azeroth Wylderake; Riders of Azeroth Slitherdrake; Riders of Azeroth Proto-Drake

(I don't have the Aberrus drake transmog so I don't know what it's aura is)

**Comment by mbattersby** [comment]
Yeah I know why this is but not sure how to fix it yet.

Because you can't dragonride in azeroth Blizzard added a second copy of all the dragonriding mounts that only works for the cup. They're meant to be hidden so LiteMount ignores them, but that means it cant tell you are dragonriding.

I'm away on holidays for a few days so the earliest I'll get to look at this is on the weekend.

**Comment by mbattersby** [comment]
Should be fixed in 10.1.5-5.

**Comment by leemitchell25** [comment]
Yep. All working great now. Thanks!
