### ISSUE TITLE
[Request] Adding Spells

### ISSUE THREAD

**Issue by RAtwood90** [xod-wow/LiteMount#162]
Hello Mate! Another Mount Addon got it already so it should be work. But this Addon isn't get the Attention on Updates like yours and that since other Years and that is great!

Can u please add Spell Support?

As Example: Then u are an Mage and u can't Mount u will use "Blink" or as an Warlock if u can't Mount u will use "Burning Rush" if skilled etc. same for the other Classes with there Mobility Spells.

I'am also here if you need an Tester for that Feature/Function cause i got all Classes on max. and also i can tell u all the Spells for Mobility u need to know.

Would be really nice! I like this Feature a lot in the other Addon but like i said it's not getting the Attention that it should get so it will be every Patch more and more outdated and not have all Mounts :/

Thanks Mate for your WoW Support and make WoW Life things easier!

**Comment by mbattersby** [comment]
There are already at least two ways of doing this

https://github.com/xod-wow/LiteMount/wiki/Unavailable-Macro

https://github.com/xod-wow/LiteMount/wiki/LiteMount-in-Your-Macros

https://github.com/xod-wow/LiteMount/wiki/Advanced-Options

**Comment by mbattersby** [comment]
Since you didn't mention what the other addon was I have no idea what you are talking about if it's not that.

**Comment by RAtwood90** [comment]
> Since you didn't mention what the other addon was I don't know what you mean if it's not that.
> 
> If you mean, can I make it do that by default for everyone: no, sorry.

https://www.curseforge.com/wow/addons/bestride-mm

I don't wanted to advers. so i didn't Post.

It's just Categorys (Classes) with 1-3 Spells if u can check that Addon.

But may if i read it correctly i can do it with this https://github.com/xod-wow/LiteMount/wiki/Unavailable-Macro
Like /cast or use Burning Rush or Blink etc.?

**Comment by mbattersby** [comment]
Exactly right, you can set the Unavailable Macro to whatever you want to happen when you can't mount using all of the normal wow macro facilities. E.g., `/cast Blink`

If you're happy with Bestride and it does what you want out of the box you should probably stick with it, it seems to hav been updated less than a week ago.

LiteMount supports a lot of different things and ways of using it. The defaults out of the box only work for me and anyone who wants exactly what I want. Everything else you would need to do at least a little bit of configuring.

Happy adventuring, X.

**Comment by RAtwood90** [comment]
> Exactly right, you can set the Unavailable Macro to whatever you want to happen when you can't mount using all of the normal wow macro facilities. E.g., `/cast Blink`
> 
> If you're happy with Bestride and it does what you want out of the box you should probably stick with it, it seems to have been updated less than a week ago.
> 
> LiteMount supports a lot of different things and ways of using it. The defaults out of the box only work for me and anyone who wants exactly what I want. Everything else you would need to do at least a little bit of configuring.
> 
> Happy adventuring, X.

Good gonna trying that and see what will happen :D

Any chance on an Support Channel for this Instead of Github for asking Questions?

Also about BeStride the Addon is good yeah and it was updated before 4 Days yeah but only Minor fixes and adding Burning Rush for Warlocks.

Still many Mounts from the new Patches are missing Example the Dragon Mount from the Trading Post :/

So if your Addon like u said does it with the Spells i will stay with yours cause that Function is an nice to have.

**Comment by mbattersby** [comment]
I don't think addons really have support channels, unless they are really really big like ElvUI or DBM. I think people tend to ask questions on the comments on CurseForge, or otherwise as on the reddit r/wow subreddit which is the only place I know if with general user wow support.

I don't provide support. At least not in the way I think you're thinking about it. I don't get paid for this, I do it in my spare time for fun. I wrote an addon and a fairly large amount of documentation. After that you're on your own!

**Comment by RAtwood90** [comment]
> Exactly right, you can set the Unavailable Macro to whatever you want to happen when you can't mount using all of the normal wow macro facilities. E.g., `/cast Blink`
> 
> If you're happy with Bestride and it does what you want out of the box you should probably stick with it, it seems to have been updated less than a week ago.
> 
> LiteMount supports a lot of different things and ways of using it. The defaults out of the box only work for me and anyone who wants exactly what I want. Everything else you would need to do at least a little bit of configuring.
> 
> Happy adventuring, X.

**Exactly right, you can set the Unavailable Macro to whatever you want to happen when you can't mount using all of the normal wow macro facilities. E.g., /cast Blink**

Another Question possible you can make this available for in Combat too? (So in Combat u can't Mount up then using the Macro u set) Notice in Combat your Addon does nothing sadly.

Would be nice to have only this then since we discuss the above one and that u mentiod does what i want to use for.

Thanks for this Addon Mate really Great!

About Chats (Discord etc.) it's depends on the Author if you got one or not.

It's your choice there u give Support/answer Question or something similar. All Up to you Bro!

Stay Healthy also your Family! See you :)
