### ISSUE TITLE
Keybind in 10.1.5-6 does not work

### ISSUE THREAD

**Issue by Kanegasi** [xod-wow/LiteMount#164]
What happens?
When I press the mount button, I get the "You can't do that right now" UI error.

What did you expect to happen instead?
I mount on a dragonriding mount (happened in Nokhud and then tried again in Ohn'ahran Plains after the dungeon was over).

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
Yes. This just started happening literally now, Wowup autoupdated Litemount and I reloaded before entering the dungeon by happenstance.

Please do not modify anything below this line.

--- General ---

date: Sun Aug 27 22:06:44 2023
build: 10.1.5 | 50791 | Aug  4 2023 | 100105 |  |  
version: 10.1.5-6
locale: enUS
current profile: Default

--- Player ---

name: Kanegasi-Stormrage
class: PALADIN
level: 70
race: LightforgedDraenei
faction: Alliance
spec: 3 70 Retribution

--- Location ---

map: Ohn'ahran Plains (2023)
mapPath: Ohn'ahran Plains (2023) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Ohn'ahran Plains
subZoneText: Maruukai
IsFlyableArea(): false

--- Debugging Output ---

VersionUpgrade: 4
VersionUpgrade: 5
VersionUpgrade: 6
VersionUpgrade: 7
VersionUpgrade: 8
VersionUpgrade: 9
Initializing LiteMount v10.1.5-6, debugging enabled.
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PostClick handler called on LM_B2 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PostClick handler called on LM_B3 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PostClick handler called on LM_B4 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)

--- Options DB ---

nUvwpYXrY5Fo2gWlrEF8Oo9AijkbnCnG1ddMMInjBOEMwUNzOG8dZVD)fvgFrugy5ITFzkMvKrg3xzXB
J3(MBV5x)4HRYF)6tpE43)9Rx(0HZVC3F5L7U5PlxV)6HpCCdOlp8(tF4)641hpD5HBF982NU9MV7Wdh
)WHhp9ph03C6DhF8Jx(J)PGgW)HZxE7HZ)DF)nNE4XNo8WVE8r86xhfk58P7F3LR3(6WT38nhE8PJxF4
L7(Utp8H3D5(hV91P6OD7nXWRIVQ(YDV509hF5UF(07F6XnI5hE(65l)6l39V(f)V3Fep(0h)3WP0lqK
C46VD)LlaxF7HtxpceHF3EZB(i2)nF8W7U8hNp8W72oGgiRV4ThVE95h)3F5UNCio(UxU7RU(8VE6TNb
cITsg07ZNfY46bzRTC9ZtBV5eyuqA)TZV741fLn6Gj)jCUhUE6GC0rC0V(45NGE85nAjbrYp)8B)ZxU7
7p9EGUF6YLZlPq)ZFs)8L3E5jri8QF5vFZR(5x9JV6nV6V(kCEPSik(LJxp(0hHW6Y1NoTHSz(ZJSV88
HF93E5UV5(FhITnj7)Z)Is(XrjQIW)2dGPWYBy7FGq4RpEVOdawo(hxpSHLuPi6hycjV5)8XZWw41Xqd
l(dx(WZBlbre27HtNHG4lUE8WM0hQVFrKDNHrVi7W)()46gKRt9lE3No(WtpVPSRXMsPV(YV9XNbm)47
F)XhE80NK3wQIy5W1dNpcw9Ro8jy0D7RBfSNV(4XF)JxoF)MYaARV8kehhF4JWf4L7(RxoF(YFaIjkOh
SWXhGL7Mnp8(E)PZh)UJ)5J)J9iXj8(dpF(Z7e6a8z87ma8JDDM6Y4XRhFeGF8BXwE82V8VNF47pF4dF
1hp8WhwEI5EBcbk263(9)33EZFzXu3F55hE6NUE6Y1tpDsDzB5qQiUUVoMkT6C7XsyKJ51Qca1ThZZCS
Vwm0fnYAxHb8eLhtZsCUaiLtLPd6Ary9gYlqBXsnUGCmXHPVpeRoKf7qhlmLBGywBQ1c11Q5yRRN)gaf
FvLbgTrAbBRvggsxKxULtknd(h89cWzEUOKsSmhnYt1GrEkMAJP(2XqCQ3quV0wm3yKZkBMdJsXHCsMp
guaQz404p29hvAUnnzwjn6lKnkDU4meZj)XSdQYk5zQ7VxfuL4iTqqrLOPzRpgKLv5KW8lWIT5SM0nNY
zf5PExniavQhUiisMGybynwIR1kT1Haki01h7b9V6bKszvpvNPKArnQbsay18AlZCo18fJgv1n5Wi6Vp
5RUESo7t1me2eb915g56CTePME2YUurT9sZPANUTRKjauKcTNkGATrrFkeJQnrRqdAWXb13bSFzrjiww
LI3uORI3zOndgovNSwpOchyLQVoblJG6ApO7Cp3ujkSnPgi1RJSP8vlJwzsXiETssPoeU6J5QI9Uj7ew
xJRe6ZPtrQZCzyYJq0ILuQvNHnYaYM1JLeD3eswD3GVEsr1gaRvRkdv7RZULBQfyAoGqA9sO0xp1OHsZ
dcwy4orsKiNgvEUIcnQgRwTdrzkearzQzoOEZcN6mv0THvYx037w0yVHQrrupYZY7xOA2RTGD6UAQ1S9
mmMDA0HzaRHjhJjnwkvg7m1NsUvICgf1mRKx39nP2vLPfXofvr4Ot7gHjvSpd9OJZ4ApWrkN8TVOZ5if
C6WSMI0uTMBAixHMuwh5dk9DR2Dyt(Quq0tu2I0aQ(O0P)vCNkwzK5GuFCI8b2wQQjGGDnkTWZQZWmqF
jWPvghdglm7qb0SY)WonBh6IrGvtLHu76AIGOQYEexp5lQCmEBrT9H1KkranPjBREkwjBbZRMyMfH57g
D4OxLIBqUOZ6Cs)tzrLJ6WNuvzibUAIkIe98Jijx14PIdjRGiMgM7x3ZWNPfLCwMxUACvMzJtaKuooz8
ySND0pRRaequz6sNPULfDzUZFQfbm306l2GunthtxosPxKwBcXPmNyKWDl6jt4SohyKXK2a5PaHmOYPA
HY(T3hPeRQ6jr3xDQlXe3Dn2fOPUlfzCOy1sNe9uOjq1mGyOO1TKHJHs1sPsSAgWbwrFW9yX1XAKE(1S
wvfswQXN2GS5V3zBg4wE0YcspcenjzN6mVttYevGUhk3MyDBiQPxoqwTP2G0k2JfnwSYMKxRCL7rVTF1
Jgj(1uvTAH1ii7A47Q5p2nXIUPqqJ0hru7GH(EYF0kRJHoe)y9XrXmVfqB(JKb6XUV4WoENMQ72KAR2z
alzrvOjIhg4mwSKwiCntjoTiEL0mYAcqXMQTWmozT8Wcp47Q6GwncS7lUiq4Ef8Tx8xVdsWF4fTj3d86
yAC8JrPtwuCzpt7ivvwfyFTjOMzArz7(bXQfRJGMjokfhfDy1daPyN(zPHxIO8a1OdbnMoKthst)tVob
RS0WS1ybCQB72flNDoDTk6RYrquxfvoN9TPM1neKHDJHS4nhavdHKwZQJ3DYJDNg7ZHTGjI7DKiZec)M
D7Fy7NXlAX80nmybafu0rXXWWx1HL5iKvzvMiD3sIwIDAWH6hSGJau1IhX2Qo5sbMaGEyZsILWGEQA(I
72fr7WYycasb7yDzVMMsmjMlq710ojdd5GwU16Kb9P2rcMyymMOyBpAWtP7CftJaRhausNI7qLILmYxA
DWez3kBpYibHK1a9SP1BbhaEAiIyBpn4w92ybS(oLyD(HXwSLmySESqn4YiTOeHgzy7wtl)b(DrRQJzZ
SiAr3Bxpv59AQEuDrJfyGaqHUTlvHJoy0g2XlRvgSosBluEdLHrAqc3B29G0LpB0QZiScr3CIEWhtdNs
vTb8e133Iw9vqbqRLETh0sstSZ2nm1TdLPfGqtXV4MPmfQtKnjfTMSL97hQA4G6kyVNqKu8Cvk6rqzM1
cwqrJ9ArhPAeb44PP1aQsmQKSRKJbDvykqVWzmZkSIS1F80S4BQABAx04jPlSjMxMD5STRUZw7W1W4RO
VOAkijjwlIoSI(MAbJdzjgslf7KBlkuk7q3vVn8kKlCoey1HXbCYwiMRo3e0wyT743CsBmhp8lv)1wBY
wAY2qU2qQ53K4PIkVQwzGtBKwaTthGU)O5ABo8HuwdzuTesBZpYf8fFtlreIWxY7wvJpdzC2Pq1XBeh7
ou99iICWikgqc6ARPozsFKOS5wGsNY(539DXQeZ(erBPDOsLBW0xvHfBUbBuLQnerH5qfBUeSNCkO6BZ
LRD2Nc0YrhGHH3QBAOSJWy7aD3Hr0YMBK3RopIbbRuiGqAnBxQ8eHHgn)9kQK5lRcXyoBDKh6wPCXMv2
cWv23wARSmyI0TOIiUIR8gfhwDBcO7WRBPQ11Jueb1Ricb2G1hm6uKNreaf2uA373tUmrz2YUJ2jzfiv
qLAMLInrCed3mpTi)PEwRIFBtU2vTVMD6HlgvQYTN5a3fTu23J6Rx5UHbziUB77ipA(Y6nr8VOANTbk9
1dSwkbR0tIXQW5WumOYa1KEdtk3d1nhpzLD7I(jzbjcoNgKuTkVFH)6OXH8dDInJ(zOqd(AGr4RCulBV
V47s50bYCmThZgbW02fCwdtOOqkLaRmD2kBvWkZCwsSJ8iIKuCSAvHBttzoJ0PxanQ4Aw14hDHUw7pWR
zbsp2eeeRS15iC472jLDCQ63ELr6YLiLWc6v(Rc9xurABMm9BXnkv)vyuZQHQOAcLMrYs2elAckMCSMD
awNfs102rRQOiZ(rYyn2Vl2KgrQwTRMbI6IPlyYSKCNjbFvfayTKnrLxildij4F4RUiQcIKBYAuzhJtI
UmPAfoOkALEVN(2A(J7q2ABOTdMKhnBen2wFQ0l0Th1OejX2TMVqHbC6fb)UgKrERlAX8fih(75MMEWm
o2v4ynOEfTHBJSWMTfqL11caLT)cpttBu44JB7xJ5Nq1k7qfdHGEktoSQ1m6HJXqXH2Aoanhz7oc66nB
29w15mlrGl6Ahrm0LGbbJdUYslxytdXaMfgpme5nnGyqAqabYi1W5XUP605QjoS8c0GC(EHjV2s5YX1J
YShrOvoGejklJncVmoGfzvcaerQsgLaODUH(hSjol9JPsayfXkQMwsVyUWsW3AZ06gOpPwaopk7KNSCC
01KD1QbwDMSkjb5rv1GUnS7fkXKbIjdDfrqpgbf1)SqaI1MPjbckZbdif2U7rlXn9eqeMWoRAotNSxmO
O9J(QQbiisnU7yYS5TX24tksWKaVtKTAl09ld(xpa8J3swnvOlCozrERLO5bYRiCdTUzpRtPj3B96rOO
RwQFwS1w7lmmTmShDB9w3nBx4AcZhfvOdBv5lswvHHq70XuYiZqJrRcouWULXq4bNcxRwH4slEqARtFD
ys3YjVQPT9ObEKRHXZywSyi0VQo7Somrh4fVKCDy2Rnw1SYaAPiUSnOOYgdyrrl4eu0cFnACvhz7URGH
QJlReu2hcCSzZKBjQzPZ8oDKRK1soGaAMimBZZa5mz6De9vJTjwbQ4sIJRfybrd7xxm50awD7UOKceTk
48VJIqMLDy3)2wt6RfrlfSzUcVyty7xy8UjYjhjszttYOzjB5ZkRAJ0PAv6zdlqqPQRenSQwIwEE0N4q
TGGWHddjgYrBcGb90bDWoteSw1f7QD9SZuNYCzdgk1xlPo51gJiSlzhQ9rRimcDZS6y3KTzwhe6EyA15
RUnW6G1Hkzw3jquScLuS6SKQ9L7qvTzGmXREPe2vulnqt8cvq5JjA)08Hzx4Sbl82G2i1P9On0tuEln)
gHDMuSMj4jOEiyp0f2RObMEfR)giI1ObLK5325h0spA1oa5cf7sqmpiND3udBgC4qJRNaG29It83HUEb
4GTzSjOyeSoNg)gk1uOn(DdjJwGDVie6UtN1qeR2hNs06DwQ0NTQaXJ7ZS2LexD6yL(0PGnXwAElFmDk
zdAoAthi5FLuDomCKsmBrcGSyjvY(nBkgw8Btc7N0nAIMM7cEDV2fzJQY5baIL5dqbYmAOuiMI1ALxcS
eeE4i1RAwRfaT6QVEw4Kd3qQAnImtCiJJOn0eR)zbsgafTYvCwLHnzpXY1Dq3vKyBNloDBsCGXJEWxK1
ZT1QE25F6Jo44R3ovkkZrRqHSLqlAXAfJvAxwN7KQmisi6FTl8BXjZlPRYrkjxCjn0HYHHDcSPvzURrL
LrApA)mtS7jX)KaG6Vuz(eo17qRoEGg90kHO(A5J2XTPTSM5jvPb2Kc85NArsO8Imv(mbV0MuExmdLqG
Pdf5iQhB6xGLrLqWsv6fZ7NwTMFug0NIleQsl5tgMo9kLz2PM3LUnJz7UIe(NJIr(aquQvcvPuqcn9Qa
eYwvNjJBf)NLWAM4xdHiS45p5C7flvZ44)N)RgFtYjZOMDMmCJw1I4Tw(HXdfGXM9Hb0sk)lM3rLqsC8
Ks9h0pw(qXw7h9RW27LRRtPpevttrodCqPYh1sGLjNS7JPh3LY3Do43psSyFSh(qDkzJuGWxBuF77viQ
CvLx5fqanAf1F3yfLPHmDqAUqtrjPiLpt2g7MLaLP5XWTQASwHkhoQaktLL5xgMugVvnj7Dv(mMuR(al
LzJsPLw3CfrSrBOhr6lVn3(1QBT7vCyz92YWnxRoQwg(HmzQThrXS2TS2TYoTVnRTXonvkmyFxDSS1T5
RV2Umtf1TTWVgg5JsJv)zxaH8rSUZsIjyrt(7EKEpC45BjnvJIbtoS9r)r1RnEXH99nj30bB2zWCQ1(G
zeJwLC9cn(Lek8t4iBXRRt(vziQKD7Y(wiY8A)LsfyVJqrXuIcA3fam64D9yC0Y2mxnxvr)BfquS7IUY
VHhWxtPU08sSQ1hXPw79nIiddJoyjjsQl9WrZlfV(YM39bVXHMhDmB31NyrymDJxtTCnevdT7gqoLksI
spSoJ0Hqf7UGho8iPVl1SaDBPTxiTnT90t8)ihp9JpC(p)HlF60dF42VC7Jg)PBV9)l

**Comment by mbattersby** [comment]
Please try 10.1.5-7

**Comment by Kanegasi** [comment]
10.1.5-7 works.

Also, oops, I had errors. That's what I get for putting BugSack on silent ignoring other errors. Sorry for not posting them, I see the conditions.lua problem now.

**Comment by mbattersby** [comment]
Sorry about that fubared the release. :(
