### ISSUE TITLE
Support for Eve's Ghastly Rider

### ISSUE THREAD

**Issue by steveriggins** [xod-wow/LiteMount#170]
While in org, if I stand still, I mount a random flying mount.

While moving, I get a "you cannot mount here" instead of instant mounting "Eve's Ghastly Rider" which is instant during Hallow's End

**Comment by mbattersby** [comment]
This is correct, even though the Eve's Ghastly Rider is instant during Hallow's End you can't use it while falling or moving. It's plain just not as good as the old broom was.
