### ISSUE TITLE
/litemount macro doesn't work

### ISSUE THREAD

**Issue by karpana** [xod-wow/LiteMount#173]
What happens?
Trying to use the `/litemount macro` option to summon mounts, and I don't get a mount summond, instead my icon changes to to one of the gnome "mechano-peep" type mount icons.

What did you expect to happen instead?
I expect litemount to work and summon a mount according to the seletions I made

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
Unknown, just tried using this app for the first time today

Please do not modify anything below this line.

--- General ---

date: Fri Oct 27 09:09:47 2023
expansion: Dragonflight
build: 10.1.7 | 51886 | Oct 23 2023 | 100107 |  |  
version: 10.1.7-9
locale: enUS
current profile: Default

--- Player ---

name: Karpana-Ysera
class: PALADIN
level: 70
race: Human
faction: Alliance
spec: 2 66 0

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: 
IsFlyableArea(): false

--- Debugging Output ---

Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.11119985580444
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 0 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 435 mounts
 - trying Aquatic Mount (underwater)
 - found 14 mounts.
 - WeightedRandom n=14, t=0.800, c=0.640, w=0.200, p=0.250
 - setting action to mount Wonderous Wavewhisker
PreClick ok time 27.660400152206
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 0 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 435 mounts
 - trying Aquatic Mount (underwater)
 - found 14 mounts.
 - WeightedRandom n=14, t=0.800, c=0.565, w=0.200, p=0.250
 - setting action to mount Otto
PreClick ok time 25.888099908829
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.10979986190796
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 0 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 435 mounts
 - trying Aquatic Mount (underwater)
 - found 14 mounts.
 - WeightedRandom n=14, t=0.800, c=0.312, w=0.200, p=0.250
 - setting action to mount Great Sea Ray
PreClick ok time 26.288400173187
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Setting mount Winged Guardian (98727) to priority 1
Setting mount Winged Guardian (98727) to priority 2
Setting mount Winged Guardian (98727) to priority 3
Setting mount Winged Guardian (98727) to priority 4
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 0 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 435 mounts
 - trying Dragon Riding Mount
 - found 6 mounts.
 - WeightedRandom n=6, t=0.500, c=0.349, w=0.500, p=1.000
 - setting action to mount Highland Drake
PreClick ok time 25.261800050735
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Setting mount Winged Guardian (98727) to priority 3
Setting mount Winged Guardian (98727) to priority 2
Setting mount Winged Guardian (98727) to priority 1
Setting mount Winged Guardian (98727) to priority 0
Setting mount Winged Steed of the Ebon Blade (54729) to priority 2
Setting mount Winged Steed of the Ebon Blade (54729) to priority 3
Setting mount Winged Steed of the Ebon Blade (54729) to priority 4
Setting mount Great Sea Ray (278803) to priority 0

--- Options DB ---

TQ1AV55XX1)qka79l6BX1UjbUvOiYOfffLq02VsMauKoKuaXFH)2Zz29CM9nXfO1avsG8r7ZUZo7C9mZ
(Ct8MV7M3)d)0Tpz)(BV9PF(2hU91p87E9d)NpF5PBxV8Xh(4DF6F)YtpF3JpCZ7M38c(77)09p(93EV
9(N)YN)8Jp8p94xE4LNX))DPyPpJ38o8VCVn6zmeEC2lH26XwSKQ7bBHzTGPoms(R2O3F3dp)YTp8dx2
0Tuk38(V(PB)0Jp86h(tpFpgEXk)8tp(X7U)Y3E5xE()5dX7)6lF82VC)1tEntnmE8Plp)YJpD5F(XN(
8Z38v4))L9CExC)J3B8l(r2(rX(rf)4fB097)xTZ)RF4)6Z3(ZVnfYV55V89F(YtF6Yp(F)6h(8lVnLt
lkC90I5A9nF8(F52V)(lV5V8XF4T1wV148nXs(mFjjEBnh5mkXfN8VC3NV7L3FXM0pC)Tp)8B)6V53)D
)XV9D)P)WF87Wm)pU7bWeV(H3)Yf7xp(Xx)Wl)0Lx)W389Mu8RU)2F8Y6SOn6YF9LNUfNGuP3FZdpE9X
4UF8TJrClZF8(F8p)pkI()doj9)njz(3OKS8)QK83Ui4xBU(zJa)BpD3JpD3l3rztld6CZ7c4XuPvNRh
lHroM3JAtOUEmpZX(EWqVgBlxOykmsP1OPzjo3tacHYC)EBQD6Tvc59uHlwD7cMgtSzB63dX6zMfFth7
nn3aZSjFRfQ7rZXwN7)AcLnbSr3ZTKcH5MbIJ2inwp2ALHt)9Ho3YjY(quarWMtN55(4xIL5OPJxn4Ck
PuBmB8inQdsOEPTpNJroh5IdJY(WTM5KpoJbobO5dCJk4VBIAdswUnxsV97h9nTgLUgCgI505X8zQ8KK
NP(59uqxIJ0MafkBtZwFm0jMIj7SVpsX2Cw3CxUKYzs8uVttdWLCZn5qYLd7jwJL4MllTTsbCqOV3Vsp
WFVNsoLYunvNP0(X4OgedGrZ7LmZ5u7my05QTrGjhgrNusqzJUFSo7Z8E9WKiWfLBu6cF5sSjDwlFKkB
ojMMtAXUwvYfaKOq713RV1gLnN2cXinjALLPTTP5zOm1XVSpDn4KkXBk0P4DgAZGtZTUn36bk8GrkFDc
wgb6KpKJDp3sBVvyAknqQxhzXijAz0ktjgXRlu40HWLKpxdBk1DzND03ELiwWK7JXr0TUmC5bKckQsPs
pm7a7SbKnUsCUxeC1t0UE9O74mOxFTp4V37DdCgPYCaHKR03tVTmuOKEVIsjZqyMKiPtAKN5ATXqe2rT
6Bs78AEQM5qO7hv3ZA5he32JK)nfovE2GDD(guLIaGmeZ69Bsn712MNSTV7QXwZxdffZLIG8X0pABRPX
ykRLsvHrtDe0P4eFikQzAVwoyyrBPqVSCfSJoIFWKhJ(G2Y2HmtnrOhp0msJG5mRq7PiJ)mhPWHpO7rV
ejlH4KTw05jE0rQHs)Qr7N5MoJkx5EAWmwLcdeNbMrkAJlD8E)PhWCiUpor(G2H9Ro1zyA7mtVHzy2v(
MzLbkq2MMYouapZGkWqnldRYw8aRgUMbYbeDbrLo1iWE6mi1n4TfYtWAk6AE6avpzBT0fkfBsPwSdF35
dA1cYtP4AMB7L6C6oOyqEI6WPKQmKlNMOMiH59Jilx1ptLZmza)qmny(WCT3otqwu2EnDTZwKvMzgcyn
ZmF9KGjS1Cf)ligGbI8qx6k1Tn4rMFoF0IaMBPXzMB9mWfCKJ0YZKJtN54HZms0Qn9KlCAYitzTbXtbn
ZaTNQfj7xVpkjwLMbMUVE4ofhJvdTzQ(rmQarXQNqjMuSrKboReb5qHaxYWZGSTHvIJI9QsYclL5(9WI
KamHPFMWQq6sgGAnZ259CRaPuOB7r6BxsnA(JWjPGmQNYLb4kBM4kU57bJqNeWne2CSxKz)tJQ1mBU)b
JnvwaNeHyqc6sh46Plns9ZKvTAjppRACwffX2JDxSWGlHad1hry7GZEDpRqU7a7eiiZrMVFuC7BBQTZJ
ANsbITBn6W3)dtvVAveZqxHSSbjmkt(OqNXIIkuraBLvC6X8kPjtBgritw5bYsqexjaBVVpSRvvptT6m
y)m4MbHdw4SCUt2RVAMuboheBi87Kha(tMA6ux5RS1m9Tuckq99IGEorw2wE3xebHMQJqJhedFu8SvCd
qswHaYw2EcraqGodiSHq5IzopZ0naKBNrvMicjMvYJosKC1QOTqgq2BhcKpeqEaa8C(SmAx3qygMIarf
f(EBcBt8isBnRh6Ee85R2nvPJkcZe3xXIkxiCCUA9UnArbmAXvjzIdiIYcGDuouGlZg9yerP0Aug8aMS
mJsj2LbhqqKsNPslEeCJacx0kE2bUzZssGyqzvBH0AWZHuEhLHNZetGbZTTnF2aQgGjXCp1EnDLKHUua
YEIXxb)L3QrJsfjJj1xRHrpTs1Pn7iiebGt606mhQrwougzm9IyIdgZA9OIeesEj0ZwJUs1H2nesuXFx
l7y1x806RspT)HGDjFQN8gjhlcsNX9ffdeoMQeHIXUkeERvPDcm0CiiZMBC0IcKEQtgWEpZ7dOgnkesi
wuO7RI6EupdREhVSY9cQEzMbSoCNcrzBcp9OYHIs(PCl0tSQoJPBhMMYkWEJdNsBi4uQ3xRocqOmKLtV
2dBjikzoNevtQYbSRkfjKACdmxoEQaQrvZu0R52wpnYJt1yfGYqLIczs5K4IKhbO3mckEoRcPX5RfpeD
EMqsKkPiu2QsNjWrHTar7fNXmRG2CIcIRNLZIQ(Iyvs22ofFHfnDjC(SQ(5yDfTKhVa5SgK2cwcJBOR5
iEwe3vq(YWnwvm41gS5qddc9TT(t74LltYwy0r4id37aI)2OEbU0cAIxat0e2kqwRrF3wBQcCYElVweT
EKqsyaKtoMWP3Glq25zc9ZJUBEtbGcPmdFu9KtR2jDe8EY7gbWIO9L8vJMCzmJuACiJApIJXzMuUIOZH
TWWWzsNiORLtqX67NykVngahv(S)NZkHHm75tRsBPRifLBW0NQWI3v116BhrX8iTpsqIVBXb1ZH5ix7Q
QfOLJh6ootWvDrECSd2vt9QntKvL6yVNiymdcHAiGyAnxisBpehIHmwVNKQ3eaVumN96ZdQdrRDi5CG3
6xSmokQW0dlI4kHZClN5YLztn4sP8XsDWuALqGEfriWumMYOZYVam3Pq2Ksx9(Rzxg4Wk5KIzuCzKW)Q
Glv96ERYrqC380d9N6zcPFTO6zd2YUzxE4MrLAMRnvHHQhZNfre7w3TzQdyOEaHfIxrR8Hwm5to5eaVx
jmrEQ0z06zvmYsvBloumgg4EvOpqpqt9fLirHzaVla7aqDyPlqlgn3V2MPu32730VoA6wbGUsE1JzGv3
JGrbrvEhEroHYzz8upqkLP)y25aI(nwWMrSPz1W5KHtMN68gBlPQAoLTkcmeHyyRiW5x3ra8)utxMZOI
gytDFeHBsL5u7gFT5QGUygi(uLsRfXDnIqbDYRrpyHnbQT7vvJsUevRYSnyq9kuH0id5bKLBvjFm7v6k
d7DHuc6DLfa5rvXUOwPy6q18zcYiRjRCBdQseR22GXuXOyrmyvT6xNde2fxB455WQOLVniFpSxONzlil
y8Ewl)I8JZOBEQGy8UWgG(2CfW80vkXmCDPy1krFEww784veJBbIz5fWGIsO0oRQTqz)ffsa4xIID7Er
Aa0GAZrORmXzR74CqpFGnZX59ArtLBXgu5P6dPyr56EVn8UGbs5v3GPQYKH3PRokQrZTRht5UasgIr1i
LYhHAptoVim6OwpfFfBklEynbMQ2Y)Mp0DVBL4m79Xuxr2cWSKBZMFfy9OaX1tPJMJ12AMbS86uerL37
fcVZlYWMAuk58PNcffune1vzGOxm6XAMBRCuUarjxGcwnkmmdeq(6r5DdkPja)ygOyBhh5G0idbYZ05g
oNkVKLiM6BRyoQVbOc2FHv1OuebAjG2W2ty0MEA0iKWY4YATOY1BnZETX2fK0DzKWmJaSS681u5JO8m1
lbu1YbcsqLjBZLoZPS6ChIQuDJ6sM9PeXBZ0sQGiiQeT8bOi2db8OOwRHatHR8fOpU1Xr1Cft7hL0x3Z
1ccotQ2MfHL0Gnq7NEOYo9SoLrFJfqSXCO8FPI6uz2V6dRigEgTgehpuv(qGBPSRz3roLDwUmECRfz3v
6kRhk62ljlFAfNUeNjmVeLcQ6CtWs1mYiOWbPK0IMoGr2SezJdtXDc1RDqG4DWW2F6bz1mUOvD2fgnB9
TJ2qwFZIU)c9v4CZ(EGuIIU3GYPUwmy7e09QzxqzClIn)QbvbaKE013kfFbtX5Bfs2AXVoTbpKU1qCHb
c1(WOuqe51No0xuW6(LcCZYXPpAmimai(mD4XbwFhd9cnOADfgmBr)9YIfMxdCzZvsbFt11Lmr(xEyXz
vRFF9EB71evYOgf1qO0UNAl2dLYNppkyOZM)fF4344sFTLlQB69ALU0iwSFrEGo0Xj7n1abyBQhQnyyl
09n1Ffl7OUThyUMOjuRgouDlhbVRe55kFDzi7hJK0S3I7REXIiSm2JzlsgbLHtBz7YgisLfWwF0Im2bX
ibqjSD53wkh9SUFsuivtT43UkZ9jHHvIqgYJz0cCn0E6a0vYuK2(6CLEbQffMU05f1TyZPKne5vDE8tD
q7gL0wwNj9XdyTgsp6OGQiOMkQyeO5WcOkJQHW5eY1Y0JvdfucbuaSq8zaDJIv9o6bJ09GwrdbxktRvu
PppDTKmhqSj1Kjy3qJ1fj5j1QMKwwJAx3xSXOJZ2FWDj7TYyQCUXdaMPmsl6drWIOop0ufeKeaolIhT3
SkbpyyPNH5mZe2t5cuydNZGBKqYoXmAODFJ0yZmS5P3GDZtpe86yKsegY6lc4C4Lyo1lEl(dzcSUovXL
wybDNJghqfQ1pH9gy1mt54SOwqUOQqDMCixB)TW2mDE2)HSnQ8UtxWcyI4AiP0q7VBat8flN6wYEPTQD
jg6ZK)iJQn6bg)BD8LOCu0flzavDK2d32hBQst7AkZmLkGIUM3fvRu85rBqIlf2txOR1NqQCSBdvWyGe
Vrgje45045TEQhxy3JBFu1pauEddLS8r37z00J9dv3pAbnZhljAtmbUrLcTQRZE5XSPfWsiKAf)ZAiZB
U3wL9HUf4O5GkfAONsW2N20T85kOc8MGwDTNukMVUT3efU5NO4ni9jjkQiqsvZ7z9uTSkXVSnzv)9X5V
lXw(VRBxmCR9XAOem(354YTJOSrQb6Gnt6BSWu60LhPy0GvjvH1HFxewj6fYa7R5Xg1GRPZQFdyDy2q9
k2E6GVA0lTlSSjscml(fGL6eulSBwjPIBN96jhQoTbe)jYJaGrTN7mOMUAFUmmwQzUsBeuPJqdK8lMBL
zwElWUNk(8y6yENc4aub9TvSbduaBakbgvpw0wzMa0dl41fyT3LdcVvIhZ6Kmvwwl4vuFmvjxZdD1jgR
w1Qyw61uNuwnvGrKOO4xiH(KpSpqkgSjCaXe1xWPzTYMcAPjBs(gL)8QrsIOWYqcam3nVyWm47nKzTZX
QqUEQYdSIDQ(zLXZSB5HV3(CSAohQKYZuHqtrDKQHk235N0WWpuwa(9zyFHSYFViUEvFIWunIjH(Xkfz
nHH)jrzF6u1ZmfmAVbLlivm0WqaXwvcW8MD2kDRP5erhGDkhFud5Wd8xygO60bSH3RcvS(nTLu6d)FTt
DVapOR03pOr2H0fENzm6sb0OL9w4Q00ltaf8URR11uwQ)8nORIUyLtTfiIzlFT41gRbORwKBvUqOcOcf
Q9mWtBUabOpDfVXJbu3U7ry4ckK0x30b8eYorzdlbQ(R(0ccBJtlcmxdcuWu1RVdicqWcMk0tiQ2PgQ1
tVW)EZF7

**Comment by mbattersby** [comment]
`/litemount macro` doesn't summon mounts, it creates a macro for you to put onto your action bars to click.

If you want to use LiteMount in your own macros, instructions are here:

https://github.com/xod-wow/LiteMount/wiki/LiteMount-in-Your-Macros

**Comment by Ankhsalot** [comment]
I had the same issue a couple days ago, turns out all mounts were unselected in the LiteMount addon settings. Not sure how as it was working fine then next log in, macro wasn't working (due to no mount issue mentioned).
