### ISSUE TITLE
Advanced rule : Grouped with bnet friend xxx

### ISSUE THREAD

**Issue by Mazwak** [xod-wow/LiteMount#174]
Hello

I play a lot with my wife.

I already use shortcut 2 for multi mount only when grouped.

I was wondering if a rule "grouped with bnet friend xxxxx" is possible to implement ?

**Comment by mbattersby** [comment]
Hi there! That's a very interesting idea. Which at the moment I have no idea how to do or if it's even possible. I'm not even sure what the "xxxxx" would be in your sentence. I'll have a think about it but I can't promise anything, especially not in a hurry.

**Comment by Mazwak** [comment]
There’s no hurry. With 4 shortcuts I have one with multi mount only.

xxxxx is the friend btag.

**Comment by mbattersby** [comment]
This should work with a new "member" condition in the next release, but it won't come out until I have the Amirdrassil stuff tested which I expect to take a week or so.

**Comment by mbattersby** [comment]
You will be able to use it in a rule by choosing Advanced then typing in member:battle#Tag into the box. At the moment the LiteMount rule UI doesn't support text boxes except for Advanced. I hope to change that one day, but not today.

**Comment by mbattersby** [comment]
This is available in 10.2.0-3beta2 if you are in a hurry to try it out. Otherwise I should have a full release out within a week.

**Comment by mbattersby** [comment]
This is released in 10.2.0-4. Closing.
