### ISSUE TITLE
Ability to use dragoraiding mount / flying mount based on amount of vigor currently avilable

### ISSUE THREAD

**Issue by SoLoR1** [xod-wow/LiteMount#176]
Now that normal flying is avilable in dragonflight zones it would be nice to have ability to use dragoriding or normal flying mount based on amount of vigor available for example, if your current vigor => 3 (customizable), use dragoraiding otherwise normal flying mount.

**Comment by mbattersby** [comment]
Unfortunately there's no way to determine how much vigor you have until you are already on a Dragonriding mount.

**Comment by SoLoR1** [comment]
Ah, to bad, because obviously WoW tracks this even when you are not on mount, blizzard just need to make it available with API :( this would be really nice QoL feature :)

**Comment by mbattersby** [comment]
I feel like Blizzard did this on purpose, even when you are on a dragonriding mount there's no nice way to find the amount of vigor. you have to basically reverse-engineer the UI that shows it.
More "dynamic flying" changes will be coming in 10.2.5, including some kind of way in the default UI of switching between dragonriding and regular flying. Hopefully there'll be some API improvements along with it.
