### ISSUE TITLE
Not working: Rules/Talent loadout

### ISSUE THREAD

**Issue by luisperezart** [xod-wow/LiteMount#178]
What happens?
In Rules, I made the 1st Rule:
Conditions
 Talent loadout, Gathering (name of talent loadout).
Action
 Random Mount, Mechanized Lumber Extractor
This doesn't seem to do anything.

What did you expect to happen instead?
I expected the Mechanized Lumber Extractor to be summoned when I have chosen the "Gathering" talent loadout.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
This is the first time I tried this Condition.

Please do not modify anything below this line.

--- General ---

Got this error when tryin to submit the code from the addon
There was an error creating your Issue: body is too long (maximum is 65536 characters).

**Comment by mbattersby** [comment]
Confirmed, loadout condition is definitely busted.

**Comment by mbattersby** [comment]
Will be fixed in the next release.

**Comment by luisperezart** [comment]
Thank you!
