### ISSUE TITLE
Actions.lua:501: attempt to index local 'context' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [xod-wow/LiteMount#179]
Updated to Beta2. When I was in the new raid I would get the following error as soon as I started to attack a mob. If a trash pack was pulled, or the boss encounter was started nothing would occur until I actually started to to attack. Thanks.

44x LiteMount/Actions.lua:501: attempt to index local 'context' (a nil value)
[string "@LiteMount/Actions.lua"]:501: in function <LiteMount/Actions.lua:496>
[string "@LiteMount/ActionButton.lua"]:96: in function <LiteMount/ActionButton.lua:94>

Locals:
args = nil
context = nil
mounts = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
}
randomStyle = "Priority"
(*temporary) = <function> defined @LiteMount/MountList.lua:222
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 1 = "char"
 2 = "profile"
 3 = "global"
}
(*temporary) = "attempt to index local 'context' (a nil value)"
LM = <table> {
 TravelForm = <table> {
 }
 Mount = <table> {
 }
 PairsByKeys = <function> defined @LiteMount/TableUtil.lua:37
 FLAG = <table> {
 }
 MountRegistry = Frame {
 }
 MountList = <table> {
 }
 Localize = <table> {
 }
 Warning = <function> defined @LiteMount/Print.lua:84
 CreateAutoEventFrame = <function> defined @LiteMount/AutoEventFrame.lua:24
 tJoin = <function> defined @LiteMount/TableUtil.lua:50
 UIDebug = <function> defined @LiteMount/Print.lua:76
 UIFilter = <table> {
 }
 ActionButton = <table> {
 }
 tMap = <function> defined @LiteMount/TableUtil.lua:15
 RuleSet = <table> {
 }
 Rule = <table> {
 }
 Spell = <table> {
 }
 WarningAndPrint = <function> defined @LiteMount/Print.lua:88
 data = <table> {
 }
 Actions = <table> {
 }
 RunningWild = <table> {
 }
 Conditions = <table> {
 }
 Print = <function> defined @LiteMount/Print.lua:21
 SPELL = <table> {
 }
 SlashCommandFunc = <function> defined @LiteMount/SlashCommand.lua:217
 Vars = <table> {
 }
 Nagrand = <table> {
 }
 GhostWolf = <table> {
 }
 GetDebugLines = <function> defined @LiteMount/Print.lua:30
 PrintError = <function> defined @LiteMount/Print.lua:26
 SecureAction = <table> {
 }
 RuleContext = <table> {
 }
 Journal = <table> {
 }
 RuleBoolean = <table> {
 }
 Debug = <function> defined @LiteMount/Print.lua:41
 VERSION_MINOR = 83
 Options = <table> {
 }
 tSlice = <function> defined @LiteMount/TableUtil.lua:29
 Environment = Frame {
 }
 MOUNTFAMILY = <table> {
 }
 MOUNT_TYPES = <table> {
 }
 tUpdate = <function> defined @LiteMount/TableUtil.lua:65
 ITEM = <table> {
 }
 tMerge = <function> defined @LiteMount/TableUtil.lua:75
 tCopyShallow = <function> defined @LiteMount/TableUtil.lua:23
 TableToString = <function> defined @LiteMount/TableUtil.lua:165
 UnitAura = <function> defined @LiteMount/SpellInfo.lua:95
 ItemSummoned = <table> {
 }
}

**Comment by Ookami313** [comment]
I should note that the error only occurred inside the instance. If I attacked something outside, no error happened.

**Comment by mbattersby** [comment]
This is the error from beta1, fixed in beta2. I'm fairly sure your update didn't work or you didn't reload or something. I did a whole raid with beta2 no issues.

**Comment by mbattersby** [comment]
Just did LFR, no issues.

**Comment by mbattersby** [comment]
Did a full normal raid, no issues and Tindral Sageswift encounter is working. Closing this, please re-open if you find out you actually still have a problem.

Happy adventuring, X.

**Comment by Ookami313** [comment]
That's fine, I will chock it up to a bad initial install. New version was released anyway, so I figure this error won't be back either way. Thanks.
