### ISSUE TITLE
Amirdrassil combat override disables combat macro

### ISSUE THREAD

**Issue by Etersarte** [xod-wow/LiteMount#180]
What happens?
During combat in Amirdrassil (Just did last 4 on HC) Ghost wolf will not activate when clicking my macro assigned button. 

What did you expect to happen instead?
When hitting my assigned key whilst running for me to change into spirit wolf

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
Unsure

Please do not modify anything below this line.

--- General ---

date: Sun Nov 19 23:15:55 2023
expansion: Dragonflight
build: 10.2.0 | 52188 | Nov 14 2023 | 100200 |  |  
version: 10.2.0-4
locale: enUS
current profile: Default

--- Player ---

name: Eters-Silvermoon
class: SHAMAN
level: 70
race: Draenei
faction: Alliance
spec: 3 264 0

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: 
IsFlyableArea(): true

--- Debugging Output ---

PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule PreCast 546
 - setting preCast to spell Water Walking
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 1 mounts
 - trying Dragon Riding Mount
 - found 0 mounts.
 - trying Flying Mount
 - found 0 mounts.
 - trying Ground Mount
 - found 0 mounts.
 - trying Slow Ground Mount
 - found 1 mounts.
 - WeightedRandom n=1, t=0.500, c=0.344, w=0.500, p=1.000
 - setting action to mount Ghost Wolf
PreClick ok time 10.738499999046
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule PreCast 546
 - setting preCast to spell Water Walking
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 0 mounts
Dispatching flow control action IF [falling]
 - IF test is true
Dispatching rule   Spell 130, 1706, 125883, 131347, 164862
 - trying spell: 130
 - trying spell: 1706
 - trying spell: 125883
 - trying spell: 131347
 - trying spell: 164862
Dispatching rule   Use 182729, 131811
 - trying item Hearty Dragon Plume
 - trying item Rocfeather Skyhorn Kite
Dispatching rule   Dismount
Dispatching flow control action END
Dispatching rule Macro
 - using unavailable macro
PreClick ok time 10.53869998455
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule PreCast 546
 - setting preCast to spell Water Walking
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 1 mounts
 - trying Dragon Riding Mount
 - found 0 mounts.
 - trying Flying Mount
 - found 0 mounts.
 - trying Ground Mount
 - found 0 mounts.
 - trying Slow Ground Mount
 - found 1 mounts.
 - WeightedRandom n=1, t=0.500, c=0.333, w=0.500, p=1.000
 - setting action to mount Ghost Wolf
PreClick ok time 11.022199988365
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule PreCast 546
 - setting preCast to spell Water Walking
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 1 mounts
 - trying Dragon Riding Mount
 - found 0 mounts.
 - trying Flying Mount
 - found 0 mounts.
 - trying Ground Mount
 - found 0 mounts.
 - trying Slow Ground Mount
 - found 1 mounts.
 - WeightedRandom n=1, t=0.500, c=0.190, w=0.500, p=1.000
 - setting action to mount Ghost Wolf
PreClick ok time 10.936700046062

--- Options DB ---

T3vBZXrUX5Fm5doUYDk4TbyG(MojDViFI(kT6UuXPmlnICi5wA5oml3v6ORu83EEAGUbA5J6OoBNC2LL
ZvLgodqJgnA0Va0pBo2E8lpE1jxmTJ(3VB9TV6ZV9vRwV5TZ7UCzzB5JlBpB95)W8URxJxCu(49hV6RM
2SB5Kl(iB9xSB(DxU(697MV(6pYU80P94VN2TF(JTd)cB)V7W(lw2SE7hzZF56Tl7V4MpYwxyMpM2U6W
2P3oTEZ0R3m)8Pt2TC8Q)9tM2EY8MZw2D5TV6)I(N)irYhpVz50DR)OO6EQdNVz51tBU7r96dxE5Y2hV
Cy7(Rrlok4sdH8Xhzp(iFkMTE8OFa)rmn6IhFe(pNlh8Ojb8F2SpGVI)lygJdOxo02CkyI1hJJJz0wpr
i0r)iAQT08y0NQJZqEGiI1MkDiBS0FybfqZt(XsRkDgVI6JpG(uFBK6zi5J0RZGscjdMk1l8vOYm(C07
kVnfghi6BP)0yXOqdzUmPhterIEsym4ldpXlHuorKKycBYo6n1Hkcjd6ymWZ2czXFmeso69EIDIHXrrO
oMYm99rtUWBeB7tqaeRZQCWgW3ZetBggYfUKPVVmRh51hIjOHoAbZsChTQ4mMmp7Dy(7QuYAgtLvb6XK
ZqpBywA0uKF1Pt2qdrMxPPrceAmLWtdoAr3zOztWmu0xsUanwKI2ULdxrQrR(6PnBwEhurN3EArTQi8(
IMgZxu1mxV969KoEr1ZITItBwF5Pl7OHooE8QNpd7rNVGTMpE9(BWBhG0FL18a7dgU9vVC9Lyp(lwF2(
6EHNFy3MLtU9v)Rp6pD5mEC)f)2Iebe(LxGw(9BpDE3UL9f6K(W05flVEzprMh8hEWtFWlEWV)bV8bF9
daTCwOASk)aZTV6OV7POfhn)UBF13Tz6M5D3(QN(JxnVB9mMo)2czE6pUEZ8VbK8fZtNCrr)g9(l2SSC
6Lth2G9UBMohC96Ty(FKnGv2v)a(ag6LZU9v7jw()yA3PZBPpNGwZQVz7BNOTUyqxwt7yXmbRw1P3J(t
h2H)PqcAHbT)jRP38C8gQLUuDH566a8nBp7q1oWyc047M2E60U1tfwjW08hwVSzgm0xVS5usx2XV)lx2
D(CLmRwoSHyWi0yw9ODNFG(dNb)XQ3CZU6uFyaZTxoF5vZxdI97MNV6HqSte6lwGcW6tMkZe)hEn5l2m
DYBGm9YRktjSe)F)B2XRWdwAfE9PZx)MLDq281t7EnPdnaJnRE(05WFdS49BarXY)0jZy7qctWNmT7nK
HtmBMarjDCA5bJZztWJaS5(eWOy2ehsI4ybUv(ri9xVD70jBMPD5qH8XlR3C202ZLjvrr71lNxMuSI2T
V6pmTBAZmMepEcMS3wNxp(IPR2tApObRozElwbwa)nqIVlMoD5ZXYcwbx2ortcSfiACV3Q43U(8l2VD9
2ZP1TySoTUyg()iMz9jVzEpTFhwdxbN7lBwUK2WrBWnMpoolQ5m3qzz(1qsE46pJ1slC67MpfDA3Htw)
AsWaLDSCUAEsRo)YDRpC5BxVdU0l2TWu5pqQDBqqhhLJMQsYMzvxE20P0imV7Q5T0mXcZzRE0HtUy92t
HxlAI4dFy9MV(TpcAlVK3lTbd210g5qGua2vTT8nxVH2b6W)JxNRtOsRl8PNIsydr9DtKcb9IxEXULTA
oTObwCqyA7E2Ek0TNk2Z88AtDVpSNHj2gsbcT(RN3S5SIIn)ErtcmYESiqI2YAonDjdJLPBcn6MD9vNF
6gfAZbz3473C6bIlSdWG)kUjVyz5nYoBOGeifeiIOT7k9nRJiqHzEkuoEnmFDjPgapNR(QDqcjY8hD6B
Xk0bAqZrmkR2JawUE)YbqpkSpw7fdZxDy7P7MEZXhzOO7OXblc)oOcF6YLxx4fRIx45nyDhjaHQcTJOU
fdITBkAa5pSgac65qXyf5wapUD(3w0obJ8L7MNVOm)DuKdFqs8K5lj9eqG53bDxYOJdE9zXc163nDdA6
)6tME3wLgbSWUE7Akq0F)H9NUSSRmYKQh2imTHTFU)MY(fNZqXhV8M5Uk5az5PRS)qYw(2Pp)Llx(6IT
FeXYQJM3ShbTtMDjxbF12f48B(8jk(UiTinTxRLUAE)EiQXdLnpbeZgPEmbZcG8Fl64j3uBo0TkoTISP
O3vnw(fhQ8(xbN919hbek1QNEdpkp6pDnyhyqptErE(Y5h(n4fKllS2vS8uuj)aIk6ZKD4NIjX0gOC9e
4c5sA53j7QAF6iY03LtKghfgyvVgjJ0nKrBVC)mBVkoJH9FOvuyTHHX)m5n9hy31AY02nxv84gdv7nok
oGpNvqRtLFyAZYUASiRV(S17j2NSXuwScKHZlxVd6(xF96nIXZYeKct4RxUAUSIeiRIVNfzsipsR1RV(
nfz7a5a773FofEq1HArDiYIOJwEZfhWe73F2zi6H1VTyV3)ZOH)sixinCOjmZUvtiEs2A4EyO7KLI5Ka
jHyvoe7aX3Fl8Es61UX3ZXurwuc1ImwEZoQPFj(S2BYqQXXZ)4HIuQUlalKZBVynn5GbkekjzbnuvvpC
zjeLbsTC98MtRHyD9Ek4vsXccJDh2soBMkwQCOBV4WRVH8vE2mf60sXGcfG0lM(tl7oJ2X9KL3v0xsO1
hb38xSJcD9ipTQ9CiZpCkfPKZBEp9SNmF1(lUUgm7v7wodr897MV567odAWANvco7dL0CVb)C5j3B1ho
1yvBU)M8HsaU3IpqoVL4Z)a54278hkF1wl6YUIGtEnE8skV0VdQk7wVFnNLq0BOeoOewCHiLhOPKLxjf
td3GHYJ(SNYPKEPjr7oOuIOSxOCGOKCqEw5AdCEhN2BPPCMPipwFTPi)kk7wk5mKG6yDO8jJDO3YqBqh
RdQpwsZRKov0muFR3gt84xAqOsa6T12kPVzkXsm6Qjogl58X0VoP9iECPHiIgt97XSpxN(ijYmLTAD6n
yACktPyjz1YuAKsiQqOuiwNNJJEVL7SzmuNCLwM5hr2NCdg8wdpqiJZAk2LxYSCmxKE1VpMQ0AmKKxIu
(9U(J(Et5zIp7s9VZc6aIfSsGalBDz4wEuMXSyIM71PKnMZdvUZhCEptCKclRAaUKhCso4AYHAdhSbBL
ldX6Ic4atQoEbKdv9FRnXJi(4LjK)UR(ODCWimaERV2LS37ITMYcDIRQAHKCy02)URjDgRpICmOtfGik
ujmCN8rw6A9dbBuwZI(UuXXBiYzwJT0lxtaWefREPA)rSNHQOkASwwLigkQ20G6ZMqwM(H6SlInPI41z
sS4nBIztJM11wFmzyHhus5p7GMHH3KpkBSt(ORUBLOolMsWtJWhowXigYP(NdSSjbzltD)GPsOut0rZ8
6MsykilNfgyiExDySjom2MrLWaVbJ4OgBuoJeEnmZRX2OJvRlp223mYNzZqAK)xEk6jx3fQKhHmQTMxB
ESONWc6ApcbpBbJKeozMA558aYHtmqIP)qBwp0gVyVL8em7PCiLzDBpwzhHTQzYtfAPNxgPxMKP6iV4c
tHSXMY3RKkNgIv2JgEEVowYIXwFyPsUSMW8rUnlR6v0PnYZYWqXGAz9otbvjeFuOO0s6ZYwTHKRkfsHY
McAQdljSBKX0iRvttsM6ztQzW3jIgAtL31FBLLZJotNr4DkPGL5jyYmgTnMIN7WlriPEBQ3wx)TYUAeg
g78keyBY(qs2RzllY1XN3nKhBSFgUge9zW(dnQZwSPjnVZiBYjX1tEGTza1PO4OiaEMTVaLwVOzfSvnu
RJ7ZiChyBcIbE)nSX76VKNX4RbMNG6KTT0Z6YdDhVKNdXBRt8Yqt(uJpy1wqEwkwAzvlAiNBBwPZdNLd
ydkVKb36Sokjs4nN4)jMV4ZSvAkB83yDJSVrpI8n0AGOtrdwUT8WwFhrUnDAf883ZCKfuNuZajEdiwT8
0oKe)40l7s9(mK1jGcNBS3Y6kncsOljzDpssYwAYEwMyj1eP30kvt8ef1mXfoiUZiT0WAudbr6x(Uvez
dSIaT6p05oXQMf628SZbEPoweRkgJSdn3lwNyQS0wXcPjWHX4XMdMVPiN43IbBOYTKYsU(DOuYHBcTFp
hKvGoF(MAfRbv(opuGuILC6rE7DWf5DaWKs5e5lSvw21qTL1qA3GcwdCsyCW05yTt0wawTsUUexDlcBZ
lucJYYFMTtW7QnC)5D1iqa23vCOCDpsVg79IfX0JPMyHTVym8MblmDBAShhDeIUj477BtTi(KOJOT1Sw
9yOPRpuxILhLbTEFeE(TsOzd2o)nO6fhmr96Cc1xYXxrIkXqQn08IbZ3vEfk5nlGbxMDOs3geNscCAWH
I5q88P68U0RHEthAYQu)LvgeB2m9UZJe9zEQ6WQMT3PX(Bz7c5cLSLDMYEex5WhRlGjXPg19CJr4T4dy
mRDckcI3tQ7PwN4ywlJP4aaSQTpu8aapXsetu3yUgrrW7wIJzjOy0YCVLTyhK9LevzNvW7T4GjLhIQEX
AiEeHFStaFNaYweeRTV3nwXpcdrS6iFnCsd4OJ47wuOBFHZRgnjXijNnsCRyX(AiBYY6WMmfPgBKsmUe
T(w8zObCWOHWqk0Pa3n6TDTmXNc9wE6aDA2)tWMenseWHZ1jlBQegc5yjl0Y2Pfpy5GJvAqyyS2v5L95
R4Inm2CXIgWw(PH13haEfbAhSFZ0Gtjz49CipuhBlg8NVUIsukiIBM6L(iULH0KvFhnsaeGtKlwgoRTC
IuE6ILDDk0vde7BUrJONGiJJ8UQHrz0G5ZiXdY8QVbi0ccOK0k9FrdVCqFV7JX1cDb((41dKhHPR1Yb0
qSRyUpghy9eOZ1IyjhBkhrReuVlXma9DoibeysKfcoySYKA9Ix7rQqCE)4JddIrElVV0JqJ4rYyfDtSP
3k(BHkph7Kj548bjMo2zAjWzebBNtzDiS)u((WqlGrJZkAoPHKPkbrY28L8xivQnQs6SqQXdaTLJNvii
tjDlBlBDQ)SsUnZPB1QwGQmj0DYXKhwWRmcs72lPGJ5x02jAU3aNiElxipjvOE56nGTeaDbo2qB265CV
PnrgHRZHENgADIZQIg2SIV6syF)LjHxgdkAXRRiDJ6qvEjRlq(ooM3AoA7DIhvq(WytzvmhxgGkhsXRe
AuTfhBKUm8YJsTjWYW6iatXrEDbBPLWyA57yjHTyilgd1geJzd7AKIPNdzJYtj2xJg6clrU4hhK2oA45
f2AMBhyggmwAW1oJq3CNcn7arXcLX5zEyO5iRCsv52ktq4wdRWtuDmiJLH19PfbViICSxkSHzS5PpYlY
qZTfkMxsTgAqYCHSNWUFbt1oIeejwZDuW3N2CGm5KVFkSrNIuS0e7nK14upKPihYtrsK7lbDPghRyHbg
6ZLuVbskqqlW2P7yVbT1tlpBO5LQPQbJTW7hZnhFroyhs3scWWaBEXMmCS2ayNInPu(oZHs95CmDiw(w
6(g5WNkTTZbTdvgDJ3iGewBMnHDhtVTHEBz7outnDoVR(oYoScgdVRXcbMydkmM4C5qCYzX5MZP(oZUf
YYgwOey5GpXAopHDdEJrs)VEi8L9DDTZMRbxYZPhu60qFaQKkNelasDLjnLfZWFGl37LWlMC780qG(Ta
2mwfX8DIX8T357tgX5jCUjjRqVDO3ljQBA4ywqSYb(xo5aeFbVTOqkMQqrOTKNedMHKewdCik5AHwkl4
03R0Fymk34awTKT1JzJCAb0n8hesXXaw(EO3lEwpAssYo4rFJbKJObXml(jXdCEdywpWbn7O4RzfkFVE
7OgWcEmyYzGHxNK2o2ySuqUvcUgalKnBfpDutTmTYdSV4eXUvM1ixfeeQskyqAljXBHfIkxHqFB2qiIY
6aPbjlhFWkhihr)6irxfTeGeCFW27IdIplsnMnObRDsawd5m7R3d3Vs(0iBlRRtvFVbIQxuu(PbGdE1l
NIUucHCNyByddT7pcYAwXcp0CpIEXXArVK)ouI4qnGOs2qNll2wM8J93Y2fHL)MSgXkw5keQuYilRyhn
lwPtbi37wS)OIy8qatzT8EIdsgFEjFnO2eelfiShRWUPwAEiwd5KumjXRTNopE(Ln3eulh7Fx6uwC5qV
uyW0ytANgL14qqojfAgWBdktM6iadHsimySeN247Y1V4B3jervj9CSrVTig4imOZ8rsAkjb2eW8xcrH8
AlzWXDp4ZCONWILCVhfAYBcjnFXN6yODulGvBA2IHWOLJ3TKPeRddUxowtIQ15pxkT0AfsM13d)G35b5
GKNecB1Z7CiJ2IP8bzzTq1(BBx)4yqeq0BdISSDrJi0yzDnlbWq6UTtvqIO3dlEsjcNmsMAol8aXRGKC
L)oxiWKIP3WP4swSyLCJvUriyNMTosZqN4J1BZnZywHObx7YUgLinkHvf6pYw1RBo5Ej3yeYVuobmyXr
YuukQ4JlPFyzjysUlXOx2TKtYwmI)KyrZT4fG0DqUIoYDTK9eDjavbGXlhggK6Y9ks3WaZRutzJx0nUv
3ftgQ7w3BH)4sYfq78Tt7ew)fLqyhHTKhg9SMNurZgMx6EO4vtsjwIhbBC67TfBwiC0kxnkNTIuh22Y(
o(CngYjjYjUSR90CYmiPbLLl0QSVG1kOTLvDbKAxqoxxF7YIOqb4DWqRtUlwIQYUrNeIpDpyYA5a5Swe
1dTm59gMzjZfIYywmyskRvsLrcvcLmY5tqY0yt6iQsdJs5fqxblNjTJEsSZddM8Aj0qzXpLeK8yGfqL4
d4jixi5oEwjMZWIQyAklh3kw(dCWNXu7oWYWpjlmZj5gHk5mYVLY3rIJfJflSghCX2I0OCUcbi4Qtbk3
ljiq7GSYrXAZIl6rFFeefR6Pxv4g4PINKwVKGQGlctP2QZv1n6GjQuTKDi3YOvNVbZ2KJm2mgjUylXdT
YzHoLv563Pc2Gf4dTs)G0TKqVQxjArnh(CKadY8HIHKILlBb2zLsqjKAPLNJ8AeLRTeIGFOfBkc8IJVN
wdzY7DTl)eeLdin5Ldk02I1bPCpYhlGGKclfMRLhDdFcqGn4rSqrL)IuFc7BR)I2oHMb1SJvMITjcLMA
pYE5(LOGfz7XynvC4GivKmkG(mtaKfIqvQmlQkquyxSruOaBLLeVruHHZdj2DiZKBcKQJvJWmr5GBiNt
8uaHFeLvGwPpb9MGVzgMVHZcZkgxCLAsXw3ViXgBSXU1jjLGHC7kmPOcKhBr2r3uTefmDx2mVKC9ZtkZ
HrcNl(EcyYj8wUF6yNSsQiJTJ3eAR8AVjgynRGXYw)hgZJTy3h5OCloffDOKCbifIYmaDBDnlcj522jM
DS32kBr1faZa8D7w4ve2GOO1C1fKs6GmVM70K3p7DsGPLipfhrb5EcO3g75QX73h8Yf3s205wsIIktbx
nYTWs6w8UdRZokxPk8dYVfov9nDlhhphcvYigObZkZvygX02iyBjgBdEjgOultiNHxxOAXO(sgEqerzS
lzyIYwQPZwW37Fq0CKZEGAALaweQGTLFLTDFFY5jucBi1xHKG7XMEjAiJNZ6bPIXxjmzg2iDskCQIaGh
k41vmUsjGYrGmkXfqZFwdY2IlIuwRI6YgJuNOmR6KZCLQgn2IIxUr8YbqPKPP(cmBrXzmTZ32kMHl5mY
B3W(vPQhnjE(HaOc9O0Dsybb5E8jdPSHs66EfXBYQgPQsZaFyHiIi2ddS2lLfcrqzTLoiEUZq0lsXwf9
4qYuInEQS748gggyJOH2L2sMBv3dahkov3xCEzmAZOh57NsaSM9ybXDffN2fZrYt(EylvWGvwK4vBkmV
X26bZBLYFHFeXyjhkLtQpfAYZB4HgI8Ybzne6f6nESNq6qu4a(j3RY0SDXGuqY2kJMf5v5mVJS8klrMd
RbT7SZL44AlMHL4zZb5EKn1aoPhzCB6owqlinaYrnqvzeN9iPIwNi0PL2TWi2nP4C4LZH2HCfOlRHduW
2kFgi6t15ec2ujq5WeSHGO1Bh4egjnzwVGizlbGq7CDn81RwofrMNOGZusuveznRAY57uiRO278YT2cT
D5cZjNyJYYNKrRrIJPWRIEwYjN)kmk2o2hRSfgY8bvj3W6eutz7g0PNYg5Pyvz2cXCAvwJZT5iRPxcnx
I)llhLrjUfopd4DKxyWgKmhdm2r2IACyuoAmAhPLxAA3SdvLXmhqjNW2Usumo1MACTJNKcr13wB4OHJH
M3lkiR2Mr5OylbJYgchfFMcaATLQGKT86CI5u6(LflFEPicjTv26XqwkugAHPFtlTtoJYtUhOGKEpwUs
kYYTLo6ntNU80Em6BNwTycQOfuja6sIddL8(kXNuX0SRkw5ws3LJ4gAOvcwmIJD0JXSuoCJs0KghluXc
PKgTVv63LSlLi1Az2u2KYpAA1RmytBNQYXWIV3YXjpiUwHxmwTbzliUPHjojzd62Bzn3i2e0cdNNG7pE
1UdBeq(wr673U(Y17xr476)IWEWPt38qiW)STlNwamZo8MxVz(pwrxtdjXqUS65eMaq3UC6QhIiS(SRp
86lN3D(8POXxU)HLep8VFZqO5dF2zBUHi5N9FF2jpeIMyKBp5Gp0BVaj5hInEClO1(HElM)X97MEifet
kbgwp(Rp9HuPAxG0WpfR9Nwb2aJNHBirZQxFy)(LTp6K9RjucXYM5P3o)dZxS(KnZ3(SNS(6l5rE7Yzq
ASE75)XBF23TB(XteAAhcXBF2JxU6MxobUy)1v28zp6QR2CZliX(TpRiSjzXYPp86lwF2EnBlcgW(V47
p6ZU9)5l)2)Z7Rl)5ls1o(Kx8OV63F0l(MN8nh9v3ff0sQpF1)X388BF2QlN2TN54V5lPFLdAtWBF1TV
6FHaj9Y7Qah6Zi4P9217N2pJh)deOD(YneeWWF9vqfIE7xUz6QAxxD1mH1i4TbVgXLeP)HQudp9aLvxI
EishCuBW(Ac3S3iO2IG29HljY(ILtoBEA)feCyx9MBUyPIyX9Z1E(9xpdsns3(AL4JwBJMFBzvA381le
KCpTTAo)wAgS(SBFfpNR9OTC)SNE0tU9z1FkikkufW28jqX8jqX8jqXC8NafZNafZVsGIPFzkFctmfY)
plyIrFZlFctmSC4xmMySh)xpMy6hy0NGetN7(yHeJ6CLT)fHiM(fg8ReIy03D)VyeXWBqylE)ncrmgUx
X(JPMyroaPFweX8Rlmy4x(piWGP8iVa()xaErDVj2pb4f(Tssp)SaE5tOCrgaEz4V3r5I6uC)ekxo(xh
uU0R3LFvr5clt(BmkxmhRRqM)HhLlQYq6Er5cxPEut)POCP2l52m)RdKlQRfWEFiB5UHZI(Ed(Redlw9
vD)Efbk7Y(xfmSOkwVFbyy59Q8M)(eel6cb7VvOyHi7)hJIf6X)rcflQlV9FyrXsVKV)7sqSOk(9)YqX
Ic6k9QV)UrUIcUkQQpxdxf1njl)MvF89JxfvrR)jaR8jaR8rcyfh3YX(3LoDhaw5UrPYDIhL7f6jn8KO
GoYDJxK7gqikyGOa)rhIakOTOW7HVxoeD8EORSGET(2r2MgVh9YcVJ3dfAd61ZWDd3JELpOWyX9a3JEn
uOkSI3RimAWiskHJEvHOQ6dfup6)A)OGGthPh66APJHsfupuf)Sgbk3hypuvmMcShTFm(pwJRefAu6G9
qvdm9kOvvyp3hwp01yZpfSh2JpsHYhDv60R9O7gTh9IwFSFgdcQd7amrvArD8HOa7rhwiQ6wsx3X3fyp
u1BVgIi)ca7HTdtkDDEXOPWwgxFheQFCO9OJdbvnA9EvCw76q7W(qvr6DyF0lsmvLJPQZToupuWKqb1d
fcr64GqxBB9IFtvowkmzO(XGqdUmfev6q9qvh8DmQOkCABh)fQcaub1dfUs64JqvhCQ6cubqcvv7Pk)U
EXgQX6r)x(bvP8PGOsVCgvf54Dc1dfUfuq9Od(RoupuvcOcRh6QRVvVLQQGxvVM3jwpEVF2T(5a7rrU2
U0(7bVhkiwOW(Lcvdk8E4v4GQJ3J2pabk4EOXVGQwhVl4EO(P4sbeUEH7QH7rViDvO1rb3JoakuieTJT
zfypQ1Ol9U7bQhQAvwvRZFaKyOX6HcOdTGIufpEh1fkya0H6HQoYvfYEh0gQYg9Ur6rh4lQcVw9BhIQe
vvyEtW6HqwEBEdxO3lupuaWqbgpvjQ3)XG4JhRhkK41RIBvry3XwKcdXVh4ZAy9qHfpfwp6fSEh(fkqF
0r6HcpwFaKE0kcEfMmSDmxOq6Hcub)uOE4pwd1J(VxEkaFDpa9qbzJoqpUlWBy7GsvbVufKvu40qb5K7
gNhDW6QGVHgtj27aPhkmDOa6rh9j3nspAWIqbfP7gPhk0NOWcKcPhkiN1HNIcMGkec1H6rhSfkiV1HWr
h)rDGGOW6HTJjKoCgtnuHOGwNcQhLojMDAhJGcSi3hyp6qwrbfmbtk3lwp6Ol79amKciwDaUXqiPmMnq
u8xcApuiS32rtYDd3df4Q0qdSd4d1VbRDuKOa8HgqjDKE1rEVcsK9Qfxd3Z7aWhkqMCNa(OJ(nbnj0sM
afNoApu48tbGrfEp6yLTJ3dfcBv49O)RAGT)la17H3JgWEvW9TJbffYG7yqPJ(rfawVlWEOXO89d2dJk
wXgm)6O9OJlufypKsvqH7zf6nu)soOaod)BUqLPemWOGTSc62kST3r9JGOD7XkyURqsCh3pkyC1rJTxJ
e5gaxSDqGRX5rhB5kWVFNa9ObOEnIrUhGE0r7V6NaafKrUtyEO(TxqbyJ(ptd3jkpu)kqO(vAqHUg9pU
enyEOHCc)lkr5X(Vde9F(luORvH0d1pahQF)pu)QJOG6H6hSB1VNA9F9fuq9q9diIcGhQFNEuy9q)BPr
h2hASE0WK4hnWhoBZ05p(IPTNxRGD(avF5XREX3F0XR(3QL8(FXOJ4F5XL)FDI3(QZVyHk)(3TS5SBFw
9Lp6WUPBFffu9NqrX)mHIIBFwrPI()o()9p

**Comment by mbattersby** [comment]
This is an expected side-effect of the change to support using a dragonriding mount in-combat during the Tindral Sageswift encounter.

I expect to be able to narrow it down to just that encounter, but not in a hurry. I can only do the encounter to test it once a week until LFR comes out. 

I don't think there's any way I can support both the macro and the dragonriding mount in the same encounter. The smarts of LiteMount just aren't available in combat by Blizzard's design. I can't imagine a fixed macro that would do the right thing, there are no macro conditions that would allow for something like checking for the feather buff.

There is no override I'm afraid, unless you want to go into the code and edit it.

This is the first time in 19 years of wow you've ever been able to use a mount in combat. We are in uncharted territory. What I've done so far has at least made most people stop hating me and sending me nasty comments.

**Comment by mbattersby** [comment]
I'm open to suggestions if you can think of something better I could do.

If your suggestion is rewrite the combat macro UI to allow it to be infinitely flexible, that's a good idea but it's not going to happen any time soon. :)

**Comment by Etersarte** [comment]
I'm appalled by the though of people reacting with hate towards the work you've done, and I just want to clarify that I sent in the bug as a help to contribute w data in any way I could. I am only grateful for the work tht hs been put into this.

I'll look into it and try to Contribute in any way I can!

**Comment by mbattersby** [comment]
All good. A very small number of people are quite horrible. I often wonder why they use the addon if they feel the way they do. I try not to let it bother me. They are more than welcome to write a better addon, it would save me a lot of work!

My current test version limits the override to just the one encounter. One option is to not do the override at all if you have "eanble combat macro" set and assume you'll handle it yourself. It seems like quite a good solution but I have a horrible feeling that lot of people have some kind of macro they set and forgot a long time ago and don't want it to work that way.

I can't think of any way to support both the combat macro and the dragonriding action. What happens when you activate litemount has to be set as combat starts and then can't change until it ends, and there's no way for it to check for the feather buff. Blizzard just don't provide any macro conditions that would do it.

Someone in the curseforge comments says they much prefer it to activate their ghost wolf and for them to click a mount, but I think the number of LiteMount users who have ghost wolf on a button would be far greater than the number who have a dragonriding mount on a button.

**Comment by liothen** [comment]
Would it be possible to enable it while moving, similar to the way it works in open world? (i.e. standing still it mounts dragonriding and moving it would ghostwolf/travelform). Btw thanks for everything your doing!

**Comment by mbattersby** [comment]
I don't know, can you write a macro that would do that?

**Comment by ThiefMaster** [comment]
I'd rather not have a dragonriding macro in this instance than a non-working ghost wolf. Dragonriding is rare and I can easily hit a custom bind for it. But there's a LOT of muscle memory for using ghost wolf whenever I need to run out of some crap.

Can you point me to the code to comment out / edit in order to get ghost wolf working instead of dragonriding? :)

**Comment by ThiefMaster** [comment]
Ah, I guess it's the changes from d93bab5b

**Comment by mbattersby** [comment]
**Reposted from the Curseforge comments:**

As I said before, I can't test the Tindral Sageswift encounter than once a week and updates will be slow. It's working for 99% of people, but I am aware of the Ghost Wolfers. For now if you want the old behavior please use the previous version 10.2.0-3. Or set Ghost Wolf to your muscle memory key and put LiteMount somewhere else.

The expected set of changes is (not great but the best I think is possible with the Blizzard's combat restrictions).

1. Only activate the Tindral Sageswift override during the specific encounter.
2. If you have enabled your own combat macro, do not override it.

There is no chance any update will be out before the weekend. And if what I've written doesn't work, probably the following weekend when I have another attempt and then test that.

Happy adventuring, X.

**Comment by mbattersby** [comment]
If you are doing the raid and in particular Tindral Sageswift, feel free to try the beta version 10.2.0-5beta1.

No promises.

**Comment by mbattersby** [comment]
10.2.0-6 has the fixes as described:
1. won't override enabled combat macro
2. dragonriding override only happens during the Tindral Sageswift encounter.
