### ISSUE TITLE
Unable to force a ground mount to be summoned

### ISSUE THREAD

**Issue by chad53773** [xod-wow/LiteMount#181]
What happens?
One specific character, my Tauren warrior, cannot force a ground mount (using SHIFT+my hot key) to be summoned in the Dragon Isles. Works fine with all other characters. And works fine in other places. Always summons a flying mount.

What did you expect to happen instead?
I expected a ground mount to be summoned. Tried using different profiles for my other characters...same problem.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
Pretty sure it worked lat time I played WoW, back in February 2023. Just returned recently.

Please do not modify anything below this line.

--- General ---

date: Sun Nov 26 23:55:37 2023
expansion: Dragonflight
build: 10.2.0 | 52188 | Nov 14 2023 | 100200 |  |  
version: 10.2.0-6
locale: enUS
current profile: Galdyn

--- Player ---

name: Galdyn-Hyjal
class: WARRIOR
level: 61
race: Tauren
faction: Horde
spec: 2 72 0

--- Location ---

map: The Waking Shores (2022)
mapPath: The Waking Shores (2022) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: The Waking Shores
subZoneText: Wingrest Embassy
IsFlyableArea(): true

--- Debugging Output ---

PreClick ok time 14.267899990082
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching flow control action IF [mod:shift]
 - IF test is true
Dispatching flow control action     IF [submerged]
 - IF test is false
Dispatching flow control action     ELSEIF [dragonridable]
 - ELSEIF test is true
Dispatching rule         Limit -DRAGONRIDING
 - new filter: -DRAGONRIDING
Dispatching flow control action     ELSEIF [flyable]
 - ELSEIF test is false
Dispatching flow control action     ELSEIF [floating]
 - ELSEIF test is false
Dispatching flow control action     END
Dispatching flow control action END
Dispatching rule SmartMount
 - filters: -DRAGONRIDING
 - filtered list contains 299 mounts
 - trying Dragon Riding Mount
 - found 0 mounts.
 - trying Flying Mount
 - found 116 mounts.
 - WeightedRandom n=116, t=0.500, c=0.130, w=0.500, p=1.000
 - setting action to mount Ironbound Proto-Drake
PreClick ok time 24.966500043869
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching flow control action IF [mod:shift]
 - IF test is true
Dispatching flow control action     IF [submerged]
 - IF test is false
Dispatching flow control action     ELSEIF [dragonridable]
 - ELSEIF test is true
Dispatching rule         Limit -DRAGONRIDING
 - new filter: -DRAGONRIDING
Dispatching flow control action     ELSEIF [flyable]
 - ELSEIF test is false
Dispatching flow control action     ELSEIF [floating]
 - ELSEIF test is false
Dispatching flow control action     END
Dispatching flow control action END
Dispatching rule SmartMount
 - filters: -DRAGONRIDING
 - filtered list contains 299 mounts
 - trying Dragon Riding Mount
 - found 0 mounts.
 - trying Flying Mount
 - found 116 mounts.
 - WeightedRandom n=116, t=0.500, c=0.047, w=0.500, p=1.000
 - setting action to mount Iron Skyreaver
PreClick ok time 18.699100017548
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching flow control action IF [mod:shift]
 - IF test is false
Dispatching flow control action     IF [submerged]
 - IF test is false
Dispatching flow control action     ELSEIF [dragonridable]
 - ELSEIF test is true
Dispatching flow control action     ELSEIF [flyable]
 - ELSEIF test is false
Dispatching flow control action     ELSEIF [floating]
 - ELSEIF test is false
Dispatching flow control action     END
Dispatching flow control action END
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 305 mounts
 - trying Dragon Riding Mount
 - found 6 mounts.
 - WeightedRandom n=0 all weights 0
 - trying Flying Mount
 - found 116 mounts.
 - WeightedRandom n=116, t=0.500, c=0.051, w=0.500, p=1.000
 - setting action to mount Iron Skyreaver
PreClick ok time 14.29759991169

--- Options DB ---

<full text in attached file>

[LiteMount Bug Report.txt](https://github.com/xod-wow/LiteMount/files/13470281/LiteMount.Bug.Report.txt)

**Comment by mbattersby** [comment]
That is expected. Now that you can use normal flying mounts in Dragon Isles, the default SHIFT behavior there is to summon a normal mount instead of a dragonriding mount.

Characters where it behaves as before are either (a) not in a dragonriding area or (b) using a custom action list with the old settings.

If you want SHIFT to do something different you can create a rule or modify the action lists.

Happy adventuring, X.
