### ISSUE TITLE
Limit mounts to Emerald Dream

### ISSUE THREAD

**Issue by xpronic** [xod-wow/LiteMount#182]
Is map id 2200 not the correct zone? I've added the map id, and group required, but it's still summoning from other groups. Maybe I've gone wrong somewhere: 
![01lmr](https://github.com/xod-wow/LiteMount/assets/43455560/04115911-651b-4886-bfcc-dd5a8e9bd0c9)

**Comment by mbattersby** [comment]
Rule conditions must **all** match for the rule to match. What you've done won't match because all three of those conditions aren't true at once.
