### ISSUE TITLE
[Help] Fly mount only in new portal room

### ISSUE THREAD

**Issue by Pegoth** [xod-wow/LiteMount#183]
Is it possible to only mount to flying mounts (non-dragonflight) while inside the new portal room (for M+)?

Right now it can mount ground only mounts and I have to re-mount after traveling through a portal.

**Comment by mbattersby** [comment]
Yes you should be able to make a rule for this based on the location, which I assume will have a uinque map or instance.

Have a look at the chat output of `/litemount location` and create a rule using either the map or the instance to summon a flying type mount.

Happy adventuring, X.

**Comment by mbattersby** [comment]
https://github.com/xod-wow/LiteMount/wiki/Rules

**Comment by Pegoth** [comment]
Thanks for the help, tried to do it with map, but couldn't find it.
The /litemount location helped a lot!

**Comment by mbattersby** [comment]
No problem, glad you made it work!
