### ISSUE TITLE
Not allowing flying mounts in the timeways

### ISSUE THREAD

**Issue by Chalsean** [xod-wow/LiteMount#187]
"The Timeways (Dawn of the Infinite Outdoor)" instance is the place you go that has all the portals to the various M+ dungeons.  You can mount flying mounts there, just not fly.  I like to mount flying mounts so that, in the case of Waycrest Manor, after porting I don't have to dismount a ground mount and mount a flying mount.  (You stay mounted when you portal.)  LiteMount does not let you mount a flying mount in the instance, even though Blizzard UI does.

I fixed this by adding [2678] = true to the InstanceFlyableOverride hash.

**Comment by mbattersby** [comment]
It's expected LiteMount won't summon flying mounts there as it's not an area where you can fly.

If you want to summon a flying mount there you can create a map or instance based rule to do so.

**Comment by Chalsean** [comment]
Did that, the rule wouldn't work.  Kept saying I couldn't mount there.

**Comment by mbattersby** [comment]
Works fine for me
![image](https://github.com/xod-wow/LiteMount/assets/1300207/c1f7db76-fa77-4211-9577-beb832a0852b)

**Comment by Chalsean** [comment]
Interesting, my apologies I need to read the wiki closer. I was using Limit
Mount instead of Random Mount.  Btw love the addon, its wonderful!

**Comment by mbattersby** [comment]
No problem, glad you got it working.
