### ISSUE TITLE
Rule for Oribos/Tazavesh not working

### ISSUE THREAD

**Issue by Flanell88** [xod-wow/LiteMount#188]
I have a rule for specific mounts in Oribos and Tazavesh, but once i changed my covenant it suddenly doesn't work anymore in Oribos and summons the standard mounts. I don't know what changed in the latest build but there are suddenly for every zone more then one entry with other ID, but it works for neither of them. I installed an older version and noticed Tazavesh wasn't in the build for 10.1. When I removed Tazavesh (strangly having 8 entries and 1 sub-entry), it worked again for Oribos (1670). Dunno what the other 3 Oribos IDs are doing.

**Comment by mbattersby** [comment]
> but there are suddenly for every zone more then one entry with other ID, 

I don't understand what you mean by this, sorry. I think I know what this is related to (the Tindral Sageswift fixes) but it's possible Blizzard have done something too.

Can you explain a bit more?

**Comment by mbattersby** [comment]
Oribos will work again in the next release. Tazavesh (and other dungeons) are not (supposed to be) in the map drop-down, you should use the Instance condition for those.

**Comment by Flanell88** [comment]
Sry, I was busy on holidays.

Here is a screenshot how it was until patch 10.1:
![image](https://github.com/xod-wow/LiteMount/assets/117266273/236a046b-f796-4677-a032-ccd99255abf7)

And here since 10.1.5:
![image](https://github.com/xod-wow/LiteMount/assets/117266273/2afc6767-7847-49b4-926c-78142c181142)

To many duplicate zones with different IDs. I don't know what this it.

**Comment by mbattersby** [comment]
Are you able to help translate this word?

https://legacy.curseforge.com/wow/addons/litemount/localization/languages/94/phrases#438290

**Comment by Flanell88** [comment]
Dunno what you mean. I just said I wasnt online on christmas days to answer you.

**Comment by mbattersby** [comment]
Danke schön!
