### ISSUE TITLE
"Auto Dismount in Flight" breaks Travel Form -> Boomkin form

### ISSUE THREAD

**Issue by Jilliebeans** [xod-wow/LiteMount#19]
What happens?
When in flight form, and I use my keybind for LIteMount while flying, I get a message saying that I'm in shapeshift form and I don't change back to boomkin form.

What did you expect to happen instead?
To go back to boomkin form when I'm flying in Flight Form

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
It did work before all of the updating for Shadowlands.

Please do not modify anything below this line.

--- General ---

date: Sat Nov 21 19:05:11 2020
version: 9.0.14
locale: enUS
current profile: Default

--- Player ---

name: Jilliebean-Dethecus
class: DRUID
level: 50
race: Worgen
faction: Alliance
spec: 1 102 Balance

--- Location ---

map: Icecrown (118)
mapPath: Icecrown (118) -> Northrend (113) -> Azeroth (947) -> Cosmic (946)
instance: 571
zoneText: Icecrown
subZoneText: Argent Tournament Grounds
IsFlyableArea(): true

--- Debugging Output ---

Got refresh event BAG_UPDATE
PreClick handler called on LM_B1
Refreshing status of all mounts.
Dispatching action LeaveVehicle
Dispatching action Dismount
Dispatching action CopyTargetsMount
Dispatching flow control action IF [extra:202477][aura:202477]
 - IF test is false
Dispatching flow control action END
Dispatching flow control action IF [mod:shift,flyable][mod:shift,waterwalking]
 - IF test is false
Dispatching flow control action END
Dispatching action SmartMount
 - filters: CASTABLE
 - filtered list contains 1 mounts
 - trying Flying Mount
 - found 1 mounts.
 - PriorityRandom n=1, t=3.000, c=2.221
 - setting action to mount Travel Form
 - saving current form Moonkin Form()
PostClick handler called on LM_B1
 - setting action to in-combat action
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
PreClick handler called on LM_B1
Refreshing status of all mounts.
Dispatching action LeaveVehicle
Dispatching action Dismount
 - setting action to cancel Travel Form
PostClick handler called on LM_B1
 - setting action to in-combat action
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
PreClick handler called on LM_B1
Refreshing status of all mounts.
Dispatching action LeaveVehicle
Dispatching action Dismount
Dispatching action CopyTargetsMount
Dispatching flow control action IF [extra:202477][aura:202477]
 - IF test is false
Dispatching flow control action END
Dispatching flow control action IF [mod:shift,flyable][mod:shift,waterwalking]
 - IF test is false
Dispatching flow control action END
Dispatching action SmartMount
 - filters: CASTABLE
 - filtered list contains 1 mounts
 - trying Flying Mount
 - found 1 mounts.
 - PriorityRandom n=1, t=3.000, c=0.482
 - setting action to mount Travel Form
 - saving current form Moonkin Form()
PostClick handler called on LM_B1
 - setting action to in-combat action
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
PreClick handler called on LM_B1
Dispatching action LeaveVehicle
Dispatching action Dismount
 - setting action to cancel Travel Form
PostClick handler called on LM_B1
 - setting action to in-combat action
Got refresh event BAG_UPDATE
PreClick handler called on LM_B1
Refreshing status of all mounts.
Dispatching action LeaveVehicle
Dispatching action Dismount
Dispatching action CopyTargetsMount
Dispatching flow control action IF [extra:202477][aura:202477]
 - IF test is false
Dispatching flow control action END
Dispatching flow control action IF [mod:shift,flyable][mod:shift,waterwalking]
 - IF test is false
Dispatching flow control action END
Dispatching action SmartMount
 - filters: CASTABLE
 - filtered list contains 1 mounts
 - trying Flying Mount
 - found 1 mounts.
 - PriorityRandom n=1, t=3.000, c=2.141
 - setting action to mount Travel Form
 - saving current form Moonkin Form()
PostClick handler called on LM_B1
 - setting action to in-combat action
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
PreClick handler called on LM_B1
Dispatching action LeaveVehicle
Dispatching action Dismount
 - setting action to cancel Travel Form
PostClick handler called on LM_B1

--- Options DB ---

1Uv3YTnow6hNStTB3liajaXCNtCs6UtB3PIDsV1CHRWitBX2sIUOKsANlYZ1E)(ITFhGZbGYIkw9uZpv
nrHe4GZVFNVdyMRkU6YRUy28Mb6pFEZNE4pA)6x)2h)HV9XlAgUTDOzDyb9RUP72p0oSURF1vNBUAZvx
86MfDBM3EuR95dDTRoUL(l48Bhw0p7UJB5Dlw01(P2MvHL)659R3SOz11hCdVPz1MMNs0vznPDXI9w92
1TVFvZNB6w08PfTN1mBO)QNhE8l6x(PMnPNSNyXtYl4I)7znR38Tp(Ig8)8Q(HLqepwS7Vg2OFGS5hEk
djyYx8)9)(W2vh1sFlCD9dD77GoGjVVbUD1ryaVB7YnDlFYeIrHHpjXHFgX7RBwDid4KL4HnRU9VGOVP
)p)lS6MNuRlLf3fx6PTOmz22dk3p0SAOD7tN(QdvsnZBUU5PxCQ4GCDn7h8)xy88jZPFCzX(A2PnlAgM
mOQZE(jm6JZkm)vQRIGjRpMCTZ3UQ9iGD0tj6Nkz7ceM7)YXagx94cQNoV4YMLTdDtaSDqaZftajmPE0
VQP5y8DPeGH9Qr(NfDTC6mXNhoJ)kWRx8W1SA9u(MhhvVC(qZIfhY5CAZWDlA7E62pMjW9((IoPi77oN
A5NS8H1RpcuKrvFhXQNQH8rey)3cMZtgO)2VeQe6w1m)OchN2S9(5DRwnLF4qzSpPsWzf)Xr4C17cB(K
OiMhbCEeG)pzf2)Q4V8QMvTdhh3LlN3Sy96Jj7l4Go5Rdp0U4Px8uvyp9g2HF8tV8t6eyZJyTlEyO944
ODj1QCFV3XvDD89c3158pzD8tDsXQWFr8PpfUvi))O7p)CO8RBoUa2iKU1h7QFe4)jONk6a)22M7oOg1
pS6l)7LngoLZ6FGlyEs)5Ub5NiZdB4(H(B6w0(M2hclA6bgV402BA2UyZbjy)4fS)0E5vmnH(87NyEUh
l(9mV8cMmGKF90Jd9y5V3SjJwWU8ChLuLxZ08)NsgRpOEmnD6Dv0hpos(TtKWSRSNK5AEj7Z6BcvB4qh
WL931VSB1Dhs1pa1Mdgfo4koK6FOEmJscNaDE0(Naq(rjO7XFEuk4brPgF(nCs(BAAx8SnZ319p100J2
8K9eZVFYlYj)6PAwps4t1JB3G3u3urEftD5eJCotoU7bt8pyj63xctnZ3OW7(CeZVCs2B5x)YUfp898p
hyUTdRE8ya7OatnuXbRo2ta738Du0DY5egf8oWuQJcGtCZFpw32RH7yR7aSU3Xb0bJd)VRpyfYHz6nov
BAYDJS29NlCSAC)8HVVMEGbPYl4nDaiPF1HnJdEzN7Dih0L)CWs57LX()085o0Y8G6WzTaTA11hvk7Hs
RoanU8cM8Mv21g30898K0kWcMF4vm9DGC4cVXS7oyI1(YbR52f9FQz6j3VOB16nnRM1sSPoVGAwSOBjO
CC15kaEaQDTdWp8MUv3ED)Y1GgMrk6ICIEtB79yJ1wiRlBx0F7WwOUVR7Mn4PET)QlEX8MLFIaa7V5BF
8Nqxu8gTYAP2EWEE9qlrD8Iw4m)P(HRBV68sCg)oyz2rhWlA(mubCYLoGw181(HBOiZBgG1b1P2tp922
B6OugCwRxId2wOzX)UTDK)Jo7xHo7GMamTQAOTN1CBhzEpdV(Y2HHMzTKI5uuL4MnlAJ760gehFwZcYL
qV79lUUzjYvo3J)YRx1JGy7T0FVqPG)7IzndlAHb9taKdADvfoQt2odyix3VD1FhwAW79Tp(ROCh1RBM
F152cyfNmF1ZURzE7M)oHrIt)3wCDYZdndQgYlBxGYHbe9i1(xB6IWb)u)jqWZAxrVkS26jIEHLIG)sk
ZIQYFxl0PpTzsrOQH188fnZUBiqo(0273mpkccXhfndKio9lnduCD7NchlSJxcpsdP6NIi7YPvVc47UO
R9w2h)Bd3o0TCjJT9I(T3pE5vvUh5cpdXXF4Y(LFADqyiDbzodD30nd2x36GTrY9InyGKVGTfwwjNsCg
avwVzON1nkJmU8tqLupfpkkCvKX33F9sKMbbTObPIN1TQnEIvtLwhe37AVhbL2Rj1U(rQn9xGr1btC4H
73efffuFGYVqC9)6BFmWd63BUlM73T5bKDubn)1Dlw12SwJ8oxzSP7YEYoFfDC40Sk28E56zn3J)8MGf
E62HvZ7xqLvWOWoF1qBl9au7qvNxSzOzd(7lBdzWokdg)1(LeOa5jQ1JTcsBC8b9H(HnTyWQ3snDMTGu
cduIFBBaQJmoJL10GtewtZ1TOOTYxXI4fBxeRYJrRrQIJSNFf4bniMqd8wuuqOcdWSwTzDmjC98EUrbJ
C4OQTFTpmqk8Dr5gCPx2V4zFUBiizn1OB1TRFgfUwtavks4JsipVB7xB6jCHL3tgMMmS9kgW5PflbPAR
AN1tHcTMGQoR)2TpB9CQh0OuzpC5bKHuc6kSdRbh)ppRfdu)LvJCuffKNIl0WbtzmwiHF7(2vj3wW8IL
KVfrKgAF2syJ)defOHzG8vq9pDO5UNHjncslcBR1uW8azYzTUOY5daFBjHbHJcU3qr0l7OwnNxwZoNBO
4hL0bPtpNsWonamFwaTwRjy)Ws)sq)pTDnoLn7CyLvynV8HwPMe(WHg8CDOfdHGd9)x2U6wcH(NxHcz4
xDWbEoS(5ykjK6vyOa2R(DoXaDzAa(WAYY)12ptZIOdNu9uiQqCLy3)e6PYDvIXdbxga4BaWA71jqERI
Qq3U6A4IjRKQqhJdfZa)cA3eS6lcmbW5t54pFO)oQH2fXC5SJOovr)7eDNHWw)51H6mk8Eq9lGBbGbu5
h6PvrQZ73CBtWtWnSDfKT381)aZ1rziuRTxdqyS9Mn9lcAx5J930jBM(KFxZY7rMd1XJWothxgCacKHd
MhZXUCE3S7APYpTFCR9trrqqocfHZB)tWE7CFLN5E8dVL0PZWq)uhoarAOQckRBGMK7YHMLKQsO09Dli
IkPy3g0t6ZbIrNh6w9p2U4zVcjhuGROIy38gKU91qD7lGVzwSlJpemcObJcP)sdzIx0oG6Xn0jA3)eFp
f7(u)Tu1CL(7Nuwq4C2yTg1zFCpq7JPrqSAV7UuoyraBb1aijC96UfKotGAulW1B63sFiQH2VeCxvvMO
10siLugrk3PhSb7M1eCg4iF)W6(zJQlCt4sxagAeVukObuABaQPDfryQGCXxSDvidxatd4hykW(vJ9Lx
2Dn1CfWZ4TNaySNfyErMHMUIGnJxmmEUuIAj59L7G3(wG6fAE5v2mmirSyf2vaV5vyKAoPmMqpVRf5(V
8pr(uxpw7jG8sOfgS46Fu)JvJyPqBZvLyt8fUNrdoDIsAPNixc(Px3hPfwoIw4ojTuoBZ1lJ0kQOSJjd
kNmmRb9g)kfuiKPDzy9LMhif1tn((cbJpQp1f3hihGmpuTFXzFaYcnCPw7tN9b7YTtdQpWeFj40r8M(h
H2wfziQpG8sK2eix7Q5h(BZ2UGkCRjWf6MmrUm5ulO0O9A39Tp(Fu)Jf)TGyl4sacBiKcD3dWuNruZ8e
JPx3Jyr)QRdnQar(NnVzNYflrf)KV(h9l(HZBhiUPqOAI)WdZgc(xqHKmSkIs0Ko9ZANHKjYG0f176u(
THUBr(ZMWmuiKarCY61eOcE)kYz0hhbiqZshit6)rfsrE7lHvEElYyE7IMhOG1l)Z7P56qe5VfmMx(ND
lAPorVlAVMsUgMOXgimm7UMaBUsIGoYZUEBy6GYOpJ(lqFD7IwrGfiLPB96Gh1q0ablPiiESwyNEWGjF
UZe1Zz9o3(E4Q3LbmXpxciPnVLkC620fhLu7RmWTHrkXiJERrh(zHPQenEWSLNRRRDizoSaFTQi(ELHO
8qVhEnNk((IAdyKh(P24DOns4PWo41gEQllbB8Pv1O4MEyvTV2WIYwRRJNkinOcl0y0L1ScwIXSIlf1(
QIAExEVkDsowR0Uc0znjGs5PgLo8um6h41fSfacy8SbGAr2wSoTilR3xPZliESWfv6JBRu7CwExALoQH
g01oUjYxYl041U4HAQXyLrxjgiE0Uznv58XtVSSOQiBtwj(uPyNgT)OqbotjhkWzwPe9SsvXcTqlUsKg
AC5feva0LsmKkpn6w6yDzDnQ2Oi2ytwVlR)CAfIF60E0CQKbvcsO27JwL1xRT5xxMmkDr(PS(J4OOF4P
SrBcYKcPExDv(m15TZ(eNssuSgNkLZQkYEsDuu(ANiE4szD2sZ6foixDEdrfMiHh(Z64jagCfSrRaF)S
PWjsHmXyTwbfF40lNVY6ZBt0lLHnHWjYEaxDTKcOkisNXqqrOUtwBoAevDRZWHnowqMiwyjx2IWI43ms
SK0vUy0Al0sLGwxNC2gPQZ7nCy3OtWcyYZ6O30a23CYi2UViARwGaWBYxQgTj2nBQTcyeTFrRq9zD(S8
SRW59sfMfWUHOPRQogbQkklI6pzjCUwjsqeyVIAU(pSDowrgyCTHfW1)aiGZldp1N3MHTvRHZ3csGxlY
slJktHvLa2qxv2yvgfRSC5aTFYVYP2aSIXRX79SZM2VOa2sxrwVJ(9svHSuiGQcrQvsIxPoHWPQhveAQ
ZNkJRvwQIGqoykCciCvsEbkyy00YALUI3Jl5jkRKeCTXYkQ3ARzDQWuWOfaIVUOmVwPjLrXfPHsBoyOD
sNlc3M3vrgzYO5CbQZwQcajtC7gJf1BHFchj3IQaydC1qzTVk(AVvq9dskAF1iVvuPYAw994i587cIby
mPeTyTzTpb8vkDiPuzwNI4EbD2t3uz4KqVKrBsA2cfv8jgPbK2Qe8kGQW(bhMvkkEVXk4lvoN0)tZ4eA
VYW13KVZYYX5JErRlC2QONJldiugokcwzsue085tKoCAbIYZzz41LP9NISLU0MaRawpnL1jpQrX(gTLR
IWd5WaL5XiFOFnJDsv8shn08jACiBMgjo8uhnYF4mPAu(NL6ANKexw5K(Kv26KMALJVKlSc(KeECPGDG
C0ywaW2k4oUbHYMhDuSrJqhNdAuEB88rd5krtkeEwi4unwQrtfBHBnqG4EHPh0QO7hjukMZfcpAwRbrp
D2OlZcva8air097QQ8PggkU9ivUXPzKOKwtUAo1hGbC5CqO(KqzVEvS3xiJt5RDj8IryGLj)7ygBPK3Y
4MSEH7zW8zGxsO1jNMGmrIk(06AdZim8EtYviWXq(vjktLEraON(OyPa9aycbVSiXoK8G1z5QZQGv2MH
9Meot8C1wKnKZlegoLc4jicZO8GXwbNSuyGUi0IQCCTIdEOyBa0Kq4KwKG(lnwMQjYvfoBuuvCaybsem
vmrWG8AbWppuGbD5vctDvQUJuvbub5n(SyzhKsrZJrlOwcH09eWuHPvwPZBIJakTWql4a4FcEB(mbxoh
HAeLWul45AqouzzULA89OQKt2kqhfXumsXk5uly3RJXET1kotGW0e1WvijnGYmNEqPQjW1uRH6sHiSYP
zZat04z4bpmoUfLj1Ig6Js08sTKfyyU)wRNXzipdNerQP4ykQ42AGcgZRhT)yUAePsg6uR4gTWgeQyib
uGtik0SdSsPvPmuMYHs8qHfkDNqqZK8L8UrYgRqHLke0qYGWUiCPpXF6yA1K3M)f4zgpjAQjUxcjtPrx
LJPbe6tYBQ2KzV5lZK(QhLGke1qshZFfEcPtoLHWVhO1C4eoCFAujURArzEy6aR74p9kpZtPQk9qeLKX
Eq3utuuu2s8qHkX8qqFdlhicAkhWj)7OHgYyKS(ro14sTe914Rr9vrUhGx625gxjXPekX)bUBm)aIXUa
Xdg7vj67LJqtfrvAcSdPSIkJJ5fuwAYdnyfJgwLGfs840zXM6NO4rbc0p5u1s6RHflmleT2wZ9iO0hDk
r1WLGi8ZknafKyoqLKwCi7MXpnwMqEfOElJbi3Eb56Kguik4Lg4AJWkWwjtbbofCcvP3LWXnP(BA2lq7
o5eegWi0lTCjNeR7uQBojn(qhbizcBUkwGIEbI1gCGCdFC0rxj8ucFMYqJD6TOdcxRHQQAbkOOYlxNec
aojQQuvsqXuNdkS4r7w(1eWOWmdP6CwBz4dsfp)A5wJWrj5s485LsjOS7cKUvz8bg1Hwz84P7sHJ10jv
Nfk33gzQmQJHh0jOvyMIIKd1NxkxG6n0hNnKxa7tyMviKmcUQISu5WKc(xPWbWQ8z5rhmJK3xY0KOCuo
(4OriynOqYYOJvaBcvf4xGaIqNScmRsHIsPwajMwou4ksmJ4UiGirGdNkej88LzGrN0cBtitBYPYGwuD
OnhuzIXk5wTqp76r5OcstLJrcOVcLmhj4QkScOfyKkJcUAd(zUYiytcfmhJ)cnLNqO2ZTidoCxkJYLD9
CUl(j3PGkV53xjWuK)uAtylSc7GALWzcdp5Z2UW6ulfr0k52CQAfhAcNPIxQtxNgORUwM5I(srIMYhf5
r54PcTC4CBQE(kjBHFnjtb6tUeg6J1Y5GwlZdbEZsf)wSL4dDGLNK1vvx5ZQPqh1MO(MUchxzQzCrLl7
o5ZXjxLOYLRPLrKiDKpAWfxiD5eyEFTHr7GEjxoBzTCNNA6Qnsmn91XiaLDAt2y0v6bRD(Wb5dtYU5JK
YcL2j0nYfnr620Y1ZsUj(pQeLuHrdDhCPBkhwhlbI)iNlazjZeaYVkwxGRJdWvwHnhHYiHvSTQKd1NYp
D5TNXgTsewU0tQ4uUeiWJxjzDb6)bn1ldDh8fSdcPQc5bsv1jNQl5unPvY3digVRyulZeENuYJXduI(z
KepstJHhnsLleNkicwj7xlZuaMCYirqRZ(NAbXTSuMvdTVRLM2qxltzFPyz6EqufcrQGu5aKVmnSjY6Y
dL5tO7(0zHKrDgGt(PoHo7iNu4xvLjwP0kzsDWTMRhz(fEVx6OaUcsZjTeadUvUkLu1rhpxRu6K7oZ5L
BuKWmLEMGivcysMqjGcWzaaxrjm51gUpfQazobbPMAeALBFgDm5j3PqCH42RL70ICW(SUYzZamSinaqQ
RK3ldVG0j5I(qRa5MvqeqQhPLMfRCV0GxhdytragIP0ZYVKPKq2eVxyOcSmnPTklXOLeCAJo942q6r6c
hR4w3E0W2NkLTjarPpljtULNhZhiZ5GMnmQbQas3Bf8Pzkj8GwYfQI0Ss5cXjHMYUSYixKqJQxM3yiom
kNjBtCMaWZLZKI(Y0dkzqcn4jW1xbvvSFvPmPdPmSyl1mcaGVKB4IEnNZaPwPYQnN)Hqkd2BjC94Ui2)
jewB(Qk5lZkivbHvj3tlI4EtYaLRCL8QzWigmZkxQjSjtEKqtg1ZMosT8lUjNXBkyDJUXcj12k3VML(M
Rz1u8(LjIafckIvMbdK2egdeIykFqxNyBBTJ83chvzSEYBe3Kd6eNKHH9e)QqyG(aqCNC0oZk3vpIwPp
gJTWka(1YSw01MWi2ENCZx4pLXIjPkmvDMSEY4cL2KymCBBGKWqvK3mdpYnqjwBrbwN)8VoqQtke5hrc
uqp1L88iHzVzLiEJAIZ0lrxtUqIBKj3CwqKcHXQkUGfimkgzS2jZfbiknJcqF7XISizuC0zsY3HRwUhz
VC35gNIj7gg0lx5lD0jICs9MxcWWzBKHfiQv58y5(m8gU5nq28PIarvrjQrvL11epfLs4mLg3bu8tZdK
U0vVRsy0uchqb7lQgdmluU1Iphcsi)cI7AHpy1OrHYCjTCsqvAgDsK56iztP7ynit2rq3huuNOpMcN4r
JaXkA4loe(zfDp6jhLpVsU(biFSHsU0ygdjtbop6hkIjuUKhTsIErikflu2KvkgLiKLYumOpSE6PA520
inndDlZzOL0d6Uq5jKnzsM1fQu6NlD11ADAykiu2uPzHtofMKDqO87DkXadov5PANlRasPG36s)dNG(O
bSheJylhw4FrYHFsvQj3QG3RvJCw6CSIjKfUN6eNXs56vO1QZABzETM8AhvyX59GKHC7wgT8fTRTM03U
wRtF1a5Z5gKk)EqcrG1b1gbze11LswG8p6g6(wKR8dP9SpI)2GQqXexbf(utr)wbMLSohV88(bjibVG(
UhLjDvccOWvUuomXmJYylLM2GtQq1NKAuu0)Qk4gcKqTzHYQvzPor01vieOSYDHdGTcHDCLC7V0v2Yzo
0Ldl0hK)DeqF)O4VKpCVTs(QYgTKDe(EfmMzrInqTx8muaNDY03firSvyte(2vStYuWtz7t3fs4ZhZLh
fwRCTZ037jvPluvRKUmqrKlyeTgeAZu(y8mDv6i05MP()Vp3SO52xmVz1TY)mTc3R(LxDX7E)5xDX)5v
BUsUI2DFwe7DNNXTC3DDXRFF3Nf)4h7U34)oR2DDXoPJFM8FV6))

**Comment by mbattersby** [comment]
This appears to be related to the "Auto Dismount in Flight" setting in the "Controls" tab of the Blizzard Interface settings.

I won't have time to look into why it's not working properly for a while (since SL is about to launch), but if you enable that option it should get your old behaviour back for now.

**Comment by Jilliebeans** [comment]
Alright, thank you!

**Comment by mbattersby** [comment]
Fixed in LiteMount 9.0.20.

**Comment by Jilliebeans** [comment]
Awesome!!!!

Thank you!
