### ISSUE TITLE
Non-dragonriding macro?

### ISSUE THREAD

**Issue by mririgoyen** [xod-wow/LiteMount#190]
I'd like to have two macros:
- One summons any available random mount based on default rules (normal functionality)
- One summons any available random mount, excluding Dragonriding mounts, based on default rules.

I cannot seem to figure out how to make the second macro happen. I've modified the second key binding to remove the dragonriding condition from logic and set up a macro to point to the second binding, but it still summons dragonriding mounts.

**Comment by mbattersby** [comment]
I'm not sure what you have changed in the action lists, I probably would not suggest that. There's nothing in there that selects a dragonriding mount, that is done in the addon's internals of the SmartMount command.

I would suggest putting the action list back to the default and adding a rule for your second
keybinding which has no conditions and the action is Exclude Mounts -> Dragonriding.

**Comment by mririgoyen** [comment]
Thank you so much. That's exactly what I needed!

**Comment by mbattersby** [comment]
You're most welcome.
