### ISSUE TITLE
10.2.5-6 Breaks dropdowns

### ISSUE THREAD

**Issue by Aeon234** [xod-wow/LiteMount#196]
With the newest version seems like right clicking to create dropdowns breaks. Noticed it when trying to edit weakauras.

7x ...teMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1319: attempt to index field 'NewFeature' (a nil value)
[string "@LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1319: in function `UIDropDownMenu_AddButton'
[string "@LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:2348: in function `initFunction'
[string "@LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:771: in function `UIDropDownMenu_Initialize'
[string "@LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:2357: in function `EasyMenu'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:498: in function <...eGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua:465>

Locals:
self = <table> {
 UIDropDownMenu_SetButtonText = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2083
 containsMouse = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1918
 UIDropDownMenu_DisableButton = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2067
 Create_UIDropDownCustomMenuEntry = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2291
 UIDropDownMenu_Refresh = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1446
 UIDropDownMenu_Initialize = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:762
 UIDropDownMenu_SetWidth = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1962
 UIDropDownMenu_SetDropDownEnabled = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2109
 UIDropDownMenu_SetButtonClickable = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2096
 UIDropDownMenu_GetSelectedID = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1592
 UIDropDownMenu_MatchTextWidth = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1951
 DropDownExpandArrowMixin = <table> {
 }
 UIDropDownMenu_GetSelectedName = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1588
 UIDropDownMenu_InitializeHelper = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:92
 DropDownMenuButtonMixin = <table> {
 }
 UIDropDownMenuButton_GetName = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2053
 UIDropDownMenu_ClearAll = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1998
 UIDropDownMenu_GetCurrentDropDown = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2041
 UIDropDownMenu_JustifyText = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2017
 UIDropDownMenu_IsEnabled = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2158
 UIDropDownMenu_RefreshDropDownSize = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:818
 UIDropDownMenu_EnableButton = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2071
 UIDropDownMenu_SetText = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1988
 UIDropDownMenu_AddButton = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:983
 UIDropDownMenu_GetButtonWidth = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1398
 CloseDropDownMenus = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1879
 UIDropDownMenu_HandleGlobalMouseEvent = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1923
 ColorPicker_GetPreviousValues = <function> defined @BetterBags/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2158
 Create_UIDropDownMenu = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:748
 UIDropDownMenu_SetButtonWidth = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1978
 UIDropDownCustomMenuEntryMixin = <table> {
 }
 UIDropDownMenuButton_OpenColorPicker = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2057
 UIDropDownMenu_AddSeparator = <function> defined @LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:941
 UIDropDownMenuButton_GetChecked = <function> defined @LiteMount/Libs/LibUIDropDownMenu

**Comment by mbattersby** [comment]
Seems like LibUIDropDownMenu totally broke their release. There's not much I can do about it until they fix it, it's not my addon code.
