### ISSUE TITLE
Can't exclude Dragonriding Mounts, can't summon ground mounts on modulator

### ISSUE THREAD

**Issue by Flanell88** [xod-wow/LiteMount#197]
And no matter what I do, it no longer summons any ground mounts attached to my mod:shift button, even when changing the button makro. It's now always forced dragonriding, then normal flying mounts on mod:shift. Before the latest patch to make dragonriding available in old world it was always flying mount first, and ground mount on mod:shift. It only summoned the dragonriding dragons on Dragonisles.

**Comment by mbattersby** [comment]
Yes, that is the expected (new) behaviour now that dragonriding is available everywhere.

SHIFT will summon a regular flying mount in a dragonriding area, or a ground mount in a flying area.

**Comment by mbattersby** [comment]
If you want to do something different you will need to make rules to do so. For example, if you want the old behaviour back you can make a rule "Modifier : SHIFT -> Exclude Mounts : Flying".

**Comment by Flanell88** [comment]
I tried to make rules, changing the makro, but it never summons ground mounts even when forced. Is GROUND even the right command for it?
I really want the old behaviour back. I hate dragonriding.

**Comment by mbattersby** [comment]
> if you want the old behaviour back you can make a rule "Modifier : SHIFT -> Exclude Mounts : Flying".

You should do this as I said.

**Comment by LyricDawnhagen** [comment]
I installed your addon last month.  I finally got the a macro for **/click LM_B2** and the following changes to the Advanced Options in Key Binding 2 to work the way I wanted.  Now suddenly, it has stopped working and now only calls the dragonriding mounts.  

What I am looking for is two macros where the first (/click LM_B1 using the default script) calls dragonriding or flying or ground or swim based on the location.  The second one only calls flying or ground or swim (NO dragonriding mounts ever for that button) based on the location.  I have two macros as buttons on my hotbar where the first call /click LM_B1 and the second calls /click LM_B2.

I did try the "Exclude Mounts : Dragonriding" and I just get an error message about "Bad action 'Exclude' in action list".

< the following is the Key Binding 2 scrip I edited and used (it worked as desired) up until the big change >

LeaveVehicle
Dismount [nofalling]
CopyTargetsMount
ApplyRules

    IF [submerged]
        Limit -SWIM
    ELSEIF [dragonridable]
        Limit -FLY                    << The changed line to ignore dragonriding mounts >>
    ELSEIF [flyable]
        Limit -FLY
    ELSEIF [floating]
        Limit -SWIM
    END

SmartMount
IF [falling]
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  # Last resort dismount even if falling
  Dismount
END
Macro

< End of edited Key Binding 2 >

Thanks for any guidance you can give me on getting my mount buttons working again.

**Comment by mbattersby** [comment]
I don't think I can debug everything you've done from just that snippet. I would really suggest using the Rules interface instead of the advanced actions unless you really want to delve deep into understanding how they work and reading all the documentation.

This
> I did try the "Exclude Mounts : Dragonriding" and I just get an error message about "Bad action 'Exclude' in action list".
is referring to a rule, not an action list line.
https://github.com/xod-wow/LiteMount/wiki/Rules

I would suggest you set all the action lists for your keybindings back to the defaults, then add a rule for Key Binding 2 like this:
![image](https://github.com/xod-wow/LiteMount/assets/1300207/06ac5013-1235-4208-9506-4975450e5123)
![image](https://github.com/xod-wow/LiteMount/assets/1300207/f3e1d196-2180-4e0a-9458-8a861a3d42e2)

**Comment by LyricDawnhagen** [comment]
Thank you for this information!  I was misunderstanding the Rules usage.  I reverted the Advanced Options and edited the Key Binding 2 as you suggested and I finally (I hope) understand how the rules were to be used.  It is working as I wanted.  Thanks again!

**Comment by mbattersby** [comment]
No problem, I'm glad you got it working.

**Comment by mbattersby** [comment]
Closing this off I think everything here has been resolved.
