### ISSUE TITLE
[Suggestion] Option to pre-cast Visage before mounting if in dracthyr form

### ISSUE THREAD

**Issue by F-Lambda** [xod-wow/LiteMount#198]
While Chosen Identity is supposed to ensure you're in visage form while out of combat, there are often situations that cause it to break (for example, using Hover out of combat). Mounting automatically casting Visage form if in dracthyr form would solve this to a great extent.

It can currently be accomplished to a degree by adding `PreCast Visage(Racial)` before the `SmartMount` line in Advanced Options, but this only toggles it regardless of current form.

There is [an addon on CurseForge](https://www.curseforge.com/wow/addons/visage-mount) designed to do this, but it is only compatible with mounts dragged from the Collections menu, not macros. It may be useful as a reference for how to do the necessary checks to implement this.

**Comment by mbattersby** [comment]
I think you can pretty easily do this already with

`PreCast [noaura:Visage] Two Forms`

**Comment by mbattersby** [comment]
I'm not sure about the spell names actually, it may be

`PreCast [noaura:Visage] Visage`

The condition to check for the aura already is the important bit.

**Comment by F-Lambda** [comment]
This works perfectly! It even does the job when still in Hover. 👍
