### ISSUE TITLE
Bug: Rules appear to no longer be applied in 10.2.5-9beta1

### ISSUE THREAD

**Issue by CodeW0lf** [xod-wow/LiteMount#199]
**What happens?**

If I try to make any new rules that try to limit mount selection, neither priority mount or the rules appear to apply. Selection of mounts is still "smart" in that it chooses the right mount for the location, but it doesn't apply priority OR the rules as specified. Removing the added mount limit rules _does_ make the priority start working again.

**What did you expect to happen instead?**

Rules applied and mounts limited as per key modifiers and specified groups.

**Did it work in a previous version of LiteMount? If so, what was the last version that worked?**

Yes, still works without modification in 10.2.5-8

Please do not modify anything below this line.

--- General ---

date: Sat Mar  9 10:57:44 2024
expansion: Dragonflight
build: 10.2.5 | 53584 | Feb 29 2024 | 100205 |  |  
version: 10.2.5-9beta1
locale: enUS
current profile: Default

--- Player ---

name: Kikotsu-WyrmrestAccord
class: SHAMAN
level: 70
race: Vulpera
faction: Horde
spec: 2 263 0

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: 
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
```

--- Debugging Output ---

```
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * args: 
  * limits: -FAVORITES CASTABLE
  * filtered list contains 239 mounts
  * trying Dragon Riding Mount
  * found 8 mounts.
  * WeightedRandom n=8, t=0.889, c=0.427, w=0.111, p=0.125
  * setting action to mount Windborne Velocidrake
[1] PreClick ok time 13.47
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 0.12
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 8 rules for button 1
  Dispatching rule LimitSet FAVORITES
  * New limits: -FAVORITES
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * args: 
  * limits: -FAVORITES CASTABLE
  * filtered list contains 239 mounts
  * trying Dragon Riding Mount
  * found 8 mounts.
  * WeightedRandom n=8, t=0.889, c=0.258, w=0.111, p=0.125
  * setting action to mount Renewed Proto-Drake
[1] PreClick ok time 13.99
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 0.15
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 8 rules for button 1
  Dispatching rule LimitSet FAVORITES
  * New limits: -FAVORITES
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * args: 
  * limits: -FAVORITES CASTABLE
  * filtered list contains 239 mounts
  * trying Dragon Riding Mount
  * found 8 mounts.
  * WeightedRandom n=8, t=0.889, c=0.378, w=0.111, p=0.125
  * setting action to mount Windborne Velocidrake
[1] PreClick ok time 14.98
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 0.16
```

--- Options DB ---

fU1wZXXTY5FooUkBv4(f9M8XxJTODPvh7kovyXrKdj3OL7OZWL2I6b(l78w(JLUb6Vgtoow2(bneOrJg
99Ub2ZTN)6Z3D5TtR8)(97F7YP7F4Pl(8NU4xEC9U157p90fV4YlxwVIM)e9)7U5WYBMoWqFZ6YdV7E(
RVE59VFH)6SGlh8XZ)IZpZvnwVN)k4noxFmx1NtTV8zxj3N16JTV8Ly2xAFfRjNR9Lp4tjaxY0glKIXq
hoVl12dciAj8x2STe7WzsbhpBJUV)H7UB54FB5HJNAuQpvikK3HCNWkr6Fp)SS1hO)XZypfkfAWaVNzh
HvgG2bJ(xcCFoyceew9yCM1gB0V3s)rIbjvY8qgLWpR6zgqjeDTLMl8FBQkft0KEEpltJhSodtj(gd2e
88XKwt2LZMgoe(uBBAOo0hUZsbHu4zzIjLtzFByRJqiJ6mrmHIHNU0yibF)K5IERroKUqGKFnC4mglFW
4HTfxjX)BBhDjgvnAky8nEgjOkm5zvTHZCfgFgtn3yL2IjgITpZXktC8kJXuTlw8oxOVBnLOC)41L)N1
eyPuUAANjN3ujLlMgce1ZNd6els5ov4j865p5DYvJyChP9A7I)aHBBN7682qOlSAWY7oZr8e53hMe32g
rXGKRPgln1j7GW7AwgnMuWsip03fBUWIwBx44kvBTZ9YPQ1lBFZyPZFPTpMA8Pgw4JfRALmvwMhBBznl
YfcGUKJqGidB2hmszgv1fmcRK0oy9YSAbrZYsGsjislBWvzgcVhHCHztmNQKAkY0c9vYEOPt1PtMH0Km
1aVJnsU6fXiPCef9hsxJKZ85uOJuBDUedQ3JtImA2fYqw0CXCwZCK4VoNRJeXptJMibht8nMezwYY7yx
BPubxGiRCh6UBKZkbHsQNlgDUM8I5FMSZiYLezag6mhhjqnrbex2YNhl735YLJxV)MFEE9(9lhjB)Z3T
)49NMoE5CZnKL86oDy)DxTSE(zMZ39vt3FAE94tx897pEZvl3DprU0ES7VF6MP1RMPXNNFhpw68DV(w6
VpB(9pCFthHG6xNxNpD7tx8YL1t75rtEAuR5z2NfF6IxV)oAbVA)1NUV5I)B)Tx80f)BnS8ltRhMoE19
FkzarC9DFXHPlF76YLV9Pl(Bt)grqeYyoZUVz6eb(Y1pDXjED7MpDIiu6JhoYAlK16F629LZKdyAdFXh
M)91Pt3(P8ci3N7(Q7MxNoCfbX680Defqos7hUFMohZV)Pl(P9hpoD5H52j6JSfVEpXzPT4VF4Q51L(w
W(c39Rt0omRNgApm0H5BNoC4((P5h2FZTNoshfEkAbFZdhVAD6TnsKKzV4U9R0FF)97p8zYrVrSFcT8V
D5DZSvd5PE33D83MybnrYl75inNvRe2E5Ynp8j3FltB)0eXAz4DKk5UVyD5TZ0OF39hi9b2X)UD3oD1Y
VF9eZv7cBxK8jS7S5dNO40SWork8Dg0xVSEJip2T8WHM2cPsDgX3UDD(4v0(eTbb4FHKWZRnXfVFneZI
0vACWlFXv)28XtpSYZgiho7E90hiw293IJ9ppV)Wmb(lNwF78j68fRcn)5)eF(E5YXMk8JScdT(DNwwV
7(tlpqzs8fRZ)EBglzNrm11B4tJ1AjL5VCDA(iBeyJbZ)QoXVp9itTK16UxC4gsf)tMw5etMUA(oAMif
2B3p(WjwfMTqn8(EjPsptBAti3uCQ)5koKz6dnojPDEh95X5pLDAgfohDiootzbnZAheYFXh(Vxo85Nn
V(WByVnoio6YUMLe7sNIFl6X7pE1(lNMAhpYREtZBJz038azCVF6yZPx3I19mt3iDOJ(ZthwwBd(Y93F
9(tmZz6Mf22KKKGwFXhiPhd8dho1u)j6LShMUB64Zj985BMU8Xo(E9Je9uOmi2rsURMw3p1mH9)5SPMB
HNU4RU7D7x7mR)XNi2z5ira)WcNW4FB)Ph3C4E9YHp532VYEw8mnUs8YTtV)kw1NcntsDOi2K2eH)QhE
ZJSX51ZSf1stqgyou)KRgoKmpZY8BxoSCh7CLraft)p9K8YhwpSCzxEptF2od1MaB(U3Dylb(VpDvZt3
67ilJgEZ)549vlVz5eJ2N9Rp7RE2RE2p(Sx)SV9zFAph03TUCnz989Zp2sB(SP9Nw()pz7DF581nbiz)
Dy)(ouVCHpXnDLna89psw1K1((PpcqKdHL9FK5F1Jl)p)Z)ks57N(TpgH8RZhN)a5N9JaYVSC46Rj)bF
SJZ(hxF4Jo)hPgLThOJtRxE7FfyncIDa)Xb7h2FA(6L3)XLcF4VepdvGM8hdtFEhxxYpTUFzD)P9sMbj
kt5EUJwhv5qTNtNP4L0cBaijt1R3ONEs0MKvzkoKPupfhBprL6auj7pkXnFh0KTLSgdjvGuXlZBSXbKb
DtLCk9jBc5eLmX(OElLFKBaqymAhwK(pdqjvKuvtP)1sQ6BLC(PsEq2)uyqKPRuSuNxfKuDtvFfvOeQi
dFFRqo5OiBvQLZz7mxIfHKYHuNrukTKqBl2uK85BqwLpP8Ifa4ILqPeouZWOckKlCF(sUJRsiJbLIlXN
(bOYjXxD5X8cpLRaRJGGW8Dvkb3coXcZJp7DWO8tRs5Nu5UEVGCI5k6oevkBoZhCkFOdiLtHTpwijclQ
aUS8PutkstNkiX33FkbCNtu(OsmabqJ67lP6BP5JbTkvLv(qXoM3ngT)jv5yv0yjTdP4nQYyCQ9XGfc6
AYp4kIAQRwfv62QCkdqqkj9egukvcYxgRvujsbO7tNyJyMXLa2PKezfd2RZKf2B1KQgfNq1oBeMdPKkt
7indJyfuGLF2NeokPAcjGlhlEv4lAgPqfSrAAHK20cbNpkypR8o(OlUGm5ADqrIDFOO8dJvD7eIXXbwj
Jw5r2U4sS2iFborVU9zAaqNsJYbkM77DYN8OMXsRMEBxO3)kbfL0WFzaEgzoHdNuuyV0Gb5Og1njnMgT
TGpwDiREJu1mFQhhq7qFwokSSFZGzCulI0LCwkEBAZ3rvnhfFzmLmezPKUMIEWRkDOkZI3vU6vybeHlx
xUIEdXihECvvmE68yrIowOQo6DwHDwYqhIpKc2RMSDGtBFnKrL3nwENoRfNzqhQMLD00PK49LPj5Oto5
d5nJMhWkCz0whbaWt69pHbiee3Z(qgMD2nsE5mvl4GyRuuI04KevSloVhT4HmLHjgbAeU3QXeIzKjnFO
KtNeHRqAYED)7hpsxkcNUzzmM9iQGstkXGcFGMf9iJ0Xe(K3HCeIJ41C8eeK2HypmFiR0Xa9G3Yq2PZy
TQwW0GsdUOq0s3W4ZPyXseIx0H32cpQ43XXlmGezMyDf1wnpYCWdvoEBvxcI2xO61dfbjyPv48MwZMJc
YxHiaRC(dzeMNhCqFJJQONq6JsYknif94sDWsbJ0cDqM4KdhR6GvBJXHwuFFivpeHNqUZaincFkgGyOn
VfCSiY2GWzCqDWNNL03TGOYd2i8uzJAWh7iG7OxRui6GKKd6Jn)xuEvYO0EnsSISA6h7w5UT1pAYAGBT
2aY0y(X5g2z8NAmtyDq(BCiHlk1WnIsewt6NpFADijpYVksEihG3h2Qq0V20Ey2Qr8Jf08T4Pfo0WMVT
EXMNYyqIXLIbKCbVQYyvPXNzLdjlYyeJcl5I3OOxsJcnqgJQPgc)mSLU8zjOA9XERqXNYMsP8GS0JQzd
tkd6lUzvIoCUQnENovwLvb3SAxYPaSwnUAv9pknqUnkLXQOIuT1n9t1mwvCaAujW8yWobsMDMXYdJPLJ
QJKA2XOLXOIhIkWezJcRf6)qCeNgjGxEvjeW(O9SVisrarz5LpiuKiASy0Iuis1oGv2akIDDSxIZi(wg
e1YuPwhqwhqQ5yatugRiRtVwYsUgtBwfYuMkfinqW4iG4oYTSGLjk(jYLeQjKskinaqKBuGVACG3n8Jn
7gQGccgMDVHehYqnBcYiBdQuL4a8ZKS(6qZbPwW32qyGHYy0bSi4cpkI4tHmfZpBgAKuMjIEsduXKG8j
ghuo4DmaYMvdoKCev5wAm4Mvb0w0OUeaoJUTdXGeFBZDqLJUnCg4FYuq9Ue9jQumMGppeHPTgeEM4McM
KRLRtjzWUnrWw4lEuRtYIAI2C3zTrHxddoSuIAjKjKCftTrPi0Bw2Wwia7U(nnYJA0AEz3LdsyeeYPPd
qXgr(FMOzWeLmFA3EkQHlH08jnXOA4KuvMKD4zqiaEEjjckVLesDzZTRrRs0iOcPK2gqtgJW1VfkFuIt
GjBHgl5kafXixqyB(m8rZeDAq0f8j4vmLIeKl68XOMzjjxG(uoMnsoWouHDdvzDxrOfIRbHbzikNkkBu
uSMvl2NxVO6tjjkQwuklOgyINegH(e0t(1rqq(wzBFs8rSCgN1X8oGjC7CBVRrgaX9aPkaZ0Q1JC3SOd
e0x1WyrrDrB8CxbzXx0ChahkWQTQ84uTbxf9yzhdkQcCaL(GuXD2XIsOUmxa5Ui3Qo2GofYjXiRIFWbA
U3b0oe52)7Na0loY)S0(gQIu0QTrjsKfscniKSwfR4uQkZh4C)tJvvg4xnHCGaK7TUTmnoizzw12TrBw
Dal88t1jTzu1JG6NW48cne1OBT(CnKmbqTgK)izn6ddujE4jHGFq3ILzXw2SPY8KpDJsuWpM8Qd4rdCV
jbrP9xHspZp2)XXwYUPM9JM8MCBqLWnjtdOzKhExto4qK4eQ9MCb0ncexxotaXXYYdaqfsKwGDaqrXBC
O6iNg(CTb0nBwwjXX8IXfRLGSomKlVKUkHDsUPWd0GNxqf)sieEO171MfyY5btqtbIWLFSmepnLvVMKB
NHSRegWklJbDdEhQVsbfuieJy1yjgg8bfkzWY9KhcbwNBZ8BjxeP1RPhqfYIuyIevkrEcAp(jF8Q2Pgz
WL9sndTfnKUI6vndpaSofAYmdk49zRFSij5yUT8jS)5rsCg7gCTHwLytENIaAEepLcJ5gJghRs88eX2s
hkXhhr9O)cukhIrrdtcsj1a0D1iQ)gprlbNvfsiU5574pws46mizfmQlvtagcrdWkEtlcaHXYKtDHc5u
1p9kfGo5q5rJOK0hwu)rikEGCCo3chWR5j3ayqJq9MYyrllOGMvrjPg1WpvThq1Qfr6yyTcYQrXHg)MG
ex6gCtteBf1Lr8BuKVL8qKhBvCGurjihHRrFWcE)4nhXpZdKFef(ak0AFXy1yXcNmdq(vK6aQlHc)IIS
PsWSUbw9daGUxck)8gi8cpQgcpQpzrIpSyuVEkIzlQwTNLKQKkoRWBvQT)f9sVmXrQZLbrJ(8WJkYv5P
FjaOXK7Vcp(tpzrlOLBnqDSS04Znit2cYvMwmevGJvp3YxbspgTcYBTGCZATFuUgOtlMXTOm66TrdtWq
wgZpIQJo8ZkjIK1uhEfdAq9CeMV8djd2NbNwDE2e24wQVduciOOiIcuZRuvOqkXoC7o49P1oIKhav2gK
epW7cSZJefwozJsy8zhbj4kdV(rlFdj4syB4u2joQUi5gVUZgTccK9SkFUjsjfIh5z7rluB4vToSirFQ
2xCxDYdhKGXrmJ0q5q8R0uo86NJo7e0xIjP8yh0Ry275UdpGfXGj3jWDunPxrzgnFMCYR9gXHlOiq6zs
QGolPD0PgkmNrZxa6C8Ezq8XacUyS4QMiV4wn)surm5cYoYysV7ScAtcj6XvCes6vjtvCl65QzlEeJ2M
QdUcb2xeSG5GpiVIa6DhNAfkPMsDswf7Jgoo9wqQvnxcAwu4dr)r96747uO)PdzFYLRbHbNxVFaAujgC
dAC95WVGhTmRbRO848ARsPqdWeoB0CPdfVO(XQQOc)SbzyZ3)js8LtYr0yIKp3HrUaajnZ4aZY(oBcV(
xl3UIKfLHKl65TGMbMn4AWACbHc4ER3rv7YCHYr7TQ1wM3n6msvrB)9od0omXq(Fj(foi4IdO3XGXBvb
r)HH2wgzjO1k51g2bdOkv0fqLzlNfbqQOc82UcweF7jYQQO5oCdTflPeMowQibxU(rufJ6ylO3NcJD4v
GKRYzIutqP2ugii7uor0o5X3nCN8Bf0u0Tsy7T3cRy)qYvKnU8SV5rDAx3CKBoetiQpgd2dJFePq2IIE
JB412YZtgc4Iy8vn5peSMzkYjKT)LKD4cjvnEumnvfdI7V5fe75iDApo0My6n69qsUGq(HvkfJopiIW2
05hlxVTvCjdPyvkEMQxgDQI8ZIG7JR5v(5o0wCTQTEuEr5N3RzPJa8ULz8712ZWyv4iKnhSu08GOYXlq
pJf)LXQqQ9gD)tiDz590ZFYncr(KKiiAhxb2a0nhWH3v5lY2aEb94(25EkVPoliWP0yuaCOiawrhCLAD
tL74tkKMKrd7lbzervUlma6qRxYt2oQqvvTKCCOmqKGJCZe0k0dEnTcCNZmDok6DBE2QZLQbPiWVLK(Y
IvCXNj)iZlnJVw63smBpIIXHPrlfjN5i9YQ(icI6nGwQivhUyNiivTLNekT91W3)EFmJ3GwlXVeiz9uy
jKVPXICsiDpzWgsf5uqFSf4NBcO0Yawi(mGxtogI1n(z3Wla1GNjc7rToWk41oK7aZae(d)mjk6YLy)K
IGi1Q2auFPDcP8Z)QBuoaAlnRtHgdXHtfmqo0Wl(GcBIUQQ)KlAdMvAfbcCz86x40bX(YJk4kQ92VHHn
X5Li6u2IcO1a6vBdbAT3klOgId116aPQJWO6tuTWJAxgSdNcvuXafteV)Uw6SYO1IztfbIyHtH1pyaWa
TGBuWXpRoJU)qhLlUUJlR63JvxhHQZdflOcfkJh1iEdwEChRo1)JNVeAi2j)RQUOwV)4jSWIsPQAs9Ct
VrqR(ja67zjRVAggPIR(eS1AVbR8a9i5vBzKtas8IR)2khj9jMW4Vpifye1ij)aXA0eLwgyPfij4mgKm
IrBt4xhJqNw)2lhyZBjtRldnlf)c2Aup5ksIoeYAh91RXJp96VcnVQ9ZV5rbTMI(YZikq8WKjZFvnfxK
r1Hx4clBLda5uloItPQgQ5l36zj3ikXmroZPbny5iVykIdeUfy82AhoS5lApOhVwfpFrsBc4RPxAf0k)
G14bjXJtZNWdRB0gc(9lbcWJIiA)u72WvL1Wz5iAsuvsXnPgH4V6V)opX)XTjp(v51EzcIdsBaBgRbiS
qJ2KnITwadaf)rzIOpHOXfjXXubB1xWOmTQHFfL2gOinqFu7zJ(AVAHYep0zutk7CjmOuWwYWsKJukKL
N8OiRQLG0iR)uCaRUTOD0TmvrKTQrRKnapynnxngdEFFnyrI1geMLJXJgWWxSesWK88io(si4kFBAwbR
69(WVRzr1OGaBB)PxwDbrFKQUfTLICSGLl)QpBRI(Jo(53Ek6KCMlsQdBix3uKLKLtg97WIGcCVtvty8
6ezTvCmR4r2GFAR22tRbLprv)A1QUW8SScDuMXQGlVEnmn0kSNsYRnYgEXAQaIuJBdJA67riw5NZRTZu
H98MWgr86T8QdXmQKI0EGCGI5P9)RIB7ODBeIGWy0xJIMJyRatOlwuUg5pYRyDZToiCfoVfXBa30rSRg
CxZ4NXy)8Jx0h7Vt8hZE7BFD68DRpCa)Ic7)Sc)H93T)0o(xa1x)IF(hF1396VAhHYTJ)FE3Yvp)YtRh
(VE6IxCq)5eTU)Q5v(hJ2Fa2PdNiqLFVyF17F38v7p1(XU9FW)s5c)b4V)29xZRq(9HFwK)LW9WX20tV
75ucCF29p8M7MxVz(kcS7o98wjnP)VGrf6h)SRp840Bom)z)JRV85expLe4zdX8aE8BR85KavGGvRkdi
MF)P1PNZPdLZF2XLT7)(REo)8Y7)m31FC7)rot735ER)HFHQ4j)kZVC5Dp(6jcFNUVTHN)M24No)8)3)

**Comment by CodeW0lf** [comment]
Actually looks like this might have already been fixed in

https://github.com/xod-wow/LiteMount/blob/55b26f0ebb7ad9f92effbce1293ffc9c6fdd88fc/Actions.lua#L90

but is not in the currently released beta.

**Comment by CodeW0lf** [comment]
https://github.com/xod-wow/LiteMount/pull/200

**Comment by mbattersby** [comment]
Ah, thanks for the debugging. I've committed a fix for it but I won't merge your PR, just a lot of work for a one character change :)

I'll try to get a new beta out shortly with the fix, after I prune all my experiments that aren't working.

**Comment by mbattersby** [comment]
Fixed in b80995

**Comment by mbattersby** [comment]
Please try 10.2.5-9beta2

**Comment by CodeW0lf** [comment]
beta2 looks good, thanks!

**Comment by mbattersby** [comment]
Thanks for logging bugs, really means a lot to me.

Closing this off.
