### ISSUE TITLE
Mounting not working in Shadowlands zones

### ISSUE THREAD

**Issue by RhapsodySL** [xod-wow/LiteMount#20]
**The Bug**

LiteMount fails to work in Shadowlands zones where a mount _can_ be summoned, instead falling back on the "Unavailable" macro specified in LiteMount's settings. In playing I've only gotten to Maldraxxus, but this behavior is persistent and 100% reproducible, having occurred in Oribos (in the sections where you _can_ mount), Bastion, and Maldraxxus (and presumably any other Shadowlands-specific zones). This does _not_ happen in non-Shadowlands zone (tested in Orgrimmar).

To clarify;

- The LiteMount macro immediately falls back to the "Unavailable" macro specified in the options even if the area allows mounts.
- The above only happens in Shadowlands-specific areas, and is verified to not occur in non-Shadowlands areas.
- If no "Unavailable" macro is specified, the text "You can't mount here." is displayed.
   - If you _do_ have an "Unavailable" macro specified, it is used.

**Temporary Remediation**

At the moment, this issue can be "fixed" by adding "/cast MOUNTNAME" to the top of your "Unavailable" macro, replacing MOUNTNAME with your mount of choice. This is the Unavailable macro I use on my Warlock, which enables me to use Burning Rush when moving. Normally if I wasn't moving it'd just mount, but the point of this issue is that it doesn't work anymore, so...

/cast Antoran Gloomhound
/cancelaura Burning Rush
/cast Burning Rush

**Comment by mbattersby** [comment]
Please provide the information from the Report Bug interface panel.

**Comment by RhapsodySL** [comment]
Please do not modify anything below this line.

--- General ---

date: Tue Nov 24 08:28:47 2020
version: 9.0.15
locale: enUS
current profile: Default

--- Player ---

name: Rhapsodicoli-Illidan
class: WARLOCK
level: 53
race: Troll
faction: Horde
spec: 1 265 Affliction

--- Location ---

map: Maldraxxus (1536)
mapPath: Maldraxxus (1536) -> The Shadowlands (1550) -> Cosmic (946)
instance: 2222
zoneText: Maldraxxus
subZoneText: Iron Trench
IsFlyableArea(): false

--- Debugging Output ---

Dispatching flow control action END
Dispatching flow control action IF [mod:shift,flyable][mod:shift,waterwalking]
 - IF test is false
Dispatching flow control action END
Dispatching action SmartMount
 - filters: CASTABLE
 - filtered list contains 0 mounts
Dispatching action Macro
 - using unavailable macro
PostClick handler called on LM_B1
 - setting action to in-combat action
PreClick handler called on LM_B1
Dispatching action LeaveVehicle
Dispatching action Dismount
Dispatching action CopyTargetsMount
Dispatching flow control action IF [extra:202477][aura:202477]
 - IF test is false
Dispatching flow control action END
Dispatching flow control action IF [mod:shift,flyable][mod:shift,waterwalking]
 - IF test is false
Dispatching flow control action END
Dispatching action SmartMount
 - filters: CASTABLE
 - filtered list contains 0 mounts
Dispatching action Macro
 - using unavailable macro
PostClick handler called on LM_B1
 - setting action to in-combat action
PreClick handler called on LM_B1
Dispatching action LeaveVehicle
Dispatching action Dismount
Dispatching action CopyTargetsMount
Dispatching flow control action IF [extra:202477][aura:202477]
 - IF test is false
Dispatching flow control action END
Dispatching flow control action IF [mod:shift,flyable][mod:shift,waterwalking]
 - IF test is false
Dispatching flow control action END
Dispatching action SmartMount
 - filters: CASTABLE
 - filtered list contains 0 mounts
Dispatching action Macro
 - using unavailable macro
PostClick handler called on LM_B1
 - setting action to in-combat action
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED_INDOORS.
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Updating location due to ZONE_CHANGED_INDOORS.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED.
Updating location due to ZONE_CHANGED_INDOORS.
Updating location due to ZONE_CHANGED_INDOORS.
Got refresh event ACHIEVEMENT_EARNED
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Updating location due to ZONE_CHANGED.
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Updating location due to PLAYER_ENTERING_WORLD.
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Updating location due to ZONE_CHANGED_NEW_AREA.
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Updating location due to ZONE_CHANGED.

--- Options DB ---

DQvYssYXX1phkDGsX(cVbWnbbBAbdna1TY6eDxy6YMAQcw1vdWHh6VD(8m9N71qcJMmHdyYoZiC3dF55
lrTlU772D)JpVCr(3V95LF6LZpD4XZhxE7HF7Bp8vhpE4PLtRR58PF8W7)l7V8YHZN2DxD31pB9h(hx)
RVS)7pT8ZlhoU8dh3)ULhVCE3xU(6F)5p(dlx93C6Zx09)NpU8Y13E4loD98LLtV9WF(45ZF85ZVE6P3
(VX3o94(JlVEbc4x(6Ltho9(3E4BF9LNx)MSVp7TIC7C7())S9)5J97oF6d4y)P)pOIWQF)XZ)WYXF1V
F)HtVCvKOxWNVlU7(VE54Hp(05l7URfB7U)7EE)Bp8h)e(FN)r8W19q0U(jSZow7DNVC95l7p9e(7kw8
x86JpF40tqp97E7H73F959F4dV9W)1YXJVaYfY7U)7p(0RWqFxkniXVBp0lxp84Bp8)U8H94tXzhIX5l
xw(WV5fOe2)Z7p9(9clH4(9xF)YLNW2(MdNoT84r8(rpS7(Vz50tlxoSGLLXF()861JlIC1sLD3)xwE9
41TtWxCbEA)SC2JTkocF7(RqB)2dxp)2dF9YLL)2ZlIEjNenb)Zzds0F4YY7pJvE)5xpU7UEcC5pD4YE
Hn40LYTIEGE3YVa(MbX)QhLZ2VGn97pCD5P9yF1boeVB59hEbQYx(nV9W3Thh0hXXa07pUiVfl)RH5)P
ZFe0nMeg9Lxo)H949F1lhHH6UEDLxxoFsTlxf((No)6fOepSjpXs)xraE7H)TX)r8FxmaL4M54JYFKsQ
WF)ZlpD(x2ouR(o)0LZ)4HJ7)69F6L)LXN3)h2)JIA(FriPVKFv3x7ZoxxzjFnE8JW1663C5W5lhUEyZ
LnnR5rxuF3LZZgmCYJXCTehRpMgJEjS92uPw1hd54SU9yV2d6Bh5yCJyP8S3A62czDTcTAkZsLUYH6OL
xFQoMJSsP2iPFUfQvBpdvalPqFBPPuoOYACmNbJ9Dk19yVSrGqFYtyQNdBpwRv4TT(YyaIQjPK)9ejvB
oRjLbX6W0qL52UkPEVP7kfsBcyU1vojevxyEM2uuX8iovfzuWmSDVjZriZBCVuI1OFKAK51q23VQ9tZI
(i4PAZwxQAZcXe1KXrp39fSr26CsguNPy2zB351My3cXCZo9Dx(vVka1LS9K2efyjtfAPNZTtvBosn)Z
fFtr)TQ8xgfkF4T0LJ0So7JQV9KVDvN0dZBeKHGClUmHORjvJ3C0V5GS9UwRUjCv1dED98vBAL6yJb94
iQSk0k3CsQ3OuuzvmpQ3vFwBtFBuSc5IR)vLvQpgQhqoNnNoHfnFT(zytoB9SA1CtbmVnn8uSkjNMktr
mJEyATyIbcPKRfYbDLtlqlNmmbKBrWAIctbOY2XgBFkUs4Tne)RBAwcBBQKhAWfIuAks06276bPqCgHt
6srqZnBAtRp71X2t1yr9jLZrrfJofZrCm6(UDdvU4lWWUgQp56BVHPQDi1YQV2kf81Y32cgM2OrGSa0u
QVIhkikvg)gYQ(fFFEZ(Pa0k9OZvvvgICPGagwYSsVUsYq3cJBcaZdNR6XQuuKIoc2u3tOQOtbWFuG0Y
iO(3W310eLk9UrM)OUhGew83s3h3LgoVbDPDvrbrtLZ1eogKhFPKDZWju)aXJDtIG6AYCuzZHhSrDyAe
xhXkimCJ4W1ujdYaqKNOEiKWcUfaSyUwkU3AEvg2bx4H(OHRHaaD7G4ASElwmBfKsfdkezKCLQ6kanub
QpBkXNzcLLHjFybT6ULSRftbrW)UcjdW)UQ1GhrIjsKmI6Mk5QgkLMbYtH9QouKD6Zir6BVemLi9TqXW
8qs)TVxZfDPPgwlZZMAQ8d1SAfe3lnwT27m6FWAde1OQqlfPc41VdiJGEOaxvvwjn6vFPntLQYeI(uNU
8CeuZDHPXLeUKsW7ufEuyHgMSstLscN2Eu8uPFEy22ypY3YcEqs8M5(wVLQBScBHj)lw9uR4GuLndAfv
W6OzFq68S6XarDs3zHQeudabBlOxRAec0Kflpa8c1i1eDAa6QQuIiGpEdrNgrvTE1sUjOGwOAiZejHoD
uaqHMxf(K0MY04TjRRevoeOxCyoOEEW6nATHkMsrgbtJQrgITxHBflcpgiArFefOYSvtaJWWTUYjXoz1
9rx7vIQqkIX3Xcu)9O4CU9Dj1IkkaSoWC8ffvbohrfdpJfYshYGQSGNQwIkifzasbWQnJgWEj3uWeiiL
(2BfGUOrEfOlfcrgqmZ03dkFLri)DGvGJYjjgt3k7OwnSdHQ0pgw8nAnYtViT8nzz9IWyjkbaxH3gxHo
uhAalMy20HhL3N8LZO5qcX3k2r)oIglUgZALGbPIgLq6f6VnmBBgVCtIlLSvEtJQbrnPXscSMwOC7wTK
2YJuET2DaKXgt6d1vq1IDTsY1owuIIiyflU1MbktznpTiNw9lfTmXglJciQk8cOyIbvOEvIjIqA62IZE
CvTNKAJv3keQXc(kmlDWIoLfsxzy0C)ZKTNIVsTgJc8fSmtmFaKoReMHL6b00WwcA8NKdXtIPrQzC8QE
8Tg)jvwsi3MvJf8pLqv5SIOsvrjPyzwGM137uHUsZgd)HBtMGgfl3qPrcfNHzNUqXHvmDu0ecprmjfA4
F2CzQT9DydlmHtJzobJudcIJyv7izE1vPnJN0P2Y2b9eph9QA5f10KooW4mOkNbQIc3QBOW8YRozSQKa
tYuYbRVM0KTacJQLKj3Yt7Oov)mPkTKtwh0m7Vuj7mhcwJfSMnWxdbqkc19ujbG9xrDZybQfcGDSG9Ai
rHnouaOkQS2WAswUv7aaljRlRYQTf)tkFjupHwYzHUciEkKzhAtM8EcNj3uBgRB1udQPsEPGBBUBtpzs
uCj2HnOicKQqrbCAcduLPMqayNnVygvDidDqvmX6KtkcQ2BoKk5lmYvKCvhHmu0C1quuINIIuvWMRDIz
gq(inEukBJiPOPnvHkEVtJb6tWA38fUXvzojB7wA0)gsQa(fjE1Lenit0jrtHo9LQhp8wIHiogdNSvta
88DR12hxDYyvaRyxDNct)rvTIIE5HrAuW5RAOZmHyCAPjHJNnhnuwfv2CMz91rfV(zOvQBADXjlzSufP
cIsdB7bTmmDs2mLkHqdHrZfo1Oh4eRgdQZYcGKcmMaghRRbUKk7rngehsCvuBoWGJ3O1VHyuQ7kkmevD
KdOZPThqUOQMrwcghoJyW4SOIVOqvvFLOvI(CA7r99HZlNXI06KA5kTMpeewvvan4XQwgHUZEMbl3Pfb
LdmgmdZuR1BDPrtLQQHas8Oo3fR5w5GO9bGWDTBWwWsWanUMFSXm2OzBcmax4blYVXgVl2eyq4atV1yo
h8VCuWDgRIISQ34FQBbXcAe6Q5OXhzkPgtD3Z5il(Qt4(jWDPx5GdYeYOczjUIkfLQ9TM2mqHQnYhe(P
UV4uyjE5anLj3M960SEslSUf5Cq4j8FmHlS8ACgYm6fXw8jQPbaIKOEivRKo0j0qZwLLjZXSviQrTcv2
tBlFtkMKnrwqQOlF0gZzAkQhMIb2lLPzBIJWdtl2Qz4nWt1c5b1tUGAP1y(XS0PgLoVzGa7tg(82iZkQ
tVCICXKN9q8wAw52t(8Shg26KncIUlZCiLYciKCyW2EQmwq83mSzofeWv6DSsvADNCwpYv)WKgO66BLa
MogzuvGOyJvHftFM)NgwxyjORYQJKoSfQDJm5KOKwqAm7uIMVvTkJokbRSgquIQHEgiRMPBxlZz2z6xl
rwso)e(Tx4jrOQkGWtFJ(DXfz7ZaSzAnqevZI4leDrLO3LQts6ixdrRdaohpz4kAndcLYgpjEYKt5DDL
tJQCGZOQo2xHSwvOlCKnRU)SmOqN50LZVRkZUBvMvnmw97IkzvDL0yEqxqnyf534LpH8xSjLjYV5Qv)Y
NsCkeOdSoXDst6KkkwlhfdNGXKtXiszzLQCtforXvQUPdGkqlnvAiPtov0SLYXs9gaKo7JqIXysUG1Pa
Yb63LIn4ROm9cvzekSLBrS2ilIM8lnAWbydYYoyZ2uXHPvH4BcYUs0K3giRlzcl40evLqf2psNWZYG0Q
dxJQzq5wtwMy58KVXm5jFsM)JNQN1umZrMgOyYJe8PG)Y9P600ZRYl5lhnYJS6ABpiLoRNdrC29ParLb
6iu)ghvLTYG0yX)eiOd5IcDL3cvXUof8WKvoozNYYfdqq5jVHZ1Ygyw6jh47SZMEW)YEMeIAaoz3zqbh
kn3bvtCVwqu30OwLg8(dKYwxFA43UBhvTQFwDywjil0fDwzMyozE0HElFJHxrJQ2DhlcPEC0sAxPj7ik
XlCsMqGg8oasNY(SnC8EOEBVx2JnZvYhHHulN6m1drwids70mbLxzYeSv3futQ1i7L1SswIWHMAMMgLX
8z2BoQ70Uia0GtWXOlScdBYQYqs4ri5Lie4TlCZWdGwxrnL5XDtT(uaTRgbvdONku9EIfUsxqH6SmrUz
rteCepFauvRsoo2ZvAYwgsS52ALf(klLdly9ohCQUXa57dFPS9MiR1bTwXRksU(aTTH8KvAj39DY5VMl
hDf4xZUDlSHGv(a8quPorJEAaaSIlQUNA1BwG)GkKoc1QgTRHFe541xBjf6Q4k954)Nau0d9Uj0C40K5
8c0sVEQ4BRmcyDg2bvbMz(tzIsQ8HiwxRYSFcvDDvJGewSISu3wzvoMSAzYYVjfDb4CrF9ghTY6AZ(AB
7yZ(2CIHDNa2wBXYs7RlDLSdNSdNSmRf6sKG7XH9lCOXkVK(ez7SikSz1XwOAwgpU7X28K0Igxex06lb
SKlmt1iYLZPCtCelMAGGsisIP)cY1340D7ruEkdPfTlLXGnNhHSE7pC6gLIDL)Ix70j7wPsOo4OBikoq
YMyv9HCRP3KzzQISOjUroB0JT4RKWeLeV(ezLQ1AmR0FqkmPyIj7DelWXbuaZPfXl6)oRXkPI36kBorD
tfNQBC6vwXleRxt2pHH2ML(6U73)xF84RpT)U9)Y7KFmwVi)(j)N)vf(45F6tF3YL3V)6lRlB3pS(Rj7
6UD)9d

**Comment by mbattersby** [comment]
The problem is that you can't fly in the Shadowlands zones and you don't have any ground mounts selected in your profile.

If you want to use some of your flying mounds as ground mounts, here is how:

https://github.com/xod-wow/LiteMount/wiki/Using-Flying-Mounts-as-Ground-Mounts

Happy adventuring, X.
