### ISSUE TITLE
Issue using limit mount for mount "Aerial Unit R-21/X"

### ISSUE THREAD

**Issue by Deakkin** [xod-wow/LiteMount#201]
I have a rules setup for my Mechagnome that limits flying mount to the mechagon drop mount Aerial Unit R-21/X and the ground mount to the Junkyard Drifter. The rule for the ground mount works fine; however, the flying mount rule fails only when the mount is limited to Aerial Unit R-21/X. I suspect the forward slash in the mount name is messing something up.

The rule I have applied are
Always: Exclude "Might Caravan Brutosaur"
Mechagnone and not swimming: Limit "Aerial Unit R-21/X"
Mechagnone, not flyable and not swimming: Limit "Junkyard Drifter" (this rule worked until I hit level 30 and unlocked flying)

Debug log from chat using this mount

LiteMount: [1] PreClick handler (inputButton=LeftButton, isDown=true)
LiteMount: Refreshing status of all mounts.
LiteMount:   Dispatching rule LeaveVehicle
LiteMount:   Dispatching rule Dismount [nofalling]
LiteMount:   Dispatching rule CopyTargetsMount
LiteMount:   Dispatching rule ApplyRules
LiteMount:   * checking 8 rules for button 1
LiteMount:   Dispatching rule LimitExclude Mighty Caravan Brutosaur
LiteMount:   * New filter: -Mighty Caravan Brutosaur
LiteMount:   Dispatching rule LimitSet [race:Mechagnome,nosubmerged] Aerial Unit R-21/X
LiteMount:   * New filter: -Mighty Caravan Brutosaur =Aerial Unit R-21/X
LiteMount:   * no rules matched
LiteMount:   Dispatching flow control action IF [mod:shift]
LiteMount:   * IF test is false
LiteMount:   Dispatching flow control action     IF [submerged]
LiteMount:   * IF test is false
LiteMount:   Dispatching flow control action     ELSEIF [dragonridable]
LiteMount:   * ELSEIF test is false
LiteMount:   Dispatching flow control action     ELSEIF [flyable]
LiteMount:   * ELSEIF test is true
LiteMount:   Dispatching flow control action     ELSEIF [floating]
LiteMount:   * ELSEIF test is false
LiteMount:   Dispatching flow control action     END
LiteMount:   Dispatching flow control action END
LiteMount:   Dispatching rule SmartMount
LiteMount:   * filters: -Mighty Caravan Brutosaur =Aerial Unit R-21/X
LiteMount:   * filtered list contains 0 mounts
LiteMount:   Dispatching flow control action IF [falling]
LiteMount:   * IF test is false
LiteMount:   Dispatching flow control action END
LiteMount:   Dispatching rule Macro
LiteMount:   * setting action to can't mount now
LiteMount: [1] PreClick fail time 41.62
LiteMount: [1] PostClick handler (inputButton=LeftButton, isDown=true)

Debug log from chat using "Alabaster Stormtalon" from March trading post
LiteMount: [1] PreClick handler (inputButton=LeftButton, isDown=true)
LiteMount:   Dispatching rule LeaveVehicle
LiteMount:   Dispatching rule Dismount [nofalling]
LiteMount:   Dispatching rule CopyTargetsMount
LiteMount:   Dispatching rule ApplyRules
LiteMount:   * checking 8 rules for button 1
LiteMount:   Dispatching rule LimitExclude Mighty Caravan Brutosaur
LiteMount:   * New filter: -Mighty Caravan Brutosaur
LiteMount:   Dispatching rule LimitSet [race:Mechagnome,nosubmerged] Alabaster Stormtalon
LiteMount:   * New filter: -Mighty Caravan Brutosaur =Alabaster Stormtalon
LiteMount:   * no rules matched
LiteMount:   Dispatching flow control action IF [mod:shift]
LiteMount:   * IF test is false
LiteMount:   Dispatching flow control action     IF [submerged]
LiteMount:   * IF test is false
LiteMount:   Dispatching flow control action     ELSEIF [dragonridable]
LiteMount:   * ELSEIF test is false
LiteMount:   Dispatching flow control action     ELSEIF [flyable]
LiteMount:   * ELSEIF test is true
LiteMount:   Dispatching flow control action     ELSEIF [floating]
LiteMount:   * ELSEIF test is false
LiteMount:   Dispatching flow control action     END
LiteMount:   Dispatching flow control action END
LiteMount:   Dispatching rule SmartMount
LiteMount:   * filters: -Mighty Caravan Brutosaur =Alabaster Stormtalon
LiteMount:   * filtered list contains 1 mounts
LiteMount:   * trying Flying Mount
LiteMount:   * found 1 mounts.
LiteMount:   * WeightedRandom n=1, t=0.500, c=0.016, w=0.500, p=1.000
LiteMount:   * setting action to mount Alabaster Stormtalon
LiteMount: [1] PreClick ok time 14.09
LiteMount: [1] PostClick handler (inputButton=LeftButton, isDown=true)

If I can provide any other information, please let me know

**Comment by mbattersby** [comment]
Yeah this is a known long-standing bug in the release version, that mounts with / in their name (this is the only one) don't work.

I just closed it #122 since I've fixed it and it will be fixed in the coming release. You may need to delete and recreate the rule at that point to get it to work. In the mean time you can use the group workaround from #122 if you are desperate.

Happy adventuring, X.

**Comment by mbattersby** [comment]
Fixed in release 10.2.5-10 and onwards.
