### ISSUE TITLE
Druid form dismount

### ISSUE THREAD

**Issue by Antorinia** [xod-wow/LiteMount#206]
Hi, can you help me please with druid form?
Is there a way to macro addon to use druid flying form while flying on a mount with one click,
instead of dismounting first click and flying form activating second click? Ty!

i tried to add
```
IF [mounted]
  Use Travel Form
END
```
into macro

but it doesnt work
im trying to add travel form if moving instead of dismount at first,
and just dismount when you stand still

**Comment by Antorinia** [comment]
i tried to add
```
IF [mounted]
  Use 783
END
```
into macro

but it doesnt work
im trying to add travel form if moving instead of dismount, and just dismount when you stand still

**Comment by mbattersby** [comment]
I'm not 100% sure what behavior you're after. If you never want to dismount you can just remove or comment out the Dismount action in the advanced options, which sounds like it will do what you want.

What you have written there definitely won't work because `Use` is for items, not spells. For that to work it would have to say

```
IF [mounted]
  Spell Travel Form
END
```

or

```
Spell [mounted] Travel Form
```

or

```
Mount [mounted] Travel Form
```

**Comment by Antorinia** [comment]
tyvm, it worked

**Comment by Antorinia** [comment]
i just had to make big rule with dismount for travel form

```
LeaveVehicle

IF [aura:Travel Form]
  CopyTargetsMount
  ApplyRules
  Limit [mod:ctrl,nosubmerged,flyable] RUN,~FLY
  Limit [mod:ctrl,nosubmerged,dragonridable] RUN,~DRAGONRIDING
  Limit [mod:ctrl,submerged] -SWIM
  SmartMount
  Dismount [aura:Travel Form]
  IF [falling]
    # Slow Fall, Levitate, Zen Flight, Glide, Flap
    Spell 130, 1706, 125883, 131347, 164862
    # Hearty Dragon Plume, Rocfeather Skyhorn Kite
    Use 182729, 131811
    # Last resort dismount even if falling
    Dismount
  END
  Macro
END

IF [mounted]
  Spell Travel Form
END

Dismount [nofalling]
CopyTargetsMount
ApplyRules
Limit [mod:ctrl,nosubmerged,flyable] RUN,~FLY
Limit [mod:ctrl,nosubmerged,dragonridable] RUN,~DRAGONRIDING
Limit [mod:ctrl,submerged] -SWIM
SmartMount
IF [falling]
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  # Last resort dismount even if falling
  Dismount
END
Macro
```

works perfect

**Comment by Antorinia** [comment]
but
![image](https://github.com/xod-wow/LiteMount/assets/130331287/724a4ef6-1a04-4f89-a5f7-ec8c88897e16)
doesnt work, summons my travelform when i stand still

**Comment by mbattersby** [comment]
Glad you got it working!

Limit is described here: https://github.com/xod-wow/LiteMount/wiki/Advanced-Options#limit--endlimit

Happy adventuring, X.

**Comment by mbattersby** [comment]
p.s. I think you can get the same result by keeping the default rules and just adding a condition to dismount. E.g.,

```
Dismount [nofalling,noaura:Travel Form]
```

**Comment by Antorinia** [comment]
> p.s. I think you can get the same result by keeping the default rules and just adding a condition to dismount. E.g.,
> 
> ```
> Dismount [nofalling,noaura:Travel Form]
> ```

tyvm, ill try it out today
