### ISSUE TITLE
Priority not working (or I am dumb)?

### ISSUE THREAD

**Issue by Antorinia** [xod-wow/LiteMount#207]
im sorry, but take a look please
i set drakes to "disable"
![image](https://github.com/xod-wow/LiteMount/assets/130331287/6ccb6e23-5aee-446b-98e1-9dc1b7ebeeb0)
and i still get them summoned
![image](https://github.com/xod-wow/LiteMount/assets/130331287/3875f17e-fc06-49de-be0f-60c75d8e419b)
same with usual flying mounts

upd: i just found why,
so when i make any rule with mounts like this
![image](https://github.com/xod-wow/LiteMount/assets/130331287/37e1f5ac-f9e1-44f2-8182-f54df5871386)
priority stops working, is it intended?

**Comment by Antorinia** [comment]
okey, i get it now, i have to set it to
![image](https://github.com/xod-wow/LiteMount/assets/130331287/496be30d-8d21-4bc9-a64d-8efacec6fc11)
instead of random mount

**Comment by mbattersby** [comment]
Exactly right!

This is in the documentation but I'm going to add some tooltips for a coming release.

Happy adventuring, X.
