### ISSUE TITLE
You can't mount here

### ISSUE THREAD

**Issue by disstress** [xod-wow/LiteMount#208]
What happens?
Error saying "you can't mount here".

What did you expect to happen instead?
I should be able to mount. I am able to mount if targeting someone that is mounted with a mount I have in my journal. If I don't have the mount, then it does not work. 

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
unknown

Please do not modify anything below this line.

--- General ---

date: Tue Apr  9 12:50:46 2024
expansion: Dragonflight
build: 10.2.6 | 54070 | Apr  2 2024 | 100206 |  |  
version: 10.2.6-2
locale: enUS
current profile: Default

--- Player ---

name: Faim-Destromath
class: DRUID
level: 70
race: HighmountainTauren
faction: Horde
spec: 3 104 0

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: 
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
LiteMount:
    # Auto-created by LiteMount addon, it is safe to delete or edit this macro.
    # To re-create it run "/litemount macro"
    /click LM_B1
    
```

--- Debugging Output ---

```
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * filters: 
  * filtered list contains 419 mounts
  * trying Dragon Riding Mount
  * found 10 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Flying Mount
  * found 165 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Ground Mount
  * found 240 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Slow Ground Mount
  * found 1 mounts.
  * WeightedRandom n=0 all weights 0
  Dispatching flow control action IF [falling]
  * IF test is false
  Dispatching flow control action END
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 15.75
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * filters: 
  * filtered list contains 419 mounts
  * trying Dragon Riding Mount
  * found 10 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Flying Mount
  * found 165 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Ground Mount
  * found 240 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Slow Ground Mount
  * found 1 mounts.
  * WeightedRandom n=0 all weights 0
  Dispatching flow control action IF [falling]
  * IF test is false
  Dispatching flow control action END
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 15.44
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  * setting action to mount Ginormous Grrloc
[1] PreClick ok time 3.37
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  * setting action to mount Ginormous Grrloc
[1] PreClick ok time 3.59
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  * setting action to mount Ginormous Grrloc
[1] PreClick ok time 3.39
```

--- Options DB ---

1T1AVr2rU1)qjyR3p(AItqIDwNfBBSbibPH61Q9mcrs9Iw9Sg(l63EoSkEiVjizgBO7u3QyrYIpoK1vN
JN)PZN(5VE5U8Z)XlV82Np93(5tF31pEC)2BxE811RV92F(YJF)LF((TZN(Dp)YhVD7BV)4ZN(pw)86Z
)NF(9)UpEC7V8MmJ)Nd)61l)1R)1RF9LF(1RF(9NFG)E6lVE7pF5vHWF8T3E727)9Y0)a)7Fm3gJz78p
wM45Ejw7N)Xe(VAzeXpJ4nPsPp3pMJZzAnH(iJfKckfW7lYeIZARVMBU16JP(4ygWpR4)JZwBevQ1JTn
1sPEApyleJ6Mfl50MwLqVwRRhhJEzZxGBdD5NYu7JXy)yQMZd5NGhRZEEn3uomhBAnZ5uZfSc5WXmRCi
yMWqwTq4rAiAh8VN9AlSMDCKJrLZa1O4etHftim6OLdBgobjY2LWSIhHo(HCe)(V8Yx(txV)Xl3EhK)8
PxE)JhxE)NVUoyINp9dxE9L3E(29Z)y48P)HlF84693)8PF4L3)YZ3E7drRLsNp9tF96NpD6RxE(2V(6
L3FgJhlTcg)Y7xUG5)9F79V86vmAm2oF67UF567cjHEcl(p(nSPF(0TF5ZN(xUD)5lxVl8ssoxo9t3U)
LVID9V5ZN(PB)6177P9q2UV7YBVF9zCA0bN9hWUE5(lxKnU3pF6F6YRVQ08pD511EvkL1w)LBGH(N)41
RFS0ZyX)D3V9FD1hSMXy)RF7HijY6QzNpKJrOjp9VF9(1hF9ZN(93U)4Lp2g4)L73(LxE96pC93eL3PV
7LpG301p(4)TR1PV76VC5BV(4)Bhp)TNEC5(hlD6))KW329EQdJhxEJ)H7VC7(lpErpoHbrQiNKqWlT6
C9yjatP8Euzc11J5zwmVKbHHpo12RkmWXT8yAc)S9es5uz6tDpO4zK3tTflInTmt4doY67dXQpZITPJn
LYnWm7f1AH6E0CS119FnHIp6EULuiOCfm)HFZMbAL9di2rU2TTsL)uh)zpylN0LltvC126QsqP0mp3Cn
Immhnk)1Gjk6w1wr0wY8OouwQxABfXyKZQkjhgLIpZjvuXGoHAogusHOfjFqvN0MM6vgDtGrPZbryVCY
Fmtsn6QKKNPU)EvNkrD2eOOk)IAVaXnApPBsSnN1KUYuoRugAw1WbSOUZIsizkH9eRXsCpwPPBwCe66J
W)E)tDdsP8E)Z1zkPwEJAGmagnVxcdphSqU89rJb7M(ye93N8r3pIW4t1glxOeKHbtqNzUrDrUwI8SF2
YUUsTCtZPALVwvYulQNboqv1MSvQ0JmwL9Gs2j1GPvONbujb1je6NIUg4Jt9Fk0v9)m0MonPHFpKmvM(
61URQhycPwwLbdr0Znv7dByEAL61rM8usnHALjjeETYDiDBxfUuUQuVBAurHOXQc950zonarzqTKOqy8
PsT6YUYgPqm5w9QBPWYQBjIFK6nFc7rRQav779UboBl3P5i30jbRI9tnAj18aRfgcv0ejkPrvMR1Mglr
e1QTjn)10kqeR9mN5qOBsTPNP7Jy7QIIygCyqtuh6bnIQs5xE)Muk(cLt8JSwZwZWe8PXhMjUQNfWyQu
wQm2CQJavfJ4m0mT2wVU7lsTXktlJqkQQZrN2qIqQuFcpDNMQRiC1YjF5B(CosbNpmlRinBRa2y04jv0
r2Gs)WODFUQwgNM8StMa1j9evZilIE0aSSB(hPg9tEvMairkYtKoP5ss1OEVyIV6Jmd0fdtTYqHajmtU
aGWnAKdjr1kWsoB7VgumYivco3OPEutWosrK8bz8HATOShSXyQTebtu9e7sIhMnpXKuIEOB8HtEQBLzU
5Z6CspyzWTWXAcu5u9ybJKvByrrPSh(tWfVIptcHjMgMVA3HyKPjNSTwib16RmZMqHzsv6KH0XAoikey
dyGidq2jEazqN)CrvTtG9OIQznt1oEmDvkvKrAdkmNkCIPdxTCKzkN9(atpcfaepf4mdQEQw4XW69rQX
QewcOz15ogZdqYN25SgYx4ugPkwT8qrpJCcSndFgkkAOm8xu2waGfClnLaWOzQgfXAKXgQ5bJL20iyRz
2837Yn9ZKhT0N07aXBs2UoP3dqZ2O6c89q9PteniIRompjg9r8ku7R1Im0Ke2AXaMjVwfq3NFTE1Nh4i
c6MwleYHSQHVQM)y30q6Icb1PiIq8bJ8kKlGtQKDx5ULnLXzepD9XrHw9S2AUkUPjMezn6WyfN)Qn)9Q
nCNH3Kbh(XodZglw2oeNN5vNw8XsAQjEJi8QwfesUmzrgWYp4RQ6tTAmy3hCZGWTl4lV4Vwf1eo1I(Od
FuncXKuc(O0Bb)H5rswMaz5tJrO6l1vHggcmlRSCNrj806iyvZawn6Zv3aKXE67vMqzdb1SSnMtFMSYj
dPlovOlQqvcanpCB1cTWe6RUnzu2Wbc4IaZ7ubQ9SVmLynesIfpcqbnFc65gs8nRoDpOpoSBSulEWiQ7
Ppt)m0qtaNSdKYmIlmotlMNULdHwuaCMItHHpQpxMCrgLz8rkt19l2PfjqMO2jRPQUeiMy15CQ7KjOB2
SKi4iuIxZh8WQizhMtlMGgut2w)yqZVjwhAw3EnDqZWZ8WGfgd(tnPekXyEmdZAnm9m0MkLgbIPaCsNQ
7qLQLms0wDBQIHwUDWtNH6sJanzaUAIeQo4gJiPTJSJ7luOF3UnCYObR4yjCPZcEBasgCaKBK4)c1GRe
vKpIqWKaTgH5dlXkXTnBMjtl6rgsgy0wKqhsncDbHWcDBvfMPUR9xGnZmSmiOXhaorLCKwSABgx7jCey
9EDgJwy6MZ0d(i1vcNsaYd791QHSma4buRu7HnRG66jU9KdGg7kZ3cTgpmGJOkvanklwlAngqwVA6dqI
QPfGSWYHHoP4P(uYJ46bL9Nf1Yd6rUCHMA0d4zQjjbLsmcgmmTkYWZ6OWuGUPZyMy3ISBf4PzXxu1w0H
i3ADdWUpZ4xjwG1AvDxQoqRHjwrFqwLAKMIiVC0xKURIeomBvgJETbBouaXCyvM3qJPg6aYLjbSPDi(S
2Qhurk7jNxI0A9m6wRPEXT2uFFrW(ZhlLUBc2QUYI6faiJZ1YdcpZP1xoSztFUDNUhgv1Hiob3TqkR8G
inQL3isOKIMJmBGM74ii7dQpIJGSZ1vJqwqiMDhMTg6SmRkNxSGmArAHjzjR7kaCMLHQ4OdAk2Mzp79c
ULoqkvxchd9eUyD3yT(dkcZDl2CLwp5Cq1xw3NalqcgbrFcdFcEervCeb7WupSzQEVopKfMTtsSTiQJa
c51SLPkueMsJOSEVYI9gHnMI5S1SGq3algPcFrRSVmMpT1TOMiStWNBXNRUmzQhORB(QfuGuib1Rjcn2
GYoRyeyNNmlxIHOqgDYTloO4BaZ5Mjqb58Vq1iMTMdQyxlaI2BwQwoIupRy7wl6GUFtQzVWENc67nRoW
(HGedj3QIXBLw5RGpRKuWqnepqRStlLTZPSllmjQC)xjF0QVkIjx2nLdy4oSNSvda9b7(DZYnkwef)iG
EiDc6zn1QnvE0ltyVb1rJ3bco4Ol(yY4cievGKf6qV7rP6HLPY9aPFM2JmLs16QdWuZmM4HOj3vfuDsW
FR2wzdZ8Ac(MrtDGEXkryWgxjBMvUN1oO5mYigYuzMKzvJUbyUvloj2mA0ozrAqnsBweALnLuwv1jRAh
0RmszgvMO0cjR1J51nkRMFixcTPTMKjwYw7z3x(SqQwM4UQZzJORbfiq1e92xRk7tGwInA)k7LQyYSkP
mgJveJfPb3Qv7(TGIxTZWdmTzsUmPGpQobytLn1MJPMH2e6p8r1dz5wUl2eSK177GwEmdhCLSspdM(YA
(JhiMUfigNvLeQ8zly6TNRQa90O0TYdLg1QRhgzMdsJ4raI3QbFpyvnpZmTSypWnqA34MTqkiMchqByJ
Dc8wDK4gQ5sz4iAzbq5d9GpWSwlqitNMdFQeCmIaW52MkbKonNQ(Cz(2rNzol9HE0ISwSDqYCvuP4NDn
7acx7xgvWC2lLbJZx8ap0IojxrNzCvAMmod0t0sNwIZSAYYpwHWkpGUE97QiSp59M4W7iBjT0PfygpWS
osnDzR0p04QgPtzMn3DrwnQqDYsiq8w2ZoGFSWgEdLH17EaqYJ5pCCNh4wLd0VLcYTm6BHSOyZYmjt7E
RLo9AgIf2PKolcbYfBFfIqXBVlIuL6HyKO5xNCmiAWRpVWmDHiVbm8E6NGQ90zcZcg)bQsvzlPpjYLgn
Exqb3CYWVXblOHe0K4yrAonOhIeYcBXXt4qeCUPDE3QRRnIZvQhAVbWLMLzpnioryHr2sUgiIdt(hBUr
bwj1fsG0zgAqMgtfyL1Ksv2YC5g56(uBMuXiLidf9DbQB1DdzjZQzNGoGTIrkICVQQD5rTqGvJxrSEgr
ajCdkvBtEN323pa4LeZeyNeXq2AE5yA1yg4TYjx7gvKHGD1YrV7SW(HMV8QXw9jwL6jc)Zy6H4HiwenA
t(Wm0Ljqk0r3F0qISMz0x(bpTLkpAZ(PjCKjDc8exuP0nkYV1brJQh4csuLpTlIeJr78fMtD9s1rw0s7
I3G1Lv)hqn3Czs5z9lZAj)tRLXcG)nXKIlChz77miWmAsm4QVxfxvQoliYzWIw2ikQcVPPLCRmaoav7)
kBJSC740sYA5g4eRBc44lzbTsAxQWowzesmznpQGKMPHy3dd2N3tI1zMLuGSwf6ijrmgQcHGWZstTu(m
yiBxsHUJ2T(UAQfHUpT(h1zN9qKvgWiBFHfWmTLoKDWgnBmaWeAfyXkdrGx7kEbzPzCJT6cNse8fSny1
3RtFI5Q7x4aXtaErtBUOQEKlFBdmmELgTvR2azx5fDvjMujKAJCsIATzMx(VKrY(ioqSDh600pQoeqCV
)JoVJBEXsOKwRAIqR4x6oHggHeRgSiCVIVq4ZnXrsakXaYrJcxNFAyOah244cVJXfx6vaPmIuo4q1sZU
bVQYptayRYYfrgudDJbXeqAy3eKc81aVzEbecaWH5dmTwQ6WyGFRYk6h65MvTUVckXIxQfwj0yAvzKzm
(v9Y6IqDs0IQJOyDNQvxa00mJkBx9Izh(CvhsPtG2ODR5)214k0kAdUxKer9Ggq1q5eXYIW909fHp5nZ
lxX0M8lCuQWiqpiY70GFnbIzJQyefVUm5gNzWLoZ5NLlxvpeXmtE0h1vdSfzgWTmvGqaMPAA3JGK0Ji1
GZwZjltqpzNJLEzqqpf244fz37lsQWEWaF1OLHGLhjeTykwI8o1AEaal9lV1BPiHGXiSvkWExFsqpQuc
XTAhsKMDfGskKN1)ajzpjwxdMAqHqmmAcoe4N0XWqalTF8azRucYSmEu(K9e7YLC9jDxbq04iYUQ2raD
QlLczie8Irv4Zgjwvgoueq7ZtX41fz3pkXqZMkuTgSWHGLZEfUgyLK1J7I9jVizANwCOgDn8VQJwNa4r
okgJFfiqbO0TpZi5Cr50y(4fwqe4HOb7RZo4U2vVGj(PHv62TmyxTOi)wZbHcs3l5tZupmdi8y0wglWS
Ie3okgvVpt8ZUrmxvByePIdw5HjSqOYu(a9utmjFKk2ccKHZRDkwdM7x69oXBgzsHfml1ZAsKJWaKLpl
ymyvA40s1qqhZZq57rrRoeJThCg4jO8rvXlAjZVkHv7PoOwhMsHx(t1U3VIuHUggkB35ugha9OpxLdr0
nDUWgUyHQTRxjWAdwu1Dyj2pbgUI0imzafrbDqVoDQsyKzEPklY62(dJbzlLeutvJS8telqqnOs6j)6N
LAMvTbIsA9Kk2TB2mZ8XscMPpvhwv8GkyVQ6(3CcQ3iQJGDdrcSlROd(znlBGkmt(1fUYrt8vz(rzU6B
ipnOta)9EiSTX0WVake1fIEVyAiwiMu9TQmGbdtwHW3m8N0ptYRwtJrTEf6EducEzFmlBTpO2UKjAZ2K
LYT6Fad0r83RErOsOC1Vvs0iXQd5MyZaWuobCCrOT6V)klXvaLOkHbDe0FxoKh78dXgipTC)sX8zLVJ1
gdqNSmet2AM1NSOYSauZHpc)PLyYDfTyDOAF)R8pznZo7FA8HGzNAMrOmo7ZyFsKuyEdNO871T2mvO)5
SHkySdUaVh81fn75Dy8fP3rdJR2MjpoF6(L3F(2B)BxF5lF9XPh)2RxpF6pE5(lp(TZNEE)BlH(ljXVT
xG83Z)3)

**Comment by mbattersby** [comment]
In the mounts settings panel you have (I assume accidentally) set all the mounts to priority 0, disabled.

https://github.com/xod-wow/LiteMount/wiki/Priorities

Go back in and set them all back to 1 by clicking the right arrow above priority in the header.
