### ISSUE TITLE
New Mounts being added as priority 1 automatically.

### ISSUE THREAD

**Issue by Blasphemous666** [xod-wow/LiteMount#210]
What happens?
Every new mount added or learned gets set to priority 1.  The "set it to 0" option is clicked.

What did you expect to happen instead?
I want to manually add new mounts rather than mounting up and finding a mount that I didnt' want to use was enabled by default.
Did it work in a previous version of LiteMount? If so, what was the last version that worked?

Not sure.  I remember it working at one point but it's been a long time.

Please do not modify anything below this line.

--- General ---

date: Wed Apr 17 21:44:43 2024
expansion: Dragonflight
build: 10.2.6 | 54205 | Apr 10 2024 | 100206 |  |  
version: 10.2.6-2
locale: enUS
current profile: Default

--- Player ---

name: Moltisanti-Stormrage
class: SHAMAN
level: 70
race: Draenei
faction: Alliance
spec: 2 263 0

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: 
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
Mount:
    #showtooltip Renewed Proto-Drake
    /click LM_B1
    /click LM_B1
    
```

--- Debugging Output ---

```
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 6 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * filters: 
  * filtered list contains 447 mounts
  * trying Dragon Riding Mount
  * found 7 mounts.
  * WeightedRandom n=7, t=0.833, c=0.357, w=0.167, p=0.200
  * setting action to mount Renewed Proto-Drake
[1] PreClick ok time 24.04
[1] PostClick handler (inputButton=LeftButton, isDown=false)
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
[1] PreClick handler (inputButton=LeftButton, isDown=false)
Refreshing status of all mounts.
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 6 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * filters: 
  * filtered list contains 446 mounts
  * trying Dragon Riding Mount
  * found 7 mounts.
  * WeightedRandom n=7, t=0.833, c=0.550, w=0.167, p=0.200
  * setting action to mount Grotto Netherwing Drake
[1] PreClick ok time 38.98
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 6 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * filters: 
  * filtered list contains 446 mounts
  * trying Dragon Riding Mount
  * found 7 mounts.
  * WeightedRandom n=7, t=0.833, c=0.550, w=0.167, p=0.200
  * setting action to mount Grotto Netherwing Drake
[1] PreClick ok time 23.65
```

--- Options DB ---

fU16UX1ns6hNmd2md49l5FoXzYeKeLSU94fywSc(yPJKA4wD7TvlNi)ddmpB7l2(vKFfzhSqBUG4JphY
I196RizFP9YxF5MRUB5O8N)0HDN2(WY(tB)8B)lF(TBoD449hxUDfF7e(3n3U7W7w2jJ8HhV)(d7)Mdp
U)0d4VFrW6Ro3LxyTxEHpvJ(K8Uc(FUSZH)s8YlCUQVG)m0EmyZy44)cot23EeJngWyRya47vmaqbRp4
J12aQoBmkVrwLqkgdYkI)xUakKSbUiL26fSoJ8O1imGZAmrzDm45CPy6RPpNQwW4o86GP4T41f8S15Yg
H)9cfcfFn158OplcPty3qiNA8O3hckbJ(scV1wLjBCUyNzCgJiq2OOGs5sT9AV35ergtSKlbzHJzz0fW
TYclejjsr1lp6sc)Nf(glOR9ynhKpg7VSwiZLZUGAqmvrvvLf1zd5AxaCXqrKDBt3jmQ8u1x7pjRRq4S
p0PNWNcPTGpWQ0mXvFi2vQEqSKR9AV1Lt91WhH1l0FRqpXs4A8rsMOlwffp0QIEU6Y0cMvhcN4v55JHU
gbJUByBe1Nn2MPb0Vkp2CocXCPPDSPAn2fsVXyJ0vZ7IXs3bmd222fTM3GNgm4gh7mUhKijudXaxDy)n
BV9nRhFy7H9IV6MT7F40Y(RwBbc2l38dl72E)1hoE5fMl38TlpCA94(p)2Fy7(BV(W9pakg8xU513D8W
(1p)2d3853E6o8WR3E9A7JXl3817wU69hpC17)8B)MLpIP)G4x4nY0WqVy7T3D6Ud7UUP)W4TM)Q9Vgf
ACp(8R2EZPhAbWVCfbPF(T)Px8P1F94YP7(ZDBo4Q7xpUS7AmIJRl33CHUCZlxo((7pit4VTS94k4f4k
2xX3C44P1F7ZV9x2UF)Yv7wfZN))Nf(1BHgbl8)y31Rhp0x4aCd28pxW6UoKlX8i8ZRpUDzxxz8MLDIQ
ZAH72Mn3TC9HFTZuF9J9b9DhrwNRfnIfoaBE5XL19YmGKbJXlUF7XRpU8WdB39LuZ2KXVam2F)Whwf7m
IR38Dh3IuBB3jkPpC4K4ybt8MV9jAtEXNEajfxAUhoq29ix4JpOKe8YEypHG2mJsWlmo)YY(RxatkHtj
Q5ge8Bf3GTNEQLAbd(RpE49RqS((h2j2DBkjC)XBF8bXHtf9BwKv5hwx)GiGdQEXH3F3JW89Z3CZ6(h2
(rrSqynM17FQ7yyZHWVtVU50tn7wejM2CX6Utq8K1Yfrq3M)(YUDp0h43V)Mh7(2Xm8MVaM(7oUUh0Sg
L)(6V9ig5pUE7QiTp1OaE)RE8DpHxV9gWE)YHd7ezsYlT5nlpU70zo6)hlhVEv8Or6tmVxV8j4k8WDQQ
9nRB3Tcr7NG346PM5QlxWkE1DTvRP9qeY6(7qqJyx3T7WVc(nkriR3)H1hoPknRfH5B28tVbM0D72kXP
WfA54XTpiov)46hxHcQvhk)71d0rmjUTF32D7xxEaziArH)8JN2TiAKisbJ49JlF6UL9TGI6ZhuGuhpE
821w8494X9RiSiJ0UDBkQ2UF9QdsGNnI8y9SaGaho8(MmkH7s6qo8M)HWgTqHI4K(4v3TD)1i8aoKOK5
M)5J7(IV7XJp(UwCgSf)WJ7e(cXhnh(YWta2Bjc5hrGVmwXq)Q1tpkjUoDa6YHiAdPupvXDRlhpjraBV
QzOCOOg5nrY)1LNab)tVC5x3FMXhoxBruaEc6WRpC44FUzIQ)XMiFZ0J1(f7UD90DFXYrm8RwUE9(NKI
JssT9x3xAqspGi8hssxZhm0YHC7HzSyg5938JheNOVbrSNNK(WUV4Jnvul2a4FoEsdVwo2IMSQ98fF6X
JI)S4(l2z4383qA1UfRbN6dhpCdC2)H1NKshWj72LthoOEldWxBE56nnISzZtxVFD9HLpUiUrpZGE96X
TVBD3UNFeplmV5q(59p9BxVChuDp7qE52hUF9(3TE8zhXRq1IdF85PW)Z)60PT7E(V)nh29b4R(8CW6Y
1NyD0NtJDA5DVBl4J)aLXj4F)8l0xVU(P3lA(NDe)7pU969pR6CARBgA914X7fe0)cc)oU90wIGibuJb
b8aY9bqU12Jk2uhhqS9wF1lWOLHAYs5H(Smfb1Ka0LWOfSyExOJIUn0(lvuKDeGiQVnjaJsWtl0hyRIZ
rgglAPVsEuORpsxkzI936TPmx)2acDciVTp2bwy8FLuX1XHLeKaTpdbns(dlfLFG)m3fva5ZvZJHMmDk
HqztNaecRPbvTwsQ8hndrHlvQbiv(APelutMdPokYsrsJ0Koa4meO2bJSQkkRHdi6TMU63H(c6Q02lPo
jvhQxaUp3PvjK1xcKRE38r)COus8nWX63PLaTy56eiqLVRI0W8rVJkpr27I05OHdoVpouUD9G4eWfx0d
UHEOpWOny7Czi1TAGdmzA3agO(F2hcATX3xF0)gq13PAjAugaV13NIysYDbPIwIsJzr9FZ631PqLuSZV
7gkQs)Xynxvm(HMeidf(mgoFFI6C4LfyidSKj)ux5OhvTsh92SCd1c70d20CIwNGk9PuHn0LmTEtLPNc
g2TbujMqv1pboheMR6)E3WYcvnP6KMQVF24gQm(52QtNd4fzyetrZsK9jxp0hUXQ1c9Ax8kp5Oxukuv9
m(CGQSm0(gQCIMoLYdnQOq6H4iXsLRdBeTjrfvljkekMOBagnkY(GncM4WEwPxa6oJXaThtZb050wJET
)SV2jV0AsJG1c0xdVI(WtAAKup3Q4Oe82rssnZPpAPmhJjMore14yrsZp3Lk0uzi2)o6l2yYdPEeqgSt
FFkkIBanPYlZQOwOHgjwzMP237KQMJPo7jCsEyrtPXCOwP2SjKpQdPS7JHgYPpe48w65M9Uk9QPeVOuu
hP8znymM52gKdTyfr0rAhwuIBPHVlKK6vePpPPL(d1Qxlz4SmTvT4mt(Gbn5GLSesVMs2bprrhfec5ZE
BEowQL1TNIdqd7ZoURdYE5qtd6PIAzBZY3zfgxulQGyROIsItohvpdqDMOxeFgJunvAJHqhzsfuVkP1x
YWZNfLqyn9xSWt2REEHUsd(sC6fuqXouprg1JQeU5l18dXyGXyWhZo8hyewCwBxQ9Of0DADkrpKh8b9L
b5vDRmYURvSwhrWY(61EebA1kloc5mtBkarqFyrrrahwu9moeVWCKSqIX6kKuaUqAoaMuTTSJuc07Zxs
bT8JmupTPvcJPTZvtzrb3aoWsfqiRycKxo1)tzLokWH0vMJSB(bGJPoL(MIoLjIQEQsSIVJoBBmoDJsQ
VNchae3z0rAOBwmO2H23TQklsxcXpio5onPh3BWotLN6rnvfAMwlezDAIuzd70QgEtGiI09Nvu2aeMIt
cIaja8AQ0RWgTKzRYUN2FzFBpDCKP535sb2wZZlpYO)GlXqbKWXzuh8Qg(aeTjrDzVCSF0IzX1qeABjw
lw1Twt)iHf0bRnPbIsAGrztxEstMgzg03Mpd6bqcdx0yWxNZQmNvA(yNwIgIPFmgwxWIC8Mb5jMlauk4
NXY5bos1Pxc1P)DjOE9bFEebh7gtZVBpsBVTmyf6ni0knNfHDK18BYlltZUMN1ggL7qIETWADKGm4QSY
Rf5xzNqO6cr15qBe5UC3MvCo04WBkpFzNbryNzoDUsYNPO6GvZoNuz(wMHO2OKTfJQrl4F80vWL1QFY0
RdgHb7rSM9jbhbTmRm98ysejSlwmJoAaRANlfxauYM5qAtJCnGBWahKIrHAJrwNJCyG1quHQSwgkZhcZ
V7MZI5f5wGB5a8tcy5BbSD)CAKyjKsIUJ52w6ogaXjHkF14CHNgoFA(wTDlTvrrDFMGnTHm5L1HGSZiv
zqknptYQNYrBae1QCQbHjf40K3o9Y0QlYBP4aFAwjkyZQhjGM4CtYYqcKtK1KA0YoPfd0QbNIocT5LMV
CkVAzxEElCaSgGSS(5cqlc8oQDBAo6otZO5NmLwZXgzpuJ(UfvOuqv3K6T5WKUNDeEfJcQaCsMoQEt0Y
EY8Yr4n9PcAg((PzP8QAg5rFjAlGeIbyXIUWitQMbVnTzSqqJ7GFcnnMEdYY)H0LUXSO0k54hGCqTrAL
qBiMPVmH(icHweiLuC(WtmQa3QPHltYQGaDzYaY3jicaCjrvJdPWm5XSOhb6KI7Xa(yuwlxZHGrREGCI
RKXQESivGvliJabcTYKDmUvy60KPPAdSxzYP0DcrT63JXb0sdGhOALy201GOXEUbsnsLhRQwVfAnwVuc
ePub4OA3A2XodiZNU(aLiDTaKfTFyOtcZsFK8iVENrAh0yNtHEuNUqZ687oLsoAFhhGjhatpaxbUVB2Q
1ZU4LilJY01WKQXXKypzYYwv2ctQouW(5SYtP6mArZ6aWu7L0vqkOCjJxl25K4QcYhkdFv98OBlqNdfq
mmGpNktW3TJp20FBzibw6SJ8ZjAwqCEEsFAvXaTA2TuIawsPk)UEO(Th7hyoDbjo5MYs1laqMo2rDqez
wh7nhwmQne6QpgcQ0iuyujoPPTmopt6isJIePDwyQLjOCRH(7cvlbDTm01xmc(HVflDH4LYzlk9xroDk
a6vcqwuJkls6ewtgm1ydwa8SrnQG2zVmlfFQFUJWj3zKIAteAqBCyS5XnUknvf1PnEQ2icYgheNctEoa
Tfj4gyN0TmOltQk0LIJiyNn0ZwmIR1xMius6MbcoxHDyqoV0qjs9jYtXCwTVtouo6EQeTE)y7cm6Ex1w
b3Gdg7WD)(F0uyP8iTjY7yMJDe1ujacVmuZql5N(VSJcudXWWgluyAsOqjZE9a65QcnY5o77ABxcleMC
otYi96s0PW(tzxUqeSvfxyC4aiF)WtDuLWL9eDxBsX5c0jfVmj2o91DNwgk14O0G7mtMYlM6yN5qNade
DgQVAeZpjM6x78tHrRJI6CA3mYBJZzPWYLLJ6EnJh4FD7gaae633ifPk8j45FanOM8mK1dfa1g1MXWiv
BV89o9JLKEsiWWPH4LQr3yb5mBjvHoKAR2acZPrXUGcq1XJ0ThCGUXoavTcGbpWolGyhjSANGaNox(oQ
zDatEu91b(LrtcLeHVIW1G2Xjcs1TeQwTAkdzS9PHyPilmNf(vncrngdT37g2o1N1I8fD(cWJJ0LSrv6
gKJANq(Gv3Epzbk0GdtlD)q1e1NoQLWep5Xo02VhtcVK8kYl4AODSGcZA73O5mRBolg3kdqDetAOGSwe
RRx3PEpExPmMetUfJJt5ckEMEfpmkCIzX8)Yl53Hlvx(fTMgExdLjtR7aK8wQ2L7EvyS(JQ19lRwtdJ4
BQHLnnOoNwA(4zeR7eGwGu8ePOc9ip2TQ2ox351qompbcnqfXmwUbfTT(xXHMRCdceOdudi7wefrKONW
GB1ISQjmzvWJjJUXoMCvZFuzMerTQMfF7GY6wGa1MwJwZss0qNvHK0akJuXgJefK)nfZqz7lUZOA3Do7
9d3MCHUGqsgBgKzC6SIBJPnjKPEEuukcdjCtZ2lW4CtQQ7WGVD55idO4Haol(Ku(trZGGmfWwLQYusNn
VACDnT2RyJMmtRaHIXW(YylsfEDIstpSmbyc1R1SUZYaCCT6M0nOglT)bKPnRN3yWe0T7gkJKc5RJlOn
wVEagTMFtt6YXINh7TujOIjANtHdiJL5fHRzsTivfdGeunWEO9GihPMMJ171ZzG3CurHAvW8YPhLvDR1
PyHdAroJ1OTOH4PUO0ARGVuYk3xOAwd4KdWjQyKmAl)nS6KQGP0oe75mSTnFwpFj5i9uMYB1gBJw9GXL
vvdtbEpVgWbbqdjGBid4qiT2MDDGWbmT2pw7CGuyyYF5sgEh4gaaFE9KoR6w53gjrx6hD2inrQHeirtD
ounNHx3)wK(oQygg7jz7(5oCKnJwRnE3mbScCRFxy7MdJI)fElmxARMVQcmksx9M824au8vtHJsq8XSj
Q7BxPDrBBRGxp3aRdLE4kGYz6g3eBxcUgb86jKnU3YD7bph12cOHLoTZe96V2OLaROVy5rUc4Lqnt7eD
7dL323(izb7kAdK(dW3Zm1RAJl2iLkjtbJ3e4O0VWPNYPyw1BArvpetN0HKIzZM0mjWhB0fiGoNMYelB
y1drsW5ONDHFUNfsp)Q45Ax8aBxaOJHa3D47RTNl9rtukOBPUkjiPxzYhKisrMJaQZBjGMktVAHLU7dJ
94oee77cx3yNvVbbgojBvdZqJe6EuJQnbNMILPD1dJiQTskLb1SSyLPPxcv6b(aiIBSVJUmDQLDvwVso
gJxpQ1(P)2n0jE4WONrUTEYfiip5SU8KrcDTzh4fRvVR1XPoatsAiL6wKwb(QUYd5FhN0lOkDJHh9yF4
6aWSKvzlmI5Vm0OKTfdDxwbVODFkuD0ZGvTPWtBKyxoAZjPOnTIkPKVskwfiRAF9vVEjaq1t142AQLuf
njQT9aNI(8fOaDluYRiHABiMJA9usZlkjE1qsucI6Di06bBk466Sksagy)ILXUydREslcbMsjfQuZLnK
z5WgNQvz6Tkrpa9CXKlavxzk5nv0YvhJLZiLsAYukwi0eGFYa9HwY6j8lybvKTO)lVA2RMzxHrfcoAsq
BpQm2jw4SAPVqmON2Ivoqzol7a(H3moKrJx3)GmsLLNunQpMvmKLywR4lmBr1wrTzoJxpVkG1zC6TiZM
6U61ZPumq9NK0Q1jrPY27uCTYblr1URQ5YeG52HDZXc9IFvNvLl1r3xWBGbYYpNB15PJfdmqTe)SDC9a
bCWwRzjCoM6aZEC7FaVwpJSKaY50QGufOiD1Ihn5NNKT7eGIfChwKT0G6YAq3b5gvZtrGf3LImSYxq3O
KgrzpFaznpiDxpi10tcWGaJITaw1XMrbyPd0tMXbYfMaRtMK2ZQzuzxuaCrrTw9(SaNfsGAr9ltr9ra5
YQ3TJIEphexHz7q6pTgbyTwnZPIKFCYVX8O1xNrpAzXNJEIOcKUv8srfw0OiB3qFSiAvJXaTmdVQroq3
8uKiovjdkTD16zBtRE0vsJtmuJ5mesRUdJcaTMMgyWh36heuQAz93BZLJFhwMEMcY7s5FTc0aRM1F(rw
OxcnBHhG04N70L9RbLciESBVXqM3bobjME4mqLMhASrCYzxcf)4Ef2UbrM5ayKgWp1ja)TP57Qun9vng
1Gp1ocJ08Ye419XxYkRzFe8vQSooEZgcQr54rAzzB6td9Qgsk1J7pMq7Q0Ps(1jqbqoLUoTagIXbOaW3
mKc5e60VAsAvh5EpzOAtVxciLNH11BSkfabwhDpnvAa0Flxn9xiqlOh6)mDgM3PT2PnZ0R2axRgvP8z0
odg)SWUSfNQBgTKssJ0hxr6Mg8m9kRbk4c1qrBGBGM(ZwS9y)hcwZl2o2DEXFSZyPSE3ZKG6oho(9qEz
VZ5EuGuTu3LdKtrHak9(3FRC6eAwrNxH7lnagNmBAOdmDgmz51Uu2U9(CAvBz5u3yxwAiR1U3q(ZUIRT
nqmkSOTSjn6sajTDfubm1)jbA7yJitXFwDg2)m56eQqQ5f7)CaTc2HeD4HZuMG7KlsRE9m8JTmgq3JZB
124oGYFeH22f)SlaYE3QfGGSOD3519Xr8xzfiz7im0aOflaCXGvJrCJF8J5XokbtLEbOKvNX2YwgrNCe
fZClLKFSN6Z0KEJEpr8D(t(Eyc5fPM0LTQf(XIQER6ppsHaU44(Lb0)0jpZsTOrFN2YTpOObeuOmzqCS
H92PNMacmpTzPH9N2xHQmjNCHp0D)tWUnZORzurcdfeICkZuweeDuwLTAT)wXzRrRtxU54J70F)K9FeL
)4273E673F1UhLFHx)N6VXYVs(v(9F953(Yx9IV7NV4vF)l)(l(oSQC8F7VPJF)HB290Y72T()zSE5N8
XJ7pHbD)Yh(kap6lF4X3D)6XBxVgd((tFvR)KWVFyaZz8ljj)Y)7BU6RG2lL44LAuX54h8kA)GJq8JtZ
rS(BNoU8vcSMC(l3F481F71FLC)2B)MrUz3YTFZDl7VTRAyg0xF5Mx9pU4Yn)fme9iP(9VRFCJ67(36e
76(p6e(Bn5PUEx(3l)F)

**Comment by mbattersby** [comment]
What was the mount that was added?

**Comment by mbattersby** [comment]
Make sure you are reading the option properly, I think you have misunderstood.

>  Every new mount added or learned gets set to priority 1. The "set it to 0" option is clicked.

This has nothing to do with learning mounts. As the option reads, it is about Blizzard adding new mounts to the game. You can prioritize all mounts, learned or unlearned, at any time.

**Comment by Blasphemous666** [comment]
It added the level 20 parrot mount from Plunderstorm as well as the
seahorse from Plunderstorm.  Also a few others that I can't recall.
Basically any new mount I learn sets it at priority 1.

**Comment by mbattersby** [comment]
Tested this out, no bug everything is working fine.

As I said before, it's nothing to do with learning mounts, only when Blizzard first adds them. If you want to prioritize the mounts you don't know yet just scroll to the bottom of the mount list. You can set them all to 0 if you feel like it.
