### ISSUE TITLE
Totally unexplained "Cant Mount Here"

### ISSUE THREAD

**Issue by CosmicCuddle** [xod-wow/LiteMount#213]
What happens?

ive keybinded everything correctly and its setup to only use two rules and both are for ground mount, but whenever i use and wherever i use it just says "You Cant mount Here" im not sure what to do
What did you expect to happen instead?
I would hope it would summon the mount or any mount for that matter rather than that message that appears

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
it worked a few weeks ago and now does not work

Please do not modify anything below this line.

--- General ---

date: Fri Apr 19 17:22:49 2024
expansion: Dragonflight
build: 10.2.6 | 54205 | Apr 10 2024 | 100206 |  |  
version: 10.2.6-2
locale: enUS
current profile: Warlock

--- Player ---

name: Ñocturna-ArgentDawn
class: WARLOCK
level: 70
race: BloodElf
faction: Horde
spec: 3 267 0

--- Location ---

map: The Maw (1648)
mapPath: The Maw (1648) -> The Shadowlands (1550) -> Cosmic (946)
instance: The Maw (2364)
zoneText: The Maw
subZoneText: Detrithos
IsFlyableArea(): false
IsAdvancedFlyableArea(): false

--- Macros ---

```
```

--- Debugging Output ---

```
[1] PreClick fail time 18.12
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 2 rules for button 1
  Dispatching rule LimitSet [map:1550,nomap:1970] Colossal Ebonclaw Mawrat
  * New filter: =Colossal Ebonclaw Mawrat
  Dispatching rule LimitSet [nodragonridable,noflyable,nosubmerged] Colossal Ebonclaw Mawrat
  * New filter: =Colossal Ebonclaw Mawrat =Colossal Ebonclaw Mawrat
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * filters: =Colossal Ebonclaw Mawrat =Colossal Ebonclaw Mawrat MAWUSABLE
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is false
  Dispatching flow control action END
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 18.11
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 2 rules for button 1
  Dispatching rule LimitSet [map:1550,nomap:1970] Colossal Ebonclaw Mawrat
  * New filter: =Colossal Ebonclaw Mawrat
  Dispatching rule LimitSet [nodragonridable,noflyable,nosubmerged] Colossal Ebonclaw Mawrat
  * New filter: =Colossal Ebonclaw Mawrat =Colossal Ebonclaw Mawrat
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * filters: =Colossal Ebonclaw Mawrat =Colossal Ebonclaw Mawrat MAWUSABLE
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is false
  Dispatching flow control action END
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 18.22
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 2 rules for button 1
  Dispatching rule LimitSet [map:1550,nomap:1970] Colossal Ebonclaw Mawrat
  * New filter: =Colossal Ebonclaw Mawrat
  Dispatching rule LimitSet [nodragonridable,noflyable,nosubmerged] Colossal Ebonclaw Mawrat
  * New filter: =Colossal Ebonclaw Mawrat =Colossal Ebonclaw Mawrat
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * filters: =Colossal Ebonclaw Mawrat =Colossal Ebonclaw Mawrat MAWUSABLE
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is false
  Dispatching flow control action END
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 18.32
```

--- Options DB ---

T352oYXnsc7hNzmWSZK8CsFN8znESSHlpEa8IPrNQ7QvxqvxLq1vBznx0Vd7JWE5pwSyV4)MDb270l2g
bzCQLtPYs(84c2ak7SizsgmyWGKXxMN4o5lozXzxoTd)3N)VT9S93SBZ0TN(VC7P3B3JwUz)TN(EtpDt
lvBV6Ht7)KPZ2T9Kf)PZxD9vBVb)9)12)U88)(T)5)0173(KRWuC3BVE50xV8RxE5QZwV82)8j7H)BXJ
wV9HtRXc(6BU6QTBExm5xd)9d8fFPma)7jpiNhQU2vPyXxp5bWF4gRHCSDzoLJP2phQrVl3UPp4Jo5QE
EI(XHHEklPAja3bYZqXNdu2lXbm7WJ15lHHX(JketLG8a8duXogtyfaVDim4D0ZOedjUkw7naxjs11si
4GIkGTIOl56pbi3HCVfgsHXIVvZ8PXHC)Hvhlyslyr5YutmowkWnJduU6TSunLH7IpeOnKQDjiubYTRq
PHiHs9shtyUx9brqDSNW6Gl471jVhBsO8YvghX6CS3O6n0OZpG3DmfA3ES3ukG4U0AjWd3tYsVVGI1c2
uqPwGeqUXyPxyq1kn2Yw2pehjPQpoMPEd)qi3(DOpSg6TLiuu9kJppavHEJjNRzFxwmMCHEteuxcWJkH
pUuiow5MBH6nW(LGwwjrU56LvQMt9(vq3Pg6DwHCnM6T7SlMlK6cOW1BGGw2qVTowgQd0dA03AvT(9bF
xaajT21xHkNl37cIUWOVxtCGACzK7Rl9gL3xbnGUWgtAVOGoUAVo7dy2GCG)oOHq)oQ357sfONHhLKcb
sVSgCDPAa0yd9uw8TkDtO6suM8y3cvRHwYaxtJLUUOZbJ8CCLk2LzGAtOsJvkvFeVfkzcWiiQSWUIEli
omulKI)GRYdrcUHm1aIOgewTYJoFM1RYHUYGhQS44vmbHyCO3dNd1CGRwbAWIZhObg5Yaneipo201QTc
DKsameDmMONAUG9RHE3EVsJ2OOhpO0nqA4UyDmtDRjuaN7IAsONQJrAybOZ65QcubWmH6(qB1im7sWmm
AKuGGbM92uf62YTIhhFq6pGvLEwhJCBhRgz6Xut4tahGp26C4gFTvoPYyKUhyiR3iazyQRqa2r8JQwGR
lpHlPMgoikWnhW(sZIgufdKGdnj1Bx1rySFp3yNfv5GbrP(qFqFMnygBYLEVvM0qq7HJHM6EQwRK6QNn
9HvUUYCiwinWamjtZE(yZGwQnOff11AtSUhN7BZfRE0xUC31R2UbQJNSy1MR3pT5SLTzSCNS4JNwV6QZ
3Ud1mGNWIVC6M1WKJBV42t3F5YBp9(BoBcMzDpKbOZfmZTyXN8LWKSRxVclMBp9dN2TB11B3C7P)fyQY
13EAtQbtES4lW8)jtpfRsj6p)0hE9QZHCE7PlGSV)MRWodOAC)ZwcZ((u4(V7Q9tNVCnwFaj3I3)QL7M
wFomD(ULtx90PNHvdWc3I3z92TNFfuBHIA90JGN0QnyLmbQVl(KPhb1(DRoF7MF31qnBAvVbcf49w)OL
7V83nTdAeNbpPR6Li8llUC68Tp9QTyB5DUz3QjOO)WDW07NFnAUcMCEXFD95yvgkPYjl(OP1RVUlQU)M
lUPlI9oym93U5C7P)(X)O7TGUaWs)I3BA3J7pNpaQzlbzayjAX7)q8oF021NJ9PW8nl(ILx9eWZJ2Jyb
uRbjXQRX2imyEXNEZ(1tBohL2yz(vl3bPaedB3TFvtoanP3D7Q1xmT5rV9TN2e))1nNVC3d3(i8baMrx
83ME2z7wE9ESFAdQe4CWWQfV3UPLB66eGTOfUH)4a2bm9iScE)RxV86MNwGyA90zpw)jPXc)4da9IP9R
(A4Pk6FGjvOvb(TTD92Rq1h4wzW06IVcAitRN21gqcj59wEXYnxtT8pEA30d7vUriT37MZUC1MZH(LMU
oCJl387E80Ll3ZTYpf1x(4vBE05BXolpQx3(HEpmk1AcrpQ(VB6FC5euuGNBy370v4F0u90h0B3f)lFm
0wB96qkqnCQ537MqZyWCBl(ITRrNpFut(bgkAYp3FmbPB1vqL4ZxDX(U8dgEEd4SkOBCV)b415UnlFR2
GSWjl(G)gQjS785gGHMDqpwwSy5tUz9zGEUz86hSAh2D(PTXcGLwOvrJ06j692E1ky4CR7ibEdT4d3DZ
nR1bjfppY9ZV5HpZmmfmGJdhFg1PCV)X1G33tOkcQX0YXd2(4lVbe9F6fyVh01J)k4p0lmighKGJGROw
1d(S3hA)py5tV90pB90ZW2Y7)npbg6UeupERMy69)MvRxI1WpF50zxEYdGM07pD9(L72i9Yn9DO78JwU
E9fWikrvKvjAwlaPdUkHZ61luZ5Qv7oF301xVA9FGKFTAi(W(OTpzjQim(ckc4FSCZ0k4rS7zpzFZSiy
qEX93HDrV32ZEmk4XXZFfix)aCuWJpb9C0DytN(M4eY6dwUEpiEVP3hIJUbz96LGU27cRiz3Mw3XOKUv
3Xmxg8GP3HGkCGjt4N(94QHUJz9lwTz1ECWYn7pF72DVvZQguh7D7)Lvxa)2NTDBtxhMcCwr7NpD1tM2
HYaiVq3Y7SdgpSCZLRq9wWq26Tpfhr3)PTWVqwpoPTCIfl2dwiaBbxHcACOZdaBxxUB5MMbqyvc0O2B2
8u4HJIc02(DSdHZhIf02Dx9uOlcs8EOhaQE44(qMm12MLWmXc4(kO3pHPVpM8EN)1WAgVbmf3wJ3t2T9
cqN7Jx(SRpW6lblO7wdprObck4pB92VHSnE3ub2ZW5vHX1RF()7fx84nRE0L7FvP7RE()VNC5Z298)Nx
zPDVN)FSBf0FUgNK4BLSZHA1xT6jWGPhU68xz5S45)xBwHJOw9kt2xGZjIT2xzDAZZ)pF8Z)3Fvj5(xp
D(Z))VBoXPwLw)SlE()938ksI2p16K4oc4Y2k4)myubiCwrE6Kb3j7(16aFQiN1JdJbAHtTeq(vbo2kl
SHDZexWi5bMVcliPNaDL6TKsRrbwtEGxJc72l4L5Wi5jzzGxJcMYO8q5fVdlxMxnxEir(y7Yf653squV
l5rShxUrpbJ5rA1R5mVEuOHsEBJpkEHtLsHUzggswKKsRIhKvrApfYvELp8Qb6TFEf5qtHEuz29w)4yA
u9WVliaVCPL1cRzzKxRbMsADzJv3aLaDTsWcWIE9MKmHwblF3EballNVjTHa8L8kV9TDEO1sR06oB)oj
tXf52lGij8JK(c0CDYv0dXLR1e7AUpq7KckzjfhOkspzui4fHqpHjxBr6ywY8I5hhk0LfAz3f6b0xXhE
vQ6L9vknWva4UbT)GwPnTMk(3DsfSiYJrN(7E9U9l1nTicRSHAbbqHHwrzmKzzrif5DZcuccQSI0C91k
VWkmxErSWRXQg5vmdpkQ1NZJ0QGYdohV40ipYaejd0GqC9suEGX4S83pui5FDix1YKv8BRy21fz8(CGp
Ds8O7tqCKnruczs6d6WCVLVKgdYYgjvOCSYfe8ZuTJ3PWwktuPxejQU5BMDwbRCKbI4ilLqbcBFkMsAB
NQg(bNx165vDcvzAyjy)WxYAc63nrnOuP)SZqnJ2QQ6yG2jguROFvM1KYQH1iBcfLeEUL649GiLLDrH3
so8HK1FM1cWMvpL1WaTDeyRwxEUt1951s7zJfTBkn1rQJgSQYTF837fvTKiJEynr7YYzjpJsdVk1drfN
KZJ9TqfVxmX2M9LAFNx7foBAM12A)CrZePJfRYmcEhjohlSoe2iPsx3iqAFNX)hgQf8A271tAtkO6HOz
5y12uitMPX6e10HzdIfZDlAAjPmVfmucyzsXZIzDdrIfEeOZ0ZtTjAtJXNvfMorYIT05Dk17P5oGr18q
mOrNytH1KSrwfqZNvYHwcjvan5G887npExuWUXcDpu8qQGfykcVEt2(qkrBOfTfpUU(anfFsNyN2gu8U
4gD7e5qrQhAXZYwmL96jTVq8n7noyGwT6L2zH3fYCG0H19Bdxi8G28IAkzxyC(rzSArDXiWQC02Zt1vA
oHAqAuqk)wBsjUt9AtHDSbQaoQ9hlS)a4n16N2u5nTx2t(wkj94XQkszbPJ1bXkh14qvho399vLeo9Nd
O6XUcafoFIjJUbsoLIC3q73DSelXULaLzsRDSnphOV74kvrfJSLkxsMhYPZi7HQnB(CisEdfGXlu1gDa
J9rcAcubaknvsPqppayK5iBlntwWAPmR)U2UzZ84LY0N8OdWEJxEQvE0d4nBMfx4w6tJPLdcbSRYExuI
S1hCubPF1YK4nj72AuCmJoMamt6y(w(PX8GFed0dfwOAvZ1OMRSEzrKquMggObfoWe)Gu8KlxMthRDxz
2u2odosNU0S90HImaojDM8bfX3DuQkA9lL1FN0HlS5n8MKSefvSzwxuMTRTveT2cF6eNG9Gvh7yb4AlP
IuD8jrblHOmO5kPjnjvWIEZEfeg2nOzpQ)m1u9qVMtV7OExYcrLljymkpAX3wZE)szMam7vPIWIp4z2Z
eOiWZYIzxROKZuTNjp9auvDAAPhamJDvFwKXih4TbPwMhRvnLvnLshmpeflv2b0WOQRgznmmx0WMqTQ9
18H70kahD3Gph0SrfwgmjXlESTT1scO(nyIVAslxJ8W804LAXDmO420W0(qXBcyqMPOeL4OCUJo9GXGe
qtdfb3zIAjmQ3vtlp5cEx2x2GJMik6kYXfHh4NMuAibytmP1Cw2XNmYj9dyNmQm4yzaEttU4IDug0QNA
o(y1UbA(nu7GM1TK8gjd3NpmYlmgQF8X4cLeBZJNHbEqLGyPlYJZghyFkAjGKBdjwSeWdCu1PII3YzZi
D2uhfdbn5c4ie7KD)CaB3TWwWBzthlWrHaFQVNGZ4XlognxQvbDBa8I7aWCJS)FdPbviYNei0i4jbYz2
nFqtmX(TvZIkt2PwgOka(7KteGFlz21fWe2qrYfPralKI2Fb4htj20VJv(6braELCw8OPaErm4MsWR3R
W2OXkDwR0J8LSScRPu3fmQL)9us8SCaCpGLkPYa5dSNxcEROkYtLNVfKACNbmqKAvG3O8I1KJfVLFs1N
ptWMll8YHbzsuN6Jk(Eaa466JKMhihRQjuEJAGrM0KKCScGjfMwH1RGPJzFMavbEyA1fyF3KJTgUQg1m
LKmj7dvXx55MHmXZYZlWQLRI2QmL1O0SC6n5vP6yvryXDont5bPfY(UOhaF7b0RH6HL3YLmAGJ3LqbC5
sAb8M2rX7c2SHX5fT8ZA(zRB5mnkoNR0VhrF)5lJXIQcMLHq(klxahY40kXMdmYSk7lNlRBgysc7iOCR
Ajiwee7ed(avhWwdP5n6yxjrjNMhNuOJr(rnWlFi6iDKw1ojLK5zs)EQiUNf4LLJ6cYImX9WKRtY2RaE
Njtrfv3dYKZn1sq3m4S3uuKWegzqDXrz7nA5Nnicscz8MlRsTIxRbjnBfnb8kKg5anPLGrnbQjrQ5OHp
tlPMhgj4tvZ0W8(jHkxSBhdGnVSKnsGsbid)7uvSKz)g9Uqq2TGHI4TOll(a1JEboB8eQ5Iy2eS7O9ES
iftlLnmPMYv1FPvuaZHmqdBCGeJTMhQdCJeSqqj1lX0bgXzdAnqvk5v6GR0LmYb9)rwmcPMMesJtlWCV
OPktsGbDNxZKr23lQAjYBEku(6UvpWBiIgrsTCX1fj0HOG)QjmWnPwlRGwwu1o4dABHNffJimVE3KMl2
PC8Pr1a2Eh8m59AaC)G3(Bnq1qncEtxt8AXdW8b8EqMKD)fsj3ZJ)EV8tJztCAXJWhRSzbWe1axQCmos
fGjBuZECGJXs8YGud4D1XekEWfoPzN4aTc9)MuTcIpZTeOpmwtxdlphyfkk2dJJItXY(bvRo2IbMwhvy
1eLwWp3eVEm8PXkTvEvAGeN1zbBRSJIyUsAXs6bLeBPmeDS0hJOr6zLG(whvQ5kRtl7sgQjl7plKu2ZL
a74vQw5qUeMxMx9nS2mNxZvqtaRjMLDtfehQzz2ZlOcWsoixK1TusoHlq0tkAWf8eNE84Kg07sja0QyB
9dSIo87STTy7OXL7sDZoCtMLeitx3J6t8skOpXSH7AqvZwwV0uy0JamYjRtcw7tVHHBSLmVGSVkfzbI4
w1s5huZOHiqvH3BAOAjlBe8oGD6w2fS2CqoQSgZYZQhlL9CnWBTZaFUoCyp66ke0cBIJYts3f(bEAlC6
AErmyzoQjLmCnmil3Pgy3ugQ8uKykzNkbR8Yi8rhBTiYBhKpZJOsJCCWb2Q1JIAGfLOYIA6NFuyHAsRx
QazzUJ4GA2GEw4MZjMcI0YlYSDvoEaX)VetAbj1ky(iQ9JbET55RUPXXfn0tZBYjmZMSDfbERDBLlvyP
kVacWylVJDG3JrE7UbHHSiprhbn4ZJZ0yoVvUuDaUw2CPr(4ka32JM4tNhPxt8IrQSla(ahdUW0n8mAO
3zKjunuh9yK12ZF2fmXGlFykWk4KvNh5P5gC85FPrNjQ4t(Pcw)O5laxxzNYXfJsYh0JwU3qwHgfB74d
smyGNbyWm1jx9doEDTjhFM446hOhf4UhVn2OFM97oQNNHgxSWcGy3B440VLlVeHNd45C0VBbprv6YHeB
tudYzmP8ubY6AaNAcckbo2)3wAZscylLWuu8P)GN2fvDJJbs1dDpG31bCPtCTPYJZlJSJiGTEDSnzifx
oBplJs8dqr2BRsdRaLRtjEJ(b9Wr2xqWWgT6cjAHts0GJRlLvFGoyUjlHSBsIKdCKqqukDgRvSROy0o7
OSHou0FOdmLeUkmJM0q65bF6KzTcpGPMJvUyg4ECuAYdICsGoadZyTNoUcUw3rSQgTL7coOufzdxavy6
mDYISoHh7ib2MeViLTUQk7xmUvc0dtp(ty0zqC)EGSaZ7HF7brvA4cElKrhDe3QYS7Ory1zSEk4nxLfg
8koXvZqZ7HNwPMuwjdwpiB3Mc562Zvy)GdmCNg08m2bTINfpq1ivfV05tEIzHW1xiUoRfvr88Yrd4EAj
UWYJ3qXev7LZ8fD7LNhTYlIpk7yutDNTNP2ws1Sx7rYSP5OSpTyGfu0eqUUfKnkclwXDjoSnG(h2Zlq3
yCW09lEQgKOpNn(qOIWLkxdL1a06EOIAaMsHeLikb9lB9fuZnZs1M)EKCRgKd)hhjw4klBQgDCQQDbYm
zA8EateW9REoieGv1YROaS5sUqGGRq1kOvZXubUYzrA55T7e62PrJG3qEEcuLbciBXG4KcFi4yDLSpbJ
WYYtv1l5E2eR2bZEYhdBbul5EBXjtepaDunpvuOfyOTlH2mVdJWuvYjMvI6KUcMte8tTAQSfSG6kjvWz
xetHv(qisYwE32OMEAXGFH3yaWAwrlv6znkB5(yI3Y6wD1ubi9cC9Zz(Ufznub(0RmCKPWsGwwnsaUX6
f3zj0OWlZSIjEmtSRzkXBqpj7utTWhKFya88LYLJ18r1kPhCKJBodgqOBpzXkEvwPoFsbyDLNqaw1cpi
aBRMzeO(aIDi8UO7a6SySpAD(5A17iV3XTILMze0CO(y08K49lpTmMs6rf5G9bTOOowXd4XtNY4fk7YV
tKMG6SX5)E5d9Lw)GlQaGhyngLDupioXbfqwCyJ3RcyIBh7h8O4gmEWpQMLCoxCydGXNNmEHHgemEk7F
HN1HHgvHdVfWumlkdIF(4ggZdhQEZ2UWJYW9QiQfBul2(taTJs5c6PKyl0lxwg0TqTA2fx(KTIYuIEXo
QLuonaGqfpYlFy8oxTXWnZPjLSn2Pi11nUyoZcEQgmgvyx)lYU4AyHde29cWq2QxoDruaWbTyN5Twvr2
J42GmsBcfasBrcodmqojjONd8guBLD)PYNEJH)qLSwCnT0qmxGDoexGnBM3lhVj4YyLJlsIeUwD1LJgB
YKJMbUcKH1mWZzkNbx74n4bwGfhzOpRTJoTrnQbE)WXWQIpQLahxcnhHIAv14EhvOXa3cJ4kWz3J88qe
q8tBIslKbP2k4Pi1wjQdXBoMKZxzGxAqRq1HRmeSqVM3SiGO2SmY1QwSChpO461YvL2cZDXaVDf45nsE
2u4fLIlwx8RRYX)mUWzznnbztPCYi6bU3eNDPQPuYpdkDRUMLKsUWsWbZnwsZgx7JABGkkWzwo4xWzLz
DGahlMnxWPXlv1fjzJhyin7ERYtPilGK5bUDjyzPNuct5E(DCSvGRBLK1HQerFbzpJB7CjxSvE9zmLMU
tisjX7HlRoOxYtkh4WMe1x5HRvE(BgIv6rXHxtq2VkOxN94f6RyppjsnB5kZBtcu95PAhZbzx154Wg8h
LN1VTAB1olpNjyAINDOYZ1BWegw0zv2izuC1VeCHqJmFzizCqWXFyOWlDFWlBRDiQBiGS202MhWZGJUe
1UewMfVPrqXsfaUC8KmVvq9NK(zWMHeX7G6opzm45c1WWPLyvppDc)7pzXUBwZCE2H98VS6Qv7xSS9Yp
y6jVnyED4pSzB7YAz4VF7PV721BV(Ae8regXZwp90gbN7M2dvJ7K)nBpVXHZUvNp9W1lHI5I1pJU66BE
4vl39i8DOWRQe7)NWZXVsb3qxL5rWnocUXrWnocUr7QVNGBO7xYrWnocUXrWn(nn4gg)spcUHQf1Fo)A
fCdZML9BtWnm7k1SGBy362FQ424ohjYrUn(nn3gMDTSLlsd5i3guA)XGBdD)9)fo3gMDR8hlUnmreZrU
no5NBUn0y94xpyBydgWJCBCiUnmXZYrUnC)IKBdtOF8lvUnmNlG7i3gTcBoUnSrN7VIa3qdy0JCB8AWT
Hjyj(EZTHEczVoyByIWDd2gAWU)gsTHgJ7hH24FEH2WWxXSuBycBjd1gMWVWsTHEk86j8AEDry4aYESU
ZsTHgD9gUrmyHmh2gwAWNhBdjewnaKOyB4nX0PcvYSuBycEqtCmml3gkRjodwjk2gMti3GTHfHlfXetO
(BI)X542qz9WWTHjATom3gA8GzJL5VVyBO8KyP2qJoIdsTHHlctK4fuIuSCBOiZOGBChWryypMLBdBqx
ibm9bW2WavI9nGTflfjmO1aMqj8WYGNAZqPgXq4X8CByIQfd4gAmYBa)47a4gA06OGBOKHOmGCqSn0i2
ZW9XHX2qP94WyBO4GyO9yEYnyUoMJBdLQdd2gkRggG104)XenZhGBdBOuzIKwnyYEn42WewxYlXanQWM
LBdnKTMhCdt8HPrQMgtyMqk2IWHLBdLMdLBdleCk3ggyhmGBydlDtG(QbTRcUHL2fnE)mWezGT5LWUHj
UNvCDCAq0zcjrdDag4nmbDQckIjWTmVtmmbnkBB2qEJHJdd8g3jcMLy6udQwd(gkNhZIVHjonn8BOrgV
LFdn07n8BycCCfjfnoqnH7480ByImsd9gkqow6n04U(a0By4e6fr2yqVSFxtKSAO3qFnsAO3WGIIYzXS
WBiWdPHITj4znKBydjytGc)cSBqTkLiKGEAGg2nmWb9kb3WabIgCZgoSmefzq3W8AhZWUHcbIbJqd6hk
6gAef389QxRuEqmKzml5gMWK2GgIn(11Gx2WRHjoGnOByim4GSBmpWggMv0ai)7o6ggOxNhtddtNkksw
kru2nSFIwu4nmXOVL9cd0Lk8ggkmMfEJGYyLHr42oYzk2EpMsKXHy3WaCGb3R5y3WIQKLidjmiv2mekp
mm9ya64ouyilq2aKX8WByOyWlqbBjR2nd7ggoxSSBOi6oh8ggaVoi8goLQOG(kxZqVH9ThHcFHtrUyw6
nmyAAWOZeJ2VeMmu8nu8m0xY3kTu4jctpEfEdNcoMbWifSS5H3WPKTzG3Oi4WziK6GWBmA)4oj69mWcM
xWAgsGnyI8MWUHbDcdZKZdVHHtI7akPcVHcmQ(oIrH3WcCQWoHbnvdpIgkfpa8ggMoNhEddgfg4nCkXK
g6nSC8QuiO0ByiX9q0Byq2qyx(GSBOuvzq3WGjCqHRwbYoiGm)MrUHbYc99jGbDdlzfk6ggoMTOvimoy
y(vrdXGjPIlO5fXGIVTHScdVhZIUHf6iL4CZBTcfcKdXZHHCdLTtdC0ZcUHbbdbu5dYTHI6Gf8dfHJdc
UH5d513zUnmV4dnuvml3ggcnmVioMNMdd6lgUnSVVLuynmeACNVWCcQ6gUnuSWVd3gYlu578casEZDDq
YnuCn03mmhaCdlCfl(B3)to5faZ4IPZWVUpVn)zM5LsMXhUB50E8JQZ53E67VE5JFChhJZ2(KN9ftqA2
F9NG4yCYdpzX0MnWLNT8lxn9xV)jVdMSZp(L2atWrGn638iWg4Lhb24iWghb24iWgUJaBCeyJK08IAkz
xyocSbv4)iaSH5SG)NlInm7963xInm7u1pGiBy2i(WpzmB8s(wByFjoCKzJFAy2WSJ8UFwy2iC8BTbxc
J6D10EKzdYQ7psmBC8BTrRE)ZjZg23ES)Q5BTHjeDCVgqByFNe9Jd0g6gc)BEOnm7CS77n0gMTwEEOnm
bg33zOnmbCPjQ0C6zj(dh0gAGU8AWSHjoApi0gYzy7(XNzdZo27(fkZgVWPsCKzJ3iMnKW7X9ZdYgMtC
6hoKnmbR63BMn0qs)hsKn(b9tTXBgZg6rS(BGp0g2VHb)wfzdf4Gzr2W82fWGSH5f9GfzdngLmHqVb7s
ZPYBiKCwMnuGHShATjE4NNzd5OUNNzdLjkdSMZ(P2WCa6VmOne0unN7(SqByqGZWI2HP2qjn2Cs4gunm
XdGsTHgyaMWcmyX2qIcR5X2We7bgi30pAfZsTHgpdheAdlFgZfAeHdbTH5JjHYSH99t9by2W(DsY8vLC
2p2gcPggqdo03AdjGsmHgIc3GbNafoalhk6BZaLzdZlhutqO8s(uBOCMOiByEh2yI3NdZSHsWNHzdZR(
FLpdn2EmXmOj2FmVIaSrFZHG2WeOpZdTHnaG1WmXe0qZdTHjMCNJBdn8JmXKKnsLuWnmrsL5RNGLmJz)
IBOVpFnHc1Rb5gMyr2eHBgUvmOI9DgEdtiOzILony10OcZeQygScmraNeaDMqLZgaDg0n0OU7oFZnKGR
v5nYecJMi4ZeH)2VfrMWrxH0WGUHgR0goxuecSFhzmrdUsRHnuHnbePeLKMyKZed(A8SBcssZBZCjAcn
GBGBSU4eTSX7oH4fnCnnFsfMJBdteEkyByPxuX2qPB0qTHZWQHjAwnyYR8Onl3gwSmM9RUHbSd7B35d8
v3WqOHg6YMVddMp6gk1Kk2gwADmF0n0On1aUZSCByO1Xg29MOCvr3Wg8Uk6bg0nmH6MbYedgng0nmqa4
oa9ggeRCg4qu8n03pVg6nmXxSHEd7lFDjQNTFLDu8nSG0enr5MqVKgKdZZVHsDLHokdNngSTmVtYM9lV
HLIHdIVHgI7gcBSFHcuWC(UZVHb7l9T2MbWRGIqLbZbnG(Vd(gcrdg8nmqDemebo33EdlEhZJVHYZMbx
mLCN3m6nu8mmeZR4By4pX(P3qrMqO3Wa0NZ8IQ3GNHH2CLuedkhktgZJVHbaedjhkOKVg4Byq(Cg6nCk
smwOAoe9gk8Mg4nmSfyqVYc5hV1Ig0nutHfN5yx45Nu0lmF8AmF2nuYp8kJvkgPTJ4M9(9UOB0ZftGwr
iW4L8r3qFtZz42WadNbbYdbUrqHnX8PGY8H(srhvP2Z8Uz6nbCdlZxMVxaZ)v3qFB)yOT0cUH5lbLHxq
LHZ7G(M8kiW(TKsr)qbQtXj9L(z3iP1vQxvj3qz4ZaUHYMUHBddJhgeooWxDddVUk2gk3O6RG07GTHam
SbJydeWgKJ13Ezj9mwKpKyZ852WG7S7qqByGYWqcIcTHb8Bl0gk)igUKmVrfmVileumm8Gz43WqJKLvd
ftoV5DIMYBVYJVfwt9B7HsfI(gLqFjeyqbrXz3(52qF9Fy43ygOnmVXOmO8FiQnSFEF0xCckFZZdTH59
jH5LKG5DtXSyB4034f6R5cZRicZRudLAJ7(rrDqCuxXZW8g5rE7LyG2W8MsXqxH59nGfAdLUc9ZrPW8H
bzd91gM5TNI5vCHcSHHs)78Iyr2)SVRaB8s)sz83V907D2Ll3DZ13E67TCA)LNDjYDXUtEbIo(weF040
4fzYyoWn6FHno5)7

**Comment by mbattersby** [comment]
I suspect you are having a Maw-specific problem, although nothing has changed in LiteMount in the last few weeks.

If you haven't unlocked general riding in the maw (by completing the quest "Who is the Maw Walker?") only three mounts are hard-coded in LiteMount to be usable in The Maw: Mawsworn Soulhunter, Corridor Creeper and Bound Shadehound. As far as I remember the game has no indication of which mounts are usable or not, and they all appear usable until you try and they give an error.

You can see if you have unlocked general riding like this:

`/dump C_QuestLog.IsQuestFlaggedCompleted(63994)`

which will print 'true' if you have (though I assume you know if you have or not).

The unlock is battle.net wide so I have no way of testing anything to do with pre-unlock mounting in The Maw. I have no way to know what mounts are usable pre-unlock and which aren't. I also have no way of knowing when they remove that requirement.

**Comment by CosmicCuddle** [comment]
Hey its fixed now but what i meant was i was having this issue everywhere i went including in Dragonflight zones thats why i was confused im not sure what fixed it but its working now, just wanted to clarify it was not just in the maw i had this issue it was everywhere i went

**Comment by mbattersby** [comment]
Ah ok, your debug output is all in the maw so my assumption was that's the issue.

I don't have any specific idea what this is, as far as I know there's nothing different about Colossal Ebonclaw Mawrat, nor should LiteMount be doing anything different between the times you say it works and the times it was broken.

There were some issues in Shadowlands (that may persist) where Blizzard would mark every mount as unusable. The most usual way I was able to repeat this was in some of the Kyrian storyline where there were scenarios where mounting was disabled and it didn't unflag when you returned. There are probably other ways of triggering it.

That's about the only idea I have. If it happens again, please check if the mount journal is all red as well, and otherwise see if you can do any debugging yourself about why it's happening.

**Comment by mbattersby** [comment]
Closing this off, will forever remain a mystery.
