### ISSUE TITLE
Flying mount is exclusively being summoned with rule to exclude all but ground mounts

### ISSUE THREAD

**Issue by coden1ke** [xod-wow/LiteMount#215]
What happens?
Added Rule to Key Binding 1
Conditions: Modifier key, Left CTRL
Action: Limit Mounts, RUN

Only a single mount is being summoned, my Otterworldly Ottuk Carrier. This is also the only mount that I have enabled for Ground, Flying, and Aquatic. When I remove my Otterwordly Ottuk from Flying my rule seems to work as intended

What did you expect to happen instead?

I was expecting this rule to limit the random mount function to only my enabled ground mounts.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?

N\A - This was the first time I setup a rule

Please do not modify anything below this line.

--- General ---

date: Fri May  3 13:15:39 2024
expansion: Dragonflight
build: 10.2.6 | 54499 | Apr 30 2024 | 100206 |  |  
version: 10.2.6-6
locale: enUS
current profile: Default

--- Player ---

name: Codenike-Eldre'Thalas
class: MONK
level: 70
race: Pandaren
faction: Alliance
spec: 3 269 0

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: The Artisan's Market
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
```

--- Debugging Output ---

```
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching rule         Limit -DRAGONRIDING
  * Add limits: -DRAGONRIDING
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. -DRAGONRIDING
     2. CASTABLE
  * filtered list contains 481 mounts
  * trying Dragonriding Mount
  * found 0 mounts.
  * trying Flying Mount
  * found 35 mounts.
  * WeightedRandom n=35, t=2.304, c=0.411, w=0.667, p=0.289
  * setting action to mount Ashes of Al'ar
[1] PreClick ok time 33.97
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 486 mounts
  * trying Dragonriding Mount
  * found 5 mounts.
  * WeightedRandom n=5, t=2.083, c=0.563, w=0.667, p=0.320
  * setting action to mount Highland Drake
[1] PreClick ok time 25.97
[1] PostClick handler (inputButton=LeftButton, isDown=true)
Clearing flag FLY for spell Otterworldly Ottuk Carrier (376912).
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  Dispatching rule LimitSet [mod:lctrl] RUN
  * Add limits: =RUN
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is false
  Dispatching flow control action     IF [submerged]
  * IF test is false
  Dispatching flow control action     ELSEIF [dragonridable]
  * ELSEIF test is true
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is false
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is false
  Dispatching flow control action     END
  Dispatching flow control action END
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. =RUN
     2. CASTABLE
  * filtered list contains 17 mounts
  * trying Dragonriding Mount
  * found 0 mounts.
  * trying Flying Mount
  * found 0 mounts.
  * trying Ground Mount
  * found 17 mounts.
  * WeightedRandom n=17, t=2.659, c=1.006, w=0.250, p=0.094
  * setting action to mount Frostshard Infernal
[1] PreClick ok time 14.34
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 0.18
[1] PostClick handler (inputButton=LeftButton, isDown=true)
```

--- Options DB ---

n2tAtYrnw(ZHHyyCOBLIVzS5AaBiCvde7SX2Ht3UC3v4QRYB1vdJ5d(3((oLsP0g25ICvRJ3LE3Q2RSx
T9QnxF78z8F(KtVE3X9VD3hE5)4dV8Rp86Z7(ST3oFy(E4pEb(3BE35tVz)HD)WU3FVo)5l3U7486vS5
P7EZ8dhUWZcM0D7V)VAwhpD5cnNFy)59h)Wl3E68WmU)YPZZ38raWXP9()Z)5VAs1t7XNVz3r4ZNo)7h
hMZRMp(2)S95XNNp8h7)l3MgrD(msV(WlFX(J38PM0Ne7pFl8)8xHwN3nZWX)pX(pfMD9BpV7Ey0l3(x
c5i5MM0ZM3D4(lNpD3WeMV)YUZ7)lLsQuGVz(mSn7bKzCk3T7Iih9NrUvC7BiXZZ3D60NMJ8Nlf9xnNl
V)6B)Z2iyA3C40RMpG3xU)H7U70XNC6HJxW7pp3hlbt(QNpbF6CbZvp3sd6ZPREEa(mLsHm9PZv8tr4F
ctkyMsrVm5GpzPpDwVZu4rdUug20eUo)KfwV1j7mpdRZxkWqW)j4T0N0S8bys19ycHip(DYgSvOBYk7N
pzcamfjWVKOjec2OLqjxWBCrEvExXe4pNIUeSVaA5YUCg(eoqVjANC8PzDzBCsai478IfItb)oNkieay
bsLkHidDwFjwIcg6YgyxMqIGXAktTDpvKTXhctYw6MmzxHGly0is(WtWMD4OEEYEpHTttLcsAW)Rlfrw
OfxNnwMYm9W7MWDg(maigbe4esEFMbptoAzkgaOoMB6YLacBocgsr(ZybocMvHmEb9ctbukb3dGl4cem
AZ2PqcpEyYUqYWhwWf9EeHqO2LbHgllCumWcye1LsgKQteuabH)8esDDaXfHPijgeJbgVDtfRXsIMwVb
GqydrXyZKzsWqVXqYviji4DQalWhfjmGAe80jwYrJiuvYHINGoFoykzcVC4XXRYfdtwrsjyS0jqFdIDt
8PHeFrAnzkie7PtEYt7rGLItz6ObjBNkXasgi(aBtomfzEgCtzczFKaVjx8kkv8b9(iFTkXaHiTIxTzG
Wzd5ITI9zHqGIZPk4emUR0l0eehzcqwwiEX0jaeaMrc2bzSmba0TFpjLeyXKaEbKKAtgpEm4(ybMtra)
80emLqs0Ne0XDgCChDBTKsiH0tep46bVnEacqaGVigSOKfscdEaWG5KjqpriAweATI8lWqrGjI6fV(0X
3S)MFb0XVhupd4ZM9hV)Y8XR3rkhTxT5hMpS)UxdMbH935UAZVGQu)Wlp9Mp8YlOw3V)41ZNpoFbwamd
qUBJ18i7JIGTZ93Tdnv9MlSXIxC6vNGv(3E8J(3p6RF0lE0p9OTp67E0Nt3u2S525xF63FZ8XBaBV729
oe1az0nBE2VaMzoCypctF4LF785Z7V)eyc8h39B7o8HxImsdiXS5zNU5baAU)W8XxJgK2F49O9PDZeGN
aJPhUbCb6ZMpddF9myf790Fba4VB(WH7zu67p(MhysXeOvCZpdB2my0e5dW94nBoE63F1Ht3F)P7(Wl)
L9hoq(b934tf2cpGn2eCvfCk5MhUhHnqN3MT3E(0XD8jS92hoc2uXZgUJ9jjwF1H5RbVE(67E3(Z4r84
)4)9ZoF6YT4bmbx4G9eNpyKDpsYEgpRkGu(C6wmydC(8BrtVO9CyoOSosT2oFCEgg8F(WXBoSdbg4o1M
x8aW9zW8hpD(1Z7oJuIOhOe)0dxWTgfOXT9FdU4GoL8StNbFbG5aA8aBX7pGCWVeXsaC(xiI(Qt3G8sq
h5MNEEgClarDhOQEZZF)NnFaqP5VqeL(153siZt2F59eGMy4)2DGFp4EU)63U7cE7Zbe1VB)n3EhimIe
e4Q)M)5PZaLfyLlPdzKEH6dy61VoJGeDiWuq8gmvIuJ)y(3ahTua5x2boy)A0vQZ0b6SWv6npb8f7YBg
oaR9ZrQhXYF1UZNF4EDtyjACBEY5hUE)RWJlcQs28CGMD75DeX0nbB8gGMbuEynpD37UClErc0k)PLn(
UF7Xaiii0zcq(CAVIWEHYlcp8X3F9UJS0mGNbIbCdkkG4oEkoNkiXalTv0Ph)0N(29xqjN)2)6aqkzjs
hACL3ONV7AyW9xtCZD0FQ)g2JVaxfUd8Ae5BtOcLDGKg6e5VU)asrB02jwyh41BE7(lxeg33D6WHt)(Y
5fP5zqTi7aPsAwBU90z(4boZpd3tFyhY6WBKGjHnBaLwh2bhkbzeOal)xVD)9VtoMxSB3B6y0MpNOmLp
nLb0M(W5B4BR3bFEChrBad(BE2(7VieGT7pJXQT569GycYzMq4z37E4a4f75fAw)M9Gd4F4L)0rMxbMV
apAH)VVqtBd4zoAJavt9vZxUCq0V8uqw(mEXIuXaA5z(YJ)JhqneK2BA380Fa0Blh5ppV)iTIkN80BV9
bq69NEZBqPOFJ0saM02813TdI4cvYcAxVdXGiUzNoFZTqmgOUaGR(D7oC4nKsj42mOT9GQu4RoC6eS2V
bipZxJxjalMB2U7U3Tdrww1pSJOoMz4y2bkbFcC58mQicvi81VF3cA0giwugeaQdiroF38XVenoCZ81V
xO3VNPeaJ757GiPMptkMDoKWD(0B31UqaJ81uyshXaapEZRpDhs6rlQv87lWGc)9og1tNV74UxtwtO9e
0CV74T7XWezHvu(c1b9DaIC8(FNianjlhPbjGAqUB)5xFE((73Fq1Iq04p7ECNEhQ9od(aT5Xhb0UPP5
RaAjjZY2ziaXIAZFfqc(X9VbMYpF6ejMhdMrg4VpJkBtGxGB(HhoqYNZ0ncWVpWQ6Hlib6jZVFjiNiqg
bLV9mzVLVk84xd43fqqRltfuAk0yXGpVdJ96NpV)059x2l(zKGWuyN2avTjX5uWRfVL9uJMGehtXBx5)
o6YKJ9EdCw2w4j48oXNkAQ8GOhDIdKGFNsqlGAc4WK)UXgBZmupu2ZwleRxscvqCxN8hlLLZNMqOnkp3
GZyeOYoLGOryaG8r0sba6J56rj4peAwwgmbrVLRtnzeSoemYov8sqxGJ(LPKI)rtfvKJknjrjcEUg14e
YbjcwqpOxijqCeHqBMIR)smh4Nrp46f)jeOJRnOqtAXec)1jjesiKjDWIX6DTp9TPkyIV4YT)UqtXy54
niieFiS380KIXAmkaUZtdc1Sefp7doVx2CG4kYoaukhoshCv6aprW7bReVrsywGXMS8z2i)t5aCu4Wwk
EckQvCxNIgfaGr9nwIezrbIwk1(72kaMRKenyk8V7AJYFgl5IiMHXSkhfiZyKz6t1GZH4ov2Fj5B0kr4
1vkIGoTkxLSixoaEQq2WJsWEieLapyYyLGVCPGE5aijg5Eylflj4AUs)bRyc9VysL2EQY(znWmmAut70
fYtlPlHjvlr2NeQpgoSWTCzi(ZQGIifbHDPBe8NfOttlcnZOS75kffjiI6kiC0sd4eDeAIbycIQIkeJn
CxadNX6Ac(YntqVHtUdqFMAtGH0OGqrjvsjFsKwDLjkQAllvKRKLC9KfsvqvJIKcNIQwbPJGlTXkUgRN
sQ9NvXaeV4zw8gjBhiAxj069hu4vWfuoyXGzfxNeonOzvunr)DERk5OO4dHKgplLQRzQI5LkCuLXfcTM
5iKIgxM2NyOU5Q6zvCJ(Z52IeHSqPAvWzfY5uwfIqKu2Dnjp8EA51a318U2Yz4Sm5mn4OkAXr4JuEFst
2iMPkr2YNc5fJkqkoxHkdCtL3jj4IOjzNsMbljcRjK1RG2fCEbNktkIylGjL6swU7AYcb0xUKum6DmaP
JQUWsmPgyYGOVkLhYI8IfeL91ZNrpqwkQAOZA(qHperWmyMW1guvqeJb56biJj0ja8KRyXMXD04JAr3P
gQq6qUchTTxPT4mz4mwk1RWWGmYvtUlJN5wM3ezyKqjGh8Vmn0l0MP6gJ1nvVRMBUz4vro8yR6eePpm3
ytTzQK0IQthZLudvuNBaaWk4FiR(eGd2GVgQkYjG8O4zdntroEQ0iPkH0QYGHw(WrrhD12ySjfXNdi6P
Udi5CJNPrOtXGYgO)UvPyr11eypJnOt151Ymiau5gzu1uzJvdr2Mjziak9tVrZYyn5SW)bCctgfoRMxy
WTgzvOSg)jC1CsvMMevy0utT)EdXvf94NvdO61dqHJtDpdCKmvDPnP0lPggi66uxcbfRQ)f5GQ(HYpBO
TiHC0uQbgoDnQHQhPDRxtWlUZGReg5uJb1RdCvtTvT4aeZw2O4jEYyKRfwqjVPU9IxxGRsbF7YCUAqv1
0G31LpNcv5EPip6NkUKT52GtviPbEXflseIZQ(TATzynmQEwBOAUdu0RgwlvfKbi8E11cW)wrXrXw0in
arFtBvX2uJvam3gKbq4ENPT8q7plKxhW0STrNAJkm4IUtWLu96c8Vuv9UQPaC5LkGi80iCM8Ia5a1mlU
8gGkUtrNPAFaavBBUYbaMSlTZs0gHv3qelbDmL2mlTzwDYOwjaxZfu)utuvt(pTkraXdboKAtOHc1cXb
(T7Blt2SeOtsJGe8ki1MGW3AvitR(OoHfNMgVLYyqY9ceRXdRUtivbtMWuDRSQqK1xAsoQVfyH2cTDyQ
nABUQ1fCu1BwVvSefSzvIeCnrKtOPkxjaLIXgKR0oTaFWNLGt9ocIZl1gCXQ0TDQA2fMGZup2gBqupTO
2x5OBbLr55Mjn6ya(erkCNuDEQjgAnQ9zGAk70KrDQaGKSsU1AOEvTCr6oaOLJCxoT4MUAzjAuKf8ulP
UcfN0dguKMwcoT7c1IgXv4eh1uJqg1w2aHMvix1FaW4O6aOjAAerX1hejuJaPADpXIdRoUvsvrMKTPzq
aGmW5LXaDjQRlGgmtUUirGaIKslmMbwMQ43QYEGJtknwlhnQjqdIPvDsVjRQOHqWvDfAbTPpvsfcOc3c
U0Q)9yS6zjWwuXPCmBm1D112QC9uvdlart5fW9qbRaVr1O1S1mdGRxK8bNefjlWLfnEyGMeAg(KThuRx
nMhebpGowAAq1K1axmftKWo5ufyGCznIm4BzuqsqVLwSE13nRMUc4RsOTOyDr1CrLDf1YmSi1gFUw05G
MHlcRwSxtv0Y2guJs1QsIqWD22IsMkgQUUGHWSGSXqi6dJSkSCOvFVdfFD0PkgOjUdupl56bIivZlxle
j4cssDsqApeCQPI83dOV)P2QMA7F9gKtbaSy86YMmj1buUng0dR0MRQ4hItAXOvfcv1egNxGbeBejVj7
u1nhxOTgBDtNwmQOFh4b(gyhR70IZu(7GgDtfMuTyGSqnitmpMkmvZVc4Bw1cvqJRhxL6DQVLq4KBXwj
et4MHWId10BqqLQpeOe17B2uJQLDnii2wwUnbncjqkW2MWuDFJnrhbDqeBXuxCycIfllScRjusBSf8td
OZlvxMqqZovNf93fqeBbhHkA9(A2cmAURO52aHAgULo3bPyPCvTjO3PX9McT5kldNQPb5n5xjGcWeIrU
2SOnhGB92QB4f1XiNQJcSOVeAJnXpnqhmsxrfbetR6mteMTydQ1JtPutsTAKWL9IVD0Iwq7zQO0Tl2RQ
TjHfZ1Nw6bWD(ORjuP6B12OaJOr3jqo1yxSvlavvQ2vxp83vdRGbnxB0yBvQl54PjqGQUdotnvd5A78q
BLSRGarOXb0liz1NheQl1zkn3e9359poL0YGaSn9c(uXe07erJAKiQzhI(7H2QeSwARl5tFfa0C6aouR
2lHpSvSokEu7qNVfblF1HzAcnquD1hCDPgFWufWmWru9iwDCdpnvDjoxRSzLOoxCZcTttfzlAiAabxLy
bnRIyaIz(2Uksb5OQM0hSkThmvlmzQNQSYMMkQaDnfzOyCn5Ss7xr3iuNUILIKAlSTb1aVH4YSU2Q8Tj
OYHP0cWwK98TgHmvPBydnYhqmwRWfq4fPmQj1eCblNKPnQmbqKs1ZBInhQv9AsdtQJkmzST1c1junvZn
wi(PhUDlBlMVGsBzP2Nl2m5iafC1qKsr1ZJClzv5GERuBcoHYWtf8SQ2Vya)sckbUlzxCTXuJLqdKm4l
wvfG0Rw4(z8A2EWo5t0NQ9qgTzslKDfvXbv6kgQ9BNRMBRsrTf5xKBEJAmd9Yq1cJ76uBQQ3nbXleYpM
sBQL2uzYrwTOeYtcdhmK5QPsiRAlOpzch4UuRcvMQkGurGuWnuTev02kewSWDvzUgaknv5vKt3Ah(bAB
0IH6KUlLSnuVjhQrXcbQKA7ALFRPGcuxhIlG2QUzRPAopxtnn3pF0(61u(s7BqxMwHcqlSMipW)WGMgC
GCKuPwBuCwKIxtMli7OUNG7RktvB2scExGMY(61QTO9wiTbf1zmG2QQxZ1CwH(IjQEKEqeh1cYomlnzv
N8rFKB310fLdQ9pTZFXRAgBZ(xT(Eatw1XK1eJaKvTGejqBq1njFs9nAsRtUTQoHIYt)7G9hDd8w1dIO
vDhh4NQZ2GJGQjd0z7KURcsBHl1QzIs1XhWWGgMwThMVcJymRXjv8QQaSzELPIP1i1MQWxXO)OVKMELX
fn)g0mfVPDEnRUGM9OVQW0xRM9KxB5xqlUcwsVGk0OM4FTCirGC3UFR6zXlc8rmv7VaaAeRtOQMQ)2b1
xyPvKrhmZgTIDabo6Q3FNQPoArtjt9Ihp3ADZqRlQrxVw(uABB3UupvtyNBi7L0PS4CltvRsWYK7gGBe
UQpHQCaId8FVaXhQBLrz9iHvyctOJo8obU5wZCSxLUrtPkpa4IjfusIf(AF0F1ZR928vpx77yN8zQHxT
ji8l0pinZaa9U0om1KJVgUS0T)8NQ5jmOq1R1SMrkh4VGQzL7CDKlgaetTIO1geuefe8kzmlLhwOoUkC
Q5BGk4OqnI1YBI5dsR(PPglk3x5UROukR(qXTnpU)ONQYTRwhHtvWxNGtdgLQUQifpTiN1Q6pqNMx)Sw
ByIdWBfetzTu52AKIibqVrvZhl4CPg2mDavMHxalWCHQ)f8rtIbcaKAHGNcUf(Ql8DB1jnBkoPz5afbQ
6vDTVCYjL0W5GtQ22eAIYX63PomaXi6AZ0kGVXh0Zu1VJwW0unu8AhcGvwx1)c29eEf4Gv7VxuFuRDHV
8QaCmttdBemPzBIAIpWG8LatacNQM0up5Y10B4ADiaO5YvtaH2toalj4RUwOvjhbur5Rv9IbnD2SDAuZ
(18mdM9RfQnRf03VWvup1XHcqPfIg8AU2QfKIjEzfLJIz5vnPGXcV4tRcR1K0cms9yD16thsYr1EsfEt
kud8O5DlOll32tHMJw3LnDkMRgxYAQyO5QYKUCQcv5ACwET8wGKsufRcANTGkwlTDvylEx15w04K4Bji
SiEAuuTsuBy0C1O66g2QsnKLHQfVOcuSsZZlQmr18dKibVawNgrJZvtKQrT5HaRsTHGBu3NJfTydipix
9RQOnEaeDzvGWQbvIj8qV5f00ltBlVQiWKeeV2(FG0APTLIhwGA3AZwzRPpkwBusSz3u7D8lLrGuj9X0
zkaDr78g0n3wWDUqtgqCRbBUjTgiOMtX0J6haydu9i3w5LOWAtui32YQTOwQ4ST7DQDZOQELWEvvCjRD
)IZOXzamunfQeKuDs3PMqGltARvHA4u9sAYCOTLxfQ)uwutbicacM408Ddc9Mf18vzzGMq(GaLscsH6k
ejz0QUqCqD(ICgyCq1fawLLB6yyI86JAbDT(LvZqtoeMPlrgZLZv3T8Q(tSeocchY1squl7iI71ih9kH
gyyAIQGJVDnQ6ClwTdH7LQe3ItBjhKJRj)PO11bLsRIg6vpkBjv)6k1YvKRM5aAkYOryeBEkHO61EQaZ
FVOsa7uF1KxrK3bDRv1mvMdYgfBVyUNeNnJAVVaQK1IG700JGDBLwbgVgPi5eXc)bK7nwVT2Ub100r(P
P2bkHAEBZMAtCf15QDMbicfAoHO1gWKx4sQoiCbT6nqTgKyeglM6udslninwpavTfoxbORVRoW7C12mT
kE0uwJhvElKkOwfo17GOvYAQQS6TyCR0yhn2uRcC(uZHkv1M(W9y)yeR3yYf5)mE5IplSHrR67HO2lTr
RHcmvvyoLRvhiup2j1of2gh1s4xlrf6rNmyeL1vWwB(sQ9YuZZkSsBLE)ePx8gy9ACGypZQKlSpA0ybG
qLRFsgvDu3G2SDPOcyZuvj61EPeLwf5smTfAemMCTHhQDIggbJEqzTHSrUvEXXRMKGB9QlPtAm5tPAqd
z14aCfqn0JxVD1qf0UDa21IgdxrnVdiqTt081gYauve1RqrT)ZOkXR3cmAZ)tb)gRedJkLQgsbRJASq6
JGLZpU6Ooyriv3u1P62RSfiMX2DC9KGqzmvZ8MMhOPQhOU0czycxUC1MZpCqF7L8dW8z4ZL4dV8)(U53
9Lwig4V4(hE1D7oFZUx))8HxE3LV0XUrxNN(ao)sqCxMbExY3MXU)ZLZZFj6hro)fhpTC)2)6VKA18Wv
B(X93T)YMD0rF61F5HRVC(amJx8VE(v4lisGU)0zbOZR539H8CpEp9gBEZH5BEYTZhVHru5zwS9QnFZp
(FD1M)bU9sKUDJXDglmeU58qs7QVEPU(XenYDJj3W6gJdLTFPCYFwVDLXJLQJ7WyuEi6pwUWvDOHux31
73ailfFSBTCdxT(iIFKJyaK5c7U(ek9lvUZmq4P6RnogwOTUX42fggAZV(9pB5(Lhap(9PmGguLs7bzo
p39ukoXpdOl9olwJhdup5nQmqdW0a1pnQCL9ZIROupfGFDfdYku6265zC)U1dD8dRPNcqVML(ProyoGd
uli0VsUdz7gJFrfRzJJac36)DJX6DxjP4tRfYYJ3F4xMv)8yL3dCrk231NXkjfktM9Obxx2XXMgLaKan
7pxUHr7hJSypSukXm9Gc3FGRp2bHr51l1FeC0XdOg1EWdCiQsxRHLX73u0i9hbxu0HLsTmz3y8RpQNWZ
z3BBVqlfsXadNAr2vcbtJcbCAbgL98RWmUsd9Ob)oP2oCXyupOKKRv8XHPjTY8OiGBKNjngr)yCFk2dX
CL76NNL69)(ZLdbDqwHAL3EQmNwJbuJE0v9uaouRU5X(D3FS87yQBPsRjmsKxBCLFuMBh1noGfsH(3ok
jNhLU5EpyGbrvdPhlq)khLYCJcYsNk0JyXrMnNfUEchx32bSsDpy5bqHiUD4kGBffMlg)k5UbCqQZ(a4
rDgv)sPCPUDuxU1TwmXnWdLsnmWCOaa7Xw(rU0VwUm79GILEmiduLPrPDl3FWJCSv(wXnW5aetn(XaMr
nYkm2tFXJ)2F65V47F63)8VDjyoE71sp)KHnMkN8A40(riJR4k(vYcCaRBhvlvgf75Oz3oQminADMEza
DtJ7j0EKiVIQIXbniwrj5C7497rFPKYP2gBPdzCrFxd12pcbCuEGByIHXOxP5kqFCPXvs1wUXI7GC5vY
Tskmps)kL0i9BCzClW1V9CxI3tS4iZ2oEbzDqkyHZgoIsy0hyU9lxTBRmGXvHE92T6ki18o9qcNo)X16
gD8uAF(EriU1m6gJ72WbKLENM9Bhxo(bEivcObckL3G173ajGt5)kErE0FkVBLhL8JVDa6OUFzyEuRpQ
J93zca9gk6NhLvWbi5JiPt9FzBSL3QKoN8J)hLm9SDuRWObh(1cmmgMpZTJ3mJJsIC)8VAEHYi)IAZGT
9sS5rcI8RkqpfH7zOHLMgnYljBTNf6w5Df3BK9dXncx)HsTjE)q8B6A7krZ1ERkkWwq05c51FSCbVxtI
hPjCNu1TFCwqhxAAmCcPM1B7nArDrYWryeRm9cIJQR5g5AGStDE(WsPhQ7avXSkktPzO6hJFqodR1gg9
HxEo(dsfXrx4LgVF7h96b)ZiW2r50rFfsIDUfZIZl72rX0rLJsh6pkEewLhbUPVwjbUk)s07azGoqV64
bPnQck9ZJlcy3y8Vch9hb3mR9yb9Q)6L)8YvHfRK7f7vu6)oZg08cTGisDy4aaLdJXiY)SnSgihjHC)t
3tc5oMCGnf8Jmy53GIrOBAumKFfrdGcvm(1G3O1z6N3J(TJ7cI1IFRILmpQ5ukqD)yOp9dNa3HHJtZVI
rSkvhCZc0t4CUvjJK7TVEHf6hbI(9NBp5(dG7JYb6Byv82Crn32RaJ(9Qz7QBgR81Dv6lKFvD6xk)cw6
MhvRVEYgxvNTJ6wYFejEzb0dDQhICRY(O06BdqevO3EYk)l3t)84(uPBm(huMHTRKwLRv6bvTs0BL)0C
d3oYLgttR8o232RdI60V(JGFkI9ZJ)nzOhI5I1UwGzLVSuFMnmpQv96P75vUuYVQZEsmv5XTR0PVkYX4
Qyo56L1pg3U39Nk3GMB)ObDk)MkmCwuJ42tC4M(DB)vcQfm7hJ)5dAaaOAmnSFujUhj2RciGFC2d8D6b
lnak0Z9UFECrS6pw(LcoaYu3i3FS8JXAGEtphHEzl(5x1pg37S9YB0JoOBACfDh4EAUz7SCSsYx(jbyn
xU8P4Y8lwBaDsRS1iV25E0HR1y)HXfDC7hvhKLF)FdBmvfYriUWYQFeiwE)z9lGF5w9yb)IywrzhuUjp
JQbrqJFmVTYVrjdYw5(qY6u4Yny2kbVrTRCZ71n06KlW)WcTcNhfMKE8VNaZnUCpYWVF5beKAjJEAi)q
(7pxU)QgP151fAe)PMQxGH7nPHJnVYnb(hBJXXMwPrHFmO9hb3OORW2Xmiz530z)yCxW3t9OFmo2oOeE
1vbPhjxlaUUIAHvoas)iGmWBZRceG7WSrIsy0Ue3kXdah1(Q94f)gx6He(TH2Zf53A92(Rh0BYA8msRc
DI)TGBKDVU4r8pOHBxP2EmoE(hqITJkb9JeEUhM7HfUbi7hJ7T(rUrXSkxC5vPRx6YV(5XVG9rwKBvn)
4hc3i)WmkZZ)8R0tw4xkz)XYTV6aitT322bRuUX8hYp08Eoo)G2gWcQz665KCBN1pg)RDWGua1t)JsbR
sna)dd1iZWTU5c8sa0duLXaTPFUaggYVY7m(H43lMX91E)s5F9m7PX8VEnRf9gUwz5xkE3zWDpvpRGFx
CB)4MPDIxcdiDyK3fhdMK(1o)DVF785B2D5EQxyU6v6V35x(PJhE)Zo9B4))vJVIM8LRU6)7

**Comment by mbattersby** [comment]
This isn't a bug, it's just how it works.

The default mount action is SmartMount, pick the best possible mount from the available mounts.

Your rule limited the mounts to only those that can run, but this one can also fly. So it will be the best possible mount in a flying or dragonriding area and always be chosen. It is not "limit to mounts that can only run and nothing else" but "limit to mounts that can at least run".

The rules don't affect how SmartMount works, only what mounts are available to it.

If you want to summon a ground mount ignoring where you are you should probably make a rule that says "Random Mount" -> "Ground". You can also change to add rules that say "remove all flying mounts" and "remove all dragonriding mounts" if that's what you prefer.

Happy adventuring, X.

**Comment by coden1ke** [comment]
Ohh okay, understand it now. Thank you for taking the time to review this!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
