### ISSUE TITLE
SUGGESTION: Goblin Glider Kit

### ISSUE THREAD

**Issue by Antorinia** [xod-wow/LiteMount#222]
hey hey, can you add  109076 [Goblin Glider Kit] into your base macro?
![image](https://github.com/xod-wow/LiteMount/assets/130331287/e367d9f8-4e4c-4d06-83af-19cb76a66115)
might help someone someday
gr8 addon <3

**Comment by mbattersby** [comment]
Hi, thanks for the suggestion but I don't want to add a consumable in by default as people might not expect it to get used up.

Also the falling actions often trigger by mistake if you are jumping etc which would just waste them and put them on cooldown.

It's pretty easy for people to add a rule to use the item now, but hard for me to help people through editing the action lists to remove it if they don't want the behaviour
