### ISSUE TITLE
Can't Soar when swimming or in Tindral Sageswift boss fight, need fallback

### ISSUE THREAD

**Issue by F-Lambda** [xod-wow/LiteMount#224]
When swimming, dracthyr evokers cannot use the Soar ability, receiving the error message, "Target is not on the ground". So, SmartMount rules should automatically fallback to regular dragonriding mounts if attempting to use dynamic flight, the same as when Soar is on cooldown.

**Comment by F-Lambda** [comment]
Likewise in the Tindral boss fight, the Empowered Feather buff only enables regular dragonriding, not Soar.

**Comment by mbattersby** [comment]
Oh dear, how incredibly annoying. So Blizzard not only didn't make soar quite like a dragonriding mount, but they also removed the part of the spell where it goes unusable if you can't actually use it. Thanks Blizzard!

Thanks for the heads up, not entirely sure what to do about it (especially the Tindral case). I'll have to think about it.

**Comment by mbattersby** [comment]
Should be fixed in 10.2.7-2. Please check it out.

**Comment by raptormama** [comment]
The fix works as expected during the fight, but Soar also needs to be excluded post-encounter while transiting from the final platform to the midair rift that leads to Fyrakk's arena.

**Comment by mbattersby** [comment]
What happens in that circumstance? Soar tries to cast and you get an error message? (I assume it's not one about being underwater.)

**Comment by mbattersby** [comment]
Also, if Soar needs you to be "on the ground" does it fail to cast if  you have levitate or zeyphr?

**Comment by F-Lambda** [comment]
> What happens in that circumstance? Soar tries to cast and you get an error message? (I assume it's not one about being underwater.)

Yeah exactly, you get the soar cast noise for like half a second and it stops
