### ISSUE TITLE
Request: "in sanctuary flag"

### ISSUE THREAD

**Issue by polski-g** [xod-wow/LiteMount#23]
Would be nice to have a flag/check if you are in a sanctuary for the advanced macro section. Why? If in a city, you mount your nice looking mount. Otherwise mount your utility mount (Sky Golem)

**Comment by mbattersby** [comment]
Sounds good, I will add this to the [pvp] condition I think, which will add:

[pvp:arena]
[pvp:contested]
[pvp:friendly]
[pvp:hostile]
[pvp:sanctuary]

**Comment by mbattersby** [comment]
Added in LiteMount 9.0.17
