### ISSUE TITLE
TWW - Not Working On Druid

### ISSUE THREAD

**Issue by meenie-1** [xod-wow/LiteMount#235]
Here is the LUA error:

Message: Interface/AddOns/LiteMount/LM_Spell.lua:57: attempt to compare number with table
Time: Sun Jun  9 14:27:57 2024
Count: 1
Stack: Interface/AddOns/LiteMount/LM_Spell.lua:57: attempt to compare number with table
[string "@Interface/AddOns/LiteMount/LM_Spell.lua"]:57: in function <Interface/AddOns/LiteMount/LM_Spell.lua:48>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/Mount.lua"]:103: in function <Interface/AddOns/LiteMount/Mount.lua:97>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/MountList.lua"]:120: in function <Interface/AddOns/LiteMount/MountList.lua:117>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/MountList.lua"]:271: in function <Interface/AddOns/LiteMount/MountList.lua:257>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/Actions.lua"]:426: in function <Interface/AddOns/LiteMount/Actions.lua:416>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/RuleSet.lua"]:65: in function `Run'
[string "@Interface/AddOns/LiteMount/ActionButton.lua"]:75: in function <Interface/AddOns/LiteMount/ActionButton.lua:29>

Locals: self = <table> {
 flags = <table> {
 }
 name = "Travel Form"
 family = "Shapeshift"
 icon = 132144
 spellID = 783
}
(*temporary) = <table> {
 isEnabled = true
 startTime = 0
 modRate = 1
 duration = 0
}
(*temporary) = 783
(*temporary) = "attempt to compare number with table"
LM = <table> {
 TravelForm = <table> {
 }
 Mount = <table> {
 }
 RuleArguments = <table> {
 }
 FLAG = <table> {
 }
 MountRegistry = Frame {
 }
 MountList = <table> {
 }
 UIFilter = <table> {
 }
 ActionButton = <table> {
 }
 Actions = <table> {
 }
 RuleSet = <table> {
 }
 Rule = <table> {
 }
 Journal = <table> {
 }
 Vars = <table> {
 }
 Conditions = <table> {
 }
 SPELL = <table> {
 }
 Soar = <table> {
 }
 RunningWild = <table> {
 }
 Nagrand = <table> {
 }
 GhostWolf = <table> {
 }
 SecureAction = <table> {
 }
 RuleContext = <table> {
 }
 Spell = <table> {
 }
 RuleBoolean = <table> {
 }
 MOUNTFAMILY = <table> {
 }
 Options = <table> {
 }
 Environment = Frame {
 }
 Localize = <table> {
 }
 ITEM = <table> {
 }
 MOUNT_TYPES = <table> {
 }
 ItemSummoned = <table> {
 }
}

**Comment by mbattersby** [comment]
beta is busted for me right now (won't update) but I'll have a look when I can.

**Comment by meenie-1** [comment]
Thanks for the reply!

**Comment by mbattersby** [comment]
Thanks for the bug report, please post more!

**Comment by meenie-1** [comment]
Working great now! Thank you for the fix!
