### ISSUE TITLE
TWW - Adjust for skyriding/steady flight

### ISSUE THREAD

**Issue by mbattersby** [xod-wow/LiteMount#236]
Probably a lot of stuff that needs looking at including

- ~flags and UI for flags~
- ~default SHIFT behaviour for downgrading mount type~
- conditions for which flight type is active
- ~actions for changing flight type (maybe)~ "SwitchFlightStyle"
- ~default behaviour depending on flight type~ not required
- ~detecting (if any) mounts that are only steady flying that don't work if skyriding is on~ done by mountTypeID

**Comment by mbattersby** [comment]
The new continent has steady flight disabled until you unlock it somerhow, I think at max level. Seriously Blizzard?

Starting out, IsAdvancedFlyableArea() == true and IsFlyableArea() == false, which I assume will switch to true, true once you unlock.

Not sure what happens if you switch to Steady Flight without it unlocked though.

**Comment by mbattersby** [comment]
There is an unlock spell for Khaz Algar Skyriding that you get from an early quest

**Comment by mbattersby** [comment]
I don't even want to think about making Tindral Sageswift work when people go back there >_<

**Comment by mbattersby** [comment]
Blue post says (below) which I should check.

> The ground mounts in your collection will continue to stay grounded, but most flying mounts will be able to be put to use for Skyriding save for a select few such as the Otterworldly Ottuk Carrier, some fish mounts, and brooms.

**Comment by kayti-wow** [comment]
https://www.wowhead.com/news/the-war-within-pathfinder-requirements-added-how-to-obtain-steady-flying-in-khaz-343641

**Comment by mbattersby** [comment]
Thanks, have you completed this? Is it account wide? Can you send me the output of `/dump GetAchievementInfo(40231)`?

**Comment by mbattersby** [comment]
Does IsFlyableArea() start returning true in Khaz Algar after you complete it?

**Comment by kayti-wow** [comment]
This is what it looks like before it is completed
![image](https://github.com/xod-wow/LiteMount/assets/54023126/eefad00e-e099-43d4-9547-5545f69e4db4)

**Comment by kayti-wow** [comment]
Unfortunately it hasn't awarded the exploration achievement retroactively so it will probably take levelling a brand new character to collect them.  I don't have the time to do that right now.

**Comment by mbattersby** [comment]
No problem at all! I don't have the time either, I just thought I would check in case.

**Comment by mbattersby** [comment]
Note to self: don't break classic.

**Comment by mbattersby** [comment]
It seems ok for now, I think later I can probably remove DRAGONRIDING if there are no mounts that can't only steady fly left, or I handle them another way.

**Comment by mbattersby** [comment]
I'm gonna leave DRAGONRIDING in, because people could well want different mounts for it versus FLY.
