### ISSUE TITLE
TWW-Not working after last game update

### ISSUE THREAD

**Issue by meenie-1** [xod-wow/LiteMount#238]
Doesn't matter if I'm indoors/outdoors/moving/standing still. Same error as far as I can tell.
Here is my LUA error:

Message: Interface/AddOns/LiteMount/LM_ItemSummoned.lua:51: attempt to call global 'IsUsableSpell' (a nil value)
Time: Wed Jun 12 11:16:24 2024
Count: 8
Stack: Interface/AddOns/LiteMount/LM_ItemSummoned.lua:51: attempt to call global 'IsUsableSpell' (a nil value)
[string "@Interface/AddOns/LiteMount/LM_ItemSummoned.lua"]:51: in function `IsCastable'
[string "@Interface/AddOns/LiteMount/Mount.lua"]:103: in function <Interface/AddOns/LiteMount/Mount.lua:97>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/MountList.lua"]:120: in function <Interface/AddOns/LiteMount/MountList.lua:117>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/MountList.lua"]:271: in function <Interface/AddOns/LiteMount/MountList.lua:257>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/Actions.lua"]:429: in function <Interface/AddOns/LiteMount/Actions.lua:419>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/RuleSet.lua"]:65: in function `Run'
[string "@Interface/AddOns/LiteMount/ActionButton.lua"]:75: in function <Interface/AddOns/LiteMount/ActionButton.lua:29>

Locals: self = <table> {
 flags = <table> {
 }
 name = "Loaned Gryphon"
 family = "Gryphon"
 itemID = 44221
 icon = 294468
 spellID = 64749
}
(*temporary) = nil
(*temporary) = 64749
(*temporary) = "attempt to call global 'IsUsableSpell' (a nil value)"
LM = <table> {
 TravelForm = <table> {
 }
 Mount = <table> {
 }
 RuleArguments = <table> {
 }
 FLAG = <table> {
 }
 MountRegistry = Frame {
 }
 MountList = <table> {
 }
 UIFilter = <table> {
 }
 ActionButton = <table> {
 }
 Actions = <table> {
 }
 RuleSet = <table> {
 }
 Rule = <table> {
 }
 Journal = <table> {
 }
 Vars = <table> {
 }
 Conditions = <table> {
 }
 SPELL = <table> {
 }
 Soar = <table> {
 }
 RunningWild = <table> {
 }
 Nagrand = <table> {
 }
 GhostWolf = <table> {
 }
 SecureAction = <table> {
 }
 RuleContext = <table> {
 }
 Spell = <table> {
 }
 RuleBoolean = <table> {
 }
 MOUNTFAMILY = <table> {
 }
 Options = <table> {
 }
 Environment = Frame {
 }
 Localize = <table> {
 }
 ITEM = <table> {
 }
 MOUNT_TYPES = <table> {
 }
 ItemSummoned = <table> {
 }
}

**Comment by mbattersby** [comment]
Seems like Blizzard are continuing to move API functions out of the global namespace and into C_Spell, C_Item etc. A bit of a moving target, I'll try to fix them as they come up but I can't anticipate them in advance. Please keep reporting.

**Comment by mbattersby** [comment]
Should be fixed in beta3 thanks

**Comment by mbattersby** [comment]
If you get more errors like this

> attempt to call global 'BlahBlah' (a nil value)

the will be the same thing, you can put that in the title as what's wrong if you rememeber.

**Comment by mbattersby** [comment]
(Other than when I have time for addon development I'm not playing the beta so I generally won't pick these up very quickly.)
