### ISSUE TITLE
addon doesnt work since 3 days ago

### ISSUE THREAD

**Issue by borgepitza** [xod-wow/LiteMount#239]
Message: Interface/AddOns/LiteMount/SpellInfo.lua:78: attempt to call field 'GetSpellName' (a nil value)
Time: Fri Jun 14 16:09:08 2024
Count: 1
Stack: Interface/AddOns/LiteMount/SpellInfo.lua:78: attempt to call field 'GetSpellName' (a nil value)
[string "@Interface/AddOns/LiteMount/SpellInfo.lua"]:78: in main chunk

Locals: _ = "LiteMount"
LM = <table> {
 WarningAndPrint = <function> defined @Interface/AddOns/LiteMount/Print.lua:95
 Print = <function> defined @Interface/AddOns/LiteMount/Print.lua:23
 SPELL = <table> {
 }
 PairsByKeys = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:43
 FLAG = <table> {
 }
 PrintError = <function> defined @Interface/AddOns/LiteMount/Print.lua:29
 Localize = <table> {
 }
 Warning = <function> defined @Interface/AddOns/LiteMount/Print.lua:91
 TableToString = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:171
 tJoin = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:56
 tSlice = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:35
 UIDebug = <function> defined @Interface/AddOns/LiteMount/Print.lua:82
 Debug = <function> defined @Interface/AddOns/LiteMount/Print.lua:45
 tUpdate = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:71
 CreateAutoEventFrame = <function> defined @Interface/AddOns/LiteMount/AutoEventFrame.lua:24
 ITEM = <table> {
 }
 tMerge = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:81
 tCopyShallow = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:29
 tMap = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:15
 GetDebugLines = <function> defined @Interface/AddOns/LiteMount/Print.lua:34
 TableWithDefault = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:179
}
L = <table> {
 Skitterfly = "Skitterfly"
 LM_PRIORITY = "Priority"
 Shardhide = "Shardhide"
 LM_HERB = "Herb"
 LM_PRIORITYMOUNT_DESCRIPTION = "Summon a random mount. Uses the priorities/rarities for summoning mounts more or less often (or never)."
 LM_DRAGONRIDING_AREA = "Dragonriding area"
 Deathroc = "Deathroc"
 Hivemind = "Hivemind"
 Salamanther = "Salamanther"
 LM_GROUPS = "Groups"
 Charhound = "Charhound"
 LM_LIMIT_MOUNTS = "Limit Mounts"
 LM_EVERY_D_MINUTES = "Every %d minutes"
 LM_PRIORITY_DESC3 = "A lot more often"
 Mechanocat = "Mechanocat"
 LM_DEFAULT_SETTINGS = "Default Settings"
 Mechacycle = "Mechacycle"
 Drake = "Drake"
 Goat = "Goat"
 Bakar = "Bakar"
 Rylak = "Rylak"
 LM_PRECAST_ACTION = "Set Up Pre-cast Spell"
 Dragon Turtle = "Dragon Turtle"
 LM_RENAME_GROUP = "Rename Group"
 LM_LIMITSET_DESCRIPTION = "Limit the available mounts for all later actions to those specified."
 LM_EVERY_TIME = "Every time"
 Bonehoof = "Bonehoof"
 Wasp = "Wasp"
 Corpsefly = "Corpsefly"
 Basilisk = "Basilisk"
 Wyrm = "Wyrm"
 Eagle = "Eagle"
 LM_ON_SCREEN_DISPLAY = "On-Screen Display"
 LM_RESTORE_FORMS = "Try to restore druid shapeshift forms when dismounting."
 LM_DISABLING_MOUNT = "Disabling active mount: %s"
 SWIM = "Aquatic"
 Courser = "Courser"
 LM_NOT = "NOT"
 LM_PRIORITYMOUNT_ACTION = "Priority Mount"
 Panthara = "Panthara"
 LM_DEBUGGING_DISABLED = "Debugging disabled."
 Bloodswarmer = "Bloodswarmer"
 LM_SEASON_WINTER = "Winter"
 Hand = "Hand"
 LM_FLAG = "Flag"
 LM_NOT_FORMAT = "Not %s"
 Core Hound = "Core Hound"
 LM_CONDITIONS = "Conditions"
 LM_ERR_BAD_RULE = "Invalid rule '%s': %s"
 LM_GROUP = "Group"
 Devourer = "Devourer"
 LM_PREUSE_ACTION = "Set Up Pre-use Item"
 LM_CURRENT_PROFILE = "Current Profile"
 Beetle = "Beetle"
 Murloc = "Murloc"
 LM_MACRO_EXP = "This macro will be run if LiteMount is unable to find a usable mount. This might be because you are indoors, or are moving and don't know any instant-cast mounts."
 Crab = "Crab"
 LM_LIMITINCLUDE_DESCRIPTION = "Add the specified mounts to the set available to later actions."
 Felhunter = "Felhunter"
 LM_PROFILES = "Profiles"
 LM_SHOW_ALL_MOUNTS = "Show all mounts"
 Dragonhawk = "Dragonhawk"
 Ram = "Ram"
 LM_RARITY_FORMAT = "%0.1f%%"
 Slyvern = "Slyvern"
 Brut
Message: Interface/AddOns/LiteMount/SpellInfo.lua:78: attempt to call field 'GetSpellName' (a nil value)
Time: Fri Jun 14 16:09:08 2024
Count: 1
Stack: Interface/AddOns/LiteMount/SpellInfo.lua:78: attempt to call field 'GetSpellName' (a nil value)
[string "@Interface/AddOns/LiteMount/SpellInfo.lua"]:78: in main chunk

Locals: _ = "LiteMount"
LM = <table> {
 WarningAndPrint = <function> defined @Interface/AddOns/LiteMount/Print.lua:95
 Print = <function> defined @Interface/AddOns/LiteMount/Print.lua:23
 SPELL = <table> {
 }
 PairsByKeys = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:43
 FLAG = <table> {
 }
 PrintError = <function> defined @Interface/AddOns/LiteMount/Print.lua:29
 Localize = <table> {
 }
 Warning = <function> defined @Interface/AddOns/LiteMount/Print.lua:91
 TableToString = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:171
 tJoin = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:56
 tSlice = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:35
 UIDebug = <function> defined @Interface/AddOns/LiteMount/Print.lua:82
 Debug = <function> defined @Interface/AddOns/LiteMount/Print.lua:45
 tUpdate = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:71
 CreateAutoEventFrame = <function> defined @Interface/AddOns/LiteMount/AutoEventFrame.lua:24
 ITEM = <table> {
 }
 tMerge = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:81
 tCopyShallow = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:29
 tMap = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:15
 GetDebugLines = <function> defined @Interface/AddOns/LiteMount/Print.lua:34
 TableWithDefault = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:179
}
L = <table> {
 Skitterfly = "Skitterfly"
 LM_PRIORITY = "Priority"
 Shardhide = "Shardhide"
 LM_HERB = "Herb"
 LM_PRIORITYMOUNT_DESCRIPTION = "Summon a random mount. Uses the priorities/rarities for summoning mounts more or less often (or never)."
 LM_DRAGONRIDING_AREA = "Dragonriding area"
 Deathroc = "Deathroc"
 Hivemind = "Hivemind"
 Salamanther = "Salamanther"
 LM_GROUPS = "Groups"
 Charhound = "Charhound"
 LM_LIMIT_MOUNTS = "Limit Mounts"
 LM_EVERY_D_MINUTES = "Every %d minutes"
 LM_PRIORITY_DESC3 = "A lot more often"
 Mechanocat = "Mechanocat"
 LM_DEFAULT_SETTINGS = "Default Settings"
 Mechacycle = "Mechacycle"
 Drake = "Drake"
 Goat = "Goat"
 Bakar = "Bakar"
 Rylak = "Rylak"
 LM_PRECAST_ACTION = "Set Up Pre-cast Spell"
 Dragon Turtle = "Dragon Turtle"
 LM_RENAME_GROUP = "Rename Group"
 LM_LIMITSET_DESCRIPTION = "Limit the available mounts for all later actions to those specified."
 LM_EVERY_TIME = "Every time"
 Bonehoof = "Bonehoof"
 Wasp = "Wasp"
 Corpsefly = "Corpsefly"
 Basilisk = "Basilisk"
 Wyrm = "Wyrm"
 Eagle = "Eagle"
 LM_ON_SCREEN_DISPLAY = "On-Screen Display"
 LM_RESTORE_FORMS = "Try to restore druid shapeshift forms when dismounting."
 LM_DISABLING_MOUNT = "Disabling active mount: %s"
 SWIM = "Aquatic"
 Courser = "Courser"
 LM_NOT = "NOT"
 LM_PRIORITYMOUNT_ACTION = "Priority Mount"
 Panthara = "Panthara"
 LM_DEBUGGING_DISABLED = "Debugging disabled."
 Bloodswarmer = "Bloodswarmer"
 LM_SEASON_WINTER = "Winter"
 Hand = "Hand"
 LM_FLAG = "Flag"
 LM_NOT_FORMAT = "Not %s"
 Core Hound = "Core Hound"
 LM_CONDITIONS = "Conditions"
 LM_ERR_BAD_RULE = "Invalid rule '%s': %s"
 LM_GROUP = "Group"
 Devourer = "Devourer"
 LM_PREUSE_ACTION = "Set Up Pre-use Item"
 LM_CURRENT_PROFILE = "Current Profile"
 Beetle = "Beetle"
 Murloc = "Murloc"
 LM_MACRO_EXP = "This macro will be run if LiteMount is unable to find a usable mount. This might be because you are indoors, or are moving and don't know any instant-cast mounts."
 Crab = "Crab"
 LM_LIMITINCLUDE_DESCRIPTION = "Add the specified mounts to the set available to later actions."
 Felhunter = "Felhunter"
 LM_PROFILES = "Profiles"
 LM_SHOW_ALL_MOUNTS = "Show all mounts"
 Dragonhawk = "Dragonhawk"
 Ram = "Ram"
 LM_RARITY_FORMAT = "%0.1f%%"
 Slyvern = "Slyvern"
 Brut
Message: Interface/AddOns/LiteMount/LM_GhostWolf.lua:15: attempt to call field 'GetSpellName' (a nil value)
Time: Fri Jun 14 16:09:09 2024
Count: 1
Stack: Interface/AddOns/LiteMount/LM_GhostWolf.lua:15: attempt to call field 'GetSpellName' (a nil value)
[string "@Interface/AddOns/LiteMount/LM_GhostWolf.lua"]:15: in main chunk

Locals: _ = "LiteMount"
LM = <table> {
 WarningAndPrint = <function> defined @Interface/AddOns/LiteMount/Print.lua:95
 Mount = <table> {
 }
 TableWithDefault = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:179
 Print = <function> defined @Interface/AddOns/LiteMount/Print.lua:23
 SPELL = <table> {
 }
 Spell = <table> {
 }
 Journal = <table> {
 }
 PairsByKeys = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:43
 Options = <table> {
 }
 FLAG = <table> {
 }
 PrintError = <function> defined @Interface/AddOns/LiteMount/Print.lua:29
 SecureAction = <table> {
 }
 Environment = Frame {
 }
 Localize = <table> {
 }
 Warning = <function> defined @Interface/AddOns/LiteMount/Print.lua:91
 TableToString = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:171
 MOUNTFAMILY = <table> {
 }
 tJoin = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:56
 tSlice = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:35
 UIDebug = <function> defined @Interface/AddOns/LiteMount/Print.lua:82
 Debug = <function> defined @Interface/AddOns/LiteMount/Print.lua:45
 tUpdate = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:71
 CreateAutoEventFrame = <function> defined @Interface/AddOns/LiteMount/AutoEventFrame.lua:24
 ITEM = <table> {
 }
 tMerge = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:81
 tCopyShallow = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:29
 tMap = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:15
 GetDebugLines = <function> defined @Interface/AddOns/LiteMount/Print.lua:34
 ItemSummoned = <table> {
 }
}
(*temporary) = nil
(*temporary) = 168799
(*temporary) = "attempt to call field 'GetSpellName' (a nil value)"

Message: Interface/AddOns/LiteMount/Environment.lua:24: attempt to call method 'InitializeHolidays' (a nil value)
Time: Fri Jun 14 16:09:36 2024
Count: 1
Stack: Interface/AddOns/LiteMount/Environment.lua:24: attempt to call method 'InitializeHolidays' (a nil value)
[string "@Interface/AddOns/LiteMount/Environment.lua"]:24: in function `Initialize'
[string "@Interface/AddOns/LiteMount/Environment.lua"]:138: in function `?'
[string "@Interface/AddOns/LiteMount/AutoEventFrame.lua"]:20: in function <Interface/AddOns/LiteMount/AutoEventFrame.lua:18>

Locals: self = Frame {
 0 = <userdata>
 IsDragonriding = <function> defined @Interface/AddOns/LiteMount/Environment.lua:127
 PLAYER_LOGIN = <function> defined @Interface/AddOns/LiteMount/Environment.lua:137
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/LiteMount/Environment.lua:153
 PLAYER_STARTED_MOVING = <function> defined @Interface/AddOns/LiteMount/Environment.lua:141
 MOUNT_JOURNAL_USABILITY_CHANGED = <function> defined @Interface/AddOns/LiteMount/Environment.lua:149
 GetJumpTime = <function> defined @Interface/AddOns/LiteMount/Environment.lua:78
 OnUpdate = <function> defined @Interface/AddOns/LiteMount/Environment.lua:54
 IsFloating = <function> defined @Interface/AddOns/LiteMount/Environment.lua:100
 GetEncounterInfo = <function> defined @Interface/AddOns/LiteMount/Environment.lua:198
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface/AddOns/LiteMount/Environment.lua:165
 ENCOUNTER_END = <function> defined @Interface/AddOns/LiteMount/Environment.lua:175
 ENCOUNTER_START = <function> defined @Interface/AddOns/LiteMount/Environment.lua:170
 IsTheMaw = <function> defined @Interface/AddOns/LiteMount/Environment.lua:109
 IsFalling = <function> defined @Interface/AddOns/LiteMount/Environment.lua:70
 ZONE_CHANGED = <function> defined @Interface/AddOns/LiteMount/Environment.lua:157
 IsMovingOrFalling = <function> defined @Interface/AddOns/LiteMount/Environment.lua:105
 PLAYER_STOPPED_MOVING = <function> defined @Interface/AddOns/LiteMount/Environment.lua:145
 Initialize = <function> defined @Interface/AddOns/LiteMount/Environment.lua:21
 UpdateSwimTimes = <function> defined @Interface/AddOns/LiteMount/Environment.lua:94
 ZONE_CHANGED_INDOORS = <function> defined @Interface/AddOns/LiteMount/Environment.lua:161
 GetStationaryTime = <function> defined @Interface/AddOns/LiteMount/Environment.lua:86
}
(*temporary) = nil
(*temporary) = Frame {
 0 = <userdata>
 IsDragonriding = <function> defined @Interface/AddOns/LiteMount/Environment.lua:127
 PLAYER_LOGIN = <function> defined @Interface/AddOns/LiteMount/Environment.lua:137
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/LiteMount/Environment.lua:153
 PLAYER_STARTED_MOVING = <function> defined @Interface/AddOns/LiteMount/Environment.lua:141
 MOUNT_JOURNAL_USABILITY_CHANGED = <function> defined @Interface/AddOns/LiteMount/Environment.lua:149
 GetJumpTime = <function> defined @Interface/AddOns/LiteMount/Environment.lua:78
 OnUpdate = <function> defined @Interface/AddOns/LiteMount/Environment.lua:54
 IsFloating = <function> defined @Interface/AddOns/LiteMount/Environment.lua:100
 GetEncounterInfo = <function> defined @Interface/AddOns/LiteMount/Environment.lua:198
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface/AddOns/LiteMount/Environment.lua:165
 ENCOUNTER_END = <function> defined @Interface/AddOns/LiteMount/Environment.lua:175
 ENCOUNTER_START = <function> defined @Interface/AddOns/LiteMount/Environment.lua:170
 IsTheMaw = <function> defined @Interface/AddOns/LiteMount/Environment.lua:109
 IsFalling = <function> defined @Interface/AddOns/LiteMount/Environment.lua:70
 ZONE_CHANGED = <function> defined @Interface/AddOns/LiteMount/Environment.lua:157
 IsMovingOrFalling = <function> defined @Interface/AddOns/LiteMount/Environment.lua:105
 PLAYER_STOPPED_MOVING = <function> defined @Interface/AddOns/LiteMount/Environment.lua:145
 Initialize = <function> defined @Interface/AddOns/LiteMount/Environment.lua:2

Message: Interface/AddOns/LiteMount/LM_Spell.lua:22: attempt to call field 'GetSpellInfo' (a nil value)
Time: Fri Jun 14 16:09:36 2024
Count: 1
Message: Interface/AddOns/LiteMount/UI/UIFilter.lua:271: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jun 14 16:26:39 2024
Count: 1
Stack: Interface/AddOns/LiteMount/UI/UIFilter.lua:271: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/LiteMount/UI/UIFilter.lua"]:271: in function <Interface/AddOns/LiteMount/UI/UIFilter.lua:269>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/UI/MountsFilter.lua"]:174: in function <Interface/AddOns/LiteMount/UI/MountsFilter.lua:157>
[string "@Interface/AddOns/LiteMount/UI/MountsFilter.lua"]:273: in function `initFunction'
[string "@Interface/AddOns/LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:792: in function `UIDropDownMenu_Initialize'
[string "@Interface/AddOns/LiteMount/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1803: in function `ToggleDropDownMenu'
[string "@Interface/AddOns/LiteMount/UI/MountsFilter.lua"]:65: in function <Interface/AddOns/LiteMount/UI/MountsFilter.lua:64>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

Stack: Interface/AddOns/LiteMount/LM_Spell.lua:22: attempt to call field 'GetSpellInfo' (a nil value)
[string "@Interface/AddOns/LiteMount/LM_Spell.lua"]:22: in function <Interface/AddOns/LiteMount/LM_Spell.lua:20>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LiteMount/Mount.lua"]:33: in function `Get'
[string "@Interface/AddOns/LiteMount/MountRegistry.lua"]:245: in function `AddSpellMounts'
[string "@Interface/AddOns/LiteMount/MountRegistry.lua"]:97: in function `Initialize'
[string "@Interface/AddOns/LiteMount/Core.lua"]:46: in function `Initialize'
[string "@Interface/AddOns/LiteMount/Core.lua"]:77: in function `?'
[string "@Interface/AddOns/LiteMount/AutoEventFrame.lua"]:20: in function <Interface/AddOns/LiteMount/AutoEventFrame.lua:18>

Locals: self = <table> {
 IsCastable = <function> defined @Interface/AddOns/LiteMount/LM_RunningWild.lua:31
 __index = <table> {
 }
 Get = <function> defined @Interface/AddOns/LiteMount/LM_RunningWild.lua:18
}
spellID = 87840
(*temporary) = nil
(*temporary) = 87840
(*temporary) = "attempt to call field 'GetSpellInfo' (a nil value)"
LM = <table> {
 TravelForm = <table> {
 }
 Mount = <table> {
 }
 RuleArguments = <table> {
 }
 GetDebugLines = <function> defined @Interface/AddOns/LiteMount/Print.lua:34
 FLAG = <table> {
 }
 MountRegistry = Frame {
 }
 MountList = <table> {
 }
 tUpdate = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:71
 MOUNTFAMILY = <table> {
 }
 CreateAutoEventFrame = <function> defined @Interface/AddOns/LiteMount/AutoEventFrame.lua:24
 tJoin = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:56
 UIDebug = <function> defined @Interface/AddOns/LiteMount/Print.lua:82
 tMap = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:15
 UIFilter = <table> {
 }
 ActionButton = <table> {
 }
 WarningAndPrint = <function> defined @Interface/AddOns/LiteMount/Print.lua:95
 Actions = <table> {
 }
 RuleSet = <table> {
 }
 Rule = <table> {
 }
 Journal = <table> {
 }
 Print = <function> defined @Interface/AddOns/LiteMount/Print.lua:23
 SPELL = <table> {
 }
 Nagrand = <table> {
 }
 Soar = <table> {
 }
 Vars = <table> {
 }
 Conditions = <table> {
 }
 SlashCommandFunc = <function> defined @Interface/AddOns/LiteMount/SlashCommand.lua:224
 PrintError = <function> defined @Interface/AddOns/LiteMount/Print.lua:29
 SecureAction = <table> {
 }
 RuleContext = <table> {
 }
 RunningWild = <table> {
 }
 RuleBoolean = <table> {
 }
 Debug = <function> defined @Interface/AddOns/LiteMount/Print.lua:45
 TableWithDefault = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:179
 Spell = <table> {
 }
 tSlice = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:35
 PairsByKeys = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:43
 Options = <table> {
 }
 Environment = Frame {
 }
 Localize = <table> {
 }
 ITEM = <table> {
 }
 tMerge = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:81
 tCopyShallow = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:29
 Warning = <function> defined @Interface/AddOns/LiteMount/Print.lua:91
 TableToString = <function> defined @Interface/AddOns/LiteMount/TableUtil.lua:171
 ItemSummoned = <table> {
 }
}

Message: Interface/AddOns/LiteMount/UI/ReportBug.lua:97: attempt to call method 'GetLocation' (a nil value)
Time: Fri Jun 14 16:26:48 2024
Count: 1
Stack: Interface/AddOns/LiteMount/UI/ReportBug.lua:97: attempt to call method 'GetLocation' (a nil value)
[string "@Interface/AddOns/LiteMount/UI/ReportBug.lua"]:97: in function <Interface/AddOns/LiteMount/UI/ReportBug.lua:46>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:954: in function `DisplayLayout'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:899: in function `DisplayCategory'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:841: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:834>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:178: in function <...rface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_CategoryList.lua"]:140: in function <...s/Blizzard_Settings_Shared/Blizzard_CategoryList.lua:138>

Locals: self = LiteMountReportBugPanel {
 0 = <userdata>
 Scroll = LiteMountReportBugPanelScroll {
 }
 RevertButton = Button {
 }
 CreateIssueURL = EditBox {
 }
 category = <table> {
 }
 DefaultsButton = Button {
 }
 OnShow = <function> defined @Interface/AddOns/LiteMount/UI/ReportBug.lua:46
 OnLoad = <function> defined @Interface/AddOns/LiteMount/UI/ReportBug.lua:26
 OnReset = <function> defined @Interface/AddOns/LiteMount/UI/PanelTemplate.lua:119
 OnRefresh = <function> defined @Interface/AddOns/LiteMount/UI/PanelTemplate.lua:127
 OnDefault = <function> defined @Interface/AddOns/LiteMount/UI/PanelTemplate.lua:139
 name = "Report Bug"
 hideRevertButton = true
 RefreshButton = Button {
 }
 Title = FontString {
 }
 OnSizeChanged = <function> defined @Interface/AddOns/LiteMount/UI/ReportBug.lua:30
 hideDefaultsButton = true
 OnCommit = <function> defined @Interface/AddOns/LiteMount/UI/PanelTemplate.lua:146
 ExplainText = FontString {
 }
 Disable = Frame {
 }
}
savedDefaults = <table> {
 profile = <table> {
 }
 global = <table> {
 }
 char = <table> {
 }
}
sv = <table> {
 char = <table> {
 }
 global = <table> {
 }
 profileKeys = <table> {
 }
 profiles = <table> {
 }
}
data = "T33wxYXTrA(BzEs2NDTojsKazM7BuIuMYwQLoSOLph)qEys2f7UwvDvCRUAkr(a)TVXxCba5fYMJO3r27WXEgMdkCjqGiceaiIVEWn80HnV46Xt4FFW(BU9Lh)139S)07E2MD7F92t3C84b6xot)NnxT)4Zh3J6D7D3CZXdF9X7oC(w6))l8((OVE4cx7Wf1DDTnvdx0rFg6RRqXrQk9HytJ8TRY76ds1DDEh(xQ6nUgp)Z03U6kpxfp10qFxd9VbTLOko0JDOZrPn1vTuf6PHS2xH2Js767j6a10hRI0y7r)26AbzeykTbJrKl2JodvQTX1wlJmMkDYNG4QJCn4pbPtJNVjgcA)5JExBNmT8bAE1ZKKVl2e4oK()u7DHUEMQA8916e3378CdBvkmQmNwxK)xMlu304KrL4bXoN07Uy0N5FEqlv8CluffwcTk44PU25TYQGVUUPwNq(oqkGUrPALPp7LfsAM1w5qxHPtlnjWmHAyDWZeEdyV1udGaa1MqFBxiphQXqt1ORTkTKqJJYA5Aq)BnZuC99ATR7XmAGxSJrMlllp9n6O0HzkvgT6Igxl9ly2T6AANovqRuMADljk2RL7PLD0smKvUayiq8H7gz1MK(8XOWCWNTICeOzTZjEASbDEqguW)5bI6KozQ00u1Ws)mRTVNffCsp2kI2eRSQt6Cs6QPkWJo1d9yfh0Am227K(i213j9GdIxvc)GBNUceBBavll0uXDm3RPM(QwN7yS7K5lPb1GVJAhQvbZsFjz3ivNKl8yQP8eikIQ3qmZ6GoJ99vvY4Z9sSOxcSqLRQYZgncIOMQl3xf7lBOkT2u5qnW6g1WGt4zOD6SH0LJEzS5E2ZtypX5JY6Blju6LHRHSCeywDJZfI8WIf9((qu7o8To0oiK4zMJVl06LjEKeufjexTNLzHCtJm9GiBNhYPGEIoMmr7jUFOAqnXrnZZ9qGg3wEgrSZMkLPqZoiwbglzoSRdDPi)gDQCqdT06nYNgBOU45Q0f1_ = "Vulpera"
race = "Vulpera"
_ = "Death Knight"
class = "DEATHKNIGHT"
level = 70
spec = 1
specID = 250
specName = 0
macros = " :
    #showtooltip [nomod]ashes of Al'ar;[mod:ctrl] Traveler's Tundra Mammoth;[mod:shift]Sandstone Drake
    /click [nomod] LM_B1
    /use [mod:ctrl] Traveler's Tundra Mammoth
    /use [mod:shift] Sandstone Drake
    /use [mod:alt] Grand Expedition Yak
    /dismount
    
LiteMount:
    # Auto-created by LiteMount addon, it is safe to delete or edit this macro.
    # To re-create it run "/litemou

**Comment by borgepitza** [comment]
nvm just reinstalled and fixed :D

**Comment by mbattersby** [comment]
That was you trying to use the TWW beta version on retail. Make sure you are not on the beta release setting for updates.

Happy adventuring, X.

**Comment by borgepitza** [comment]
I using this custom macro since 10.1  . just reinstalled addon and Bam, fixed. Thank you!
