### ISSUE TITLE
LiteMount won't select skyriding mounts in TWW areas

### ISSUE THREAD

**Issue by kayti-wow** [xod-wow/LiteMount#242]
It appears that the new TWW zones are marked with `IsAdvancedFlyable() = true` and `IsFlyable() = false` which causes LiteMount to only select ground mounts in these zones.

**Comment by kayti-wow** [comment]
FYI, Kaz Algar's map ID is 2274

**Comment by mbattersby** [comment]
I'm not sure what the right fix is. I think the reality is there is no such thing as a dragonriding area any more, nor possibly a dragonriding mount.

I think the right answer is to remove skyriding as a concept like DF never existed. Sounds like you have a work-around for now, I'll probably think on this a bit more. Blizzard have always been super bad about making IsFlyableArea() and IsAdvancedFlyableArea() match reality.

**Comment by mbattersby** [comment]
Merged your PR, should be in beta6 cheers.

**Comment by kayti-wow** [comment]
Agreed on the need for a more permanent solution, but this does now allow beta testers to use skyriding mounts with LiteMount in the new zones, so thanks.

Not sure whether you're in the beta, but when you try to enable static flight in Khaz Algar you get this message, indicating that they are going to do the same thing in TWW that they did in DF (skyriding only until you unlock an achievement): 
![image](https://github.com/xod-wow/LiteMount/assets/54023126/ce6d3614-abb0-43dc-8d79-ff482f454810)

**Comment by mbattersby** [comment]
Totally agree, I merged your PR much appreciated. I do have beta access, though not that much time to look at it :)

**Comment by mbattersby** [comment]
I'm keeping notes about things I see in #236 feel free to add to them.
