### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by milotic** [xod-wow/LiteMount#247]
Date: 2024-07-02 21:20:08
ID: 40
Error occured in: Global
Count: 1
Message: Interface/AddOns/LiteMount/UI/UIFilter.lua line 272:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [string "=[C]"]: pairs()
   [string "@Interface/AddOns/LiteMount/UI/UIFilter.lua"]:272:
      Interface/AddOns/LiteMount/UI/UIFilter.lua:270
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/LiteMount/UI/MountsFilter.lua"]:174:
      Interface/AddOns/LiteMount/UI/MountsFilter.lua:157
   [string "@Interface/AddOns/LiteMount/UI/MountsFilter.lua"]:273: initFunction()
   [string "@Interface/AddOns/HandyNotes_BattleForAzerothTreasures/lib/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:792: UIDropDownMenu_Initialize()
   [string "@Interface/AddOns/HandyNotes_BattleForAzerothTreasures/lib/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1803: ToggleDropDownMenu()
   [string "@Interface/AddOns/LiteMount/UI/MountsFilter.lua"]:65:
      Interface/AddOns/LiteMount/UI/MountsFilter.lua:64

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by mbattersby** [comment]
I don't have and can't reproduce this error. Is it possible your LiteMount install has gotten corrupted somerhow?

**Comment by milotic** [comment]
was installed via wowup to dragonflight 
![Captura de pantalla 2024-07-03 100902](https://github.com/xod-wow/LiteMount/assets/1099848/4abb5a79-825e-45ed-bbde-2d0f7f748549)

**Comment by mbattersby** [comment]
TWW beta version installed on DF. See other #248 for details.
