### ISSUE TITLE
lua error 2

### ISSUE THREAD

**Issue by milotic** [xod-wow/LiteMount#248]
Date: 2024-07-02 21:23:18
ID: 40
Error occured in: Global
Count: 1
Message: Interface/AddOns/LiteMount/UI/ReportBug.lua line 97:
   attempt to call method 'GetLocation' (a nil value)
Debug:
   [string "@Interface/AddOns/LiteMount/UI/ReportBug.lua"]:97:
      Interface/AddOns/LiteMount/UI/ReportBug.lua:46
   [string "=[C]"]: ?
   [string "=[C]"]: Show()
   [string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:954: DisplayLayout()
   [string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:899: DisplayCategory()
   [string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:841:
      .../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:834
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:178:
      ...rface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua:177
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:181: TriggerEvent()
   [string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_CategoryList.lua"]:140:
      ...s/Blizzard_Settings_Shared/Blizzard_CategoryList.lua:138
Locals:
self = LiteMountReportBugPanel {
 0 = <userdata>
 Scroll = LiteMountReportBugPanelScroll {
 }
 RevertButton = Button {
 }
 CreateIssueURL = EditBox {
 }
 category = <table> {
 }
 DefaultsButton = Button {
 }
 OnShow = <function> defined @Interface/AddOns/LiteMount/UI/ReportBug.lua:46
 OnLoad = <function> defined @Interface/AddOns/LiteMount/UI/ReportBug.lua:26
 OnReset = <function> defined @Interface/AddOns/LiteMount/UI/PanelTemplate.lua:119
 OnRefresh = <function> defined @Interface/AddOns/LiteMount/UI/PanelTemplate.lua:127
 OnDefault = <function> defined @Interface/AddOns/LiteMount/UI/PanelTemplate.lua:139
 name = "Informar un error"
 hideRevertButton = true
 RefreshButton = Button {
 }
 Title = FontString {
 }
 OnSizeChanged = <function> defined @Interface/AddOns/LiteMount/UI/ReportBug.lua:30
 hideDefaultsButton = true
 OnCommit = <function> defined @Interface/AddOns/LiteMount/UI/PanelTemplate.lua:146
 ExplainText = FontString {
 }
 Disable = Frame {
 }
}
savedDefaults = <table> {
 profile = <table> {
 }
 global = <table> {
 }
 char = <table> {
 }
}
sv = <table> {
 char = <table> {
 }
 global = <table> {
 }
 profileKeys = <table> {
 }
 profiles = <table> {
 }
}
data = "95ySolmmmq4NigyKvOILFbdKkgTQtXPy1u7kN0HU0N9)0iHetipyR77UtgocTGR)nA77hi)Ie)eXBDh26AmCCenUGYLXnevpgRbujWdpjlXQa3pTtNnnWr6pAn9RUCnuaxI5VIu9)rUCAukRgDvTPeCgCOi6I0tx0OAvLEDETfTbkNUvqzWx)Wma)d"
_ = "Pandaren"
race = "Pandaren"
_ = "Caballero de la Muerte"
class = "DEATHKNIGHT"
level = 69
spec = 1
specID = 250
specName = 0
macros = ""
(*temporary) = <function> defined =[C]:-1
(*temporary) = EditBox {
 0 = <userdata>
 Instructions = FontString {
 }
}
(*temporary) = "|cff00ff00What happens?|r

|cff00ff00What did you expect to happen instead?|r

|cff00ff00Did it work in a previous version of LiteMount? If so, what was the last version that worked?|r

|cffffaa00Please do not modify anything below this line.|r
|cff777777
"
(*temporary) = "--- General ---
"
(*temporary) = "
"
(*temporary) = "date: Tue Jul  2 21:23:18 2024
"
(*temporary) = "expansion: Shadowlands
"
(*temporary) = "build: 10.2.7 | 55261 | Jun 20 2024 | 100207 |  |  
"
(*temporary) = "version: 11.0.0-1beta8
"
(*temporary) = "locale: esMX
"
(*temporary) = "current profile: Default
"
(*temporary) = "
"
(*temporary) = "--- Player ---
"
(*temporary) = "
"
(*temporary) = "name: Raidenbmei-Drakkari
"
(*temporary) = "class: DEATHKNIGHT
"
(*temporary) = "level: 69
"
(*temporary) = "race: Pandaren
"
(*temporary) = "faction: Horde
"
(*temporary) = "spec: 1 250 0
"
(*temporary) = "
"
(*temporary) = "--- Location ---
"
(*temporary) = "
"
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = Frame {
 0 = <userdata>
 PLAYER_LOGIN = <function> defined @Interface/AddOns/LiteMount/Environment.lua:136
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/LiteMount/Environment.lua:152
 PLAYER_STARTED_MOVING = <function> defined @Interface/AddOns/LiteMount/Environment.lua:140
 MOUNT_JOURNAL_USABILITY_CHANGED = <function> defined @Interface/AddOns/LiteMount/Environment.lua:148
 GetJumpTime = <function> defined @Interface/AddOns/LiteMount/Environment.lua:78
 OnUpdate = <function> defined @Interface/AddOns/LiteMount/Environment.lua:54
 IsDragonRiding = <function> defined @Interface/AddOns/LiteMount/Environment.lua:126
 IsFloating = <function> defined @Interface/AddOns/LiteMount/Environment.lua:100
 GetEncounterInfo = <function> defined @Interface/AddOns/LiteMount/Environment.lua:197
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface/AddOns/LiteMount/Environment.lua:164
 ENCOUNTER_END = <function> defined @Interface/AddOns/LiteMount/Environment.lua:174
 ENCOUNTER_START = <function> defined @Interface/AddOns/LiteMount/Environment.lua:169
 IsTheMaw = <function> defined @Interface/AddOns/LiteMount/Environment.lua:109
 IsFalling = <function> defined @Interface/AddOns/LiteMount/Environment.lua:70
 ZONE_CHANGED = <function> defined @Interface/AddOns/LiteMount/Environment.lua:156
 IsMovingOrFalling = <function> defined @Interface/AddOns/LiteMount/Environment.lua:105
 PLAYER_STOPPED_MOVING = <func

**Comment by mbattersby** [comment]
I don't have and can't reproduce this error. Is it possible your LiteMount install has gotten corrupted somerhow?

**Comment by mbattersby** [comment]
¿Su instalación está corrupta? ¿Puedes intentar reinstalar LiteMount?

**Comment by milotic** [comment]
> ¿Su instalación está corrupta? ¿Puedes intentar reinstalar LiteMount?

ayer me recomendaron el addon, lo descargue desde wowup y desde un inicio tiro los errores, lo reinstale y continuan. 
![Captura de pantalla 2024-07-03 100902](https://github.com/xod-wow/LiteMount/assets/1099848/6b9b11f8-af43-4871-97b6-a3fdab3d7ddc)

de hecho si uno busca el addon para dragonflight en wowup aparece duplicado, asi que instale la version de curse

![Captura de pantalla 2024-07-03 100902](https://github.com/xod-wow/LiteMount/assets/1099848/b2cafe16-b62d-40e3-b1f0-d30a39d8e17e)

**Comment by mbattersby** [comment]
Ah.

WoWUp está instalando la versión incorrecta. Esa es la versión (11.0.0-beta) para la beta de TWW. No funcionará en 10.2.6.

Para LiteMount debes usar el canal "Stable" en WoWUp. Ni "Alpha" ni "Beta".

Puedes configurar "Stable" en las opciones de WoWUp o hacer clic derecho en Litemount y elegir el canal "Stable" en el menú.

Felices aventuras, X.

**Comment by mbattersby** [comment]
Por ejemplo

![image](https://github.com/xod-wow/LiteMount/assets/1300207/73f75e65-51f1-4b0f-91ae-e89435e19452)
