### ISSUE TITLE
Non favorite mount is being summoned

### ISSUE THREAD

**Issue by Xanthos-Code** [xod-wow/LiteMount#25]
I think this is due to selecting the 'Copy Target Mount" option being checked.

**Comment by mbattersby** [comment]
I'm sorry, I don't understand what bug you are trying to report.

**Comment by Xanthos-Code** [comment]
I had assumed that only favorite mounts would be summoned when I use the hot key to random summon a mount. Maybe I misremembered and that is not how it works. Turns out I can set priority to zero to exclude individual mounts from being randomly summoned.

**Comment by mbattersby** [comment]
That's definitely not how it ever worked. I'm glad you found the solution on your own, good work.

Happy adventuring, X.
