### ISSUE TITLE
You can't do that while in combat

### ISSUE THREAD

**Issue by MateuszKurowski** [xod-wow/LiteMount#252]
How to disable message chat "You can't do that while in combat". Now combat is bugged so I spam mount while waiting for combat bug end. And it spam chat so much
![Untitled](https://github.com/xod-wow/LiteMount/assets/80587569/0267ff19-0a4e-4fd0-a71a-785461a4452e)

**Comment by mbattersby** [comment]
No idea what's causing that, as far as I know it's just you so I assume it's something in your custom config.

If you need assistance please follow the bug report instructions

https://github.com/xod-wow/LiteMount/wiki/Report-Bug

**Comment by mbattersby** [comment]
Sorry this is my fault I have found the reason. Please look out for a new release with a fix shortly.

**Comment by mbattersby** [comment]
Fixed in 10.2.7-4. Thanks!
