### ISSUE TITLE
big problem to summon normal/slow flight mounts

### ISSUE THREAD

**Issue by Spidermew** [xod-wow/LiteMount#257]
Hello,
There is a big problem to summon normal/slow flight mounts in the latest LiteMount release 11.0.0-2 and 11.0.0-3 : we can't use shift anymore to summon normal/slow flight mounts !
I was forced to downgrade to the release 10.2.7-4 of LiteMount.

Could you please fix this bug ?

Thank you very much

**Comment by mbattersby** [comment]
Hi,
This is not a bug, it is expected due to release of TWW pre-patch next week. Please continue to use 10.2.7-4 until then if you like.
Best wishes, X.

**Comment by Spidermew** [comment]
Thank you very much for you answer, I hope this will be an easy way to continue using the "slow" flying mounts with LiteMount, because I hate the dragonriding way to use the flying mounts, too fast for me.

**Comment by mbattersby** [comment]
Starting from next Tuesday all flying mounts can also dragonride, which has been renamed to Skyriding. In the mount journal there is a toggle button to switch between Skyriding (dragonriding) and Steady Flight (old style flying). You can also activate this toggle by holding RIGHT SHIFT while pushing your LiteMount keybings.
