### ISSUE TITLE
Shift bind only summoning ground mounts.

### ISSUE THREAD

**Issue by chrisistansell** [xod-wow/LiteMount#259]
Not sure what I'm missing but logged in today 7/14/24 and haven't been able to get anything but ground mounts when I use shift and clicking the litemount macro.

**Comment by mbattersby** [comment]
This is expected in preparation for The War Within pre-patch next week, where flying and dragonriding mounts are merged into one and shift will summon a ground mount.

If it bothers you until then please keep using LiteMount 10.2.7-4.

Happy adventuring, X.

**Comment by mbattersby** [comment]
Closing this off, I left it open in case anyone else came with the same issue but tonight is pre-patch so it's over.
