### ISSUE TITLE
Poseidus and Vashj'ir 

### ISSUE THREAD

**Issue by milotic** [xod-wow/LiteMount#262]
Vashj'ir unlike any other water place only summon the quest seahorse variant and ignore if you have poseidus the rare mount of Vashj'ir , Litemount summon any of 4 quiraji mounts in Temple of Ahn'Qiraj, vashj'ir should be allow summon poseidus.

**Comment by mbattersby** [comment]
This is not an error, Vashj'ir Seahorse is faster than other aquatic mounts in Vashj'ir (370% speed compared to 270% speed).
