### ISSUE TITLE
Using the macro while mounted doesnt dismount

### ISSUE THREAD

**Issue by Peach774** [xod-wow/LiteMount#263]
With the launch of the prepatch, when I use the macro while mounted, it doesnt do anything

**Comment by mbattersby** [comment]
Can you please submit the bug report info, thanks.

https://github.com/xod-wow/LiteMount/wiki/Report-Bug

**Comment by Peach774** [comment]
> Can you please submit the bug report info, thanks.
> 
> https://github.com/xod-wow/LiteMount/wiki/Report-Bug

What happens?


What did you expect to happen instead?


Did it work in a previous version of LiteMount? If so, what was the last version that worked?


Please do not modify anything below this line.

--- General ---

date: Tue Jul 23 22:43:08 2024
expansion: Dragonflight
build: 11.0.0 | 55818 | Jul 23 2024 | 110000 |  |  
version: 11.0.0-4
locale: enUS
current profile: Default

--- Player ---

name: Liendell-Hyjal
class: MONK
level: 70
race: Scourge
faction: Horde
spec: 1 268 0

--- Location ---

map: The Waking Shores (2022)
mapPath: The Waking Shores (2022) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: The Waking Shores
subZoneText: 
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
LiteMount:
    # Auto-created by LiteMount addon, it is safe to delete or edit this macro.
    # To re-create it run "/litemount macro"
    /lmt savebtn
    /click LM_B1
    
```

--- Debugging Output ---

```
[4] Combat started
  * setting action to default combat macro
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
[1] Combat started
  * setting action to default combat macro
[2] Combat started
  * setting action to default combat macro
[3] Combat started
  * setting action to default combat macro
[4] Combat started
  * setting action to default combat macro
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
[1] PreClick handler (inputButton=LeftButton, isDown=false)
Refreshing status of all mounts.
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,0
  Dispatching flow control action     ELSEIF [dragonridable][flyable]
  * ELSEIF test is 0,1
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,2
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 245 mounts
  * trying Skyriding Mount
  * found 108 mounts.
  * WeightedRandom n=108, t=2.939, c=2.353, w=0.043, p=0.014
  * setting action to mount Algarian Stormrider
[1] PreClick ok time 51.75
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 0.18
[1] PostClick handler (inputButton=LeftButton, isDown=false)
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
[1] PreClick handler (inputButton=LeftButton, isDown=false)
Refreshing status of all mounts.
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 19.73
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,0
  Dispatching flow control action     ELSEIF [dragonridable][flyable]
  * ELSEIF test is 0,1
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,2
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 245 mounts
  * trying Skyriding Mount
  * found 108 mounts.
  * WeightedRandom n=108, t=2.939, c=0.221, w=0.019, p=0.006
  * setting action to mount Golden Cloud Serpent
[1] PreClick ok time 31.44
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 0.18
```

--- Options DB ---

nY1wxoXrs6Fo2Zz3HtE)Y8gdyBSXG5GyWN1p0hk6UOBnOwITKe4Mh43(gFrgrMsCXZo2EOiRSImUhrgr
M6c7fV4IvxEZ0c(ZFD982RM3S5tV6V)Px9O7(3tBOrpq)ZQR3S718FB1(J3E7UTpy3XTh2t)9N6YUC2C
XtJ2lEAWzm18fpL(xFovYr(rN35ONO37IXunDXtl8GHkpyYgcz(PGpAko(rFnhm0mdj8CWzR4tOx5dXm
(tBBjkyLPxz9otdCUCS4b8O)kTWbcEaKLA1WV3MdPqBnc5ILExaOdbwaF6FRMKZ2WhtXBXIfBGnGpYGj
7trauhJZ2OVbpJZNCn8jwmjJGYvBYt)PZjltS9CWwjIbqamUO3xaPI)pI1ePxaY35l5gA5lPawuawF2W
88cO3AWcqaEEYuJeTvQUgd2jSvxYsZoWdgBSbgYD2UnzBlskxCjMe8rFPGHCaJO54eIp7czGhzqcbVn1
yRoFTYci6)mwwiXZOyYLgpPASayfMZs6jjMe5puq0GnxBYg6PsPaMNHXbNpYYXCSciJ57lbxBTbdJLPG
BADg(dTmIrAK88bJYvQqPiYyB25mmC8PAaOc4qfVS82STG55ApgIYOgpuvbJmHX8m)34DqQXI9K11ugG
cxLwTeuUkKquK6oRXevEdjz866Le1pFmBBQFPurnmWmd8c7j7cOKa80dnUgMtQQjGWrMGsPKkznHUYET
rfjNbA8EbSj(rNp7k52JrFYxBcEYYmyfTBBKfFzw)3WAXWIZNc5g(cnr26xX4s7dtec5AYaO1vBZMX4O
i)sgMDYQdzV1OyV10wCOmN1NInaqM)vRkdlfWSlgwjnx9IYkeUSCml8yr6f9gtGPflXSGgjuP5HJnMGR
6lSefiDQgBQF(yk0ulbBpxQcIAzv4M(URaYaY9a5Nijyi5js8)qQEY35dfl4mqVfULeRasZ2fv6ImAOr
Trf9AgNWLQO54RriyJcolkmKpzOW0SDQNa4md4ym6fHgaAJRagKT9Es7vWrO(7eY0fAwkm8JW1mMQ1BH
Peut8MM1o7wZwJjbAGKBFizFOqlxH)NsBDHOpWQnvmtO(LYjSAWPBnhbBasUA0l6Pq9qihGdq(ZM0Kkl
udY1MAtJ)Z4ETXqmo2Hjwhs(WcXKOdrdxrifgJBSYOnyB8pYmo4lk97yF4YJbErsgRTzT5suurH)NdoX
Pbqcj(guJDQaWcbaylKqTyf9sW3B2MEFn5zpry2f2BKRH71t0PA20vYESHnUectWCyghtYctUpadKrns
hVYOMpwlmtbQLMyeQmktb)PLjrshvS4y1Msxo4fLrNlJrDCqk4v21umGdd2uI4NLgo7nPG4YdAZIfbzP
XEbagseaOVSQVjIpyIzhkonKGI15ftxIuISdB6)YCemostPkUJi1dWnRmunCmDw0WPEaqvRwWvWFnL4K
dAC4AJ0tKQMYl54MnGApj0HyBrcZiimiPZHsuuSjPCTjbbQeysXto9Zndkyebjud1j4kbylq0IzqPJD5
UTVz91VCEz)6DBbuxTE7(dtBVCMZjZEXQhpTz9TxTBbkvKVOvpzMsY76DB)0REW6d3btMin6QN8Yp9Q7
VzZA8PF6v)00YY69ys)687NP0az9tYqzL1Cp79IF6vVy9T08E(63CypNK4toUSz3LF6vF)9)4TZ0JhU5
Vb(cHOREXn0mFY0hyP6fRE4887wosG(flt3sOmrwREX8YYew4DV5tV6h2E1M59eyx9UL1BVMqr4JE1Ql
Nw2mFGa1UTt7pmVqiFIyWR(5lNVCz3hAu0eL2kRuVA1ntxT7dVzA71F6vpMwtOiqobw9de(nT5Qp9QhU
mpD7hMUdCgY(y1tN3CGY)LyKFhT4)606Lw6V7UpHkxoVfVcidOPNS76JF6v)8(ntBbKMwV5oI)raKaMH
SDw9p3mD5Bx2D5BP3o)Ud304spCAHg4NxaN9HFyAHO2hD81G3swLRU)MRNpCZ3nrR79VKiKBbQfjTTgl
8(F84c9hVC64MdaNjn2v)RnxD8w(7jc4rtB2SVXd)5TV5ytLOq5hU6zeAsO)eZlJ0k9Px9pxM)WAWBwD
y3caHLCo9L8ssIwUNLKL2eeE3F56J7buOShxD)97bUqRin))yA739EsSbf0KIYVC92RwF500cti(VT6d
ZUir)TVBnOrsl6)97wAkrKpDd4N72rC610kDaqE12DFaXdizbyQ3Ud4WpsYS5MLhjoN(4)E6awARHIjq
)93prKZ)C6WHnZNkrDiU53eZE48Ta0egn)HLjfJScbUIyxZheM(ZNUE(nmgqEfDxS65hjJX2R(1Dlxnn
VabcX7G(bX(fKEE)H1eQrUhaH(BhpaLky8aI7pMj4Fdu6xoSMyUuqEr1(Vtc1ZmgGUn)mn8Jjr7v7Ufs
dK)7QhUmnVfobSb2KCA7e(6F542R30W3aZcmWSO5EGuUNBSGU4rFvx3GE5tjxftebaPT6gYc)URU)h3F
Clu5kbvFy1XTFG2wjcmeBlO7EeiwF9nhUz3MRqKtI8(HxJf5r8ai3z8TKVIDlZWW8hNW(s)(h93yL5mC
mqF7UBHNRl4Dw(1TXTuQBNAIq69BptpG0BJWv0MDxVCCFthGdHzAAhqhNG6mXiEW07j2CJ78GBMEhX0)
0RsNRurUU)MkvpF3R3Dakv37pU3pCVNFVF7EV4Ep6EeffHr4d2TEd8B9pOpK5ABMa79zZBz5jLuZQhU7
21Bj2oyupB36Th4vKmWEXDldM0j0gfJLuMGBGnWKOYMOZ3(UnItx2O6xiPk0PxE3CdIzJQvWiYpUB51R
V6QzArF(80LKA53)GBwd(mabLutGToO8ow9O5PLdNa6FdZ6NGj8j8OKO19v5rp69KxQVNx3FN88tO(Ea
DpS9(pfUYX6gMVUMZ9rKjK1MOtYXjy4Z8jIj(4JBa(SmXU6OmEw9tlZe3VPX8Y1B2qw60RQuq9vK8)2x
d5pOvMSHLSdrExM(4ntSjVP0Iz8D7Vb2DSp89GdGqYmhitR4Dld2Zx6wKL9b259VUU5e7zKkWmR3xtGT
ax5ewE8qZ)o7wG8wrweRwpFTiQ)TLRxwF7TSNrSFIv)4VdRTLR(wb(B(F)S4zmvvptq)JZcm9)1We5wH
97S6f7wU(gYL1)nr77(GYdz9LhoD725R4fXEsSF2(foyyJaOld25)A7vZlVMCSWbmPS0j5fhyUPtD)RE
pPpFKDmtjksVD7oYbX814BptD8VioWliFEioafXDwIm5cis)Q53DCZL3Cg2)JRx2ty7VTDEphFj))ppi
2Zqhhq1hSm9UDVB3M1ntFss(ltKLpyqcXF6xqP6(v0hBUCMFhIocwQJ9ZDwiaKXWHLDqpcCVPdN6wy18
HdTufoUfuDSL4Xe5Y9FaH61txExB6KgmYlojMw)WDcy(bevIt3KepXVA(m1A4mtKNr0xZHEgjnoHCs6y
eLEZAcE41oK(6GlX06PUH7iZt392Bos6e)2BEdzktbSWBPS6)SGfmb6h6M8FpDAwSoSXQwSltZt1iOYl
N2SRL24twV)nRpOXm3dFcEKeYF(NKdj4yHalIVFUcbRfw)2AHuc)hxGHmYZMEC7m0dHD4FCCZ39Jiw8B
PLI2Q0QNszmCZYmNkrK2ddLEjjfMUKrYnZWZallE0XnCcV)EllnBTNjmNPhkpgLTYU3oR5eGeSah4fuc
LB0yP3H0iS0(EpZvZtxF8JtKRSwKga(g0iFjZBVzn8oqH53Gu5Sg4M5bl39o1Bcja2D4WSKnZEuAgAgK
P1S4SgbC4uBg5RWlHfPE967GBY3aNK72bFg0wljs7LR3ZbnXk8)SN4hNNBpT3qssVW(5zf6BocFlW2dz
OFEA)pBHYuGs5Lb4paFmCeeeVqZYKv()ZDuY3TYN)ULDVz9M5hpF3EUo70kV(ASy)Djr8fezH2J0ByRI
vVKKOZ7V5K6WpE3Zx)Xps(8M(QV8H7w2E4R)D)eLT0L3S(Tn)c)(D0IodVv3)Yljh2NmXFEZvKJ79FtK
7XueY3sSI32u45Sz)PJtNbJhFhf6(RJhu6I3r5J8nbpfaMYADZ3EcpzA56PJ)5F(FIoEgTDZzKbXDFtq
9GBM3CnTpI5VbpBfSzVzA5R(YNU(T0NV5BlfFcIaoTD70FbJ6LZe3E(TFBM9Dluc83U(RIb)cH6BMHBZ
)dCIP3EZ0MJ)BzD(lM5J39EcPpU)VaJ)1zIVsgo3ojmTVgAtzxTD76PVHskLG0hNxoCG(ZV6e(k9HA8Y
7tXF(QWDyNXgz6W0J3IUv9mYwFznL4uRejjpYWRv1QqkkfLu64JtMGuF6Q32kgO1KJ9gEykOeGOOqsHV
rbbdvezQp32NP1CcRqi7KkQNSbPu2Us1uKYSNn244JcDeqaQpHuzAqQ6sA5gtgzv92u25gZnmgv(mPhD
CvEtfPi9TcDHgjq0FmpwGAhb0IaNZsFJ8jVRktL(QKwlYqWiaT6LEoO11fvoS1cktJadYmlAj1kLOu4v
ur8g7Pu8A1Q9MI0qdEMvL9znYeq1uLAuBZrTgRHEVWWGHXu1wuiTjqMqAmH2kuczvujDXYjp61fG72jZ
kQU8yQA3xAfTeVpkm6rZbC1uUuecKB1P5cTrhGPMQvHq8bN3h7ccrtmmkaBRlcMgpRnrPa2yjts1RLMY
bYn3KfCl9m9ItA5YOQvL1wIgfbOr9sbCjXN05NQ3RTIdV32rWCN7uSJ37gJ2EKYugLENv)cAFq8K(LrM
PpjSFs5myvvLAsWvPA6CH7RvXur7sRRXwAWV3TV2sLBla60wIFVucFW)tb1MIyjgPz1J(4KiNgk)V1Kr
8y1KQdyML1mBCDnE518QlSNrZRdf2NdwETn2x07QItgTRPankGZbUtkYhjON2wE2IlEsVXrbVfwsJqj)
uvH4KElIxhkkFcSKKWCdX4G6B6XuIIAppHevSJ9OxBXXJPXeK2QKlYF2w7Kpj6RUAXNKjr6fTNsQUuA4
RoOELbRq8eJwg2gdh1a19nr)Thbv34Vy9sDMIcsPZ7SKS1xmHb055AZGGISqvYPmqhmRun3ns89jJ4sJ
FFdu1CuCycmj3XePZT4BkDEqTJhD9DNxmZ1Z1GEcgy4udItUqOODVMhTdD9RWGIYJE2eqZkQ94noRWLl
zv3ceSxI8zYYm5vQ2bVTpOOXalZEmWsPBp76evS5quyjDvsRQWJ3B7yTWOoT)Zy08yUImrAPuqMGYb7n
4JmeLigOh5ccyz9KgQiuDTOKQTsbU6FsSRhrUwcDgKyCvnvrJGyaA8isJmPHXYKjJADqusBcwYeW3x)g
5rAEYNxkzzmWEef2mfRXngSRWnms4MvzAFUB8AHMqemnfcNgTd8HChpgGx5TyMn8mwRDtF0SUgklng31
OtXu3JZdtUZOe)D0)ZmiVWyMsmiYltV3PX8iVgVQuILT7lr0pdvFNOOz67Zu7BhECqlcphNxd9myeYAQ
hyWbcoOvrrHuiLCP4z2WVwxhnYeZDEQ4UHWoH6GUJ(1wndfWDAEEjDpnPcc4oJot90DedQCGFVvzzrrM
HQGhhyNthLu4fQZv994IrkjRo5Po5Sr90OWJMhFwpBXGK5kLHqqYhZt2rc1Gua1S0ikllzbrFLiHg9qL
0vdkZen8xrSu5KPMgVp3uX0JzJ8yp6SAbrETCDmOQwyug3jLJkN6d6r5uYyzp1AYlKDJr1ShNnf8rPoD
v0yYUUDxqZcu8lyBwEI(a5blAKfng6z0qFLmyTiOhVOLbOYJrffkU0o8hzmI1eLCyqqplfuX0x(S8Exw
xjE0EO84jFFTVO6O0woeTbYRVYjJDLi(rvhjBhEJYLoMMga9KpsOKS62edEcwlIc5idyACQqpUsTN9kf
wrJ5x7EJdUQKFaF(kezz1w9DaOEBXPljmaqCmACaGyNygYcxA8yEm12OLAzilfvC(1Y3JtLNGaYrVYjt
OmMGezOQaL8JOw00)tdh56rMj3LXtO6HUIOlfDAabsPuZHaqAG(AM4Y5AeJImmTJ5k0co2BdYs8DAXHf
rs9OuRJzw70NVhrsDDaOk(2dXUiINGBSaYOEAlsPb1whJQAr44Km(mXkmrUq1DB3oag2MOjmeYIXHEqR
uCyiWdNWMsJjigYfv0bbsD8r1XhnK9AAt4qLQSzs2DYcu6lGufbxY23L94SOYZv4cbILegaRmgDqKAqu
mQ4SGmSKaU0EIvdGeoaxJPkmxYhFCqpWcYitqwmCcEBpsjXQmj9y9kFLc22zIZ1ihnHW(5QeMOQpe5CR
QlRq5KUMCG3Yr3jSo1ZRPONbw5uWzAWxc940WRq5qp0uOcpcKkMyq3xbLCGqGMOYS0ZkRswQoLtp6u8O
QwPXj6e6P20Dr)mEXJM1yt8NnSScQvCrpADu4ETgdWr)WgrOwe9QNmeLyGGc0UCndDg9SvseXO2s6wIi
fyT2j5AQRiLSdxoccKj9bzmYjLQgrQS6bbN8OAY9Vx85YlGWVmei0qzwv7KYGu53wvLM8XOz4khWxhEF
wdQuDAbjyWx0hz2MPH0IKJe4Y7hNXl90cYcUy2y6a1nGulxgSOAKqI)PIfYMvplLKbJKHA)yqQhDptBr
ZYwYBhGA8EAR)IPbKQc4POiAiryf0jVKDa0w4rEcofuoruRN9CNmbXvcPvO2XvRxZH1Yv8Hrqxnmw2y)
JojKq1mw2uNxOInmAEqxNamnTgDlG8GIoocv1gK2uSD8rNmvnFESzUtyCnuuotK6ufPTLYrtZaSDrcuM
OKtnfrr0giB(8a(ICvoTSyuYYvSOtPQw(r5iYYp2p4Sm8h22znOMVOk(UEewYkT2RfkTy1bCRd4whqOm
GBZtI148coaQr09k2spZSEko2(LEahs1GUuMG62Thzbc52E2aKkJVxEp5030XjDRTYPof6BbFsSDiCsk
ahxaVE8SGwpe8vAg)9dWjo44DNx9QgbJdrgh6LiIrl17iXk6MC20GTj5bZOqC8z5Xe0TnwmQPgMqPd34
q3rk5gOStM6jlMqzXEPXXe0kQsOUMqJH86L6FMWrjpvL049ckkNdEawR33lCs7kIOZDGc9gnqFMgZnPP
MG5ghIpLLI5kFgMQIUUQzOalBCIcOye7glXXgh19SYZXNjZ1DYrH)u0noul1QcID9pua0BdGCq(XJ6Ls
agHqxfqdsen1NSxQcREm)1fO5ZTMv3b6DPamCVxPB5S86KpsrL29yblAulJh53Yypbu(bQQ61o)Gu0qQ
uCoDlzNC1iOiYYw6Wru2O61bzFq0AQbQKdZTtaLavsJq9weWWIpFTaf(qwZgI)Qy)RuTamH2AfljT1uK
iCCpxg(isgxlZh96B5UOjdkdyfhpQziqXLQ9hfBbIDQ7eJ2gGglLEyukwDRYuU26Up8JeZXX5yGTA0Aa
aHhIluLy4ACHspX6Oeyuph4ozUwbXPTD1O3mq3gYA0EjYVUlqv1yYHB3LMT7Lbav0nYr19Ppy1AFc4le
BKK3wbQPAFBNu2ssos96jsXA1cMALRsJraGOC5Z9Y3L8AQBm7s1tCA4y5qRZOvFd)yhK6nIaGve(K7tn
auGpFB8OMuQV9MIXmWwn5bFVsBr1OcopBWh1bwtmOF1j0tTpEe71tJS3UzoU26RBIgUkQdku4rHSgqpg
7TiL0scDnkn0VELhAOGVF3Li9u)yUNeowJCoUDDYnzdAuKfu7RIuWm)GeeESCBFCxC2nHdBwuSuinQO6
yZP1pbP1R(iRHETYIwtpwt(KIAOEtmNOYr8ln3H2fPY1SM12Nc4Qut7MO5UO1Tiz0yVBJehVx5gcU90Q
Axme830BTgCZeTAoEYvrdWvVVyx0VmFm6u7vwbZvwcShsvdU3zq5UUzU4SRHgUqQT1TDn)4SutrTqLKJ
w9ABG0kgSrT(VJo2Ox7rdR1emQxeVwYj21r3pvV6JTlMKJhuBZhbETKD07f9pA7vA6GelQRF608jjEH2
evuSyXnx13DpNmA1pnANvT(Ec169e12mf100B9(cW1WCk(Jm10jaTmMAAq0NaG8yUcTqArnwL1Am9ssK
lQvf5UrLqi)iX3iTrfnjZqE0qy1Wp5vgKdnepmGQe)bt11rR0i)kJ6JrR8TED7e(Q2Dx2VIPL3S43tUZ
OkmLvIYkOF1QkH4jO6jav8CLSQbJCLczW2V)R97XAZ2rZDoAYQXvWe0(grScvjLc7P1)tU7MaXA3zwfS
Q(mzoyhyBdwKI9qjR3cnkqHwVl5cO5AUc0c4L73AlJl3jSXnntUPRGBc9i(j5M85AA(IQfLSIKWMZWNf
pgO0e14yuYLkVOy61FYRnJwVWAycPuFJu97LhfhmQLyO5c1kRVMByTQ8kkKO6lKS8eTf96zJrP9lO1ta
Bkl1PaXlGEDiVOFXVXJ61wVPWQ5sa(2jOqpz7IwfCkHmPMp8CJ9LqKbqJQo(Q4yQdRdTPwKlPEAsoBVT
FKZqnUAqRAKtJphm2ET0QAfj8u2TQDoL4K4t0Rf2Tmkhz7s)Xwjg3iqUr9c40Tksrh6oxJEnjrKSKUby
J2AwYGlOEu9ojbkKaMvPyTebmqhww6EzW1I0kGcPEYpIESOsIEfzJ1AV(IH4jaT9yLsTqbKXzKomqKVY
7RA3CiN09o2ILx30uvlYMEZYzu1R0s2p26yw8xIZ)GmX(f7LHzQp4iYIOrjxd2w4kxxHYOLvb1bONnJ6
Jg5JvvMNw(xeyt2MwaUvvxfTlFjtiOpRco7uRE9swBzguVBBJBlpWADZOKAQ2hr5Q1JW)(Qrib5MQYoJ
CAW1a6bI8vOacchgLHtaRCRWz3bTFbdWlGJbLF0U2LyXcjF)axPLDarV0Dr0o0fMg7wKlXQwHyCFFvdT
syCMmI9Ioq53OgAz3Oeiimb(ljsVuZo0N1gs67LCeqnOyIz0RCnvBgvvJ1Ai0T88AS8OroWmeQOorhxN
yhjHCJi5Aij5(46K52y86plfa1AH6XGv9SVyR(upPiB4ZUj6yuCQreSIyMsQcfnKiR6kVg2iI7wkEMOJ
GEX33UJvpQferNgPpR55g96b9HIYaHbBWsXRsdaO(ZjDOEYKPtq1AFvvHzrpAKKENiljvyTNPu23NCUg
uE9ihyUw(I)s8lSGSM6XKcPcQX(GujORKOStELpTeCgfr710N4KwHKZsjH5gw3Zon2Barw7NOpt(WoXB
uEa14aR04HrTjibBvB6mpxjoCrZ1KDNx6eOSwY1ahMDrNwFC4U)KLsg0700AHRxH)wGnGaFV6pTK1tGK
El4HkQPvGdNSQ2(ufPgochIcASBQQBfGz)ItbNtkup8l774PAsqBASZO8AwmiMSUhE5hYbfQYEcRvTbK
0EhBBws)XDXjqn3zKQBf8yp9xrNMNQ61YPBGavivqWOP)dYJVFihXbaseuq9w4j6pRlxC6p)bCnG9ALf
mPX2w00zOOT2roc5tur1fo46Ny5UDlzlOTNNIc3pugey18FjPTMSTZoIU1CBWvWsSGKFTsW)6j(QAHBm
92e2)5JHHQWeiRvB3WupHGHXpJk8NPzNuvpdWjQVp1Yj(2fNqOFV2gIj)ItG5GeKLrd9mqtETViq03pa
4LXPnrLcu2t94eHChbn2EtI1dSeYf4KoFzojUU89YVxicDl65jVEYoIHSCCl40JsDgGg8QsbIRJVVbk(
N6bwhPokiRxQda2jIWPQoBVSGLUDDvBaiuxf)6LEgt8EGfznYKr4oGpOUyiLrj7WyQFcr6U45g9Oes)3
NeoEPq9zFVD(CrQmnItJSAS9Zvu2fghriTkUJFhPWzu0mIYNfMs7xqd8ExVX(8Us6AOD0w(5gXEXt7)C
HG1kRhaBClQemahH4g3s(H1YWoP79OZKLGSWZPMDnzUQ9ZO)l)IFCCTWmpbvL3dGkr5jevXpmxD3l(EQ
(Ox6suIaAZCdbZ8(sni)DnJgoiHOj56xvc(NwRgYqBEsnNZ9tioFU4dJPk(PXXWWpqwvAZ7LJ9UM1dkP
JZtO9iI4k6qOd)clkRvrGpLU9GF2rnf1(IW74xqwAVqAip53xgBlOTU)QQEXqk9JxkpOMdDOxDduZDXL
AQQB7s)1LP5NtB7aTvTyplE9upk)uUy5ZEDGzaHXpDlCPbvNGE9ald11IAdRXeq7qtDOl4b5RC0HO(or
jzLAUbG25QAHuiDC1Trjn2dXi8RxJ4Zz1p8lQP0rUL6NY7(pfzWivT3TE3imrZf2j)m8a)M6QgmUENsY
1XDGrRDcTx2(z9C8BBuwQJREgb1FI7CniEsV0eiITQkRiAVzFNo85PW1KZgnL(OrdYj)2oH0KqnTzo5H
lw9Mntx)GBM2ED7wn1kVYlUy1Z)xp9Iv)xxWxJvUSJNnMSxNZhR1YMZhRvk2ZhRDTK(S5X3FMZx3w7to
FETURC2yYEdpBmPAWNdVgh48XAxsIVG2O8nohETZs3N9T8bV(851ovNNJFTBr15FBRD2NVUTnc9z8a(I
H958aS)1pdN5dzY5J1ohrFb9g(c(mFHKo)BBBv7C6OvyQZP3w7lpFETZL3NTU8oMp)BB3JSpJ)XN37pJ
VWno9ZPx)xOx1UzoFMCJBdYzJ16j1xi2(C1kP)3FPk05Zt)Nl()(

**Comment by mbattersby** [comment]
Thanks, it looks like it should be working, I'll check into it as soon as I can.

**Comment by rursache** [comment]
same issue here, same fix as @rodalpho

**Comment by rodalpho** [comment]
Thanks @mbattersby! Switched from using a WoW macro to implementing the same functionality inside Litemount's macro. Pretty simple, shift=yak and alt=brutosaur.

```
LeaveVehicle
Dismount [nofalling]
CopyTargetsMount
ApplyRules
SwitchFlightStyle [mod:rshift]
IF [mod:shift]
    MOUNT Grand Expedition Yak
    END
IF [mod:alt]
    MOUNT Mighty Caravan Brutosaur
END
SmartMount
IF [falling]
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  # Last resort dismount even if falling
  Dismount
END
Macro
```

**Comment by mbattersby** [comment]
Nice work, glad you found an alternative.

I should probably point out you can do this with LiteMount rules too.

In any case, I'm going to close this off. I opened another ticket #264 for the rest of the problems with macro, in case I can think of a workaround.
