### ISSUE TITLE
Several things can't work with macro /click LM_Bn

### ISSUE THREAD

**Issue by mbattersby** [xod-wow/LiteMount#264]
Bad news.

Blizzard has put significant limitation on what LiteMount can do when called from a macro compared to the keybinding, and the following will not work (and possibly never work) that way

1. unavailable macro
1. combat macro and the default combat actions
1. ~using PreCast spells or PreUse items~ should be working again, except for in druid forms
1. ~restoring druid form~ should be working again
1. directly running Script lines from advanced options

**Comment by mbattersby** [comment]
It's possible the default combat actions can be done with a combination of OnClick and SecureHandlerWrapScript, but I don't really like the idea of double-maintaining them forever.

The other things can just never work unless Blizzard change it back. Such is life.

**Comment by Hayato2846** [comment]
Hey,
before Pre-Patch I used LiteMount as part of a Macro Slice in OPie. I followed the issue in WoWUIBugs but I'm still confused what will and what won't work with TWW Release (or Early Access) and the new limited functionality is active in >= 11.0.2.55399.

I don't use any Combat or Unavailable Macro (beside the instant mount setting for Druid's Travel Form) and following Advanced Syntax

```
LeaveVehicle
Dismount [nofalling]
CopyTargetsMount
ApplyRules
SwitchFlightStyle [mod:rshift]
IF [mod:shift]
    IF [submerged]
        Limit -SWIM
    ELSEIF [dragonridable][flyable]
        Limit -DRAGONRIDING/FLY
    ELSEIF [floating]
        Limit -SWIM
    END
END
PreUse Prismatic Bauble
SmartMount
IF [falling]
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  # Last resort dismount even if falling
  Dismount
END
Macro
```

Will this work again or is this part of the 'limited probably won't work in the future' part of the change?

Thanks :)

**Comment by mbattersby** [comment]
I'm not expecting any more changes for TWW release, all the limitations were applied in the 11.0.0 pre-patch.

So anything that's working right now will continue to work (until Blizzard change their minds about what to allow again).

Other than the `PreUse` everything there will continue to work for the foreseeable future.

**Comment by mbattersby** [comment]
I think I've restored everything I can now, the others are fundamentally macros by design and can never work.

If there's better things that could or should happen in combat I'll leave them to #268. I don't think there is any point replacing the macros with a way of running lua directly.
