### ISSUE TITLE
TWW - Druid Travel Form missing Skyriding support

### ISSUE THREAD

**Issue by Hayato2846** [xod-wow/LiteMount#265]
Hey,
Travel Form is right now flagged as no Skyriding variant in LiteMount:

![image](https://github.com/user-attachments/assets/7528d498-a995-4138-89f8-1cce8cc2f756)

As Druid's Travel Form supports both Flight Styles in TWW it's currently not prioritized over Skyriding flagged mounts and as such is only usable if you're moving while pressing the keybind.

Would it be possible to add the flag to Travel Form? With its current state it's no longer kind of limited as before.

Thanks!

**Comment by mbattersby** [comment]
Can you tell me if Mount Form is the same?

I'll get this fixed up.

**Comment by mbattersby** [comment]
Fixed in 11.0.0-7, thanks for the bug report.
