### ISSUE TITLE
Soar Issue

### ISSUE THREAD

**Issue by ryande87** [xod-wow/LiteMount#266]
When Steady Flight is enabled, Soar does not register as a valid option. Soar only becomes useable when Skyriding is turned on.

**Comment by mbattersby** [comment]
I tried steady flight with Soar on the beta and it didn't work. I assume Blizzard have changed it and it does work?

**Comment by ryande87** [comment]
I am sorry I didn't see this earlier, yes it looks like they changed it. I saw you added it to the latest update so thank you!
