### ISSUE TITLE
Missing option to export profile?

### ISSUE THREAD

**Issue by CloudyMcFox** [xod-wow/LiteMount#27]
The option to export profile doesn't seem to be there? Is there a new way to backup my settings?

**Comment by mbattersby** [comment]
It's there for me:

![image](https://user-images.githubusercontent.com/1300207/102855678-340e0e00-4479-11eb-8095-821458ffa57e.png)

**Comment by mbattersby** [comment]
On closer inspection, it may be commented out in the release versions. Hmm.

**Comment by CloudyMcFox** [comment]
Ok thanks, yeah not there for me:

![image](https://user-images.githubusercontent.com/18708122/102855841-3a997880-43da-11eb-8750-8c47a914ec4b.png)


Thanks by the way, this addon is excellent.

**Comment by mbattersby** [comment]
I will release a version 9.0.19 shortly with the option enabled. Sorry about that.

You can (and I would recommend) also backup and restore the LiteMount settings from the WTF/Account/<account>/SavedVariables/LiteMount.lua file.

**Comment by CloudyMcFox** [comment]
Thanks!

**Comment by mbattersby** [comment]
I've uploaded 9.0.19 with the option enabled. It should appear as soon as CurseForge approves it. Thanks for letting me know, much appreciated.
