### ISSUE TITLE
Limit Mount Group not working

### ISSUE THREAD

**Issue by Demothrin** [xod-wow/LiteMount#270]
Tried different ways to limit mount groups (exclude ground mounts when in a flyable area / Limit Mounts to Skyriding or flying when in a flyable area) These options are not currently working after the skyriding update, sometimes ill still try and use a ground mount, a lot of the time multiple times in a row.

**Comment by mbattersby** [comment]
https://github.com/xod-wow/LiteMount/wiki/Report-Bug
