### ISSUE TITLE
ghost wolf no longer works in combat

### ISSUE THREAD

**Issue by vioray** [xod-wow/LiteMount#274]
before the patch using the litemount macro in combat on shaman would use ghost wolf, however now it no longer works in combat. the spell still works, just not the macro

**Comment by mbattersby** [comment]
Yes, unfortunately with changes Blizzard has made for TWW it's impossible for LiteMount to summon ghost wolf in combat when activated by a macro on your actionbar.

I suggest switching to using the direct key binds if you are able.
