### ISSUE TITLE
Receiving On-Screen Message "You Can't Mount Here"

### ISSUE THREAD

**Issue by Sylphi-0** [xod-wow/LiteMount#275]
What happens? When I hit my keybind, I receive an on-screen warning that I can't mount here. I'm in an area where I can mount - I tested by mounting manually and the keybind works to dismount. I haven't changed any of my settings and hit default, just in case I did and I still received the same on-screen warning/error. 

What did you expect to happen instead? I expected to get on my flying mount

Did it work in a previous version of LiteMount? If so, what was the last version that worked? Yes. I'm not sure but it was fairly recent - within the past 2-3 days.

Please do not modify anything below this line.

--- General ---

date: Fri Aug  2 03:49:25 2024
expansion: Dragonflight
build: 11.0.0 | 55939 | Jul 30 2024 | 110000 |  |  
version: 11.0.0-14
locale: enUS
current profile: Default

--- Player ---

name: Riyoko-Skullcrusher
class: HUNTER
level: 70
race: NightElf
faction: Alliance
spec: 1 253 0

--- Location ---

map: Stormwind City (84)
mapPath: Stormwind City (84) -> Eastern Kingdoms (13) -> Azeroth (947) -> Cosmic (946)
instance: Eastern Kingdoms (0)
zoneText: Stormwind City
subZoneText: The Canals
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
```

--- Debugging Output ---

```
  * found 87 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Ground Mount
  * found 129 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Slow Ground Mount
  * found 1 mounts.
  * WeightedRandom n=0 all weights 0
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 23.53ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,0
  Dispatching flow control action     ELSEIF [dragonridable][flyable]
  * ELSEIF test is 0,1
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,2
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 218 mounts
  * trying Skyriding Mount
  * found 87 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Ground Mount
  * found 129 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Slow Ground Mount
  * found 1 mounts.
  * WeightedRandom n=0 all weights 0
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 22.38ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,0
  Dispatching flow control action     ELSEIF [dragonridable][flyable]
  * ELSEIF test is 0,1
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,2
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 218 mounts
  * trying Skyriding Mount
  * found 87 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Ground Mount
  * found 129 mounts.
  * WeightedRandom n=0 all weights 0
  * trying Slow Ground Mount
  * found 1 mounts.
  * WeightedRandom n=0 all weights 0
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 22.37ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
```

--- Options DB ---

vYvstY1XX5Fos6GLQ9fFtCrKsGyed0quoKdpbEyMhW0c90nCp9aqOdZpgh(GJWHUQB(e(J5C7RQMsKWJ
5sGhQxwzL7zwzvV(s)Lp)YnxDZYr(pF22pC4nhE4f)tp8InV5(D7U6493DZQ8QRoC7lxo90LRoE4Yn)Q
R3E3ThUF)PhEX)Q8NRx)V9WV7xD3PdV9wgIF4W7wxE367wVz7v7wF43D5j6F386DhE5YogX3D)T3Ey)N
ZGFh93Vi2tbF)YlAxErVfCPlVWNV8IKp7RxEriqaec9cnAtHn4ONP)VvDD6pi4loxGMcdFm7y48bEQ1q
8YlQkKEc70yXq2jJft1Eww0qmgP)WwtEa(r6zAYEgR(sGMkrbHMpNtY0lPsUQOm3doE54vTg5hzQlKYv
HOO)EPKvcHGnYRQpYSsK5tgTHEYOGAoZSk9FXspL92A1RvzqFnXRFqEQeuadHwxedSCQkZGO5wGfKg9h
JcPscNGkXi5GVJNcS4qEkffQGLsEL0jcR3LjN71wtj9sPLQczeY5IWq0GeNjYi6rpjD05xBrwyMmqlkD
0kPmpBqEvtMLBUItaHLVDDubIMWx9yHrvr5WOQjt5MqaPy350vLLTvLv6opZ9bvsLcc29ep7e7nvsQIh
FxLuSKlquiHDpZrrFI5kwmfkvAMQfklndMDdjAAQfQyd0GXMmpIGZcpgurRP3iASz8DOtIe998cySOl6
zbgBgw7bMEyQJeUSYrFQO6Bg)nzSORgy2jyIOQXVM4KXSOqnRvVzoKQjXWLnyyK1vBNyUAqWuR5eeD9g
ZmDrIgvNiw2g1jLtv(DSUT1BDtu4tr1oHKXQ3kZpPgZHnzrtUbzNudFIcdSgWRco2CXSyvoO4dMNzIvk
zLGHWHOZHyQlVT47M3frIQ5brvm2vnxS35Nnpf15mtw1DfaIA9LGYK0shnlvIYJQSNw8GqIcQIQ8Mz9u
WWvLh1exPlHrFlzrVAKUXPuaBwM1ivetQZN4KQfXJ4KQrjzXNGzapPJ6d3QwQRdtsr2TNJW0lC4pjihH
2WqGNTyQmYYdjPgamsiInP8zdwg9QPwpkAg(V3Z9SAu4D1mR1sk6kgBsrzlPP0TcPB1qxX59jyygAMzr
j1umv4aFjd7vZMSjgTmTuC9SGDjstdEMXezhu0hdIleRXIc)iIjxTzEdor3iedfEYRQjNZlIgmSIvHav
FCYeV3NU7QHGaQQO9Uw1SoiQvJZiy1c5ejNbZqPMlIaWzlGQ9OXeVfwrKsonkrHstkHUiqIDiy6fZTGK
KMuVKiFCveruQOa4ikKo0RQz2KSosiAHpZ1wsefrhXYXrUrZiGSOZnlNr3fLyCmWfY8nk0cLEiRjCfV9
eusnXDVN1qhjlqAQhRwWjVV5A9lHhFsv0jsGgq8tAT72JcgI6tAGwjCV5ds5kTaHKFrqdUiKan9uqdKW
b6ON6UIynqauD1QesM()g5xyrQiTqQAHRzTd8UJK8RP0llHs6mPaKbj(fdfzyvGQusBMv7EJ7l1A1m7D
rRKe2OOmJbYc7MIPoEQLGTsKQ0WmNPy7M7czcOseFvIrYzdPGFEiAjPOjXiQJZxX0axhIfRlqP(ex3MA
56m2LGbgjuGXQnkzpf9MFAdE8SPvxfQbrqlbAZ5k7Cjr)j8Aps5mGhblCv)uoXVekmQcxlijtd2JK1sw
IDcIizEvTHtdXtEjZKt8v0G6cMvZ(abBwdegZ9MaQj27odIqsdHqJPghMeUBfgLlntxsXSBAico5RhwN
mXWRbhj2Q5mK8iQbhNMDdsTwEmLuqPzsJiM(8Of260eUnnIUWQjvcifmKfjozl1edXlLiuotEMkwewUM
wDqwWYseoWcxYkVosMfNlp0tvjWd9F1uJlYtcxioss1wHamv4kXn7YuRwvtSIw0ReiHSjmhn2epGYnJM
XkvOL4LX4GslghcZsWKh86QUdCgQKLiij1j01xlIf6XyXkMKqBOOKDGI9wnzeJ14O22Si571mBtwmKAo
gr1hSlXhejxK3tZvh2)QTV(7wpE32d75xVz7(7oTS)QvzJn(l38KLDBV96dhP)sN2zZMnNoC823VD)1p
8IV8URwE76dV4vhpClT7RthU6nlxttKe5KZYMNV9427E1YUhEXxTthpWHV388BO580L3ZCfXEB(SJhEZ
6Ecb3C4i9MnxTUF542de4CXCB(JlhPfG2P1dV4lwo(M7uOOT791hoE9kdfjn20)LUhEXfF7x(Wl(5xS(
(hEX3UB5dRhjA87F76XTRed9lKj9LF)2DR)mcxpBD5QByfctsp9WRV)Hx8BVB3cZxFXY2DF4Hx8RpUUW
I7greF2ULREZrIbP3U(2t3CNGmMEOPruh987j6KiQ7FjB6rH2281RlhPDBEGg9eZY)(DeU)QdxFol691
cjtVz56dV)2dmE(S7pUvKzhPTxE9DYw)UCZ3segnJfwM1Hm872Ey36jwqS7ArArYH2V0)dKtNlnPq3B(
TxTsB2990c95BprAfAL(50C(fS)dL8DZV(4RVx0u8Q(0LDxFC57)(7VtKg7LLNk8GyTD3SD9wwCEIeVh
ocPfLcVXuhjswvw)53qSX6rHWZmRUDD31Qc4UtSaiYMa7oWYLT7nr1M9hEVyEti7IL)YFE50IGbkKX)i
hqg)mo(93FIvF0FlZcO1BFlTap8INSU(2)zMmyJU1RUzzVGkU(InFXXL19IPnxzWMVEz3UZ0xF19lhVE
7c5weYuy5nEhBJrZ51SEImwwvRasNXwhZxnKS0lVy54XLtBFhRUgEzuwNna4nhUFhl8PKzB(I1LRVD7E
XfI341MVE7RV52fbaHhfU4cAWt3O6CkALqyKs)pTCCz3krgF(Y7wpUxPTp)ML3EI9dkNBkWvSU5IdhpD
dPuz0WBVDZpGZ4q9ualDfv7tw6Yugxy4MNCpXFKh(cpsNYpVHwQBFjVuSauS9zvbjL)13F1nu8cYCM0d
Bwjz7BiQKf2sOcQa4nFXYoI6P1(pW2kVCD3UpWsDk08MV6O4t(8T3seYV(63TU)09hxzniLUDZV5pAXb
i1fjP3EhZaFZ67yPFuYhqC6Fy31l3UWR(3S(6LR(Gzy(brXt7UFZfRIj(3rs6tSqLTH9EwBRIW)b(IO6
)(axm9sH1Fukd)pieqoan7xE7knTRnv8TlmwZmB(JAn)zhOa1BVI96AjGIn3V)9K4JvtSf(VzH8exel(
iBa9PKxCQSS7VBXezizC83XqI2PadYdV5M7jQ(3)QxTU)oYw)Yli08Ll3rmlH(NSD)RV(WT3Xf4q2jpB
51RVAlhBIKh3DROjPH380VJ0V72TLt(8JRnP6I7SbXHBVD5UBwo(dKI8gehAKHjC)NmKxKd5rByGw538
b1BY3O9RsS)UdV(iBp8STV6exWDN9mxF7X7ju88Jl3kXl8CcokR2BoW84xVC8LsGKKKHJcYWwZ)U73)6
DRIltGfHum8DSUiKPsD38S7Fjzk(nBFfXUF7HdI3qIZLHeKQj3fmVYkuhvKRKP6NrdS3mxfUmYXYOy(C
OIZcls8JBKQy)1KPcT4sRmF7XdVIYd(K1pWP538hpU(Ht3i2Ou8)vUhPFXY73ZS9ReFInp7dF8VzDz95
K1(27Py)KWM8LpEdf6(mi)MT)7BV)tIQFIg2oHydvYbjQ0v74HD7E5Y(1ZE)xU7(RxVA7YJHCE6YnlBF
9Jc0N)X)Qf0(NIYx(luTrAzeuyGBylTNrg3)4G8)XQ9VSD5W1lB)W9pgG)mYLE9oY(z9XaTOS(4F7tXk
FZYXp(FSF5tbYFIkFB)JIvU4J)x7(KcUZSV(X0Np9pt5r(uZNkA44Y2pniFy3BVz7JHAF629F8)8XIQF
eQ9jlxBILFcZxkS27E3YnpgAzZ7(4)nx1YJsm)ukU9H9)5hND)38X)6NwM(DuIMp(xV7XGRnF8)zir(j
TN2V)XXYpz7PtFsuDUXY)Fei)eO7I138iLVxS9nBpDZJb0tJiOs4tmm9OCesFlxr82tBT9qz9psA6G2e
BEVLoAZ1rDuRDY8EY0U(ZdATGuMLUtyEB79KVRaKs9aVtDaRoAK2NBmyaud2kynCNrqR7ArduNppNuAq
agsJubeXXsv03tBc1zRA0xQgzjWMMJAtJ2PQrSuMOwqNM2pu(1e)NN8sPpiatcfQsFL4blXayBAw8EIv
PzYziv3Fo)EABgnvUzNuMXG2QwK(3jawZshiVu6QGkEATy0eurN0FkrM1Kg2PIpVZaih9UjQ4gWW9Qjj
T9adQ9Gua1eA2zIbakywTQUywFh5fWAeiEufQcOgRQ9vbV3K)jFlylGPOsjTncYqDiA8JNS1Zx69CWqs
igTfH0cMzir4gryhDNjWuaZ(K348ITU(MRApwT1VAlG2onN0XkP7Emw5EvggJg1PW6UQsH9ymuMV3piW
6q008Z3hMJQpAhEbpPycCqKmUCgKXcKfXCY8(ivEjoLvMbFO3n)ezwHHyX8Ti1Sj24LY4ERZIUXjfWtV
KGdfjsCPoKpjBouedi)dUQj)7UsFIt4KuDHHiZETS6M4HSMCMRvdbCQXIj9j7DOTcvAxrGMcM1KDeU2R
nQdTtuGmByVoKOw76CIhEmmJ20TymPgetwh)DIBDopz(bDKC68zfQ5dZ0CZ4EFjyOsaqhnBCuUQKwHin
dl9wSyaPhGGjxQJv2Kvjes2oVjLx9gxBNEmtbDsaKhbuYJf0yq9WLzmgzou51E05QdbWKx9t)aJRSJ(f
do46MP0jxCik43ROQxZMNptit1xPmMtBid6d6yyUBrYTd1JhZAWQGNUCu(ImspaqBDqGEyekqwNZ3m9s
9rQMG3KXTkmTSJJ1jr3Q(2CH6d07hdAgmSF5i9N2lAGFDw21ZWiuZYVYNoJUuzkuPFq0MyIY4KQNnADc
RPriBatnlaa5N2Zvga9CVKNQWZ1FMrIX09g4uFNszvMmvEGDlrHD(RcOo4AsGMri0UEQQYSihg4BKQMT
LNCaIJ1h5KqeUwRAJXIhZCTszzcZbrCLC2u(umzi90tmWjwJJskSEJZJ6dipNDham6yIEiBziv6m37WX
Nh0S94tmom4tZrpY3dI6qqzKIphTsEy2lnH0sa58H2WdVoROjcBsEzhrsmZt(S)AtiHiTJub0CoJvSrP
CsYX8ZGQhWjgCk(NSQzNq2JwrucKMDCRpfPqq6HnODWKmZXMoy26LaYeo66yh4NH8Gdq6m5KD(w49EiX
YMkJndYtQdrk5wSm0ZOkakvrlniAeGZNhPY8ZK6bIdgvjM8WqZLS6WIKxKXmCPFouix1cjiZYKqKvv3S
A0ZcMrf562qG5s7milZ3pfmWrKFCKxgUpueRakpKkKvUYbxooWfJBAMtFaLKsbPBdxneEIVvhU4CsMmA
gvKYhhMIieNzgvG97mZbk(v2sEwYjumdplu9CZOpzvBtuvNJ2hYndtoNL5HQlmz0NNsO4glVvShvHwko
dguhfYMpB(9XIIrPTAuV88BVHrj(ZqfOVam9KrBdsDk1YL57nwPIOM8GNr2TzimeixV)lojRsFu5Q3BP
(Ll3eSbdDR2aCf24P19OYtcbWAXUjwab5blgYteKhmZuzekZhRtq1rP4bU5RBZxBZpqgliXjN5BcqBcG
zJ1bs5Y3mp6G0Vr9XrEzkAz(mUEASa1czdOZNSkrbemMMKVvZOS8iBgjG8tynEXUVkyAihVZzgH61ddq
2NqokFcXoySAH2PDgbvKaqyonB0yFuahZT9jgWEoIHYuAI9JvOqOOWx50(emqQM0ujBEh4kibaod2Zet
LjrA0qdQowH0Nt6mwFQ7rrteaJIMiD3zlWWtcghHIpEgDLpJjnxHejsstK1MJozsKdLhff2qvgy(v(kC
ak8DIBcQ5Isb5Zt(bICgaBXSZ62jvWcHKDVCXSaABJIlSlJRTStxuedHyxRIgbbgNt2Awjh1C4mrhc96
AOZdevBgOm(TYXci9QmhlHc3Ahdt2vcrPVk0hUmewrQkJ80aDyNq6PZWlIT5GiGQsTGYaZJc2PKeLZjN
PNvcEXTacV7gnxGJ0pjHzFwcJAHOcdqXVUSBAZyL9XmXSPsy)qKbCgfTQ3QhbbLHgLNLXVK5jKOuykyi
XJAIukMQRoWqcLSuTKn0lZzKmZdZt92qXp58WMMcYG9aYDaYeNUkYQWmqzYan8iKB2TMXPHdW7T7rKGQ
Gh2w1C1PKspGEyGBqLTQOYsswafd51ACfvwo2SRF0zf72(jd2rp5OA3q)e4lJLTuLr)b17mL7YXT7MFK
0QNZFweiY51s2tOkykBQeQimYOYoq1JmgmYQ7JOkwp63d9upnNuEmPrx)0R1KaqiIyGbSTuzw1jBDgUq
HnOByYGMTaNRshK2sSFojduMdBdd3K7m5MsH296gZcf8tvPzKvLQTCWbOBP2fVIzBYPVoXVPwTl5fpk5
6AU0LshnEK3fec1HgbiOppLvqSeBi9vqVJ6cbM7T6CT6t0IhtjSLkgdJOdJygUq0ib7EglmJhLmZcoGu
h2LjH02zJIWUJml2fOZW0zRP9EkOVBqtiKMDPUDxIlCQBCjfLxtfwosNLqVq4jHQWJZwZxgHUgnmIDmm
fCA0CiHOktbXWDZxMcTAysb550Qtamveh43pbOnbygD0yh7whdqpBXqvITzLpODCSLfQMX5q9f8SmXjf
LcB0GFVrH1cQOn4JXrttC1rXR0keM4koNgs4wQJGMou2HaBAcRnngugPgS(jSwOKKZz(m4Q2kJ2QqKhP
4dgSHWzV3ixbTPjLJ8VrukbR)nEpKjOTCmPXP0OFmmotHG6E0pCgmPPI2m16vekGXVXx1ioei7YQJ5ak
X1hn1mw7JD(48NHQ4CvHvDiozfKpLYXHnKXJMNZc19ZlNrciyhr9OLluHiOO3Yi1iBrGqfjE4bZaFLkk
fY(OmSjbJa(96sLBfS1osdIAXOOQiZyRpdvuCwcv7RUWzkJ2e00exMyP5QyhD0JXbznclfg7JLEy2nwq
2uf3ypiuHzoutDkhN0nCeS7tSaBdKiFQbZnQo6AgpAFclsZ0ZwOPktUkX6WrjssDS5ssDa7zkS7iYMFe
TXUl)8O1mcIgtEOpy8psV38y3PLUHaUzutPTTufNzI4TpchmDZgR4Taqueuu9MSXjyonACLDRUn2ZOzA
pK(WePt)Tck9NiqyKxGtg3kbBdoSuDe7x)8NCAGeuDG9rLiaGTbYHirla5opHqK8gbShlj0KiIeqqyUd
ZMiSOxpxE0Cen2iNLu(E1ijnmOq6)aFeKkjWnSQGQDzFYjSw2v9lCHxaNxmx8Ilb2tavG2OcXqhHV4KE
iAljBY6SIvSvizRooWcZ6XdwtuSpamvWKM9JchUgF73sZ9wc)x3zgCK4cMzrCWdSRComXRPh9P4OUHs3
OMuECAJC5sLbAhfwPFtC8J2xLcJwULv9jAldsavrXT3cPnZUXosjyhJIt(KRF)SUVGZGKHf8tioBdAAS
z6s2HOmnKDG3Gck5Y((7ekt)kdLhBioxY7ZfeZECA3KRxgDtkggDHSI(xWMkMWLOv08u2c1Kn0USYJDw
HttNYfgHQKCNIJk7rTK94isDXbFBgsZnnoRRMRFefO5rfyXZobmhk)HiLwPnrBBcQHa(yjRJhh7NRxgP
LqfUK(a9(lvBMJfXGb0OeA(dBIaSfPS(YhhNsag(5DHzY1qgDIxWAyiSYJCnjCq7uHjOd2CAJzLL42pq
IlCeVifnhtefBBFWcaRJklMNfT(rFysl08qgRgS9sfwu9QFe0lItlrWRTW6h2LSco0IBYCiHdqIegLPw
e1uLhjbJ6xrjWkCqiNc)KATehPwSpQig760(U)ee0r1KCaHrvSyVSIhiCW8yxVb(J9qzb7ZMKbL2RDyu
YXytr6xvLWwECs02hDTkHA48aOcQgD)JCLn5gRLIGxWEM4(SyAw9J41j5irzw23BMq)uPZiysevSWTRd
D7OMqHA8EhGXhh)gUxTYzYnSrm7t)vaiHD2ZDKb1X74tp0eSv0pJ5jelhyqzcQMHW(ITCwu90a06zGwe
qzpbC8wufnOJbejIepmSvnXdLydjoq2mzphM6I(Nr10KJWOY(e24xPwmwSn7nPBCOJuXlWNHpU7rcBSX
rkrrECNy4JpqhnoAzJCAAiLpfeBgKvxv7ZCxEDdxzjbRtVlS7gwJduX1GkpkxXeyYn6qllUvYY(q5bw1
h7fuEJ9HW7mhQYar2OrY0B4OZ9xYq1yp6snnZTbHEMr(eHPjFzSJJ4zL27MSLTUu5WO5QbS1DYCa(u2V
ZbUlXxyiw0rPdMhjxPPz2edyhY8ELnnmhF1mCP8SUHYgT0Z(4(mmzkf(2xHhhn5Ljtlcov)zDeQfDH23
PYlhk984krmQIcFHEYJuoO8edM1M9XfZaW(BMcUIuesKsO1dZneHYIPiArm)X9VW(aTDCQ9(qLmBhmtu
ijDBy01hsA7RM0DPUVL0KRqjwXkoGY4O9J2xONi2Wr)sQfuqifzf5pelHzsCKFjJYySpFBNQ1atXhgR(
E735cN6QvMq6HGmIk8Mz7J9ZU)gUXTERIoQj7O2OF((JyQk93KdNkEHRcHmd)uuACSlugTXPosfTvmwb
5x9epp40(4ucSpgwNzccCPFiFUlX3YVsGP4OEfC)sysfb(sJd7HspHRoweLZi1lbt8oICwjkeUYZQHzh
dNU(zSTqY(dULbPmmtavh5KSFUlCQzl6uzPJ4XYhACCinnteU)TomRH6KpiT52znqRXEbyTItDeF(Ymw
PuEOh60o4G(MP22e2HBCh9Gohq7W5qR5XSgKiUlzCO1(eP2CIb38y(X9NiQ)CgWGwcWYwCxh70jA2BjN
hMw8hIUzfBFzQo10ACAxbC8mr7WV5vW(rhWw2ZmOJt0ApY6luvDeBppJtd23LdS3Bu9zwg2UC0V2vEnT
p4yGttVWLzAXEQJDOMQJQVdZEtG7FN0EhKMCS3E7J8vEFC06q((LG0jo)zvpa23(nhqi1EEAU2hfwItq
JTrrZ84A2tMKOJEt6hXJRES9a7x6bGuuemvJjQ8nGMAfOQWDgo9tUhAmkDcYh7CJOb6VNgaNiEvh3rBE
RNPZsTaPgUMqcA1vGJHAEZ2V1kqOzuqE0GFUnmOY)ko95yACHYkrCcjCF(X1XMl1eBjXH27t1oHO8sxu
6yAWOd)gh4u12zht0OTI(cUBYKBjsPO)4fXpz)um4Ue)cSiZFCM3SiaxHio7fOa)OUw7Zl3P7ecBupH7
6LqawLubCP2SpdCE6Kzfgmd1j(rNqg8Shj9Lrvm6Bdb74C8KpapB9HKh)MeWpA)ufyidDaJ2WbYjKWny
ILRMRdhLXMe7Azkr9xYjMRCqaZ3zr06O4ylaCtdJtX6z(yirqe37Pe3EmlkhBVAyGua4kz4Mn6IVHIQG
X(fIGbTLhNzNREowN(Ri)L9BFIiaW2M5f9S6J7tKokkchKlJ0cKvsMsokxocFhwdyv1WOfxathQQHMvp
mkvdEK4NWcrW5HpT(RvIikk4GzWVeacTKg3qtMwl4r09f7hDcMuO9QJKd8wPJ27rXoYXKzAGuevRYB36
m2cxX288unTFfj4hTFptCJFFa4b57uqf4A0Cf(JCWCDC9X3qcHxCucCRf8taGZ7p4SigxzGuejySFXuC
xA)MS4K(SKuDKCxWrqRiUaZHiQHwAQOXwjK(MikC58XpBcYcvhQdsBHqD2VwkozhbJ7BCd3kKwjooQg8
Xrqr3qsF5cnm0Byx5fYcYSl6OptScYqV9RGJWi(8ikxinkMlIYztomQ9ZsHZ(9gZn(DCqeNdBgUJdZtE
fDI2(XZYW4OaBkFXiHAVb20JBKofUDCdlOXqp27XXnA3tuG5SY3RbzANUCZ1637K9zo9bDu(FV8)9d

**Comment by mbattersby** [comment]
Somehow, I assume by accident, you've disabled all the mounts (by setting
their priority to zero in the mount list).

Open the settings and go to the mount list. Set them all back to 1 bu
clicking on the right arrow in the header.

Happy adventuring, X.

**Comment by Sylphi-0** [comment]
Yep, that did it. I don't even know how that happened but thank you!
