### ISSUE TITLE
The Primalist Future allow flight mounts but the addon only call ground mounts 

### ISSUE THREAD

**Issue by milotic** [xod-wow/LiteMount#276]
https://www.wowhead.com/zone=13992/the-primalist-future

use the macro in any place this the map and summon ground mounts:

![Captura de pantalla 2024-08-10 135102](https://github.com/user-attachments/assets/d7a9693b-8874-4379-9067-05351f8b539b)
![Captura de pantalla 2024-08-10 135202](https://github.com/user-attachments/assets/f2505e1e-b70d-4197-abac-74da254ebe8f)

manual summon of flying mounts:

![Captura de pantalla 2024-08-10 135350](https://github.com/user-attachments/assets/2795cb6f-ec55-4564-93eb-25bbc9225cf4)

**Comment by mbattersby** [comment]
Thanks for letting me know.

**Comment by mbattersby** [comment]
If you can help please https://legacy.curseforge.com/wow/addons/litemount/localization/languages/100/phrases

**Comment by milotic** [comment]
@mbattersby done, but the cloudrook dont have official name in spanish es-es or es-mx, the correct translation should be "Grifo de nube or Roc de nube" but blizz sometimes use weird translations.

**Comment by mbattersby** [comment]
Fantastic!

That's totally find about Cloudrook, it doesn't need translating. Once there are some in the game (TWW launch) I can copy the translation off wowhead.
