### ISSUE TITLE
Maw mount not working?

### ISSUE THREAD

**Issue by polski-g** [xod-wow/LiteMount#28]
I got the Corridor Creeper from level 8 torghast, the following line in my advanced macro has no effect:

`Mount [map:1543] id:1442`

WoW says "Your mount ignores your call within The Maw"

**Comment by mbattersby** [comment]
Please provide the bug report info:

https://github.com/xod-wow/LiteMount/wiki/Report-Bug

**Comment by mbattersby** [comment]
Also, LiteMount has built in detection for the maw and maw mounts, so you shouldn't need the line.

**Comment by polski-g** [comment]
After updating to 9.0.23, this issue is no longer present.
