### ISSUE TITLE
The Dawnbreaker - Can't Mount on First Boss

### ISSUE THREAD

**Issue by kayti-wow** [xod-wow/LiteMount#280]
The new TWW dungeon "The Dawnbreaker" includes a mechanic that requires you to mount a flying mount during a boss fight.

You receive a debuff called Radiant Light (449042) that allows you to mount in combat.  
> Radiant light bathes the player, protecting them from Encroaching Shadows. Enables skyriding, steady flight, and mounting in combat.

However the LiteMount keybind doesn't summon a flying mount - possibly because there is an earlier check for being in combat?

**Comment by mbattersby** [comment]
Out of interest does the summon random favorite mount action work correctly in all possibles cases in there?

**Comment by mbattersby** [comment]
Does the buff get applied in combat, out of combat, or could be either?

**Comment by kayti-wow** [comment]
> Does the buff get applied in combat, out of combat, or could be either?

The debuff is applied as soon as you have cleared the two big packs on the ship.  Usually you are out of combat when it gets applied.  Once it's been applied to you it will stay for the rest of the dungeon, with the exception of during the boss intermissions when you have to fly out of her bubble within 15 seconds or you lose the debuff and die.

> Out of interest does the summon random favorite mount action work correctly in all possibles cases in there?

Yes, Summon Random Favourite Mount does work in combat and out of combat once you have the debuff.

**Comment by mbattersby** [comment]
Looks like The Dawnbreaker is a fair bit nicer on things than Tindral was, and the mounts are flagged as castable so just calling SmartMount works.

On the down side, Blizzards overriding of IsFlyableArea() to true once you have the buff falls off if you DC or reload.

**Comment by kayti-wow** [comment]
Oh, yeah I did notice the reload bug.  I was testing using follower dungeons so could use the Teleport Out of Dungeon / Teleport To Dungeon feature to fix it.  I didn't find the solution because I was so focused on testing the main issue.

**Comment by mbattersby** [comment]
11.0.2-2 should have this all in it now, fingers crossed.

**Comment by kayti-wow** [comment]
Tested as working.  Thanks so much for getting this done so quickly.

**Comment by Eviloverlord1989** [comment]
Sorry if this is not the right place: the fix you mentioned for Tindral in Actions.lua only works if you have one of the OG dragonriding mounts with priority 1-4. If all are at 0, the macro won't do anything during the fight.

In case you need to repurpose that code in the future.
