### ISSUE TITLE
Amalgam of Rage never summoned

### ISSUE THREAD

**Issue by ryanm798** [xod-wow/LiteMount#284]
Using the default keybinding code under Advanced Options. Have a couple flying mounts set at priority 1 (none are any higher than 1), including Amalgam of Rage. When pressing the keybind many times over in a flying area, all the flying mounts with priority 1 are seen except Amalgam of Rage.

**Comment by mbattersby** [comment]
Does this work in the chat boz

/cast Amalgam of Rage

What if you disable all mounts except that one, does it summon?

**Comment by ryanm798** [comment]
"/cast Amalgam of Rage" in chat box works.

If I disable all other mounts, it does not summon. I get the message "You can't mount here" on the screen.

**Comment by mbattersby** [comment]
Hmm, weird. Unfortunately I don't have this mount and probably never will.

Can you go somewhere that it works and paste or screenshot me the output from: `/litemount mounts Amalgam`

**Comment by mbattersby** [comment]
Also if you can make it fail then send the debugging info: https://github.com/xod-wow/LiteMount/wiki/Report-Bug

**Comment by ryanm798** [comment]
"/litemount mounts Amalgam" output:
LiteMount: --- Mount Dump ---
LiteMount: Amalgam of Rage
LiteMount:  spell: Amalgam of Rage (id 369476)
LiteMount:  flags: DRAGONRIDING,FLY (default DRAGONRIDING,FLY)
LiteMount:  mountID: 1596
LiteMount:  family: Gravewing
LiteMount:  isCollected: true
LiteMount:  isMountable: true
LiteMount:  isFavorite: false
LiteMount:  isFiltered: false
LiteMount:  priority: 1
LiteMount:  castable: true (spell true)
LiteMount:  isUsable: true
LiteMount:  mountTypeID: 424
LiteMount:  sourceType: 8

**Comment by ryanm798** [comment]
Solved: I had a rule set up from a previous profile that I copied my current one from that was limiting mounts to a group that did not include Amalgam.
Major goof on my part, I apologize. Thank you for the help!

**Comment by mbattersby** [comment]
Aha! No problem, glad you found the answer.
