### ISSUE TITLE
Add a "skeleton" filter

### ISSUE THREAD

**Issue by Kanegasi** [xod-wow/LiteMount#286]
Similar to families, I would like a "skeleton" filter for mounts.

Twice I've had to redo my UI over the years I've used LiteMount and then disable all the "ray" skeleton mounts because I hate that flapping BC ray skeleton. Same with the shambling vanilla wolf skeleton. Searching for "ray" doesn't get all of them, since the shalewings from Zaralek Cavern aren't labeled as rays. There are several "ray" families, but thankfully they have "ray" in their names. Another example would be the Gravewing and Vile Fiend families, both using that Demon Hunter Felbat class mount skeleton.

**Comment by mbattersby** [comment]
I would if I could!

Unfortunately the game doesn't provide any information about the 3D models, only an ID used to display them. I don't even think they are in any data mining, not that I've ever seen. Not the skeletons, not the texture, not the color.
