### ISSUE TITLE
Transmog 

### ISSUE THREAD

**Issue by pottervogel** [xod-wow/LiteMount#29]
Hi,

I wonder if it would be possible to build a filter with the name of a transmog set. So I could name my xmog "GREEN" and combine it with a flag "GREEN" and each char with GREEN transmog set could summon the right color mounts. Not sure if the api allows something like that, but it would be cool. ^^

**Comment by mbattersby** [comment]
I agree that would be cool.

WoW didn't support anything like this last time I looked at it, but that was quite a long time ago. I'll have another look at it in case there have been any improvements.

**Comment by mbattersby** [comment]
LiteMount 9.0.25 now has an updated [xmog] condition for action lists.

[xmog:<SetName>]
[xmog:<SetID>]
[xmog:<OutfitName>]

all should work. See 

https://github.com/xod-wow/LiteMount/wiki/Advanced-Options

for using the Advanced Options to choose different mounts.

If you are waiting for a simplified user interface for choosing mounts, that is at least 3-6 months away.

Happy adventuring, X.

**Comment by mbattersby** [comment]
FWIW, what you probably want in the action list (assuming you made the GREEN transmog outfit, made a GREEN flag, and flagged some green mounts with it) is:

Limit [xmog:GREEN] GREEN

or alternatively:

IF [xmog:GREEN]
   Limit GREEN
END

You can put this at the top, or it's slightly more efficient to put it just before the SmartMount line.
