### ISSUE TITLE
Mount Type Not Recognized

### ISSUE THREAD

**Issue by rewzone** [xod-wow/LiteMount#290]
I'm pretty sure this message was generated by LiteMount. If it wasn't, please disregard. Came up when hitting categorize mounts.

> [01:54:03 PM] {232} Mount type is unknown. Please screenshot this message and report it on Github. 
> [01:54:03 PM] {437} Mount type is unknown. Please screenshot this message and report it on Github. 
> [01:54:03 PM] {436} Mount type is unknown. Please screenshot this message and report it on Github. 
> [01:54:03 PM] {437} Mount type is unknown. Please screenshot this message and report it on Github. 
> [01:54:03 PM] {437} Mount type is unknown. Please screenshot this message and report it on Github. 
> [01:54:03 PM] {437} Mount type is unknown. Please screenshot this message and report it on Github. 
> [01:54:03 PM] {444} Mount type is unknown. Please screenshot this message and report it on Github. 
> [01:54:03 PM] {436} Mount type is unknown. Please screenshot this message and report it on Github.

**Comment by mbattersby** [comment]
No idea what addon this is from, but it's not LiteMount. Best of luck.
