### ISSUE TITLE
The Dawnbreaker and Ghostwolf

### ISSUE THREAD

**Issue by S4mmis** [xod-wow/LiteMount#291]
Ghostwolf does not work on the final boss of The Dawnbreaker

**Comment by mbattersby** [comment]
Yes that's expected, the combat actions in The Dawnbreaker dungeon are used for flying (one of two places in the game where that is needed so far, the other being Tindral Sageswift in Dragonflight). So the default combat actions including casting Ghost Wolf are overridden.

**Comment by S4mmis** [comment]
Is there any way to make it work? Or do you just have to make a separate keybind?

**Comment by mbattersby** [comment]
A way to have ghost wolf and the flying work in combat? No, it has to pick one or the other it can't make a decision in combat.

If you just want ghost wolf and no flying you can set your own combat macro in the settings to cast ghost wolf in combat.
