### ISSUE TITLE
Shadowlands can't summon flyable mount

### ISSUE THREAD

**Issue by xiaoshu-lin** [xod-wow/LiteMount#294]
I didn't complete either quest 63893 or 65539, but I can still fly in Shadowlands. I'm in Chinese Server, not sure if it's particular or US/EU server is also like mine.

**Comment by mbattersby** [comment]
Can you dragonride and steady fly both?

It seems likely Blizzard has removed the requirement but I don't have any way to test it myself since the unlock is battle.net wide.

**Comment by xiaoshu-lin** [comment]
> Can you dragonride and steady fly both?
> 
> It seems likely Blizzard has removed the requirement but I don't have any way to test it myself since the unlock is battle.net wide.

Yep. I can both dragonride and steady fly in Shadowlands and Zereth Mortis, I haven't been to Korthia, but I don't think there're any difference.

**Comment by mbattersby** [comment]
Thanks, I'm trying a new battle net account as soon as I get to level 20 I'll see if I can fix it up.

**Comment by mbattersby** [comment]
Appears Blizzard have removed the flying unlock requirements for all regions. Thanks for your bug report it means a lot to me.

Please try 11.0.2-8. Also, welcome back to WoW, glad you can finally play this great game again.
