### ISSUE TITLE
Advanced level rule condition doesn't work

### ISSUE THREAD

**Issue by Honobe** [xod-wow/LiteMount#295]
Whenever I go to set a rule with a level range using the advanced condition, it sets the level range to 0-0. I tried to set a level range for travel form since travel form is slower and doesn't have dragonriding pre 20 using the "level:<20/80>" in the conditions bar as specified by the documentation on the wiki (without the quotes).
![image](https://github.com/user-attachments/assets/4ec126f5-af5b-4ef7-9532-2975f0aeb334)
![image](https://github.com/user-attachments/assets/e91d32ca-f311-4399-9e51-da1f868b1456)

**Comment by mbattersby** [comment]
Your syntax is incorrect, it should be level:20/80

**Comment by Honobe** [comment]
I see. Thanks!

**Comment by mbattersby** [comment]
![image](https://github.com/user-attachments/assets/7bb60a69-ce47-43ca-b4cf-4f9ffa203b79)
![image](https://github.com/user-attachments/assets/7daaccb1-86ea-4e33-bf41-10837165df73)
