### ISSUE TITLE
Any way to change the weighting of the priority on the mounts ?

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [xod-wow/LiteMount#299]
The priority system is great but I find it gives me way to many prio 1 and 2 compared to 3.
Is there a way to change the prio for each rank ?
Be it a new option or with the advanced options ?

**Comment by mbattersby** [comment]
The weights are part of the profile options but they aren't exposed. You can change them by hand by editing the saved variables or running some lua magic. I'm pretty happy with the weights, and I don';t like options, so I'm not planning on exposing them in the UI (or debugging and configs with them changed).

```
/dump LiteMount.LM.db.profile.priorityWeights
Dump: value=LiteMount.LM.db.profile.priorityWeights
[1]={
  [1]=1,
  [2]=2,
  [3]=6,
  [4]=1
}
```

You can do something like `/run LiteMount.LM.db.profile.priorityWeights[3] = 2000`

Happy adventuring, X.
