### ISSUE TITLE
Tek'Rethan abyss mount selection for druids

### ISSUE THREAD

**Issue by Hellzbellz123** [xod-wow/LiteMount#301]
i have added a custom rule too fix the issue but im unsure why it happens without the rule

What happens?
druid travel form (aquatic) is not selected inside Tak'Rethan Abyss

What did you expect to happen instead?
Tek'Rethan is mostly underwater so i was expecting Aquatic form too be selected like other waterbodys

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
unknown

Please do not modify anything below this line.

--- General ---

date: Mon Sep 23 15:33:11 2024
expansion: The War Within
build: 11.0.2 | 56647 | Sep 16 2024 | 110002 |  |  
version: 11.0.2-8
locale: enUS
current profile: Default

--- Player ---

name: Aqusing-Shu'halo
class: DRUID
level: 80
race: NightElf
faction: Alliance
spec: 2 103 0

--- Location ---

map: Tak-Rethan Abyss (2259)
mapPath: Tak-Rethan Abyss (2259) -> Azj-Kahet (2255) -> Khaz Algar (2274) -> Azeroth (947) -> Cosmic (946)
instance: Tak-Rethan Abyss (2689)
zoneText: Tak-Rethan Abyss
subZoneText: 
IsFlyableArea(): false
IsAdvancedFlyableArea(): false

--- Macros ---

```
```

--- Debugging Output ---

```
     1. CASTABLE
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 19.87ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * saving current form Cat Form(Shapeshift)
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 5 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,0
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is 0,0
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,0
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching flow control action IF [mod:alt]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 19.58ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * saving current form Cat Form(Shapeshift)
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 5 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,0
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is 0,0
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,0
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching flow control action IF [mod:alt]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 19.63ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * saving current form Cat Form(Shapeshift)
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 5 rules for button 1
  Dispatching rule Spell [instance:2689] Travel Form
  * trying spell: Travel Form
  * setting action to spell Travel Form(Shapeshift)
  * found matching rule 1
[1] PreClick ok time 2.09ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
```

--- Options DB ---

nY1wZXXX15Fm5bNurkPV3tZ3OifL1ngveY2vCkJIdbgaSfxSl9IfIb5b8BpFNEoFNEuvMPILkXH9LtFU
FR71x6V8xV8IRUB(K8NV8V)4d7oC7ZV)RF(9xC3J)H7M3Fug)6Lp84TF7H5pSF56l)MlpJ)5IpD64n72
V8Jlp9GSKxnFyE)U5F)wV41l3m)4ES63UCAE5WxE(loE44D7omF4H7o(LwZRp94URVB50h2D4lTKxnVF
pqKV00)8YNp)4xAYFD(PhxE6lU3xUFz(WHLVibSCE(lo5)q(6y63D86Rp(F)LM9BMVB(W1l77Z)hx2V)
HRoTmF)Mv8lZh2D1hxU(tZFzoZfl7b790UVW8yf3U)4hM3lYYhE8(7pE4vhF8Wzr2(2yiKCx(2e(xFCk
u7FgltnNF9txo3cx(w8385CnH)mIptbxf)zg)BlxAyeaeFOgMk91gAjFR2xGpMI5w)ZySvIRal48U20L
VDcZuCoNmAh4HqdGQT(fgf)Bk7tY6co5)utf5WW5Kst(jadVapVZLbgfYf50DXGaCmxnjdlOF1xIk2Ll
(agfii(i060umx9jDLaWDeou8XwUpDih9Y5diuZnH4lcXxYRCpFiLCtD0nNQcid9JCkv7uJCGUo0l(wR
SUNykRakuBfz795tPvXa4MYyfb3ItcHbuPfJHYkchctkQxtDMPS7PwB9JGlnTI5riUM6yrkvC5W6OPyj
VklkLowkC)IRLtDgd0bMAXozGdkMvDKGUhzSvImMQt(aXOuyvsdUQcsWllRYrG59TxfCcFsXYu2V(j41
T1rJIstyvdeYfvbSeDYUK9xdGlVkmXckPUWocnWCsPeG(RCSWuOmPyDUnLw1Bb93bMOgmjAirpXg3k2k
qOP8kWGxjriB8nLzavI4klgAWH1bH0t(cgsWS7QJhUz3T)5LtpS74HlfBKl2D4HZZhUAPB85V8IFeEwV
)6JNawuWF9xVdoA(M5ZN3J)8MJNE(9F3U9hwMFq0fNK1FA3YT)28()Wdp)(3T8W5(4nXd3h)63TCgUtE
(9V8dp9GSHmuaU4BVhUN3F9ZV)1DplVTZlU4VU8XFB3jbi)08UtYOWQB90)tWH0PpUS8P(OacE))MR7A
5v3nF)hwaoD8gXB18j50tGHFXFDgNXYhXsM)TLthKDcz6fVE(0hVz)89aQVA)YnN74eq2xE)UtxFA(Hh
2T)RE(9NLtTJDc(8hp(PLowgv85VmFE50NpE6JDEaukwh(IZhpS8BDhCW4laS)BoD8JlG8)(h2d27BH3
kCspEfc9CnC39INF)pJWhF9VE8(p8GOlvee50TpUYAtkyf8amRFzNa2jxu8Uc2A3d)f3D8KGB1ONCLxp
VhKoo0lUArCbFuuHeoYBoTSC3X9xdZUAALtC)XJyHVb8BaeOuJiNhpD(UtlhUwqbbFE1UZpTYE)17eeP
JBfNGOZF9pItcSRXA(2RU7OqPW1JCeNMV94G8XM(25haRdd9Ja9V(49czpvOC(pd(YURMNfPpyaseuKR
qheYrauCkJbNVDNaLh(daNwoDA(QU0PqXWRN)8Hpau9JlcCIIyy)8vF80XRG2WRx(0576AIIy7hVB()b
kN7VDgQq)Zx84PBaW(x6C)c4f7U9UZ3Gy8GxcdKZpcD1sgOfefRK7fZNeROSCi)hpEgjdi8TQyv9Ypde
4qxi1XQFEwe7RyQimE8WTZaWV54(9cHHiExirBVbIIo1oJyWVq37f3bZVLtlql4pc0r0KGtTV86)M9hp
I1(MhpDqzovij)5NU649IH(PHrHVaFpx8Jpcm5x3DsTPRuFE3HpcfMLU7yCCYrVs3VB5M9lxDU7cjueB
6(gE3rOUF6PUrrrI2V8P7Mfy)U5FtPDN)3X1fkbR8vh3T)M5d3scOBW)HJ32rNUAd0kV608NbS(zaPv8
Kh7fFcOoM5VSaQseTvSfVtmg6Z)MJijURVwmeF3cedqu)Q72joGeAruvHipxaE8TpTSo4z1E(u39K4G4
xGL0PN2o78vDjYBeVjDsU2t88Xp81I20VaZqvX0lwrDk60YNbbaRiHlTnV2EsTm7i85j4hfw2aZHjY3G
)(J7P)5vN0x8PfrV8)IoVFH4Z9Vbc(e4bD9QoQdPUKxfw49ZF6fbx8RE4Xpa3V3UCnw89NFri2dI87wM
pMZF1n7Fssa)R(73C1lYLAPORxcMLgR3oFKlIUIuprfBfl)3NpnJJgrSQF1HJBp)Dx)IjebPZiGt5BH3
8d3UsNAcwGv8U)0BV8I)1lfp1RjuHXU4V89)86GyNF4XZWX7l7QJmg2pjQc)5L72DfIA9dVE3d3RyZHJ
Ibnml)Bp)dV64NE6xNbUC(HvK9hE5N(0(NENWRF(hU4Z7oF1DVzV4e4IZpjr)(VU)41V40d3T7MZy7F)
B0r4ap)(1)PpXg60MG)ZpT7EXdYxlKXy2V9NU4B7Bvz9)FSXx)Ux(D)hV9DF)R)(3(D)7V5N(p)hcKJZ
NxPZ)FE8V91p)d9)JryZ73sw6SxCpmgv(16jzmuzv)tWYy)Xplrv2lHs)PLFdoNoVGp)RIf4kdf)TVB)
URLrH9ZNw3QQt7JomSV6kYFeYttr5JiYnTkFa)nLGDy9G(pjrjxdu8l7F8EbSV74v3SmdlvylEXhFcXj
7rDoVSUZ)0dqE6r1fH2kWN8EdM)eIs987Hnicg(87V20Ew(nHc2bpaknVUdt9ALbbp9No(8piQM9H7Eo
2DENAalzmQj1hsL8AQXirDqF)UukLCdBr)AkRExn7l6UCtbnptTKMEkNHuBSunrxKJOwCdssmOhaYhuZ
UfjR7MI6sD(8ytj78xZH3hlaVui1cL15LebYRli6lvfR6Rnngv3wW5uCfr8NcATbsWJ(0G8Z1Xb0meqz
qHk(FRdIc2uij7Q4u2YA1ocqBrnN9Kp1y5FXq2zeyYknrNDAkpPyNunx)lO4fvgv0nLsJv20pBENUaPu
mfuPEfhCqL9uAgthv(uxHfQXHdIIBzzOYNXXsvkj2c1X8k7nbn4vaKu5qc1qPCKKQBbk3BFX6AkTglBk
fIr9qatwvYa2gJg)iy8J1fcNZAbqPIEUiZ0Q(zvp)6VRUmFVwNEPTcurnnzRciwiQiAQRyOwujN3Biy1
ynt(X8HXORFIcIBQMxmrkicDhNUYyXQXlN8unOvIdELQphAn1mytfQcBrnDGSvzBYrPuVub76GiNhpTx
s0EbSeNAWQ97qwzsYBQdDTBgYNnNujeHjTbQoLKKcTDJtxzpqBYPwot0DsnwuUpuNP0cLNofjofuTjKX
dbeMwXo4RSQehkWvHE14Ocdr9R5QAf)B6cacNtUKWqOVSuopODfncoFyyaOwOWvsqTf6FwglyftZkbLR
A3gaMTU(qBc8R1jHwX6xfQjvgoHt0DRWjSs59knNZLw2i1SDiLX0ulqiR1v2Iox1OAJptZhr3vjfTtfC
Wkj1jvqdZA1dvF(vq1Qz1AxWKHiRuS9mzeEZWdtfx5ZsBfODrMESd1wsBDrknnLgum9DtfV(kRJ9RQBP
Mf9i4vo7uLQtc9Qhudg9tJdQzG3BdMPx(wZIOnn6stG0uBk4sgIAAHEQINJf17UG0kBcbrs1nJwhRvLi
qYt5SSaY)QbksqWhvmMQ0A1Vrlrj62ePuFdrHSTSf6AWbH)O2tnhnhb9NPBZwUWysvyLqdIK1BkO1hTZ
FL8gDlBAQQJjShvDTIilHXG0xsoRcF4hMCpRBzqB0YsqIxX8bcm2MWhQgEmap5TYkxXZCRzw7wBZGrzt
B3RqNQ1nqKOQVlmk6yarCZg5LgRKPg5dtMDDDKKsK6KYXAUpu1ZulAefwjzPn6(h7zdPOJI4qvVs)Pkt
JqgCW(hKQQNa9rnVO(kv94P2GLsgPN6GcYPeNO6WDlImJ5SEoq1JzqaGhCCLoLpLtum0N3towMzZayMh
yh9p6H(UNifJ8JWdtjdPPdoF2cF5hbYdGcSe)sEQO5sAQvryfPeJKnht4ce2MDPCiOv1uTgF2tVl54eD
mxM2SYYy(bJHXmKpTyX08bEScebejOZiHj1spWulHNzMFsnrFsITcZDw2KLAkthozz5jtRmRHNG((vpb
iteNEO5etAr210yxKSZwEOYO1XOnJzPGA9EpcxUwaUYaqueND(AwDivSuC4bOAbSv)l2nKCP1KDzPW7o
RJalq1C6aGyvGAz9rNmeSyeqUmMxjGkDqkdUbzvrGWHPpBFkzbqAwIPEVfBVz(DtHMNj3GmTvnRMNjwc
aq)QacSQoba5XO5baYgXmebHHmsf99LUokm9DJPNgtR7paDKbcOEz6lyASa1HvJafUmOXl(FmWtWcbh3
K6pG0qfHIfi5x3pugzUccKgOptYop5SYZG3h)yTkTG8oAdYIeaYzsv9S7oQVY2yLwMs0nHavMgDCAyVK
CHXUup2ru8tzSGbjWiIzu7XGfWQTkWzjRrg5ZmeCPHmwnj2EVrYrmK3PnCPn4GQDorjNipAJnTHYhIEM
EewGLEeCkS5amdPeDgQ3Ei32gIuTesibU0aytJrhejJwkJQUiGDLgzn5Ru)VixL5yPQfkCNNh0dz5618
jF2sbvxd5QsMKm4MDrWoX0ieYHPcxy9dIfADOwR5U0bGs5qvRnChOUtQ5WgUi1LCtSdcGauvv5OO)Cgt
TVhnkI0HgfstoMffOLkfnUm5B8(fjeSAjkB8bX4Nzh5gi10cZ9lBzPJOeLTOZWglr75jEX4igp7IG4PF
GcJ(LeSeGq2amJxx2nuF0C9eIy0Ciwee0LZmtv7sLrCD)W5JIaY8AAtBUJ0euFvNNb4C1vnaOAp9tqzy
UAoZGzEQPcjlz4EQEd3nSCpPtoSgqKz4KraLb4N4N2dkiyjbbKIkN6lsOFui5iYHYvNwbqGnROdkLuCv
6Wr4GuWad4jc2klR1BTqr2VANGuKv1mKWgBCakXxTte5QcEerHHhftcJ(k(bqBJfeiOcQWgeAKkzYcu)
kqVGg1neikrC1EHbHwASPSTPnHhAeVWMy6mSw0(UQdYAdSyInSTx9bPW0t9suhSFSPcRBnKysAsfCB4B
RyOKT2MDXS8rAAkAvrcLgfWUEkV)evUaJ(6a(Qyvy20xyPOM0LstNpjL(WptP6qhSy2tbIa6RWOVwlyl
mtBw3mXH1gRToG7Mrn3dMtdxiQ4aFnnxU2(WHKjn20kpeEQsXnJAgVmmJG3QPP(mz0vQZNRwQBr2cdrz
WkYoY3QdqkRvui3Y448RJDXu9TkOsiTIWgyPSZIvSsUo81wc09iyfMfNVmyB2R9ayqEST6ybScrOg4hl
yASGHdsLCecBZs3CykHLTMBllG9nfAxm5gh86vSTPmu4PsDQ0NxrXAH53gqkFw3sCSnF9timGvCSng)T
W0ue4MhspYrL1oqmAnklq9HKCo1yXd20eZ5PrVur4xqxAW8mLMik2H6qNJvVjL3RSzuipt(jJvRXHs2L
SaV8M6PfBiuJAEJ9nTHHVY6Av6cq0Pyt8LLQCzubEOn2f1)Cn2d0mbfCw58BG1gCL6YH4q)LbsrWnwjM
mAESRj7aOfgDYHJK9xbjGWRhOyHefTaMFqsgwrq2kIyQYuGeW3SnrbVm)6rLNk8(KGeKPJbVPmI4uZX(
RGJIPjc(QB4VRonwBAamLTm5QSOo8z0WlwsgsNNbsXhJEVs8wY8xpG4ifDK7ACG4mungMid8mLmNKPjl
fBRhzTMNHcL16vG1Y6AL3qN6Z3XRceSDwFjKhuH2dpivJSIdyQ6i1mDDgtEkp0NONVhFDIjtHWluF3AB
OOLBn3onrB6sK5LjTwrDdNYwzV5wttwiI43SDeOqrFyalv0I6dYTXAPACHk)9fywePbJxTt7ZpcWYsiQ
ogOs6Lo9emXgKNKsCzokftgbmGvlNa3qzss)NgE61dRRg0mSjzQmwKDa3rbGu5bbvzttLLUURwnB1O2S
o1iAjumnXwI48nlHl1xNCqkFvFMPDQ2pc65uJ)EX(kIeBwhVXzozXdCMKfgAMpd2Psm0qHcmltJ3pCkK
ddWQhMxUWd9CRw9yz72c5ZwubRLWuO64jaVTk5iTIQnGRvzdDribihv8rzGS0QnQ65PlzyAVPGQX0x7e
5cSTpO(xMdqXexYvJTbQ6MagAfZKOYlIWBQdoRT8YnlU(j4m6j1V9hDWAAClESVCb5zFsj6eJ9aMf7zb
F2V9fuZMd7gVb5npq6(Oklaz9YoA6S7gnuAQ6tgvkVrEXnnUklhZNbP6NS2XvOt0(sxhvQXXRdIQzuur
Em35Xs34V1IUm5zGKuWAHfkmpn(myFY7jbOGDtgLj2rWGeSDaxQ1cDslssIxuo43BsTMEwqjJ0Hf4IS3
smaSOg5hgt(b)QWIcHbed6GckcdSnpGQAU7Ll5O)PKUT6sfrQAHbyTy0SodelMTRgfxKOwh4gQtBe4NA
LiehJXkmPHCG(3X3wZsN49(HHMAUXAv3VOAFkZ2885BvEJriZe22qKBsAZNk)qFz8c)0hh6Yb2HszPeu
8XYZNNFqSrDSzKt5GYVb7AIDn0B3JK02OYaRvkejnY3vHCQA4qZtQ09e2qB5wluYgbgzsLWfG57YrxTs
fbuVFY8c153ASBGaSaRMCTukesSKDCWSlTWJyLUKKgWO6NsMmAGbN9mHQowSw)(rnHRDVyP64rSB9Ame
59dIq3zsd1eZReNvSzMBSXqHIP(6PB)(fHsNti6Uf4mX65q9EA0UPr)hD2viIPPN(QZUr7AK(RqbCQss
wUFaskXI56YUjb4yWRifVF5kChQoMQS1a9ZzyCXYvkY7GsHKKF56X7ImmbYtRLSm0lwFeaWyri02PvSR
3qGQkRfEQsuYLwB51BxWRJxFSVvkQfP8eou3LtJUKozX24teOl9vrcQaM2iYXRkvYviQivG1Ilzqui1n
XAXLa5AOXQZ4Utr7Td4ZBQGpUj0K5yVWcyqMjUnkLRBJxpgKxurhUSRmALCtxkqbIs)3XrhgK0bP7IgF
MBqpoPQktWlhZ0aosvYYH0expxKglVysjCiZXkZ6IGnhRqPxKPg7R4h)ks4vx4CrE(JhsHW1zY7nRukO
ZUE8WPrABZTykAn23eK)vqdXH881uoY8(GqsB8khJwdffqMm0uTc9wY2(sM6msfp8L3j0Pxp9rwwmTBi
fQgjfCHbHy3WmQ8yZA9dSxz)M(vxtrrGwSSjHOb3xd5gK3bIQZafanEMFAt)z2McIwVfIMrVU5rbUivB
IkGQvdv5HAXEZjVaoMdsGDthXMdfkvqvNgjK4vsK41X3rw9WYJlFiAz9kb9hoB4T0JK0ytgK2HPiZix4
EPEbJEnuKV4PqpfL1pfrdjSjMITCNFBQmptK1ACpqq)6krWeVE(sXdRdU(dhQV9K1pfb)yzyWxwDaugn
kXh6P0VrRmKkBixFTkA3FvVR4IKtG3OqLB7yGRovT(P4yTnaQk6JbMDB0vs29)uzpN6gPXbSuii8TvwS
(tOJaq3f(IpRv51zyP6WGuYBl0ENLrE3hB(TMjSlVHT0rAWk)cjgwTwXYxhs)v35hyi1hY8Loinat5MT
eVLHouPkDDCn5S8orHTnwjDEfS6zq(OmHZmtUajSeh3KPDVzsir6EoozENAtwAtjl10kVyUohqf3iKlV
f8XdEgmZ4MeLThOJv5VOXAgsn7MBbyn1e)4vvq6kYxcrmy3YG8(qyqfeiGPp5OpFeiYhhWCyYAz63yT(
9UfYfe38cpP)bXzQUli4kuJfERPlm7zRgTx4IiwntElRU(Uywtf2Ka(dLDfw27Qd1Fyxrxs9NlrZP7CK
fSUsFC7fC5gLuYmYHskBvf0N2KJGk5tv7wPSl2w4avRyk2oeVKTA1wlDqjUDupmY1JQUvKU7Ow9b(i1e
3dQfhYgIdMPxjOIqZWEU5RJkVwhDtOAnEFOHX9PN47ft0x5RlvUshlWS1MiXvclTmWRSqoavWV5hcQKK
s)lP6AwWqJVaLMJxDI8ceDoJMj17Z2pva7287fasd(GLGEL(PeoHYtb3NxMG8BMWcs30mF1FxVYGsDuA
msN1KyaPjU904LPLyTcLgtWVhaBdtTnqvAy24L12xRQHjpRfAe3iCfjatUPYcuLiOjJTqV(b7x1Ge10A
lP3mODn(q5KF3etJLQcOogmybmYEKplz5P(Q8nemMxhkQzTWKxIBA0gJ3V(RtUFuoV1GMQNpuBjH1vIP
ezBD4pkDzxn(mg7nRszq6VGCF3ld72livY4LhYmZoZ(HJ0RsYmh5fn0l4IWkXwHYFGY((JPwTg0FrXDc
eaZteG9AvuxnNJ8fXnnT51enQC0Bxsf8CXEqakGMBcuvAb6i1buxpv4zpAxfd)1n0vbuNuzPHhkzhO9e
))5a8R8vg0kxnjON62vn6vVRZQHxH1lGk(5pXMUHjfWJaTr7xGsYBDXP7LLoSrabkSDnfvf4QkBGwzBr
Yf7XfgSSeH)cNf138b5ZoE)mrRbzI7O(xN1)5Y)3

**Comment by mbattersby** [comment]
I don't think this is a bug. You can't swim in the delves and the game's swimming and submerged checks are false. Aquatic Travel Form doesn't make you go any faster. All it does is reset your breath meter, which is nothing to do with mounting really.

LiteMount is doing the right thing, it's not a mounting situation. Your rule to do a non-mount action that's convenient for you is the right solution to general actions in locations.
