### ISSUE TITLE
LiteMount macro disappears from the toolbar

### ISSUE THREAD

**Issue by orxeira** [xod-wow/LiteMount#303]
What happens?

The litemount macro disappears from the action bar. I strongly suspect it is because I have alts in 2 different realms with the same name and that is messing something up.

What did you expect to happen instead?

The macro should not disappear from the action bar.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?

Only started using the addon recently after a long break from WOW.

Please do not modify anything below this line.

--- General ---

date: Tue Oct  8 10:50:00 2024
expansion: The War Within
build: 11.0.2 | 56819 | Sep 27 2024 | 110002 |  |  
version: 11.0.2-9
locale: enUS
current profile: Default

--- Player ---

name: Nelraeth-DunModr
class: MAGE
level: 80
race: Nightborne
faction: Horde
spec: 3 64 0

--- Location ---

map: Dornogal (2339)
mapPath: Dornogal (2339) -> Isle of Dorn (2248) -> Khaz Algar (2274) -> Azeroth (947) -> Cosmic (946)
instance: Khaz Algar (Surface) (2552)
zoneText: Dornogal
subZoneText: 
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
LiteMount:
    # Auto-created by LiteMount addon, it is safe to delete or edit this macro.
    # To re-create it run "/litemount macro"
    /lmt savebtn
    /click LM_B1
    
```

--- Debugging Output ---

```
Initializing LiteMount v11.0.2-9, debugging enabled.
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
[1] PreClick handler (inputButton=LeftButton, isDown=false)
Refreshing status of all mounts.
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,0
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is 0,1
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,2
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 172 mounts
  * trying Skyriding Mount
  * found 64 mounts.
  * WeightedRandom n=64, t=2.793, c=1.988, w=0.182, p=0.065
  * setting action to mount Riddler's Mind-Worm
[1] PreClick ok time 24.46ms
[1] PostClick handler (inputButton=LeftButton, isDown=false)
```

--- Options DB ---

nY1AZX1nY1FojBvXPU4nq(MIL06DTTSIhT2vLuHLUICe5SA4mQgskz5pWF75CA0nWihPnXpkDfUanA0p
oDJg4ox4U4vxS5YBwpX)8fB3FAD79384R)MhF9tF4WJV(hpEfFZ94F3C9(JVzDp73DpC7Thp8ThF4W93
H)(l8P6I3FXlc8XMFbp6W)vBHCenXhdox5IxuBx8IOlXhtz8yS2kOjxGpxCTe)ZlEr21AOl(f(QyQGxx
WZHsUwzB8zVp2NgFWf5J4)sTugJllKoVKqtf8CBj7DsFXOAlYtKlQ41(o3NrRSN1cB1b(W1C5aNyoSuO
wyBrohLwNyLAGDnZoKxAPOoZPMRf6lBxTe4ALSj4NKmUSl6t9jXx8rHf4KwCzFNnaBgADzOpuRzPr59o
ridcSqHsMKjSSWEOl)wNllPuJJrwI1fYdrsTIJ)zQsHzCjqwweYHfpOxIQOAiGzPMKzSgP8m2PsTpsF1
NRC6WJrmq2ZLKm9ulLeET5PIKgf(GSy8Dzo56EJrh)tHOTCAHcdkLIKSnLe0EOq5FXP2uTCUszyJdRrz
p14qi4OGo2zArEJHfIbvxbtNgNBX0jwD5U1A0fQK)dvrzTq7ZqFLOtcmyGUxzF0zozDnuZpwuXUDgfVL
OqHSZZfH8)G7PeuKlHAo21HuoJzUkQGf6YePkf0WtRhNQW1LnhxF(cPyq0H9LQVpF0DikD13GXAUBMat
dYLCMXCWfQxmPATZiBqOfKvWEaRd2vhxru9LlEDbXLzsTCihu62KHLgTuO9BQu7o7q3k2ZuAJ2uHtT2O
RhjhC4Qu1MfFHO6PtNEY3I)Vp0DtHJWIyeRCyUB2XPT0jgOav3IlRV1cQ8aoBQckaqdsyXpReZ0eikmx
l3DYacJya668UAXKHGK8nEpmYPWtmOBrIEXoSavIk8Y12IAks4OG6EhJO3PodrUatxUkkRAtxEnrzj(p
5qJAQYsxAZLknhtOlkZbdIywEe9ntJOLUvaLw0ck0ObQ47gQcktIGA(LUbJyBOAULWcDKePPlR4kycc9
jW5cU2zINOmkFk4epwX4iuwurbxCb1jGGgCGlDhqcctLDn0u7p6GUqblIPC5XdVD31)Y2t3T74bzqB2D
4U7xpC5wjYI7InF)6(D3E1Xtc4q7InV80UJN(0JV(4BF813FZ2hF9M1lpT9QhF9Z3VE7wmKmqH38k(MN
C3DRpS)E0xek7F)0X3Tf)5MBoEARimdxSX5(xxKODF76TVFD3149pF3H19KSxU9WkMlqrel5InF24p)1
zOI7Z3p9M72D1Uv2jScU)HBjpdRZnpD907Elzpmr73(27r7oeqztJZ(lE5ZE81)ZVy7hF81VC)6N2E6X
x)SF79BpTBlKc)jH7E2VTB)2)P7E81)821lVHYjGOS5hpE9dp(6)YD7xpGL)tx3ThILNCA7kvq89Rxdb
0PDxD8ah7pSU7efpWyyZtoD)U3UE59c1)PtxXjDkcqBV84P7x3)4R)1JN2dI)ID39U1tRDBWZeBMYykn
qSbSW28UD3FpM6dxtbFNPbefef)T9xjYLeSu38DR73Fxxv(xo82h6gbGcykEXURV5(3I3FMW0b)jvu)l
7oUFly)V74(R4IkbL5Fgt09uqC6Dyw3(PJhKxbVCSEV(H7esxvcS597ojlWTRFyRONkmbOtp8MVzfcJx
UUF9sPD4QU5vRV7B(zKyevTp5nF6oqQgaFe96ThP11ZHWLgFiLgSS2UF)B3rRKVD39RxTDVydrwF9WkP
XF9HdxVxOoWe78ZF7aucVB723dL3cMYF(b4i0fnp5Md)t)hGB)7evHk2pZU(ZLejafS5NE4EAtq6tl3N
CA9B(EO9(xe(rDDE2L3CCRisaoPOi0j7JRWmhkoIbqD9trkHhO7Ne9(SEkoF)5hwprtEbBaSMBHwgymx
tEd2MBVtmuGcbc03nFLkzKx(I1tNwVF3hOEDafePBmfW3SD9ewFV6MDx(UTIRdsK6CtNn3F8WN5rYOhB
K570rzo3((7V5oc9aC2n)W2R3DuCK39Ez6)UJN297hpi274V(KF)UhoSkcpSGEouv8fp)4(9FISv5ZTB
)L19DSPfIvDZ6VdcS)6vXtdHS38FcfbSLyx8bDfDl0ENzB4zEtQKtSfE(XtVz3vxr0gXHhWdF7n7OFiN
rePp(Ni5rKQnQu9vBV99e0cSFF5r1fsTwC3KjpJyfBEgKK3C5P1pIP)h3Dq1)1ZXbVz923q0aotFhL8G
sEk2otE(CK5)vN(KSeHjX3ZvZRGb6DIrcvopSxGC(1(uJajBe8TVfcJ9BHDO83(UJVxaIr(Mkd8ukPe8
Zj4Rdrq288FvutxrloySS7oQa)HTFGgqmYyID6mPpKyBE4eq42(NeSgb)g8)2d3SJebol7p(rMAu8pid
5siWffyKFxC4)217xV84TVrewemz6e9QBaKZvCzNlmOd6LAsUE66TIabcEdZ6PSZaAz39sZ0EbG8x)H1
9DO97OSoIuS4gXaydw)NdCxswCTNcCUBu7VV9MthVDNW2ijYndjOGN8MTIrRpH0Nb8OeN4v7yyONC1h2
E4(hKiHiOpE7HJ3U902R)ds)yXamntmb8y)dh4uwZld84dxT7Y1U(oAJ5NpIyMQHsEiOzRD8QhF9)Lnx
)3qzqi4N8WL3aAblS)nyJc8YV5vDzp4sozhHg)FhlrcTdq7)iMkdKC)jW5nSPJn)6wdS6ziA0bO3ejFq
zVFDfT(XJNEhjFGK)FKDMx0oyz8SpPIbGuCJevSsh4xsp9t7wPnlsmAJOUV7sAm(Z7Ky(zAL2J(qiRpq
qCr7yk2xC8D38aKk)0BF72d3T7dDRr82)2P7oE50uOkl8T7pE9PhUBqEMD0pD4t)2U1ZSA8iR(np)0X7
UVhr6lKEtIcKxS93iP(LopHmcXS(81thp01PPrsop53FG0r7OaQChfUp(6VhrnU64TckqKVaguRujtjX
TFCLc)iJF9zHh4ohGRWlqchWBsIALCTHpadBJntDwcy6OqMim2MfUsHo)XvA(iPb6PR9693pmA)TJxj4
YjV)lQDiE5p(j4QZ0pLeI(awxmMk4Vrq4jqbSKkM(C3H3DZrb9OgnFInpC4JWau8ImP3pU(Xo38Ivy7W
35OV5lF40DpiRcjQQ6O8DRN(qhvaM6)X89E5jO93E3DsSSNrV57eOohZD4naG6h292TmrUJ7VRxaN3F6
4BrEKF)2pXCR38dRWHzNwThv4S5PBFROy3S5JqQ8MJF8pulOzhE1617(Yd9Nx3(okx)kd8ViPs(vF9pD
632U7FW7)SIu9fM738Wvh))Xs6)1B)2t72V(LF1FDD3vFDg6p)aYa6DF1x)01FNyYF13dP1FxF9)Rj(R
uqUVet)ffv7U993SI9o9vwxFMfWxK873UEaEH)FBe8L1uNaX)6QYPjPypAnJhVLLwu2BXU73P7eeW)(E
joC(yoP7nDPgCA5sYATOW(oBbDt6aiw2jTmQLklNc3Qm2wER3bSfDFQo7RUHwwCmV2HIxNbRudGay)(1
G21fxAoOEjqidOenKz4vBQYArAqE56SInFxgv5b9noBvhMFzrzwG7x1sRKzqwUwIy9NMRfTKgKbujKVG
)P3yo4TLngvErLlX4Is0MSjD(ESvRAxU5dEUD9L(cmQ9ukPIijQPQYDS4kYtAneLAbTuTctXE2mXNBrL
KSIckPIJs6QLzq452qOZw7eOcavTX2It1uYJbJu9c2oQjI9Ev8gDvTopmFlrogdzvIevJlSYPqCPldCY
toKmBYReXlLWZ1fYQvg42qyip62BAT(yP4CrTsMXCvL01LI(yPlNLsc3RXDOp)HutQNiPAnTymaAvRtg
vnL(cQfc(889UbdwgIMQB(E)S1(JSa3b10kkRa21q2QihKtQShgErNzg0YHHul15Fwpo1nqgLFiw60N6
wvSXPQ0NGmsyolVxlejhEoA(lqKSevJCVp2Lyi7YKj)7LgNp2wYTjnl6Cw0JNGIm7Wa4SRIhynPgzXQH
Nuczv6dZztB5liVjJNKQgkmsR0Ni(6OkYkq6Rpgsk1ldjkfir1gSf8tWKMcHeRMyIsKSkBJjTMLCXxnZ
04ssf4EZfL8S6IcyfFjp7qV1KUIsLoRLbRPuPvdzTtWSO)uUOlX8egoAaUuuOGSHKtx0PuwXv4An1hCW
k1Ow3trpWvvVJTWIwDrUOhYzX9j0TD1vIEuqQBszSsRQIgU12YNVVtQg2n1Yy1Q8ouz58ym1X6Un4JHj
UpOE2TM5xKmeBFbywrvW0l1Topg2Tz4j9SmhVAUfBJOhENkyRfZCIR3GghBPO9uMO2G8UrJQrIuBC)Sv
3K(9rPvjwzu1AVWZ8OZEyBik6ozAvmHGiXYzTwM9vDY0QOBDWKFfVPs6f1NkVyX8wDIrsNv0fTDYCxWk
x7A5baJzPcQxId5t3Fcian1EaDnzWMWCZIjvGtI5pehhYem6dJ5xfLoVo8ATOTrXJAUwqKf)SrdljLuL
VwJDx32jzwRJSey8klFaVfBJYHYGpMKxLTriNdMrAZC25WvBpwbF)yDQo3bESMLHGszfSltnlgU8IZEQ
bDwCEn8GDCwl9oy2KCAhOhrnZLwySOqpnrAtfUCmMzcFuDEad401FSOHVKgNI)5svTtG9OMxK0t1oU2Q
kFIowgI02G50fhnDSrtv2q40TYGPNLbbiUFX65IkNsizKjVRPvajwYYMb0mn5oVL9qP1f(8qGiuMNQS0
snowDgah2HESmBvzgoSrIFY5m5P6zjQPwfGxKUyy2CARGduibzuQ(bwvn1QPFiTCc0tsKnYt4z2Z889L
(ScQAoI8XrSyZ9biwEJTklztiYJ)s909wQLaz2YpPenmj6Ry5oRNzw4c7KgLqrwwE1IG(r1(8qrLHRab
irengzofdNDoC6cuv8YQonsdLTwMT2gYkLu9JWLQqKINk1CiiYYy(lMxBjQIkP1rcRk8Im(2ysnmlaUB
BJaZV7mcyCL3mYKwRdgmpPvE(EDbum8XZoMr5rxNTcsANs08(TSiiXpAwacWkJi7ntAd9Etd9Bhrnfm9
RfHRtadwfuW2vNEG)wRPjbsJfZuf4N6ivZlDT3k88xMVUoFToEpmCvgiYyCZouNDqXRAgrzYzQhTxQLF
)Xre4Wzz(dknnrm1c089XdJrlvbsPj7RzektVf3cGpUzF11cs7OnxweLKJuVkiob7RR3KE2M9unNsndL
GuvbXp7MRiDWphMIyhAJu14Hc3MuWP0f79ykdSDBLRUflTwKpZuZfNkz1NWHOZTPvWzEIXZet55Qq5HQ
P6OcPnh0zl9PU3spcDyKEeqfoBcgEsMXHp7cNXxPZwKQRqeIK4Ky1zRZfPfTKTQyeWXsJSgDfZbiZ7pY
SRQlkGZtZ1df5eLtV6rSdTOxn2qUQMqInE2OmYwhPrGLJLkmV4f9g5nZAAxR5UieimS10KlSBXvGx7i)
zsrd8DP6vXmwaAeDovgEUftvgJgfrVNfKBQlwwuyTumvZsYKB2TmyrPWyVe5ZaHmWBFDXmfZTSL7xAKL
octKpNDMoz0uIWyeKq1DlJQiqO(P7IUAz8RrcqiBalJ3L0Y08rZ1JlIzXHSnbP3xlI)wA5Hnv2nrFugG
VxtBYUFwC5cZxf90d0v76AacOoSYmOcSLsYUHAloZsfAwtG7mZB9Y8X4DSso2warMH1XcipjF1EuKBlD
UwvDazWEFknYREX7IMekvw6SsZBfRqivPB9VumahkbnfdCG1yOixCBxTolwMmEnVH(nnKDejSzfoGxBj
DQYJ68Hqkw8r6smwFz3KP0yL6T6RtkVQSrEtbZiJuqXvGDH5u3Cbl11(fGsyqFlohuAmOr17kYvACr7W
0Uimhvxzz3glV2ADSUCZUAktNzxI9b7MmGoRCfAjPPxCmtU15qMT2zJs12oKMMYw6v50RYqntAeDrXVG
tFzsFvTsHTQ3HRR6sNZn99rU1h7XySmTbZPPWkOclK5P13(9)u4WuBuntmzTjDBt6A5(akmGheqdri7d
6(gSRJ5f9YhAbllkUhO6ILfeOA9Swnm4rygY39nlahM6ztQcgNkJC3cwjmSljhBnYs)EHkIhLIcjxocU
fNzHKveJwjmRYE2FgPuPzESxLeplofao7n0rijAxmubtPM6BimqAoRLzhuJec97MDOoO7iQDXPRg9kBA
D9SjRtw4KfAZjZkBkmUSCBwwSSn4Wu5jaQumf59klYltQkerkFJILSyv5tMb)KwH5WSWVzllfs30u5zs
u9(Q6vInnA19lHOilQVIDXvLwRftqhaUG2xVHmX3R8OmVXj7AXDdw1aPspAcp0Bn4KEJF90Xlfm8uj2q
)XWspwSmOZK4Dh3wXGai9Nv2Fr9HXops(2CuDy6ipcKSXaLMbJYk6pjwysmLVd(bbQ5KfEfrY8ZrLMJY
s(NtNYcgmh4FRclifelZ38iOinemmIiBw5qPyeIKVyjbHGJ22oXGmDpFFFQs1ST)oOdTeYaEQftS2mic
GxTyHmswPYe1rD214KwQyPIOsTXJHbBnGJ8JTWIhMfFvpncerAX2icsjBXsTkMct(2S)rcoAkFYTnwzX
fmdJCShfjR1CwSq9IsleRL0(QxLDBYmB(w1puTMjTEZ7991vysu1iPKSTGfIotFOxYD((eu8oLO5MctL
hfoK25kKN0vlDMGLzgltLH420ueALKgQLBpuhJmCldg5eOeRfmRMBy2QpnbCDdgr3mc3h2e2YQ8OER1d
xiqCJs3zNxclYGUjiEXWnu88qPG5321zGfNSlEIJqMSgiwuQr1GPAx9bWdJq5j7sllxn648XKWGsxhyw
rnjlgMnzHKI2TZgUgHXuPisCh8lt9JjvhNMNDtMx62hjBbyjSJidgYbyLrbVk2(JyWx9qxQJIqJzCA)a
zL2AK1suFS)9N4vYQMToEeh20A57gtv7Gelb74SjzRMdnskW836FPgKaS4tTjzTTYeStUWUd8shk1QXJ
TpR2jHXJMFo(Nf)KUkXqIhZsSghBqoBM004YYP2okp9BJqylOJNZ64ujJwr7H)uYQvOEj9vI66QoQLvf
g2jJBaGA1cdrUcgbWMHSeH5H0vgposVTno0yaHo2ZBZnk0rEXkI5Y44qjMtNBlJnfeMq1JJUArsGHRGW
iJAHI1zx7eN7PX450Oy26hLI1v1latVTzs8GZcBeTp2cEACAYXZV7f6heMCW4WmqwpAyd4(7Mu1p7QFW
bws)e23CVHjVApX7vX00sb4ZzDFRmrFRyJqvLNRlBtbPreeeSoMoJdstQoIxB1RuIvO(e6h0YIs3rgu2
vaabETQtJ9seTZ(bsJXXy5DJZrlhsttJzLynqoi58JQJwTZ5t)4vSUAXzz8xT1MLriHdgvKZovFwQal7
swKdLaoKbvqNGWYzjmggtqDKPIMnMFXzNCma5CDFsUlpd2im3o0S6v88BSuPG0kmKa2UvwC2hn0aefKF
GoGSFd2Jw2hS(Bw8uoRQIb5)Rg9aJUzMbuDPHPrFTsWOFeE8r9dbu77OQeEdXLtHvWXs0sXdyzgghzXZ
p6iN2H(xyK8yXofBMb3exXoAkyYz59SuScSgHmunpr0R6WQoOjSE2xFysozREodlNfZZ28wUK1bvNfBS
)ThX4ilDMkO90GQ4fxPZFLL04kSWZdO3bwekZkmAfmfg5rdUm4hf1lfDZfOQd43w3e5Y2Gc142YI5tow
22nVYVe09Sk2zAR63Vh)VsuXiAzlzeArTmfRMYc7nmn5LEADIBGokguuxlLXMUt1L5wshzDy74uCUvEc
EzMBaxvNT9zDz7h7(U)v0rhkM1PAzE23PhHIu3qmQYaus9iywHQdP3kBtKaSQzxeZQbu5SmfgF3Hx03E
vDaYNnt0wAKn5OeUeWyw3d34(TeTVFvExmwmcyr0bxzH8LrPGE1fB75mCOAUxTcpd3c7mR4DQr9crcmn
1gKRB1DbYARmE97oHimn)5CQnSFqsYMfynEw5SuhxyRzI9Z)u0A21(qkNLYPPqXoNXWOkIKQDoDCGJUZ
Y1oziMCpoADGL7RHLT9IErx0pFv2woBEn0PsJjXduvNsIavMD1n6Ap)scTQuNL9xvdTGD7zyurffv)6f
PHgV4h67HImB2C295IIzvmG8YgztKhBYmn2plC56EKoSIZZezTQ1IDMRPoIaJAkqi2Sppt2YQjb23RDa
eXYiEy1I8jBWrhfdIvMTQmi1owkT9pPC1x2W4NzcZAIDw(1gTkPzvYBJs27TusHo1sWgJXcuj3UKKjyh
fQhYq3fMi2Ry4HXDsJaVNXwMkUyhDyOaWSHqWo)zqvRUmyJBH6KzRZUoeIt88GDZVkypekdUyffrww9h
jUABsuBN1(zQTWx0Y9TyOPSV2InoUHxCDxuGTGDsfYNaR2vSBgRmT82yOwCHMUFo(Xqn8w9MfLWSgl2S
tJ3(YADQMrxyjVvkFIxOZfZqYnjRztwh1UTwS72rlANQGq1HzIDU48MlmoGoRmAcvJJzDyCoUpojlIap
OyD0ltAICeTYNZSYTKmlZlMqnovbd8yOcI2sX(GJJZl4SFE91KBHQsm3aMh7tv3HG9Xn7vYoSsCZ73RX
HahDCB28vBNzucyjO3kwkZiBeRwk8ReFzswvCdVw3mnsBlcqED2bdiFhXkD7tbXs7JIv01pNalMY8kNM
gLTh7xSzQZXnct2XvxjMdJZImJWhg9hLue7LXYEn5T8S5PzOiSdyzMJ5zNN1YifoVPeHnQDFg0VaBUg0
F6g8YLfYkVPFCq2C9BvLVvSRpgVjlA8rGkE2DcjAzJ1SsKWml7PD08Ubor18(rG6ZszV7gB)6COJ2BzD
nUBo0gToeQXZIfoIM4gcWXhMUCtButKI8vejkaSJc79v7MPl3NB1Cv)5QGgigxZYKQMDwXU41nCzgFDK
EvZGP9JJUx2WHPOh7vLh8OLPw)3kaYsq2BNDG(vX7vbTMZq)hPa21AACWBlfnwRq1P3QvLKuWUhBs4b1
uM(hMbu)N2dVs2bIPLTTqxvQLB2MeSF9q6kG6iWFWYqnotBSnwSJVHbg00sGcalwL74Tnwf2y32A(csF
92cFCPJiZMhTQcr9NEf3f9n0pK8wKeayABRwk7uNfZ2VXase6b4OZUx28iiuRHYOkJ6p2aD6RcajTtL(
HqyMI84UvedQTOKJGb52o7GW9MLFyCSc0DXSw5zKfMCqNy9F0l44N)0jiLkZWOc2Dp2(9THWDS0Fk6nV
DgQpsDK8hA0cLah)I5p7gxiq9htc3f97yG5DuTl6rnhgh9I91mG88Sa)YArTsyLCT8v6)kwiCq4muw1k
cHCSQ5f8A68YXxRg8HY4Irex8NDGPMoq)DKGsaKHXOgHdlh5kZRmqy8rPWRvJQLjDTsbZDORP)LYJlfY
IBua6L8OMP9FKsyR8l2Wa9cJpreAMj99E9FV4)j

**Comment by mbattersby** [comment]
I *think( tjos is a Blizzard bug, where they are consistently overwriting the saved macro files (and some other settings files) for characters with the same name on different realms. I don't think there's anything I can do about it. I suspect it's related to this complaint, but I couldn't find any more definitive information.

https://us.forums.blizzard.com/en/wow/t/addonstxt-duplicated-for-every-character-on-every-realm/1902749

You might be able to work around it by renaming the LiteMount macro one one of the accounts so it's different from the other one.

You can probably check if this is going wrong by logging in to a character, changing the macros, then logging out. Then go to the _retail_/WTF/Account area under the wow folder and see if the macros-cache.txt file in the other character with the same name has also been changed/written.

**Comment by mbattersby** [comment]
Blizzard did some updates to this in 11.0.5, it might be fixed now.

**Comment by mbattersby** [comment]
Closing this off, assuming it was resolved whatever Blizzard did.
