### ISSUE TITLE
Feature Request: Multiple Modifiers

### ISSUE THREAD

**Issue by Fraktyl** [xod-wow/LiteMount#304]
Good afternoon, I was wondering if this were possible.  Add the ability to use multiple key modifiers in one line.  Such as [mod:ctrlalt] or [mod:altshift]

I love having a one button mount option, and currently modified the advanced portion to call a specific mount based on the modifier pressed.

```
LeaveVehicle
Dismount [nofalling]
CopyTargetsMount
ApplyRules
Limit [mod:shift,nosubmerged,flyable] RUN,~FLY
Limit [mod:ctrl,nosubmerged,flyable] FLY
Limit [mod:shift,nosubmerged,flyable,advflyable] RUN,~DRAGONRIDING
Limit [mod:shift,submerged] -SWIM
Limit [mod:alt] REPAIR
SmartMount
IF [falling]
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  # Last resort dismount even if falling
  Dismount
END
Macro
```

I want to add the following:
Limit [mod:ctrlalt] AUCTION

I have added the Brutasour to a group I created named AUCTION.

I tried to set two modifiers in the Rules section, but get a "You cannot mount here" when trying to use it.  The Brutosaur is set to a Priority of 1.

Thanks!

**Comment by mbattersby** [comment]
Hi, you can require multiple modifiers by adding them separately like this:

` Limit [mod:ctrl,mod:alt] AUCTION`

Happy adventuring, X.
