### ISSUE TITLE
Can't summon "Trader's Gilded Brutosaur"

### ISSUE THREAD

**Issue by Cy4n1d3** [xod-wow/LiteMount#307]
**What happens?**
When setting the new shop Brutosaur as mounting target (either via Advanced Options or Rule Editor), the game errors out (no lua error) with the message "_You can't mount here_":
![image](https://github.com/user-attachments/assets/53a0daf9-e77c-4d05-abc4-57d62bf29a22)

It works as expected if I select the ol' trusty Expedition Yak:
![image](https://github.com/user-attachments/assets/c7294246-24ce-4155-b0bc-5c72cbddeb54)

**What did you expect to happen instead?**
I'd expect the Brutosaur being summoned instead.

**Did it work in a previous version of LiteMount? If so, what was the last version that worked?**
Can't tell as I have the mount since yesterday. I could install older versions and check though if that is helpful.
Probably some kind of interaction I can't grasp currently.

_Please do not modify anything below this line._

--- General ---

date: Sat Oct 26 14:18:02 2024
expansion: The War Within
build: 11.0.5 | 57212 | Oct 22 2024 | 110005 |  |  
version: 11.0.5-2
locale: enUS
current profile: Default

--- Player ---

name: Furor-Krag'jin
class: DEMONHUNTER
level: 80
race: NightElf
faction: Alliance
spec: 2 581 0

--- Location ---

map: Dornogal (2339)
mapPath: Dornogal (2339) -> Isle of Dorn (2248) -> Khaz Algar (2274) -> Azeroth (947) -> Cosmic (946)
instance: Khaz Algar (Surface) (2552)
zoneText: Dornogal
subZoneText: 
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
DrMountDf:
    #showtooltip
    /use [indoors] Cat Form; [flyable][swimming] Travel Form
    /use [noflyable, group] Mount Form(Shapeshift)
    /lmt savebtn
    /click LM_B1
    /use [nomounted] Travel Form
    
LiteMount:
    # Auto-created by LiteMount addon, it is safe to delete or edit this macro.
    # To re-create it run "/litemount macro"
    /lmt savebtn
    /click LM_B1
    
```

--- Debugging Output ---

```
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  Dispatching rule ApplyRules
  * checking 6 rules for button 1
  Dispatching rule LimitSet Trader's Gilded Brutosaur
  * Add limits: =Trader's Gilded Brutosaur
  * no rules matched
  Dispatching rule SmartMount FAVORITES
  * args: FAVORITES
  * limits:
     1. =Trader's Gilded Brutosaur
     2. CASTABLE
     3. FAVORITES
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 8.93ms
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  Dispatching rule ApplyRules
  * checking 6 rules for button 1
  Dispatching rule LimitSet Trader's Gilded Brutosaur
  * Add limits: =Trader's Gilded Brutosaur
  * no rules matched
  Dispatching rule SmartMount FAVORITES
  * args: FAVORITES
  * limits:
     1. =Trader's Gilded Brutosaur
     2. CASTABLE
     3. FAVORITES
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 8.91ms
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  Dispatching rule ApplyRules
  * checking 6 rules for button 1
  Dispatching rule LimitSet Trader's Gilded Brutosaur
  * Add limits: =Trader's Gilded Brutosaur
  * no rules matched
  Dispatching rule SmartMount FAVORITES
  * args: FAVORITES
  * limits:
     1. =Trader's Gilded Brutosaur
     2. CASTABLE
     3. FAVORITES
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 8.75ms
[1] PostClick handler (inputButton=LeftButton, isDown=false)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=false)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  Dispatching rule ApplyRules
  * checking 6 rules for button 1
  Dispatching rule LimitSet Trader's Gilded Brutosaur
  * Add limits: =Trader's Gilded Brutosaur
  * no rules matched
  Dispatching rule SmartMount FAVORITES
  * args: FAVORITES
  * limits:
     1. =Trader's Gilded Brutosaur
     2. CASTABLE
     3. FAVORITES
  * filtered list contains 0 mounts
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Macro
  * setting action to can't mount now
[1] PreClick fail time 7.78ms
[1] PostClick handler (inputButton=LeftButton, isDown=false)
```

--- Options DB ---

9X17YXXnY9hM8H7UQStH)Jb(Bsww(SSKSkTY(sUuHLgroKCd3DhMz3vk0FGVlPQ8MKxS8RB0nWOuMND5
YdNbOr))UrJg7f2l(WfBU82Xf6))YZlZlp(XV9Xp(ZlJ38N(p2EaV9e(3n3SB(tJ7OXC88(9Zh((5Zho
De)9BDzxoBU4T(lEBWzmL8fV1I36I5uKF068LIR(yjesb(rVpegWBPpm4T260c2O8K3Ldg6rlnVHK3uH
wWnyOhX8YXs2xFPpAiGH)YxW8s8J2GlKhQOJ3fDyw4djJXrG07jacS36feQehWOlf8mMNTcVyjMY8Ybu
3eRySpmW0macHPUIPUkdfRXYJWf9MHSsPEMOjah9d5kVWLhkPuFeaBkbzIdcZO4dvQ2hlyvQ8qtoARZd
VZxbMFifI1hZdEIijifgiMNNyhGta(DDSGBfRcmhy3Xc9)XN82bt0kmzGMvSpHxMyghH7dgM6s2aHV5O
SkmZMhsHjvIBbOrm)eZodXSqiaLR0Hd)JFqyN47vzgVibH8DkNGHRWnPbiWcirSUAotWMQqaV0XI2mnc
xs4XwGyMQyYBtGhuhSbmUH6kd9gHB6SqfdVAGxJmj4SewZJUiRnGm(EGjPGifc2CUUCGzNgu9Fx2qdnq
Gg6VfAi8K9rRPQCnm49vnhOsAt1fj4loXUa6VrmdsLkbITIY08dIycA1cBJaQmFi0Tvc1djTQRymwro7
ggavRS4yOAxHNYYltPsQQYhIHKyVsSHyDOGr59(oyPhf5fP)4fzRyYpeDjttmNfq4DgVyhaApx5h(ujq
ijdLCc2vaVeal2bW6zWkqR4jn4bYaYgg8fbrDPcHOEDmcSXIhvXuY0C9m4gs15rSq1gmaRZQspyXvjQd
4wQ)DNOlbJy2UJmaXqmSIojaXc6sSnsKaU1hvPQL9msFcw6IZmiQmw1jzY41fYp4uxJUcJLyz8Wj3GqS
5OQCcHAqEliqhXLd8qcSBshXNGU6azE5jMsXfy3tSoNvmldEOjw5K(YG4ylzvhrK0IOkc8WyWq6NK4Iu
LJIqmNYPUoJTruIBnxIFOufpS00W)HJnwyLLO4kkwTNzytGphswv1fCEb2KQctU1xtsFRV6zAGzyxqEy
TgXPGRuSseIGJDUtMEoGfQZBOJ5esGCwYVm5ljrwLsWnEvabk0v15jhBmgWUVGBWGkoX8CcLdpkmTBiB
RoldmANUYdL6QWyS4j0JGnbrngKD1FmXs14Qw4II8DrqXczKmccAj2LgcGM9I)FO(qA3ealMmZkC8cIO
Oe)HIvvWAMiKKWUyIOfsnoa3W0qiWmumKsFGOiwsRCNsKy(ehcyyrDwdNzKmNu(CUbvBk245qdtnqGHy
fwuC4QAjjZIIrHPyyRtczHbGHrAtq0NQQh2HsPuxee3I8Sr)xGsvPQfqEbDseCyAq(dOPsIcH5romQUC
ZWnDfHYb1jc5XMbBMylWFwvsKJPMzmieXqc8vso4IvQRAiGeSUC(W1BV53MwoUD(arexSz7HJNgpC5eN
ML9In)84UT7VAEHTBkxS5DlBNxE4XpoF9JF80Ttp(XnJxUmD1JF8L7g3prWaHu28SLPdJ1b9Sdh2E72D
JN4LayT)Inw7)SHZ477h3F)42BoGPV9W4ocCxIzI1GfKxS5ftt3VCgF)dlJ7jOdP9MxmEZntiLXTheC4
fJl3rFecHnBUCCz30Ph)4BMpmE800YdeQdTMn0OUMWsSU7MU(e9EObT5dei(BJyOFzE5UJSWC4In)6HB
aj8thUzEMEfu138M5BoJxDC34HROvD7oWjaToYlHta1MtZhM(845D1viiV(fyCywVB7jMnKwXguMAN4T
wOYV5VonUCAfV(x2ba8JZxTEKokK)Mn3T9eiGThU5Xp(CSqxElf3gYZ3bufdCKzpyGpJ)(x4bceDHyQj
It)SLBoZ0ostBZZoEKWFS0Gf)3hp8N(80XJ8AnOe59Bxg3b(204NjXUfw3BE(Uzc5AYLnhM)cZAYxS5T
tlN)03ocX27g3nE5ednSUFy8UV99tNUDet6zF6HJvCaIlcn3ptiWlNoEA7NXobi5pMYBh)mT0pF80PVw
LH89O43eulpDSY8E)4ntxVDbRzKqZF58jscEbhbHO8XV9Nhxg)gOxS9KOB)dxE78etYiS3M)64UDI68x
gVB6ayFWhfYIDZMBhVA(BFhH9FLcxs1gEX4xo8jirUBAHLbzsf925DZ7jZmYXeZ4gV8UL5lVdJF6(t3Y
lmPX9YZqlel9lN3T7bIaHJ6nVyEpSwidkWmN3EG1ZmKX6TJ)oqXD3GDw92ygV5TZlNUfgJGyleT(HP93
t8SMk1RgVI5wl3pXWjq6DVaBeJao00Ny5bceWk))PJSC63iLd6djeEBZpFgi4hG6apu4iAZpUmnb)iWm
aJD7UDG9ZCss2n9fYS)Wv7Ma)M)R)6890NZKSRAs8cOHSql0ArlzCdT3xVTk1FhyatmhmsmkMdc0GPpw
tagyB2oDJqS)YYnlB3VNymfe3EdR7du88PQbbl2aHAx5bHK6vYV8v2IVCIadIN4isL9f8HTKBLND1Nbx
8mPOX7pBZB2Eu1bbdICjU5YTGVZCdJOH8RhUAA5o4OJPsG2VACln0)aUaukac(9BPzaLkW8EdCQuv5W)
O6(Ko5xiv8Je1syj8UT2N90PtvpaNpW2Hyi)9P7(82L)eW2xpUfKxI8E8JGNXgAZ7icMwHFtCmOW6Noa
2f0gjfLsj8v6jDlDYdt346d3s(czwlP9)9lpCVYANxUzgEYWK)zGH0qISkVYlyM1NMyRbABGxS5h2pbp
rxvDWUNqIePNVSGLwSLjTTJhjNwlSLlY629vAhpFgGGD)H8iOzVB(MLZygVFlfNaPFsgPlZ3n1TkCy3j
GTb0A30DKo9NNwQCZSkh2E4oyPxD1rMNlyfHRlIj)E4tJOakQXkZ2h)4FEZ5LRbQ)xyDKH1blVDC)NO4
EegZQJSdr2J8cBRv5TNjweRlbJZxdVevH6HRyA3HKhf8JuA)Y4d4R)zYl1xjuVE7HTKod8vE188YFHJz
rolv)F0kHV)geQz7boWV1(v803U98Vpo3njXK)b2)OiBVAEp7MdBTAZBE4YQ)WLoJeMDvlee5FEzIiIx
YUH)ZpdydYvSgrxcrmYU3D0gRRe37NH0Q6lEGxA4i8YLXVaa8gGW1Ozqt5TBV52txZaEdWGtNPiIu63)
)I2)UfOsaTi2R7pq25eiODVvxV3IaoZN2EjLkXDt1cyD)Y81B3n9ZtpqPtbaE4Q72bsF6Rl3fYY5AoDH
nKbZvNVAAhpGN97WmAzC13)dQvw)Juf1ithWX(9NAm)WYVF90wIE(J)oY36YXhEQVImfRCQ)4pdFWxnD
95LNC()80Dh3pE82N67VE83jJ7X9)dX)LPZKU8tUiJ3E48tIJFy8WHPpnEEppaoQb0GGUZFWA80O5XkA
E8j5e)V)37ME4MLNqm(M5zSOWq900tkn)1dh3E5TN(04tockS1rOon9eRYpT)A4W5QZ3)0y5)Z(DtpPY
4)Ydl7hf2m7Z)kcBHoWvJ73d9S1qA8Fe5(VoEyC6jLiVLmQEsKaXYoCA74tkoVFeg2ZpLGOBdYgG6RXJ
7PAjZ5DVf5ru3TtYR1ZY6cPyBl26UV4biLbSwyhENFTsJs1o0jB1gBPt3pzO4KToYJv2VzVYFHqREWyZ
BTQKv3ElpuJudaEsHgcia1NSsLbOLs2sUwCelV78SGw8yd93ktRxcDe)BWvNwkj1UDDXJOfO0qGs)7fY
bpTD4CwlIHVVJAlx0GkJnivvivQfJGkYrOmiBlgBt30Ovbbs1QxsmfSLybrPsXWpjvXKNSrR6bpsPMVs
bYPh7vHXf0cOUUqhsba13wbWqiRVSy0cAYp6vqnivAUx8u(7cNMQYxfabTgcsz74xvuk32EswplszwQW
UwfkBLjlkCaBfKG4hUg)OoqStFROI1QCyTa50Js5wdYrd0ls(66(penkcG367IMCfdL60OF32qWCJ1my
7F31FB9Xyjl1Bk4dkf4HUJuAe6mkeEHpgSQAqj578kr1EDz18j9TGT0QluqRtowkH6ty)51xInqzvtNG
A6awIrRVPZjvTobFdk)3zKcOAlMuPdtrXp5v5dXZKVZlVWFOcrlwrdQVLSpPv700exUCCWRiLtuNsHIc
i8zb90ZgJhzuGEUXsjoIu0(qX76owkI7KWGYNiwI6zleJDQVHhb5aYANWqfN1AQztUCQpG6BJcffLAQh
LsM5kd65TqAf1NsQMuQ7qoOUEjgHtjuPUSiJ6K4wHOuT2PjPA)8NvTaIOQJS4nMCJM7KNTR7leYQdEHE
zJq1kOcZAL6PVxbvjhfRDct6sm5yIO5m0i8sdpAQ4IF6HHIEOFHO682Ll0grQCMHHqNIv34QEhpYCF(I
2wO0cK40JeDiRAte9klKwSwzHknWBBVmQE5lLwWnPKTc8RZQm4mHgI2oabRQHh9jX7oH0RonT8Q3M7Jv
REDT0V6au(x2PIKqqC)7dz1A1Uslri6YGsP2cIc1MYAORNVe4psodfJAnc6pQUnLQxZZQD4Ryozr3YcT
EFB9RKh07IQZ8S8oI9iQRzezX1FP6kjg1t4a6JcFcONyHh7jmqXR0udCASnIpKB4rh8cVna(SxvslQTo
nD9eaT6bUt0zwlWEYl67eJsqflITgBKxOpsjOJX6gA215E(kEvNKw2sdxL4hfFJOQh1Q9Ro0e6GJC9hf
DAGawH(dznnc6LD2FNuf9eOpkPiXJu0JhkDwQYiTQoyOFcIKQJoBBm21IQRdu90miwDcbdwJWNIKwy)7
wLJf1SzamJDSt9pAH(UvrknYp1adHgslo4isU0FPGlU6zRA5OgbRQNzcsMv6XIt)vOEUD2Q63Qzjopsd
(ylOOTi6p0zfxNemIhux0j9W4LJWq)ENfj56Wp2IkRgsW3LtXWSj1pWfVCo5Y5ABzF0AMk5G6DA1zbXt
QLKQMJCOLVh9zrtV7tyvpeaVxrjAzkgA9JqXluyI8j2x0HoOY93wA8kbsgJe3bzcge0ZIWjM2YNv73CW
3DfKBPUgxn)sBrvVxWnVU3cmarfspPDlBlWHCmx0AxaDadnCn1bBQrlQ2qwDAU60Z0dM1w51QFCBi0cQ
uAjRIykA8(sZxCWvSA(oi7BrAwSAYMaaQVwabDxFeaI93g7ai2iMU0W1jgrjGhQygvg6strBH)SmFQzx
eeqAycDad9bioXkkqPe2edAQrweTrxlSm1(tRO6U2IkwGsqD(qTuZFGGuh9LSex1mou7kPHDL2NH(l6a
o7KL460I8OeTq4qS0hPGkUwo8qeR(oiOkE2XMHurepaxFbK36XoIsDQT0HGvMM02dY0e7We8GQP6IKC6
sUqxilMh0zKxIDCOlWdRytROcbhgurhjqk9jv6tQl71CMWaA5mbz3QfOzjPkhTtVxM2kIumf6D9cdSH(
B7ePgcv6(jESiXaXUYMvdGe1Zf9HkMOWjFStpklxoLD6XsWjkBibwLjrVC1SuWo0YTaKJMFmw2UjQ6dH
(UTdaHYHUwP7pqIVMJUvCr1nSzqlRaiarxLwkjXmNgOLNJeqrovE6Tdgn1kqlzv0yIkFtpRDfcTnyKw5
es9Jl9siZ4kANI5ITu3Pgyzn60nYcQbDTPHO3AALwG863rHEruCTSIqkcAAWMOPR(06)oe22ZUYBDpiP
1L0njb16OMjBj1uVs2UJiTmh9gsazYLuTl6TcZfoAn5gaefjEfeENjhJAmoRQ0cHSY7TQMEVpoP26qn8
GnMMfukTQLj0cXbuDOJ162hgAFpgB5DBqYtkZkML25R3fKmOesXKvFpehuLrWwwISIC1f10EhnXZxmzq
k0IghsOtlSa1kpYsLALeS2Mi0tudh1zFjBhOL(aCkOCIC)RAZZGMpgCp7u77I1RP2A1c)GNkH(KITj1Q
UxwBlvEaDoSV)YCNSwbRHgDz7VufMARdsDPQTpjzvb4dAQB0o8wX3Qyi1FORMLUlGAplrpMtddnkqlqQ
08pezd7)Ch(IyLy2QBXusBjYur(o3AC6JHqURd2ArzWSu(sV5aHvys3MtR7K4fR0HBPd3shccpuAaoMh
48coquJMhvTtOSvjtqHQrZzov7pl9T(oELRj6fAbFisqSshSdnpvAUfqjULrNxR2X6gDl41EttB1t76w
bLRUNVJv5oa0K299Y0NCRGQWJtTD4eZDFXj3k(tZmu7a219lT0c360Y9bisUE)lZdyOb3OMrJt3HQ2Yw
cjUAwRw3CFwQ5vRo50y1sWcfXv9aRUjvPBPXJzN6GJ)UG4stTsG169TcVy0cgYRGRdlFFAAu7KMCd37T
DPRYNPX67aRRG3AGAJrSRWEamQxQWqwz)u3gkJT3PEAZVlRBOVcA4AVwyrQyFAotrVr2kh2kOwG1ukUs
IOzmL9s6M8KwXXR8UswDxSQTs7DMh2Vs0v6tsYCP3WFikKVTrhJDfOwHQQcURnF8DnqSXQ7Lt6fAEzX(
FKKcD0QjyG6qeRPwRgK3IMUCQf(KuduVj92sMmweXzi3oqM(voGUhdM(3RlvCiPhtfKGAwCWZBOMub2h
G6mzD3glxDccgK0OT7ctR)vDT9ypGayL2JAqPyRSzyxaAqx8qVoU6UTP(JwwaFpZEKYRVJ4Tl3q022uZ
GwyqQ9M6xpGw92OMdT0hRvaw9UDyjJXH1lMQsx0nMcbIQrBHNLCJU8DGkAj5O6C1JTsjGIGVqSY9VGwk
9ojCb3)n6wyXg2jEGP(izwBQRvO9Dcae9sTKLPdwDNNq4R7QYR5(r78GmWPKh73)HyPO9in9snBAN6nP
DpoUOwHPuFSQ(Fk13CQMwmHTIal3Q7gv3kx7ZQxs9u24ZQO(1wh1tJt91LAIvS4IRz2XPgZS2Y7Y81qk
qjrZla6wnLSwEdaSvsQKJ6MDHUIgDJgPA71QYnwknKdfDwdebRlnZY2HNrvoq9ucVhQOiq1yKFKcZiZh
AyIln4PswuPR7Tm3xTC4M2wgaY7kOlVXPoFwPbYntuLwWtImtUYskyffF6oliQy(UpRy7Wk1g)xGBlFS
69yHrC4GwuwKRqKc3kMp0QApjTfXjLmqQpsrCHDKQ1cmtNROGTy02(yfyrh8M6)b79uT(tQevVtdvkt3
ewqUMnYJsCq5InjOGuke(7cSOm6cnAqWlsm3eJwzZ8WjSYfXQ66z0P1hjITplFV3v)qrtpbBeTiRHNPD
1QAYjvrc4)QiEHvYXwelT45(vNLMrZnY1p2Rv3PeEOQePDzRSMIAkq35KyFOcRhQhArzO7jNg9j4A1lR
ETBO32VxAqI2w2KMGlYETvQtyvuCDW66J11qH22mGZmRInrDS5qlSm4TQtgnQnTLUKYTm697HgOvP2s7
mmhu0E1TvHhR82(10WPE2xDphzuTfvx3fdIERLihBDjOhfLC11Sx0UnAmJlA7z(70d2NGRQPcRcBhBfG
Px7OQsBl(PRDC(9BGc5MuZrPVdyKCOMaRZR1ttUpCmtuF5QBxjFK1AOHGMeLXQNJnmk0YIsXCxrwYJgB
zfQkUBO0g0SXBNzd8O12cDZpk8EQBbxUWA8JEnfgQ0FAqztZQL2zrRBvA1GaP7OviqU9m0JLw6ZRUOw8
rRkXFmo1r)QRxhz2lllTLmnXFJUrW2gliFndQwAqn5OKs0iYE9Kjra7ylsHrRqNEP3QWsD8Xh6VeGf(x
ec0JmEfl5icQ3Y0pSQI)Is2qVkNM2PxMikOnYwAQTCgquIyRHAOdIqPMIM4efwvHq9MEzR6RcXi3SpEw
QRggQDRRHqhzKHgPusfsS0oEcY7Wk)T1h7xnhsFT(uj1ptfJRPd61C2PSRfoivbaHwHns7OChAhQfrGv
OcPUMEE)GfPC6BzquuMjLb4qNQ6RLMJJt3GprjnpcimOM50GVxB3K2Mz0Jv6Is8O5OP0BlO(vRg(xLql
b9WGxDVdhYA7lWBpOtlvWtEgK6PqyQT7P03zaTuNhKeZqEP5oP6BuvVw(0gqQpInOO3cykEOiHtA39rz
gjkETZpmvAQ1PSEgg0LwvES3ghu920CflTUAXQ7BaSHGQin0QXESO8z4H1O7nkLD6gKDyFbnBbnja4cw
xFcQH(JITITNQDkQ8pwRUh4UDFO1SbbUeBEb1wQGhPGHGPlzQHKZSRgALxrvPtuFAkkmsjpw8A38adbB
pXdt)mUdAEbqbqY8bUtfUMxZLLWjDZLiCw7eST6PIYAccxP)lgWQB8zYRzwXzZ0ci5AxOEVrRfp2(SVz
cN6zpQid1mFYA5m(wInAlsXYvn(DXPhXl5xk3xlrcz822Xv12IpPdjzSrPeQNNoLoIaRbnf7v3hBlPLQ
MadTZia8WkDrf5lRKL6KLMK2FKi6LgCIWqzSyRbI8KHQGSMKQBtBJQfEjxAHVWyf1amuxl1hLjHLO1jB
Tl(osHsRXo5CTNvSQM1V53u(TQVTCReZHwJMT6EMJaGHsxJUD0aaVekhj20ujsQ9P(Z(qv2QXFDTTsrO
TQr41gSJqwnOGRVbVmckOUC6BRT)lEbdx1On2A2IHCBhAb9CmA)mxCbNoV2JFgVPhbudrtdvtr3PBhm1
kWk5jiQtx7qdUc0sQBXw7DrNCRqaLS21s6vK2wfcPvSaX(arD1ZCV3(1u)BQhKaLUVM6bIqiVDONwC7A
kZGvbauLfbI3z7B5sEh19Vcg2)rmGJfimlKtNI3GhecDOkSBy3QXB73xB2lTqyMM7YGwddYzAlhLIyZK
86bLWN4Tyjl)ebyxFNGP0DA7lOZkOkBQ5KQn2e1TPIWaPlklk5iqK102kevFAlNYJw)6dqtdwsjoisiy
7PjoqbE1OygTodXqUL0F7q0j2Qe6kJTJTkhenlS(zxixYDEaiL2EEGIiU4SXU3u1vwrplrsDTPGOZHpQ
jjZPS2nJR(TlHr1CNQ6(mAjFA1c9WzmkGLo3CHVtNcR4If5(PrjHhJHggONCNr7auQ2wQNmJMo1QFrri
Tvvf1LBv0U16a8MafvuRnQnVgTdiDZy52LriRn0nV)IEavXpMnewLCsUHPA6ygxlFuTozCFWvHz)3mhE
ljR4QLoMk6TupIUA7lQVJ6VvnmQgADevGo86kcM1TOs7Cp0rvvzR)lUdCs2QjPn33ZHi0iMESpsHtr7D
xOvAZIsAg1FLEygqPDSJGSKmYzyP5Ew0CpPCVB9dKwBH2VJjvQsZER)t)cFhd0C2ANmkDhm0SJA9rl)7
tGi3cj9IBi)OfuXLqFtfdRog72ojANpbhwtX76pxh0Yk)Uoy5M5wyCM2wvOZg3QyL2n0mzP4AP9daJ8l
Db9w6a(eze11cIqaUo1h7)q3S(3Ri93AebU1fE1VDtKb3kTGMpF9upO9PRHTqs)15tmwHfz9TCMC1F9O
SSFa1mKAzBHA9TdofB9xxa2mVoa2)TmGKgRfmvvnkRN3MVFjzI6rjrGuBvi6aqB8sT0h4F0Qec)fnp((
g)t(v8Ghq7xZc9Nel(3dILZ70F4hQ)6p86T73EAdDxO)WcDpJPlH5pUD3v0p4dpF58P5JJNPRc96r(VT
F(QVB34Ut)70fa(4XPd3qxhvpDT3oFGhW49FhYc7BoE(t7NwUz6kmY9N(oE)jHVEyivM43C9Uhg)0UPV
5)86l)oWRsjz8eVm2hV(txX3HG3Yi4FqxUyZM9JlN0Hn9FDAz87OeSZ5V5W8AK4zlxoEy7Xtez(MXdJh
h)eqD6E62(jjBz(898DjRrA0p9fpqxT2pOxhMNFXPvFNEFTPBF(fs3M)8kWUQED0KBH2d8vK9tNpDA(W
ZUKUD)6VbhVM(nw43MUD7L7ME8vVy7X9cPCyMUoMyT)3F8vF)89p8HrqiNowP0x9S7VF3dVNePp(QnFz
7PlV9L7Ol76MtpqxGEwoTC82Txdj1RwZIE5Z(TF59)0h(Hnp(QF6LyG9f5Xp(4h)NE8JB2n)L6TX9BE8
JVE6ZBpnEIUo))D66rxxe8x)4UTxrV9L7gVVo1n3pr3EuO)IxJa4j6)rT(KNEG27qMEirv1OTy8nD(b6
6Dx)rj4D7oVNa77NV86PXt3ssGn39WTZ1lw8PP6m)1JGgP(T0vQaFWABW81JhbDUmDCMUt)x14OtFMOG
Tx)4hfAUoJgl)v)WBFXJV6nJxUm)4RylMXdxnV)Vn14RxS59JSW8e)Vx8)n

**Comment by mbattersby** [comment]
It looks like you have your rule set to mount from favorites only but did not favorite the new Brutosaur, so I never matches your limit + rule argument.

You need to either fix your rule or favorite the new Brutosaur.

Happy adventuring, X.

**Comment by Cy4n1d3** [comment]
Ah, that helped me alot!
I've removed the FAVORITES condition from the Advanced Options and created a new rule limiting to favorites, that way I'll hopefully not miss this pre-condition next time.

Thanks for taking your time and the exceptionally quick response. Your work is really appreciated. :)
Have a great weekend!

**Comment by mbattersby** [comment]
No problem, always nice when there's an easy fix :)
