### ISSUE TITLE
Druid Shapeshifting Bug

### ISSUE THREAD

**Issue by Quaantt** [xod-wow/LiteMount#309]
What happens?
when in druid flight form, i enter water and automatically shift to swimming form, at which point the forward button stops wokring. Other directions work, as well as both autorun and holding both mouse buttons.

It doesn't happen every time and seems to depend on whether i am holding the forward key for a few seconds before entering water and/or one or two other little things.

Happened on my previous computer also.

What did you expect to happen instead?

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
i think i remember this bug being present for a long time.

Please do not modify anything below this line.

--- General ---

date: Mon Nov 25 17:14:28 2024
expansion: The War Within
build: 11.0.5 | 57689 | Nov 19 2024 | 110005 |  |  
version: 11.0.5-2
locale: enUS
current profile: Default

--- Player ---

name: Quaant-Illidan
class: DRUID
level: 80
race: Troll
faction: Horde
spec: 1 102 0

--- Location ---

map: Mechagon Island (1462)
mapPath: Mechagon Island (1462) -> Kul Tiras (876) -> Azeroth (947) -> Cosmic (946)
instance: Kul Tiras (1643)
zoneText: Mechagon
subZoneText: 
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
```

--- Debugging Output ---

```
[4] Combat started
  * setting action to options combat macro
[1] Combat ended
[2] Combat ended
[3] Combat ended
[4] Combat ended
Got refresh event BAG_UPDATE_DELAYED
[1] PreClick handler (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
  Dispatching rule LeaveVehicle
  Dispatching flow control action IF [form,nomounted,mod:shift,mod:ctrl]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [nomod:ctrl,mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,1
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is 0,2
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,0
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching flow control action IF [nomod:ctrl]
  * IF test is 1
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 632 mounts
  * trying Aquatic Mount (underwater)
  * found 16 mounts.
  * WeightedRandom n=16, t=0.857, c=0.844, w=0.143, p=0.167
  * setting action to mount Otto
[1] PreClick ok time 17.05ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching flow control action IF [form,nomounted,mod:shift,mod:ctrl]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule CopyTargetsMount
  * trying to clone target's mount
  Dispatching rule ApplyRules
  * checking 4 rules for button 1
  * no rules matched
  Dispatching flow control action IF [nomod:ctrl,mod:shift]
  * IF test is 0
  Dispatching flow control action     IF [submerged]
  * IF test is 0,1
  Dispatching flow control action     ELSEIF [flyable]
  * ELSEIF test is 0,2
  Dispatching flow control action     ELSEIF [floating]
  * ELSEIF test is 0,0
  Dispatching flow control action     END
  * END is 0
  Dispatching flow control action END
  * END is 
  Dispatching flow control action IF [nomod:ctrl]
  * IF test is 1
  Dispatching rule SmartMount
  * args: 
  * limits:
     1. CASTABLE
  * filtered list contains 1 mounts
  * trying Aquatic Mount (underwater)
  * found 1 mounts.
  * WeightedRandom n=1 all weights 0
  * trying Skyriding Mount
  * found 1 mounts.
  * WeightedRandom n=1 all weights 0
  * trying Flying Mount
  * found 1 mounts.
  * WeightedRandom n=1 all weights 0
  * trying Ground Mount
  * found 1 mounts.
  * WeightedRandom n=1 all weights 0
  * trying Slow Ground Mount
  * found 0 mounts.
  Dispatching flow control action END
  * END is 
  Dispatching flow control action IF [falling]
  * IF test is 0
  Dispatching flow control action END
  * END is 
  Dispatching rule Spell 783, 210053, 768
  * trying spell: 783
  * setting action to spell Travel Form(Shapeshift)
[1] PreClick ok time 15.19ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
```

--- Options DB ---

nYv3oU1Xr6hM9ISlGds))pzVYwYY2swkoMYjytWEWC0muAyehsTC4yb5lM3M8wS3LxST(5R6MgXoyJmI
OoNURU(VRUQQpl(LxVS56BxpX)9F8H11dNF8QF7Jx9n73V7M1d8tF4(Tp54DVz98lxV(0XLVGg)f)Zn)
URxVNMZRpT(JB3)4vp74P7(pF8QNSEw)9Yz6pBE3(JVzDpdT7F4U7oE4jhF4W57P)9RI(sZfO)M(VAYx
OFMOFMtXIxFAm6cv5P(qV7B0F3Phhc9YYR4zgtPinWGJhHVfBYGPhwk8JO)zX5czDWzNab69oFNEa)8y
m0Deek4N0SZawD5NXCSLlkSc9KVxvG5AHSdWLgb9updJuTNL1Wx9ewmhaVYmEeInFsWYqo6C6GLr0v6i
L85OIMXS31nOvc6pdnFoFbek6acvFnHPLsmVuMwQOWQ1IrATi0S3QcTW8YsP5fQSuWAglv6pmEcy6apV
MCjJgY9iOYumKzsJr8McyHnK7HOYDeCuz7XeHTqgwZzwgw5vSNYcOi0i1RvdZZGCiow1d2ebwLYyDaBK
(wqfBri2v9PAqPsxi1AtUyEYBv5UN048MKYfu0ofRIcP8IyUwy2TnpvlJ4bLeJJnGKviF6ENxPscB9Dd
1Jmm8SADoqczrdNicFg0rk0QQGjwlTAuxKsPKGjqSNsbfWcoRefjdt1ftlQcRbA9kSmmqdk3R9iOpcl4
bZCPApvvkH5lXcKr9Esvf8XsM1pPbuBmRsw4aP4pebPamgcdtww)jQizYvkrf1kvJ7KjkYpSS4NYGRMe
JmMX7AfwrJ1mipbSsqqz7bWNInIBllgZstd2llV9k10Iom2GtimNYu7TbBWqYqNm3A2VDE2DclKsbsBL
j4gRx17g6rQvjvfsgDsfJ00YtnVUIu(qOY6kLcW6SmyFN42kbiiY0jrtL5clGzmrWdIGDq0ldk2iMCwP
Mpjsk0uzhPTfAt2rdlbbxgHlcY3AMtuInjCFhgExHmB0xWVPLR26lWbTJTct6OBGyzGdBpASD3ucaIvg
SxxEYbrc4hpyV(tAbZriKjwlqvXuflspfGhRyQbREMhLXsqUcCYVsKlxp0JjVkvWSyfvOgfuleMzvdv2
5gZKjGf9QeHv0e5BwTB8qutmIguaczO)hPbhGgsQkBhWWoKkzDVdYI2joKyqeQWGLCFxzZFXDsous2gg
08uaNszrROi2lUwvxeFI2ucKhHAQrsiNAE2mu8iff1yM6YnZft01BQheIreXEHeljo4zmpqOc2ImBuum
lBWXOgz4OUXKrZsyEziJBxvfbKCb7druzsDHso0cS(QQfKCricjIlP6DKlSqdeQazmAsLqyfDvEallb0
qPHehbWji3WTHQEOaZAYbBTdnt6NfyKXqUQsxbrG3jYsf0xvxlrna73MPxdDgAxHU6rS4JI3bESHAcSv
oUbHWw0WyWgi8YwHiGSJ6yniffM)Lfwv3RQp8g1(fertVhvpS024INjzL7MsqI4VSErvqTmRgWugHAoo
(grzKCDbqqm4iy8XEZ5MsMaeIe4Qk4OiiC8F3uRwZfkPuWBILuvBEZbvmghM7m5v1WPi9sMbWCEERnm4
Aqe5I))EacabWffWeDuGuMeCIDGnyy)qMU(l02QQOLwzH8YalAisoIhQUJt8oLy3FI8KDhzIIK9GbulI
uWRmzv1w4RWc1tMxD8EjMfwxWN9QqKgPRLaBN2wpbUQl7u1h2Qgojyx1kK6KctckAUAeEaymrNKeZJYp
krzxiM3gdTwqvOyNMq3I9g7GkhjH94PuuRXHcJeIbtxnNTFuk4QZbWqG5nc2Qwqvsyd9mslQ3ujvGOC4
OJrIIA1NZzGUeynDbM1axWumAUK3uCYE9P0wMPsceSlaVy8y5WWdY(JeqShNsU2Kr3e90CpZBqfvAx15
jLype(KJuC6abz1N6JkqlaVG3CYrRS5bRC6QI8LHh5j1BEAQaU0S6Glf44YL)MEmDIajQIIYuT9TtrsU
cwj7dwDBqc2I6DmL6E4yZ7jMo28LXn1VdHpWvCWtgG8SeKNdbtffDs5NHGxLBq1Ou6LGX9IwadKvxw19
fLx9NeNYlqGTgPqNZEfAjEZxvcWo)kkcrS9celjYQWBILGfZn5XaYfwPhosl0UVqe0CzBdxAawOSKiu5
iKVm58qmPvAY2mmUbcMgajQYqHJnpdktxiIMm2k5aNxlH9w9SdCwLKDjxvQmYEx1DiibuaouOntHDpPo
y6amyHgjT7LZcGM8LxvhouulPMzKApK2d3HFsizuI4NfTSChsfk6ulOk6COyVhw)fAdehTpEFQbV3mhj
oGReRbJDzsfaBOr2(b4uIC0JJSsBOhnZnchLno6yWQyL9qMXJjnk58dr1IvJ7qIteSv2nCwLX8UfbOY1
uvzH(lji6ziaLak0XE2Gl5Lol2XKgoCYYHGZ6KIQbDkDj4wwK0jLIP3zxfsoAaQIa9OaR(WybRF5n2DX
jOCrLiwurSgwc)Sk74kMQueMbSvg51ScDbsTdchYqUiEmweFwQ6oRc3WZififlfhwQttjelqtI0RRpU6
9ShhMntQkbZUN8uH5XwT6ILYDpopNOvaUj59rojUa3UdgIe6AhmHrIUnapY8aTPA3csJmKIM2MBCc)QE
KCgFZmQjcj64t9IAQ2Qoe(DNS0y9lwdkr(7vEk7XkPAGYjMcQfbVdxaAU0EXqRJd7QO2r(ucCpkOoEf4
zrArYU5IcifAJs7KFz4nH876LWNaSq4mmxxcbu3Vpc2lDWIamKAuG4mFkXCs6uJkJkXh3Tb)fXgonaRc
N1JKr7IRSjkKJaur411Y4bdwOprUhZ40SCUS4TDeYGmJ8WPhV9ShcRqaKpnnjQDEj51G1(yOZhOu9zjr
pb1ZQM4kgltvzFFnNsDFYzrD1Kd4x012ompN8RS6ytWAZYLJpe6svkalftR0rJIa7ksw34HWbxR6LYM1
Q0LWhpmdKd7Gbq0N4EHv9Ybjw6KqFUX5sYEOxs0bFupE48EEWAwYrhgb5ff5LJZEgyHmoOtRzkZsG4yZ
rbSWdapuvZxsLrayqkANNMrxWry3wGILdHQmh9yCSBzsQ0ZQ6mle1tdiilwmoqvW0t6rff)Sol1xcuvM
qGtMKgIfzCjzvQOOBbNYG2g1LbL3tA4jN500E4T7E3FA7P73D8Wch8(MDhU)86HR3kPE1VS5fR73D3nh
pT8k6LF569N3E6WJx9IDhE3nhV7E2mGWNnF(P1Z3U7XR(I173rV(jhV7dpE1MZ0FX0mfkYMxV((F73V9
8TR0R)838P75PYm5lwaIJqRXRVD7Jx9dhUz7P3VD7hygfn7NU7e90xU(WEEyeZCZtxp9(3UF9o6Xpz)2
3EwwNiM(FELqZpE807VNJ0KF627(Wwoj0VGG5V)XRKr9fhjkD31RmFNu)38fNo((Te69n3VNiFIhsBos
u27E4Eb4ja8NEA76npE13T7mZXOOY3S561t73sq)LhpiCOpXtGoEYMNSJjK3CA7hPxstZEvNF15p94vh
FlJmme1fjtq797otWG4WeksV56BzCH2czZFz9WnR7xfwfzwOOdXLpS9hjodZc48oV5fhpDA99)M7F8QV
F7pU9W72k6D0s(DN2D8ew0ZYCxV(0wIwEgZijwvK4c)HhoVNwhbnT14PRF8areRVF7jw7oXQc3T906(B
u2XDFCLPRmJuV421FIeX7F36PhV6FFZdNE761B)peIJK2VA37U98Bx3VNx8dxF(H7KTgiCJPTt7wzZus
6smK72DyROLWQLF(hPf)GWtem6LeBHEpNYq6TF1PD3XkFNpUNJgIe4)W(BEGzuE2vYMx8aTEVE3PvHjt
rNU5LF66J3X65N4kr8JKsTGHvJPU7W7V94EHZ58)mIsymorL)3(I1tRFgbGHO8lV(2JcsZjNub13FK0Q
yXo70LyaR)0FB9madP78Sho8UvPQi73l6gnE5oTB77(X19Qm8Ev5wS)oD(2RpT(rAcVeShk6adP)arH0
B(ZBjcIEdV16MNEA9DhNk18HF28QJeyoTveYKl1n)Lh2)BE2kR0SW5bISe2VE97pD863tI3TF48T3ZUq
ObU5mBNFCpPSifT5dNo(2D73(ITFIDxS5Rjt5d7p(EP(qmq)B7oWYY3kANKmz9MD7o9ZQE08TF3X7p)M
1dV)x51B(FEy9(B)BKhRTYi2SE6DBzb6Ci)cfNA(YVE9NiNmYlF(dVz7UFZRV94pFY)J)()4V)Ro9VA7
XtRhwL3(6DKu(WnN29WLa4RjM6B2(t)AihJ)eb8GcIV70XhU5UJhpT9IH8Cs6UFRYaE9jsFGyhx(EsRG
uC03)5Kv3JxX2BJx)L0JoT7E51VK0D(kY52pdbxpD40XF6xF9F2297FqF)F8HT7joe5S5NXJ(h)V)l4W
pLwVviD(LG)uFruwSht)8ePItdLlg49C1dVJR9N4SA35DyNOcTLlokiYCQBzKrwpga2(wJOMJtJpw(iw
vPIeCKNO(Cs0p9qgNafhH3n37vcjQgWkGK5q)hTDRRHykRo)i0ohsHeJanfbIfpkTgVu4WuSdKSfneDg
xDBEzSP5tX0q6ryG1knePrPGJpmoNiwG(abahIFVDoPQvEflsimaunmIXArKwMLUdzYH5Br5GHGbbeOy
P0Lc4j3uWZ5Ow5uinLEXVsdvHrgz34KAvWwM5tG9CfWjMSZNl4CFW)XXR9JJ1lsv9ud2pJgOSZKHZSBV
pPucNCzfQjisgLfMFeqZrb6yEGUE(sVBP4NpVrEWKHchHTajy(HIzO(QCm2(KhhuRG1fjkG)PLF5kwa9
Wi8VYDjLGI6q2ziakKkenvfdr1FClJSd6GwWG1GtcBvm1HNQqffeuusg1kMoDmQAMKwiD(wTr9IeTeN8
kfOJYYVmsMeylk8hLHrxkq9CIyv8FMGoYeYmDiwIdNXgrqZZH8ny8FnFL8Z7oo0sbsJYGA5k3VmY2oOu
J)Gd4XJvZck9(A0kWULSgMNvZYPBCcnd1juKA8AGEw5Ke0pdOxhSuMJKGFNEmmDS0HpkKXr)iNpcZnLZ
tQFGhj7S7PGzJAPZWjUyc1YCaknNHcyUQOwHqnaLElIJYZ6fkqg1RTOUK9I1doNkZkcgPIeMtHiwgD(G
uilNUiL5Rn9auLVLrICGIWmdk(P2Ffk6Hq6IhcVDObsy8S4GpQlQuasibixG8KmRugZPniCWxi8yOKdp
1CwAmlJS5(ou7Joui1SclWRJ5i3QZJmY6C(6iRjZWH0g9GZ2QM(ekqNt8PzvouwO(a8(XdTkKHcg5wMj
UfWxNfk2aenqDNtta0TqX5bsd2KLbx7PGu4Xcjcj5n5mpaJ)vdnZIePWyrAqgis8w9ojCbun6nf(F0Pn
IktQkddoYDsAWGsMtaZGKgA28CADNXYihxma4madNuKAFCS(Gx6nhBCEm9d(d0xR0MlH5dnVjAA)fs2k
DfR8acoRXmWphD4HyKgSSwZ8H6apMG3yUO(4owlDu5p(HWFIL0BLoH5DKBXG6GrbUh9)G5ctEP5i1jrB
yhAdd76mKLOPuYlB30FqBIK0wnWgPXs72oaCwHMKcy5bUzHa9NQwKe8dN43KuHEcPqAzzLhPIEAtDydS
oyPikj0yd0)H2DrMT2bvG5OAgKQhAWeg4O1dOr6aFkNQ5jUJTc8CMJbhd5F1Hbypnz9qaHuZIllfkeCN
QrO5rJ8G6flYmIcgHbM8MIMlHORS0kYGoPf9t5FWNGLwiH)1I5XgJwxQGeYlEAYwLHsCUPNJSmF)Khz7
FW)CSZSzjrEVcw8FSWe8tIAAWOpybAsEPTOvQjZ)K1FwGf8p1Hl0MWqCL8(m2VjoDkm60PLrFmXAT5Kf
cdduqHtLaR7Umyvn5LevQBXs9ldkNd2su4Gwh44PDuGPI1qslJ(dWE6i(18fZVpqfZ)f5PVehyfwvbaM
t1z5Srx4zRGf2zgbsmsFjGLsHiZ(aQxG3qAmRrn5xlb1CUiGJiw9(Xw(9H3y0kd8prN5XttlzbaGPJWv
b0nbqEGHiMmRpIaXuhCJWuCHi)LHQKi5qWnHFA(AW3M9tipFe9SmG2CaWnw3akh1gIJM(F2UDJE6XkTV
hqAQTaTPCOcoiPxAHqWqQoMeIZ)IwjKlVJTZlpwSncfoIf2ipnqaCBwI4AAiygzK95ihbqzopyOcttRQ
s8tRAnDTPbxgOj4CGA7ti4bCr73GPbpSOwtmtaf5cC(rFprJf)K20UNNi508lDbBQmhaWHMj6ybsFoP(
q0gRdERf20fnwuGKDxSadlPK5yS4Nn8A2JTJTATWugAQjdyac8tNePTjk6UlzSuObiEn0xHoo0oVvug0
Is8kqE5ZtzcZYT1fAyOl5CsmSgtIF4KlKcywnl6cPBBCJLDAIA(qq34yaaIx0GrULrtb44IcfCtJrl8c
0N0(rNHGLcHMfSTAL5yXP0tiG4r3bi0s1enUShbQmAcpaHXzmkx4ekzs)2OHRPtJuSJM0SfMBE1lrNPr
wYmO1gwJFQBKFb2R)efM9bAyeShfKa2zF2nqwrZbIzTOdAXkgXkf7CsODICITzzOEve5StzJ(X7rGvuS
CfRKXOW(8aihTU6aaqrswbW7C1mwxsrYuA1(nKjgTwR8JrL9K1xRtLiBQ2EnmbuMeqZ(zOnXAOrsojS3
JUJuaff(KXSYvNIk9G1d4cOG5bTQLjhelaBlJDwPO1Tt(oA2pRlvynsTFV45qH0bV)sLRXsvg5fuBDoE
n5QgQykXi7tx2T(89bdsblAMeAupma4YL0qqK1(oTNuYqvSPa9REAc18ysJm8PThImaTCQELbhNlLrGA
94nyzUpKqhThc1DTyQc)T1SoEcvFuu2cjl0nU7cIZfqXq0G2aQJJbuswH7rxV4wM9tI2srikpY8VoHpu
MqfZf9gT74zouPJ3lfjhBuXN3RmHFEYSWPtSB3XYSzDfd2(iJN(ILXvu8DdU9jegoke3hcpieHVi0GuU
fnfJtjZiYKILNscQTKrdo78vmEzNayS3dtcy7IM)YR3aEpTTaOf06d8IIobMX6uSeTWptLrEbZv3avh9
QfzeozgiESEDK9z0NmgubpU4AM(sf5isMU59uBJgtW0h4A1oakHa550QZbavhRXEWaAdPHLvy0TbEDjq
GMOlbng)ugArvpBiB7AUGXAPHfx5igfCoVDkvR1lhn4QdVhioATuM16JXrQxCwsdLXo5cnOEIUKHFAQu
hUyDwOlwd4BJnor3PcooX1463Sm6Tq5PTQX(rpGW)meU49xGJ4CZYka2eNRaSJujwSM7IV2pylR0Oao6
1mccDBBKqn6qO14grzKGQvH2pZVm63cBOGnt7De6t0cNUHRUcIhoBj)J0zTnATUSWGv107VS3oSnIDE7
SC4Ahil74uzJ7kcimfVOf1sxtvVExoalawsraICRDRDQ5cmCWDkWMvEmlt4Zdqzh5wXQwfjeT44iNVMf
qRB(tiNBoBfSEff4TY5KXMMadCg0wAE9NiV2eR1sD28EOWhhEMmx7a38naaAFXzS9uqVXjIJKxADXLm2
MKCqE5Wf5sys9ro3SEPcJ1dRu9wb4gnbRdlMPv3TJMs8wtP2toxQd6kobk0tQz7OBXKVGy)TMJErVkgG
BK5B0eGFPd1F0CKc(vSWUhPPKDzcIMmjmVf46DaCc(cq)Q6Kmx3SZ(0TSZK7DKhsC7hfPAWCLiW02a2n
UMn2Tjy5NDXTYJeANh3uf2JTcFoZa4Sx4kCjshTDQu7jl1p0iXrcPFMhXLugY0z3Vjj9c7zrI3rDv82w
cbUoKaTr3YY)RC0sKcJSw0cPrMWQwJWttjpAq26OEkeYcin7YAYYkAd0nkiBiEr4SillJE7Ez0hJov9c
rEtYkySuJw1T5Z6yj3IVQpWrk6mrgQApYZ)YDH6N2i)yPqOeJE2fGfiRDLDWyH7XCZQSPDLpbCX2y2Lx
J)xOzRzAa98VBzCHDCk66NcCtEwXUNYiHjiJbMx3uWc(0Av4LFEt3PxkeMCqp3jkxLmIunHEw3nV7P87
D2rEdCZIQmCPqEMlh9MaWdGRmtzWWIdFwWlsG1nSdk3X5pihWElnS4(ajRvTBTqO244cJ7IqP7EeWvTn
It2cdMVNdG(5Xfh0pipRxIfMP2P0or1pbDlVBKYQubb6lqTnhj0sT7aOOWvgP(VpdcyuTkRNRfHzdEKO
4FcMseU4pUfnIyvnKd4ToORrLvW1mBrpiFDcwtJngZJDDsW7ix(wZRbVbYmKtl3SOZw9sWfiGdwQc8UM
c2P)5rcTbox7W(osNvjmX28CS6tBrKNCC55yiGlvfySwHD5ltT5GvVjpcK0gHMrlIxa9zIaSU9K3EXmA
5i5NsbBSOV2Dazhbhy1Ctgl2KM0nTlriUBbEv3EKgW5HFNzVIrCyrGlvIBzCd3w04(uohh(SLQJKD2vN
3kJnUI9oHXBXmHMJxwOEYYnllcGAwSAjvjeYwXESBTXcVVOLhe9EiYqIJqaX9sBgAjAbDETtTySAHrNP
WQWeFwMiOeRWm816YY6tFe4mb(84OgLrVD7cvtFa3NyESKlCRIr0MewHZ4(LwPl6OP4mEr8rgq1DAW(o
4MX3fIwDjhxn5LX99wxSik434csSi3iNrC(b7WF0MiJ7UiUtiqP1oDODDTTMKMvzr)47bx0udTSkB3Li
hOwfsK2qyKUQrcx5J5oud0B9Ux9WgnXKLuXl7I9OZ2jvW1HGUoYrHEte8JpKamgKSAAk1Mgsu92KW)JX
xuGEjzx(y9((BCv4HexDuzj1B3LY0SD2Karmxv6LQqEkjbSTVBoZXD1I0c3JjV6DX25KPjeOID9(xSRv
GG0Ap3l)uBwF3I2Mu1b)Xeg000hYXz2htY6MeMPoI6UG5hOqzS0ZB3VCLRb(xnzCs81IG5qnNvRucrTU
Dc3Vu(PZVQbK5sZo0j(kdOeGBuNnARvZ9qf72soyTA5oUsolAq7qzT6gP7YkKSDf798XHGu15IwYc1M4
GxC(WuyZYCF2tli0C77latsf7(EgXNtb(NC9sbmXvqrz(woNYXQvJZ4ivLmqvfj58UGG9J4Sj32nlXWS
IG5fln2um7G0NqfRB9S7C)YRSB0kpsUqn1brJhIBCp0jm0ICTwMi4moueyMKgkpyPDKbu7EB5xSVelmQ
Gpzf8GDrFFS1u3YkiTFgcBIW14LnyhCZJRaQB5vJBmj(PjI8wDuTRwUt8x2qaYE8jxrMMP)iyRflFze8
jT)o4m0XkZ25H5BtHfBu36vc7RGGqpAKWELlgg7fBP8oI78hdbr1Fm2OfJEZIWMtChoKfDknVHTJ6dqY
o8qCz(H2EyIkEZUPz(tW9YYHbuNqDgNQ58ZUJQaxBZXAmXrZFfdwBLsYlRafuClws1fYsLnS31(eQiAd
7dXH4CySNrQAbwmUzplYvIaQ6I9RYoWvoIjm(Yeckhx3CEwC3Hysu7JWd(Ueig9bZ(qWvGH0w)wDkNxr
r7s1iAIrRf8I69exwQwXYJldwmlwlak4TQPe0tEBRogQxexSPCXHjyaOCbutdka()zZkBBz7u9CbQnE5
SHTQj4OMmZ6qZaF8n4bJl3NtfaqwikgjJ(S6VLUO5RX3OiG)wIu86Nrewc5BwZaY9y3uZYkDkHvZ(4yy
YPxUpNc1rPVcdDxERaqxuyswWc4ZwGb2PrRDUAo(s9PjC5Z5LG7riWAsw0BS7u7KjnRknLr2k42ZWmeZ
AjcygFCuHZ0O90Y9(OYUkBHFO1ofQVwg40jWSpja8jOg7KBrfXfxy0DzXlRCgI1W(gz5ex0JsjGV(ec(
RFBo8sJlDzi)afiUADkSGCL3v1duKt2GIIT(ylOXTgo5Ot4OKqpyThhZsrSq0CYtDvOaJlDSG)TiSGyd
FlfHCaCTbt1Y6gU29EvD1YlexTOYKXbZHSDGwkQwRPK42FCOmAB3Z6mWXbUgVcdu)yrimqlzxCZjcov0
oljzloZvNF0IW8PVGCnm6B6exLtf(47ogJZe33AcfCdTfQ2shlU9RmRYUzQlIFTIj0dMqNmwTEIYBX)q
BGNTMcKPutbk2Sstyxm1fDN78eSyf4G98aS9ze2ElRMnonX67Djl)suOlMp4GE9k41cFDOecu)uSWIQO
1njcBZCcR3(sHx1kwbrS7JkS7nl844INMJJmYeAwJyGR(mVwvZ1O9H8HFp(gga6YIJY(UFTO5EW8sR3Z
ENMWvml81gIrwCpHDkHdJqHZ2bNL0Sd2pZJ4KdPr3gpQmrmy30FUu3(jcORvUoQrOErtfSwVscm30(Gb
bYcB7Z5EeIRMfZhfiA2org5zZcFex2DNkUSmdI7QUqwJR6mz7yMXTsCu6g72vqBzm21phhXPJpJkobQD
7iDD7t3KKkoBJMGz8LWn9NhkFKbDw2hPegS0gcw5u4NQaZU2SlxEtLjM(mfvjlLbCuygOgrXzF0eClVA
8D(ttVSd0v3QIeDiFe8OVhTMHxkpbwv8LntPGKEW9ZlBwpC44dhUE7FA36tUD9mFpPEZdNpF8WNF95Dh
py3x3VLV8F)PT3U769BF85pD39YLP6XR(RYFV9Mp7Wr(6xU7W7(S7oEZV)(B392ZYVU(8P9)3p(8V5z0
yF7Xt3rd0MYV4a3C9PDFGa8V7A(AuUNNYJp)lF1tF85p54h(0R5Ba357FPS4p)Z)Wh2)PV)H9BVNM3h3
D(6BF2E(IGU58NiS8Q)kVu)A4I(o(jt8GE3JxP)rgZ9p8M72sl4nx8c7pF7U72XxzTn)5V5LZ3(LF7MV
uj19FA9n73(VyIp97)8V6p8QV)BE638QV639SV9)6xeihxptS0))V8mFs()(NOsM1E36PZG1D5GGGdRY
)2JxTz)Xp(4vpJE8NrR02FC351ZBPF(x4RXSYIP)1xTF3n8tF2(1pOtDZh2Y3axY3g9yF1v4)I7WPi)d
oy3k)JcNWQXI91BjS6t8f(vVrPF3(hUJb73F863UD98T8vPDZ7)0Th1li(5T6m)H7jjm3wLHUcCAdJbm
)w5ld6PT3F8e933m0w57T8JxT7TpEfOzDgd1zLTaYOkOTMts6hK70hFU8Ph9XNtMt81ZgAQYCV)dBVE3
6E6DNTB7(5)WH9F6Lh)rADyZQlS0(HVHEWz5pl)F

**Comment by mbattersby** [comment]
While I can't rule this out as a LiteMount bug, it's hard for me to imagine how LiteMount could cause that behaviour since it has no interaction with the "forward" button or the druid form changing when you enter or exit water.

Can you check that this only happens with LiteMount enabled? Try disabling LiteMount and see if you can still trigger the issue.

I would have expected if this was a LiteMount bug many people would have complained by now, but you never know.

**Comment by Quaantt** [comment]
You're right, and i dont know why i assumed it was litemount! it happens even with no addons enabled.

/facepalm

**Comment by mbattersby** [comment]
Thanks for letting me know, I hope you figure out the answer.
