### ISSUE TITLE
filter for in group or raid

### ISSUE THREAD

**Issue by Smallinger** [xod-wow/LiteMount#31]
Is it possible to get a filter for in Group Mounts or in Raid, so that you cast only Mounts where other people can ride with you.

**Comment by mbattersby** [comment]
I'm not really sure what you are asking for when you say "filter".

LiteMount supports [group:party] and [group:raid] conditions for the action lists. There is no in-built grouping of passenger mounts, but you can make your own and then do something like:

```
Limit [group:party][group:raid] PASSENGER
```

in the action list.

**Comment by mbattersby** [comment]
haven't heard anything, going to close this tomorrow
