### ISSUE TITLE
Any chance of 'logging'

### ISSUE THREAD

**Issue by laric** [xod-wow/LiteMount#34]
As I just get the feeling this addon doesn't do very random distribution, would it be possible to get a log somehow of mount mounted? Like a counter on each mount in the list or something?

**Comment by mbattersby** [comment]
It's not a bad idea just for fun, but I have to be honest it's a long way down the priority list of things to work on. I'll leave this open for now as a reminder.

As far as I know LiteMount is as random as math.random(). It's always possible that there's a bug, of course. Randomness is rather non-intuitive though, so unless your counts are in the hundreds of thousands or millions it's not going to prove much.

Happy adventuring, X.

**Comment by mbattersby** [comment]
After 8 months I can conclude this isn't going to happen. I have so many other things to fix and so little time.
