### ISSUE TITLE
Can't get Maw-specific mounts working

### ISSUE THREAD

**Issue by filliph** [xod-wow/LiteMount#35]
I've added this to the Key Binding 1:
```
# Bound Shadehound in The Maw
Mount [map:1543] id:1441
```

Which should match the Bound Shadehound:
![image](https://user-images.githubusercontent.com/9424286/110946922-66702e80-8337-11eb-89bc-d0e78a2a782f.png)

In the zone "The Maw":
![image](https://user-images.githubusercontent.com/9424286/110946958-738d1d80-8337-11eb-9a93-d20ed81f7186.png)

But I still get "You can't mount here."

I've tried:
- Setting the Priority to > 0 (though this shouldn't matter since it's calling a specific mount)
- Enabling the "RUN" flag
- Using `1312` as the ID instead as per this page: https://www.warcraftmounts.com/mount.php?mountid=1312
- Creating a new flag `MAW`, flagging the mount both for `RUN` and `MAW` and using `Limit [map:1543] MAW` as per the wiki: https://github.com/xod-wow/LiteMount/wiki/Map-Specific-Mounts
- Just using `Mount id:1441`
- Using `Mount id:344577`
- Using `Mount [instance:2222] id:1441`
- Using `Mount [maw] id:1441`

And nothing is working. I still get "You can't mount here". I don't understand what I'm doing wrong.

**Comment by mafrong** [comment]
It looks like it needs to be explicitly included in the addon, which hasn't happened yet. I was able to get it to work by editing one of the source files. Search in Mount.lua for 'Corridor Creeper' and add a line below it like this:

[344577] = true,                -- Bound Shadehound

**Comment by filliph** [comment]
Can confirm that works, thanks!

**Comment by mbattersby** [comment]
This will be fixed in the new version I'm about to release, 9.0.32.
Apologies for the delay.

**Comment by chwba** [comment]
Im trying the same thing with Traveler's Tundra Mammoth and Grand Expedition Yak. Added to Keybinding 4, same error "You cannot mount here".
![Wow_uudPeJ3y0L](https://user-images.githubusercontent.com/22568014/112770481-22637600-9027-11eb-8022-a53912dd52c2.png)
![image](https://user-images.githubusercontent.com/22568014/112770489-2abbb100-9027-11eb-80dd-4fb07b79dc7e.png)
