### ISSUE TITLE
Add tooltip to flag headers in the mount list 

### ISSUE THREAD

**Issue by filliph** [xod-wow/LiteMount#36]
![image](https://user-images.githubusercontent.com/9424286/110950289-93264500-833b-11eb-880b-67101782e905.png)

Hmm yes do I want SPE, SPE or SPE? Good question 😛

**Comment by mbattersby** [comment]
I can't add tooltips to the headers (sadly), but the tooltips appear if you mouseover any of the checkboxes.

The user-added flag part of this interface is going away soon(ish) anyway, to be replaced with a separate "Mount Groups" tab. That will hopefully be a more intuitive way to create groups of mounts.

Happy adventuring, X.
