### ISSUE TITLE
You can't mount here

### ISSUE THREAD

**Issue by malikoth** [xod-wow/LiteMount#37]
### What happens?
I get the dreaded error message, "You can't mount here" when trying to use my Sky Golem in any Advanced Options scripts.

The script that I have set at the moment that this bug report log was captured is simply

```
Mount Sky Golem
```

(I've also tried `Mount id:522` with the same effect)  And yes, I do have a Sky Golem, and I can mount it in the exact same spot through the Blizzard mount panel.

### What did you expect to happen instead?
My character mounts the Sky Golem.

### Did it work in a previous version of LiteMount? If so, what was the last version that worked?
I don't know, I'm only playing around with customizing the Advanced Options just now.

Please do not modify anything below this line.

--- General ---

date: Mon May  3 00:12:44 2021
version: 9.0.33
locale: enUS
current profile: Default

--- Player ---

name: Jgor-Spirestone
class: DRUID
level: 60
race: Tauren
faction: Horde
spec: 3 104 Guardian

--- Location ---

map: The Dreamgrove (747)
mapPath: The Dreamgrove (747) -> Val'sharah (641) -> Broken Isles (619) -> Azeroth (947) -> Cosmic (946)
instance: 1220
zoneText: The Dreamgrove
subZoneText: 
IsFlyableArea(): true

--- Debugging Output ---

VersionUpgrade: 5
 - checking profile: Default
 - checking profile: DK
Initializing LiteMount v9.0.33, debugging enabled.
PostClick handler called on LM_B1
 - setting action to in-combat action
PostClick handler called on LM_B2
 - setting action to in-combat action
PostClick handler called on LM_B3
 - setting action to in-combat action
PostClick handler called on LM_B4
 - setting action to in-combat action
Updating location due to PLAYER_ENTERING_WORLD.
PreClick handler called on LM_B1
Dispatching action Mount Sky Golem
 - filters: Sky Golem
 - PriorityRandom n=1, t=0.000, c=0.000
Dispatching action 
 - setting action to can't mount now
PostClick handler called on LM_B1

--- Options DB ---

n33AZXTrs2(BzJ9dEDmY7w4nG3pP3YYs0AfPLJzDieeIeIeJA2Gl6ULmDCd(B)MzwNtvGSbLOJ7JyIn2
XqORkRSY3zHdaBtApQ9WtoVBs)V)842UPHRp(hU(4dVCyQFZ2X192agx)XHZEx)0MHX1Thu0UT9Wh2pn
SQ7QoB4pVBv3NMgxF6Dn632T(QnB8d(W(1F3)yy9cdnth6lpBCAbEy3M(FDD3N7Kf9dR6FD3jtJTpYU9
JhV4dDBd3zVL)WDRV50o8)4KUnBV(4h3j)ppBC6I)TdpV7Y(nNp8XTFVsGi94q)9H1NoooT5bB(YWfxm
S(S3)7J72A369xF8rtDFUF1(06)moX3FNl3UBVR2J9mPYh6)09uZ8UUvYc(XDtxDFe3pv48(tg2t1ChY
7fKUlOb(Nmb4ngVkm)ZU)cMylzq9TwrDv(5RM(ZXnNF)xO7JT8)0lBF(vY6nU()t21)ZT)6sUCVU7tmu
432)8TDFEyB3Fbj0FbdW)7EHUpB1WzNV1Vu)540srcU36I)VTf4DiIVpwAMN72UX))HG7L9NonCX9vHo
kzqxVyiLLI4(6UvdFAC7sbgwI63WH6Rhl)DJtN2TE3M)FIe65NpQ)NFBC1hTOB9txDFfqp7QDSUIV(g4
GR22FpsCze9LFU)0756Fy)N72T(0P7Rh6H9Yao)Ep6TIX59MR7ftS7jHF(40WN6wtlLUPZ6N62SWOt9f
KDLyeEF4HJelQvSiRVb7219H7j3(BDB86dX(wKg6pChA5Fs0eBp)BYaz7XRFtE4LNUyC1Li8d7fp2H7R
o(LFyAXCAlqzz0xon(XHv9)C)vM2A56Qp8j)8Dwf9HpP)JD7wTD5cNJ)6s1kh)17WmooG7OsX4awS4Wz
l)c1rzBR7O0N4mVJQeIdy5mQZLllMe1w9LZ6nJTxijYSFDXq)Zw57iA)CEF5a83X2Fp(7odxfhYIrFJ)
8(bCJ)2IXyNT9xiS6mwBXyDZfEleEZuk3rWS4uxi(1ml17iZwCelguj(ZleDk(JlfqC2EAHGk3XCxAa3
rGgtOSyyLWuLjF2QXp0TAXOshoSEJ4bCsVgJ5GeXMqm7U40XP2dAAQfgR)Ilx1F9XJF86JLiqxmE2oja
vMOdpV70XV8XU1Nj)qF)LcXks9JVxZWR37hLQ2oxM8dNoPB7u3FklqtAt7Hp(8Ul(q)KNQVOVBAR8lPP
YY9crXFHW2ThKNPI7Hvd6c8yP0VP1BK7wrhtTsRFEYgAwDJE3Z6)OS7LbFE3Mle2PUqDIoByZ2(PVt05
h1pn1DsVKOZv5Ap8rDB3YD2t6KyqFNQbKFnVqw6JgNotOJYynzY(6rR6orIQEI0(8t6VC75EBON0nj34
NmX)HNyQOX2duQ)RRoT7Iore3i)JNVE8cjk6z6)Umry2hE(6V7tDN3VLsOFzLyx9ZYE90rH1tsCY(8jt
9DNU5engXBLMgesLjt936xTYZ0pv2xRh2ELWYPjIM75dRw335zSFtyFvc9cjZWwrYmN9KrlBOxmonn8X
HtU(43nOgdEA(ltNjHTUOBYgw2DnmZb(lsf4kVwvOINXXtvfN8BR6en2RhwlMukrkwsFBm5B7VSt0ykr
QRQUPT2H9BpxCjg2SXwIsAWDXOYdps896K165tJsio)6uPbLuD42Z7EW1hVvfR)w3N82pqmLQwO6p4j2
QoBYjn5569Ng38aOpEKvdVgd7vymvQvXH9ABek)zK)OPHDx85bjKrVYLjLQsRRFTzg5Aeo6xUuIpTvKB
II(19si)Zu3oHyYc(SP((ZhxjB)m1P4WTwONvxOwOz6aE40P9R)sFNAB84Xpl6V1BnZ7l3QcZ0BOuZkK
v)XIfRkbpqOKfTioGKcxcmJfj)4O8)(cBXllQGqrcpUT)pU(43mSED3jR6TjjsSNivumPrV(11N2p9bX
aueMfzIH9VSBRkdvIioVVzachjUSvqPzg)qDBjPrEu3Mb9MzLIGS5F3zMaZ3I)Gw7I(VTl)V21lXq3O7
81B6N(CNyYz6Wmvkl(DERnrZ2DAVeeOOPaBJhVBLpQH3snkvRkKH8kR)d1GyUICC13j6r1qmTqn6vXZB
ghwV1y4AlBSKA4p(dn5XJMg)KQa(PnWaknnpXC53PoVfvY)4XJ7MO0qQBZSYkYbh(8jZosSMejGWSA8x
1QqLmpCB3QVZIhPlTsktwTSTWZgw3P67NmTt3vZnhCleZsebPukDOML4KXjDHDLcN9Aj0o3tAKTHvxPl
BFNolrMFK4VlcL(UpPBMcngYbItA)K5QOHxvVxvrigZVOB1QnHyfs6Odug6HRed3onwI8Z9xPewmqoCy
LeDxkXC60yCJYgZ5zDqrA6jF823i2Ps6SdskZfM4)w4x1avmcDoZb8tF3rN3zXK9jMKXjc2FwnxoAqlx
qe1QL5R6pZIOD45dxA2CsEXTdNObw(beJ78(bvLwP6bXir5GZgTLsUXd)Z)X4QF4G(PDFqVt6n22VsLk
k7ltpx9nF6vi02d)tDV2PP8kvTHuVI6C9YDRpt1L)06Ts)Yhywrhi70ZN6T4SzQe8z)M62k2cMVY0WgL
)FvVDWiP2kvRQLvsmqT6e1)5vDMHDwMqVdF97IwCltIsNyl8CRWXpPw2vY)CEOFV)YxKSQMQ5q4bKOzM
)Pt6LE9)Y6GB51h)Vv)VN89gDkSof6NL7sf0cL8hxIoeH3FRWiYA3Rv4fnNluU4x3EwNTZHwTkr3RD)5
)OBRP910Up3k6wsTpQ2h5QD9nLV66ul3v47Z2j2Arxd5(cl6RGckQncdGEJtRlHJZb6ECRMruYU0BRcI
iDUpZ2rNpCYN6TDuD1nSjEO6kCrVgvjPOHrdE9VC0lE6BF1V8KN(V8VOB14cjrBufsTQbgx1VLHSfclU
hVrs0UtkYB1kv(xMglArZIn(fMWfEoxSU3MQwqYRf1h4jXJyTLOyqgNTBQ1cV8XHFdmpEYlSaYYKmkKO
vxkflOE)YuhoT34aUHck33i(LAKTsNWUp9dkL4gOjZgC3wYLVPtZouLLchThjUiYiBkD3SWaB38Yo1oq
6m9sVWmxj370YDNni)Mq92tRAiRjrA(GuRIwFyUMWCCyLwdlRdZNHB8mJf3pHQMGi3XiO7KaYMWpT5on
(Z(Etx3y(YIp1MndQLzIwnXxZzoZIXstbPa6V0zz)ukn3D8Vl5gVrE(c1r82BlPMSp3RbVnXrEDIMqBY
NUs1nYw5tQ(MXWTaMAbrRNl1psu0Y8TeWsPPx4dvNi5mLyH7o5C9ez3z59vNDlT1bV5PIy4G(Vil(QUR
uL9t)dPMOHEja03BXzF6FmSQxdu92(Uto3sbNQjf6pdR9JgLcbvpbjtCWNP7lsZaAztpXQ5)1wJaspeA
Apn98AlvMXFvQRHwB9MVtxeTM(cLbdXtI17uOk3xikv0jHxrgKINlTmi1XlPPmNAHdQrw2pQfzCHgmP)
sl9OsONkf9BjS1k5VWuG6D70gswhk33eHAy7VvW5ev1vDZikVZ3ZswoAQwRj3sDDYN6uVYK6sAU(o5NK
KBAOsz9A(2RNyc2yJtRv(hEJgd91JRnU)knPQMI(HtNzAMCT1KBftqu83OQLUlKY9pB93RSBJza2T7uR
C4AT8PO)NeE18Pt1b9fufX4ovGl7Nun80vNmzDz(6oFX2jADnSsGbTYCPtODwbJj3ki8VmnCMu20wlUU
OO0cT3SbXowRYP5HAtsDf3OsQNPDCmz1UO5Jf7eueyTM)5nklybkA0uwwDQwhlpt70X4FvvjXsUHNLP7
0g8eZGNQAWJgUWk)w91(1PnJNWe5Zpzq7ybzB(YLxiS2wjK9O0Z3GVH(mXYsciin2lnT3uMLAxMiTxij
p1ltRRReBvBan1svnhO)dxMuTQFOvfvo)VNuNjDI5NvwtLK1ZUBQldJvjfUPsa)LPf1Lz2vf1n1zGsL1
P(1ptQZblFwAEn4VCPfD)qL69DkRQJPUrYDPxPlFfyQ0Qershiqoz1AjfPTQffzj(BM4ewnWPy)xk1Gc
sv20uKI9Ni3ccO8g)SYtRQWMQm1L6zWmPUJ0arXaZAs9cQKS6e)9KYvktMnBWOUQg)QNNlX7JBPsU4fU
S48H0pTjhxkRzHlouOZCjPuskw)zvXb4jRKpIlqrJ2MFyzRIRLNTLcDZ8dv39vr(Nx6k8)CM0eKFnZ0l
PIUPXVPkBQtlJ)CEyDstI3fSVOfj7j3LwCKM2ilJZF2IczsLdY00YmTqF)8BCjrjjuEn1vG(QDO)ELLs
FAQvwrvDC8EgUOcgv1EdrPeuA9k9qnBRa7irMM5avu1dSUQAkkBWyZCyAspjz5r5pKwsrX10cWjrRI72
IzYG4EWZNLvzzr1sM3PrgiLBIAjnU(vbEfBMYYKu6iKMgLcz0NRPjejjnetOq2QGrKUgGTOwQknLe)Fm
PMC3SjX7kXgDX5tUsCpRJRfCMe3MM4S8cWMQIA)vfj5jPHDsoyKkYO1j11vXzNg3F5XbaV)gxwAD8UZw
uynk2yWAZOa21fs4FpVKi1VZOA1LiQReF0bEfEdkjuXk9GDzqcl)EZS5tgOmVkjUQ(DtUlHdviqiAstb
T7YtdX3C1Z8bZQJRk2w55iwrLSv8gqA72Z92GyrcgLnluzr8UZmX9unV2L6)9SKq0eXONURzPqOPzLYO
9DEbIQk7EmfHGLq8LvQNEHEP0(pCLKKg1WtOQiLwsr(Wipz0kMjucQcLQf(hgljzjG(2D5EscbvHvnbw
Tc71WCIzbhm1u2VanLmrIOrZHMSw8fIKmgug5uuhXMiJKX5ueMtnKDs(ke)ersDEHdVPEzACLYJmk3ZI
XbgR4DbRVcjsfeevnLCJKX4NLvbEwCoPAiNUCzwGAnuAtfYdKjPrQziZIe4AiAHgA5KNvaNxX5Jlzsrf
d9kKkd7oH8ylLNxGQa0ikf1KLLcnW8ZYHUlTSmmajNuDqqdfHAKclgz1HCs4eyKYym2sYAKYlznmYUpb
7dP7)I4qzM3cYrIKlPGBPAFjo2iHnU4HqrVyJgmcsDnrIssjlvDGLr2ImxtPN(sk(cYjjvrfwbPQy5dp
lzkHSnITfetIlm9bQB4ciIeM5QjZ5OZCDc0jIIiX53wPsEl4exvuaNKmnBgMLi2q0c1mlbsWsXFSImtr
sEKSnbYcbFriJQeARHr3LA)tJkggLsYteuxINsS(IkJQLnb3lPG40irRJRpl(jHdvZtY1x8JGlLOxG1I
yvhc9PScfbskh4j1ezvrFqDCsOIZkH)sJKLUYsCAOoKOljGQILdw2kP8mmljMxktuLJFxmssYyXdoMCk
tekOK9MIkwkvvk8WKupSo3KqcL8SsKWrSwX6K6Cj0fq2NmmDsoK0I2PHU6A0nAJ6OnO0oFsAwKt98xEE
wsvKQ0CUXLhkznjeXoNb90ugi5OydZS3sgdgZVPkPGLVKsRrPMzgYxstbDTurJd7vXQHLSK2uWYg95ZL
DuvAOlg6SQI0eii0tP3m5Qdvrlr3cv7qZer4KLfSUYRr1cAtoyszOfjjYDAjZXjo9iIMiBGMVPSewKYM
fXHL8MUGwidTtiD3JcauAcUt5t6Aj5nG(Sgz1u7oSIQ6eXyf1DAryNZW1YDHeullpno)qYO8qZmvmdLo
uCPgAaQWchnR16dRJdfHUZL0LHSmPXRs4pxsZvLOHIIQZdLAwKeAL1HihIZyokakXkSgCqdT3Kk0y7yQ
vkZZ1uwH4iQvAScEwSJeZglRibHCvkWK16N7Br34LSkeNuso1WoZsTNpMnRKC6qk6I0qPbnLWsrQMdUw
suuOnmwDgxfd4WU5vhcycOcwAxKWDvjpUbvf2es(h8xZr6lngel71fDhRzDBclXS0IFF(SiQGw6kHvpJ
IpP)MIkKAqUztyp1Ke4PK0irXsjzzORDritM1xLxzxxNHJqqYzpRDO04wbviR6FMZmedPiMqrSvzcfXw
dUf1SoanSolmPjW(IXvdlkxQDjWDSCpPtWke6ugzLF)lb7tMXOOUnX4accjBcZmP5MrCevsHySjfSDyh
DQQQzWSMmOUfokllw3Llu3xHpWMymaJqj8jy9IIG7IgcJv7u0eAEupoDOeDSnsPIzOyuLSpAN03dnlf2
ffyK0iEo01pnTCwxYmvDctqNu1KhclZokLKU1i4GkWG(s6TKDjPCnOQWF1LrQITVKPSI5Yd9rLO32twv
KY1sKFKTYy488eQ8tvXBsGdIEPSNcCwiotRKtptnKflrPmu6xWhUsp(ppNuWE)uPkRatCXq(9MSkw1Ju
FfyuH9rLav2JfZZOmvNissyiaPoci0fvrdoCbPXowQKsu)8v7T8alvfxiuDUJhyMKWpuvAkLIj1UWbUi
MMu5ug6Ctzey8kwh0DtLyLbMUGozvL(4wcJId8OUbPknDpvD1WmvS4kZqaarmWiHzLXkRGuqLNC2zLH0
E1XE1LKgm6Azz8my0Fx1XsZfLKJRDq3ympslLvrnIkrruHIqSeDK(LsLOfGOswhwzvfovaD35DYKM9W9
K(Mcfwl8jd4hpha23Mgq0tBPsB6lQAJSitIjjMNLKjrLuYSzjkc3IcrvPzOEcwsQ0XBwmCvzGjr4kjOn
dyvrxZgX1fAfvde6pJg)ns13bF7MAA8wZZBvf7HtgqcoHfqkTbru0cl42muorQDIFHb4OJMe6NUpPXo(
Zr0CT5IWPWl0ckETws)v6b)fYBvwgd5eoehR0ml4qwgknZMvmXjmmkchORYu1rIM0cPkB)TPj07GOXOz
N1hGZRiqWBX(mJkkPeYMinz)HIEgA3IY4H72WI)fRXq3bffSyaXQpNLLKZU3elfwctzDO)sxYCQgkNmL
lGe9VOmEjlDnNNvHMKLNtFvolmUOm4J4Cuujg6Pblv2sGiuzYLWjdvzimYMJuInVux(yIDe3OsLB(BMg
mqTimEAvKZYLnQgD7RdmAbklrQ1agcsFiiOO28lBlqfQ0djNnkBuTkSPcPmtNp0qrkSv5Sq2HMQmMsrI
R4sJen4jZZqROezXsKWn0MxsxcDIU8jron6vMoJtjNi9Xs(ZfpBVg2pIuAcp7ptwhnaOVOo2M4aGisQS
RKz9QrWpnzc7yqRNKMyPz50VolJr90MUDrY63ps6QGHNYciVBvOGEXiQjosVmmN(cIqTygjzpg5HZcrQ
ud(6QlqAigvsricaDMASh4Q)3D1PrTvw0BjCEucz9xgRiv6Lnh9MibWN5xvfBPIYkva1e2c5m0qTlE8Y
8bOPrEsWv8SaudNO3q6mjaTCc1hj1DWk8u9kYCuQb3BdcRyfqLG)BcNtFkBiwUx8KsdpYMMWdTsfQize
T6ldN9Akpp1Y8kg(tpLNMabdP6N1tFGYPStrhBuPuFyUX9n4wj)EtS)IzpHvy3uxXsgcPlS4jqdQbKtI
e1ZCQVjmgQPTCLy1Z1PijgxmbhRttdkOiZqQKFGH1jtYRvhIBwtFnhlMVPIn8i)xAiQ0emuEvwKlrCH8
YqviziRTvikckictibLEh4bCkYi0wET)jltscPflZqjzSmX8qE8eMiS0vevvHtzwIdg1qi6z4i8uAIy7
suuqt9ra7hxDvnRgscXW2qRCZsmHGWAVPfCR1WJdxCGHzBwLlHv5i(QXIq4gwkNHM1nu)ks7Wb(Q1B4V
QqALjkpN1IwGOz8CKK2ACXyS5Hqq5HswtRcL2KgRnWXNWq4iALMZtDCxBh3VdeLgtHdd1oXcSbKk3tzv
Rf(AZfMIA2S6WrRm7XGvZd0PkN11PNzAAKISURu2vR(iPAcdLNBT9ChSll0ZthZNpWpBKqojwoizSycr
xx9PRJOfXsuttNzHsAQ5CkJefByPlbSruBuwHrrWIsv(zronMcfDzi1nXgG1dOgvJugE6)1jowbqz8aE
ft3qFvcvHHIwLDKdcn7xgopt9aQHLQkwdopfHACZy5uAvmmzvbDFSdzfQOIc(qxtlcjluBvFTps1WmvR
Qxtcm78ZnpKakVG7gXbOkYS5XXMfh7m)k)00NPddvZdriPUmZnJQEjVcBKzma(DPgegvxApejs0Nra7O
vIMglnL5vRGCxpqopplEsW9XECzmOIubttC)J9uddnAUN5bgfkaLrHDPy179)lZzIAPAuEEyAM2yUNKi
jJn7WDCEEaFbQXkiqaujsiTe2pCrsW52vhcouwqngBwx3g4NZOhFzr4Prh2osK6cg3wFIa58Y6geARHi
JYWlvmUptmOpjiSLYyYGMWbVzpIB6DQRa5jegrfNSq1ISWXi1WZjZKyH6)ly88KsCUcBx6T56JR6o7XN
3T(mp8Vq5Lh1E4Jx1Tzt7H)Tw7nAWEezYDF7VEaVNpJ0ThP)H7V38The((JvpwW9hR2f8c3vun7DxRe3
fOB1YC2(8G)b3VeNvSiNT0Dlwyx4po5BiX8fnCtHO)8LxAduE776pPb5Mp7v)92d)bUNswM73B6axmC5
T5d3653tms(WUTBhx)WtuapYxYVxRif86Jp8txD9XpFCv)fx)sZEA3MTJx8mXgAtC9oYiZw7vnCzqgYW
Xo1n0dYqhCAQXzbeaz4mtzIYqlHUhLH6LaLHo4mG(cbkdDbug6AdfuyoR3cLHgLIOm0)KCXCQbdEprzO
dE95CVKtUEpugQ3eOm0fqzOoP9rzOlyRfOkst9vqzOl48zJ0dZqtw)xeMHCpvYv3EKRomFi(bmdDbygY
HIT)(WmKdWt2Vkmd5A53kFdygIEyWCsDuvsSTThod5pNhNus8UG)3dNHoVlCg4EMbpbWmKthYepmd5nH
EeWmKlQ)saZqxlHzOR9UHzO7(aZqSQWqkbWm0KeEygQ8cGzOnwpmdn2YdZqYHSrDpmd5yrjZraoKaygI
9GNp)ldZqWRjoicUfmdbpHNkoHzOEjGzOZcf7yWgaZq9UaMHkv5jxFVHzOTtYzKgGYq9spkdDysE539c
LHkhTpkd52lpoa01kqziV7Sff6K9rziglmb)QOmKRBzuSsp47hmdjb87maZq9MaMHEQwecRzD0zx5Hzi
NFDCvX(Y)4XClbZqvReHsgEE7U2zWaKGm01oVPPiidzDv2cvbjfk7YeFlaYWmaICx7Cugcue6Azfg2La
LHCO0un6(ayg682fE2pB2JSdy2ZMvOcZyfEZkgLqYZ1UamdDTbyg6cWm0n)eZ8Om0nVqyGwDJGHoW99J
68XXWppRo5ziVzwuuFH5Ui04I1Vt8fARcH9dHIOlaVqxBaEHU5WlKi8ZyiIVWiua)A4l0VVMfjHLIa4f
6AdWleREscK0EujAxgoLccWqNpwYTayOUeaGH6aaadnz3TbyORLamuNeq0TEjaVIRLVseU2agdDMfkpr
KyhBeJHCOLbHkRkY3cdebiWdbzOl0DOZBGY(E8T1WrIyjaJH6DrJ4gx7bzOlaYqBwjSSTVnidRyWoFxS
MmZdXqx7C0modZwaIHKv5w1dXqxaIHU2zpDC05SRLNTGRD(zU81XxOlGVqx7n6vmGpu0dVRn0yUnsF7(
E5WnrxO(ZaHp2p7HxOTMES)AQmp8fDqrMeeP3cFH2A5HsNoaG9ktu6p)kDDdNUnbWi0uWOjIMtcVqD(a
NYCzHClCIk8yw4s5z29HxOEtG8m9sGVqxaFHoZ(dthWl01s4fAsvp8c1lNbesp67CEtsaNiEGqU25ix7
g4V0FMuKSbl5eKFcW9HKfwYrSmwtniHxOoDC4NU2zaEBb0f6AxaDHMMOIefOl0eVE8M5N0DbVqt4Ta8c
551QSueFH(d(x54zNYN)uACEj6SowIb8yaH9XxOskGfk9safy9YiaddNijbyOYtEag6A5Xrqgf52JiuQ
KpfBE0NUwcPrS4SkXWbeVaad1FhNKg2O3eGHU2aadTTFaGHrylsi4ZHIDpayOEjEiGoV9CsKuyO(dBhB
fyLtCq7AN)UeeWWAcGxOr(MG9w44Kj6cDTZWbkaxOEvblBdyl0KYjHhfJh)W22i(6)fFMdeBH2wUKWuh
pOcx7CORhGwiouDJMPSSzISq38dnhOD10hjm8cXviy0AipcVBh3gxH6S3hGIMG1JCo9saSqtDKZSZeyH
KcqjugFGfE4kIBg6)OefDsKf6A5j)eOkwlGSq)gKwbeqG2En8saeH9wefJ7JSqBv94dxVlGoPExp0c9S
skRh7UrwOZBIshJWZ7XmmPjShyHglrRaaulBZfq31mGfcm77AdOwMckW9aXGU2BJSqLpWJWsNnEGfEjU
djVb(lDbKfAuSc1qUpYcDTbKf6cW5JKmejGrKYyJvZq0fa2MEfGGORnaSqBOHhFhbwOExaSq3sal0OL)
DncBuK4jc6s8u9CGOqGdCf6GLjBNZJRqiqBIszw4ya5JXhu5c4kKuf(JaMC2Dd1dq4VPd42al0yqpWcD
TZqhhqNR9ZEGf6AxayHgjD8q2aYongXJStxlXrNPuIyD8RbSq9(r4Bt0AYLc1LVe0cXZ1sNpWHNT79yl
uVeyl01EdSfgFMVePDU5aOlcTWzpi5i2cJO2eWYKdSkOOrSwGTqppXhInaxO(ZLmubGwOXMHxpx8CXDE
BF8ZazH2s6rwiwDEUFazHU29rwi1iiO9EiluNZmKfMX81etaglFBSfYLp0OqqHgafiqxOsjafqsuQgVf
6c1Phqx4mSha0fsflws84eXoUmWN(rc4fA79k6Hc4f6AdWl0Ddmfgrh4m4fs4h6ANbIcIUq9sp6cv(WJ
2g7NdViyeCHU2aIaDT3BWfAIep4cDTZaxiG9HT8HAgj2cDTlGTqpLy85YywYc2UlbuizpKApGTqadqVA
ih13fXw4mSbsS9P)oaxiPpzAp4cnA5rfdglosGBaEWawea4cDqvfcbvqeN7rJKF(8iPj6cDTZrxycq6N
TzBYJsO64jDwNY7El0fAc4Lqxib6iKRmfttiAza8IeEHC9RclAiXyzDOtZGfykbniqxiz0ORpKeFn0f6
fkuds0fQdaOlKuLvwgqSgHxOExaqk3CKqMfsrmdpwaDH2s5HENRLOleSktwVh6cDTeDHKt97QzyadGl0
ezEWfAB1uMlhy8t5PI4ElK0RHNSmbwihaKoayHCSb)B2FbHXOla(wDwrCTbWcsQcMc4kKuf6NigebWcD
qK7fkap)g9DSSOeaTqiPsPYjdNCarwOdc1yzj88aM9k8dOfsYgmWILB5HwORDo08MbOqasqSVQIEv3cB
HypqSfcWjs2f1dwrd3zVTwaQRgd4HejxayUNglscOkfxIAZa4c1BgHAkWmQrQWl(eaxORLiA0bfhwuaW
vkyrM0BbeySLOgYJVqhC1cP5J9gWcl84leYXzWbfmKhFHCRdF(qtwaDHU2za(Eg6cbeZDGlz0Fp8cjnB
cBsqG9WxOXWfHN8vnFUpeGH2wVHpc14BDq8vei(Amm71ta4l01s8fss2qrywKnzfa3cFHU2WBDceMC)6
Fdo0lJqnCF8fQKmCYxnSZ44BCcHxOsC86arPziRAsmydSyTdgJKebmZ8FPqCb8d6cWl01ohPGZq3ucWx
OTKb1pa4HxTKr7O9Wxi4Z4JBHN8EeFHzZkKbViCoVXztqEIKuHNHlF180lb8c5MVKSxOgqGKqBaZGxip
MlaVqJub4fIxKusuYEPe9ybqdsWf6AJGlmj(ADm711mnKgWizWoftk(oxr0fQ7yGUq87ydb0fABZfqxy
w4JVdrxOx2bRo(M1Q)l86XPKVHhVmbsixEMa2n)0D5S8VTWoyJcMoE2raDHKtJ5q5MY)EPAlLhCH6nRy
q)zGleag0gzriAveCHZ(CMG3ECsu87aBHCx51J49KhdLhXq0IGV316DXNpiBzdVyTZEN65BApjwwqfKg
vw3cDHoZNmVOisx6PwYfMOlKJDMxvWvjNPK5zAKHpMbKQ1rQwhPkMpGxOTjDS7b8vyW1sOaARuwwmFvo
J1IVhgKQvboGsrGWqqwwYAao4FvegAuTGUGlbXWzFVqM9cC)1XyOdwSGRIORlcYq(9srhAaKH87rGFRC
tqgQci8(ZY9FOrkSNU53Re8OjTrY0MnZEP5dVt0vSCc(IAB6cMtOjevLOmec6Yy1PrlLK4izuTgQZ4xQ
nvqhq1PXEgLweKH9)XjR2DA)b9FXWr2g9pbmlHYS)v9dp54x0p(DRw9a77k4W2UT9p4g)HYr(xpF1WP6
DF2QUlV(LhEP9jo)31VSP6FeGU(yPIk5xfjsP(F0hBEMEHwICLErPAdC9lFvF3N7Fx)5dNSQ)6x(KHng
w1U(LpE8YRos)tfW2nEGV9YRF5)Q9z)9JY1alC)(fJN(J2FDMEW6r96t2oTcx2TA771VAZ2xgz97x5Pd
BTVaN)9UpzK6HRUfHKzG5EBs(E8nZDR9T1u)Af3BK4XYV932JogtSabF)nbVhN)cBPafMZi(n0ZE47(L
3(th90d5EyP5Rl8DSpm8bEdM)RYa3Gs6gyy92XDNCU(908j9DBp)lDR0VR2ETdiXJ1V)8NQ)Lr4Xt99x
QFBj1pd18Ja68H(7x0D5pkn1L9(LMMPXXFxPU(yVLXXBhV(4pQFNRvAYpLWxF8xg0p)WpA3PNAdw)OEE
I(riD2gtxQSIIhiZw)JC0d(F(4j)yrzvzPS4xS9hLOc2k(UUnN)p(UbHMB67oFCAJW2dBKf1(mAE9X70
V3LFX)vWv)Yz2FZLqsf9Gn7(Wf9IX7PGYzPE11)1pmUwz9pS7Sn(nG9PKCQBqKN)PADfif)B8WpkPrbv
YtmQ8RB8FDz7wpSzR(ry91DR720zFS(h(O8)VvLgQ74PdBoB3Go8Rg3D9l)PNj0T)p2o19JkkdRQE)V3
Tl(peL4XrfZ6X5BIHt)X6Az5F6bpr11gL23H7Mw7g5E1Wfk)87qM)(F3eCQvJpmXB)1d(p(Th(QF(bx)
)6zV6VFBwGZsS71FeR(Hx0nTfrfS)sv9nrc7TXy9cOU9GLrt9sy2DFyaZ)V2)3p

**Comment by mbattersby** [comment]
You will need to set the priority of the Sky Golem to something other than 0 (disabled) before LiteMount will ever activate it.

Happy adventuring, X.

**Comment by malikoth** [comment]
sigh.  I tried to check all the obvious things...  I whittled the script down and down and down until I was just left with `Mount Sky Golem` and it still wasn't working, and I thought I had covered all the bases.  Go figure.

Thanks for the classy response, and the quickness of the reply.

BTW, LiteMount is so awesome.  Bless you for working on it.  <3

**Comment by malikoth** [comment]
I wonder if you could make the addon, or the error text more helpful in cases like this?  If I'm trying to mount a given mount specifically (by name, or by id) and its priority is 0, I probably still want to mount it.  Maybe the logic could be to mount it despite its priority.  I'd understand if you don't want to do that.  But maybe you could at least print a warning to chat frame saying something like, "Tried to explicitly use a disabled mount".  I know that is its own can of worms what with translation and all.  But it could be nice to have a little more help from the addon in the game for obvious problems like mine.

**Comment by mbattersby** [comment]
I agree there could be better error handling, though exactly what is an error is hard to pin down. People (surprisingly to me) tend to really get angry when LiteMount prints things into their chat window. So if people are relying on the priority behaviour and I suddenly start warning about it, I'm going to have to deal with angry people which never makes me happy.

In general priority 0 is a big problem. Some people really want it, but a lot of people don't understand that it means "I never want to see this mount ever" (I guess I expected that the fact it says "disable" would give this away, but I was wrong.)

I would really like to understand how I have gotten this wrong. What is it you were trying to do when you set some mounts to priority 0?

**Comment by malikoth** [comment]
> Some people really want it, but a lot of people don't understand that it means "I never want to see this mount ever"
I don't like the appearance of the Grand Expedition Yak, or the Sandstone Drake, or the Sky Golem.  I never want to see them ... in random rotation for normal "commuting" needs.  I want to see the visually impressive mounts and the ones that require lots of time or lots of effort to earn, to show them off, or at least to evoke fond memories when traveling.  But I would still like access to them via other mechanisms than the "Random mount" functionality of LiteMount.

For what it's worth, I think this only ended up being a problem for me because I had set the priority to 0 previously, as I don't like the appearance of my Sky Golem.  (And my main is not an herbalist, so I'm only getting around to playing around with stuff kind of late into the game)  So now that I understand what priority 0 really means, I can achieve the same thing I originally wanted by simply unchecking the boxes for "FLY" or "RUN" for the mounts I don't want to appear in random rotation, but keep their priority at 1.  But that begs the question ... wouldn't unchecking FLY or RUN mean, "I never want to see this mount ever when I need something that can FLY or RUN"?  I think the interplay between the checkboxes and the priority is a bit confusing.

It does say "0 - Disable", but only when you mouse over the priority.  I never really paid much attention to that tooltip, it's a numerical priority system, it seemed self-explanatory.  (ha!)  To me 0 priority simply meant, as I kind of explained above, that it wouldn't have any weight in _random selection_.

Again, great job with this addon.  I don't want to be critical at all, this ticket was user-error, pure and simple, and I really appreciate your time and effort.  <3  I don't really know if there's anything else to add to this discussion; feel free to close it, unless you have any other questions to help you as you work on the mount group tabs feature I've seen mentioned elsewhere.

**Comment by mbattersby** [comment]
Final pdate on this.

With the beta releases and the coming release with the Rules and Groups functions, I have implemented your proposal and the Mount action ignores priority as well as ignoring what is the best mount.

Thank you so much for taking the time to explain your thinking, it has helped me enormously and I appreciate it incredibly.
