### ISSUE TITLE
Limit filters with '=' aren't working

### ISSUE THREAD

**Issue by zealvurte** [xod-wow/LiteMount#47]
If you use `Limit` with a filter that has an `=` prefix, it will result in no mounts, as the prefix is not being removed when searching for matches.

MountList.lua:225:
`mounts = self:FilterSearch(f)` should be `mounts = self:FilterSearch(f:sub(2))`

**Comment by mbattersby** [comment]
Good catch, thanks.

**Comment by mbattersby** [comment]
I expect I'll need to put out some new versions for fixups tomorrow after flying unlocks, so I won't release one now. This will be fixed in the next release, however. Thanks.
