### ISSUE TITLE
Support for limit "=" prefix in rules

### ISSUE THREAD

**Issue by zealvurte** [xod-wow/LiteMount#48]
I noticed that the arguments created by the "Limit Mounts" option in rules have no prefix, so are being handled as an AND operation, rather than a replacement set of mounts.

I'm not sure of the use cases for how it currently is, but I needed and expected to get arguments prefixed with `=`, and thus a new set of mounts; therefore, I'm requesting support for an additional option that does this instead.

**Comment by mbattersby** [comment]
It's been a while since I looked a this limit stuff, but it sounds like a bug.

**Comment by mbattersby** [comment]
Yep, not working right. Next release Limit will behave as expected.

**Comment by mbattersby** [comment]
Expect to do a new release once flying is available and I fix whatever bugs it shows up. Should be within the next couple of days. Thanks for the bug report.
