### ISSUE TITLE
After 9.1.2 update, custom flags are not shown.

### ISSUE THREAD

**Issue by zzipsa22** [xod-wow/LiteMount#51]
I added spec specific named flags, but after 9.1.2 update it's not shown at the list menu.
Flags are remain in SavedVariables/Litemount.lua but just aren't shown.

9.1.1 is OK.

Any advices...?

![스크린샷 2021-07-07 15 09 13_cr](https://user-images.githubusercontent.com/67985615/124709071-092b6900-df36-11eb-8b67-ddd1840199f3.png)

**Comment by zzipsa22** [comment]
![스크린샷 2021-07-07 15 16 31_cr](https://user-images.githubusercontent.com/67985615/124709408-67f0e280-df36-11eb-98e8-603080bfdb7c.png)

**Comment by mbattersby** [comment]
Custom flag (속성) interface is changed to "Group" (그룹) , manage via Group (그룹) tab.

![image](https://user-images.githubusercontent.com/1300207/124709376-c02be280-df3e-11eb-87c5-9c1c86b474ed.png)

Stored the same way, different UI. All existing flag should still exist.

**Comment by mbattersby** [comment]
p.s. Please help if you can: https://www.curseforge.com/wow/addons/litemount/localization/languages/96/phrases 💚

**Comment by zzipsa22** [comment]
Ahh, There it is. :D  Now I see. thank you !
and also there was miss translation. I'll change that. (파티 means party)

**Comment by mbattersby** [comment]
You're welcome. Any translation fix would be very good! I have only google translate, not good at all.

**Comment by zzipsa22** [comment]
I added missing phrases but I can't find 'Groups' in Localization.
As you commented, 'Groups' are '그룹' but it shown to me '파티' (means party) in wow client.

![스크린샷 2021-07-07 15 51 33_cr](https://user-images.githubusercontent.com/67985615/124713275-4f36fb80-df3b-11eb-9243-378ff4f85afa.png)

**Comment by mbattersby** [comment]
Regarding:

탈것을 소환할 규칙을 설정하세요. 각 규칙마다 최대 3개의 조건과 1개의 행동을 설정할 수 있습니다. 규칙들은 우선순위에 따라 순서대로 실행되며, 조건들을 모두 만족시키는 가장 상위 규칙이 실행됩니다.

I think there is a small mistake. For only mount actions stop after match. Limit actions continue apply limit and continue to next rule.

Group is translation I took from Blizzard variables. Please wait I will add into the translations for you.

**Comment by mbattersby** [comment]
I have added LM_GROUP and LM_GROUPS. I think in 한국어 these will be the same.

**Comment by zzipsa22** [comment]
ah I see. you are right. it was incorrect. :D

**Comment by mbattersby** [comment]
Thank you very much! 감사합니다

**Comment by zzipsa22** [comment]
You're welcome! I'm the one thanking YOU! :D
