### ISSUE TITLE
Darkmoon Island not supported

### ISSUE THREAD

**Issue by jukefr** [xod-wow/LiteMount#53]
So apparently darkmoon island has a special id of 5861 and its parent zone is azeroth from what i gather

However, it's not available in the map dropdown for the rules, which would be fine, but when I input `map:5851` of type `advanced` it automatically casts it to a `map` input of blank value

I can't tell if it won't work because of the automatic conversion that can't find the id or if the zone itself can't be supported.

**Comment by mbattersby** [comment]
I don't know where you got 5851 from, but that's not the map for Darkmoon Island which is 407.

I tried map:407 in Advanced and it worked fine.

You can find locations with

/litemount location

or

/litemount maps Darkmoon Island

Happy adventuring, X.

**Comment by mbattersby** [comment]
Also I have forced Darkmoon Island to appear in the map list, overriding Blizzard's flags as of LiteMount 9.1.8.
