### ISSUE TITLE
Error when summoning mount on character without covenant

### ISSUE THREAD

**Issue by philipboss** [xod-wow/LiteMount#58]
What happens?
Error when attempting to summon mount on a character with no covenant selected

What did you expect to happen instead?
To summon a mount based on my action list

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
Unknown

Please do not modify anything below this line.

--- General ---

date: Sat Jul 10 23:17:44 2021
version: 9.1.9
locale: enUS
current profile: Default

--- Player ---

name: Waverley-Moonrunner
class: PALADIN
level: 51
race: Human
faction: Alliance
spec: 3 70 Retribution

--- Location ---

map: Kun-Lai Summit (379)
mapPath: Kun-Lai Summit (379) -> Pandaria (424) -> Azeroth (947) -> Cosmic (946)
instance: Pandaria (870)
zoneText: Kun-Lai Summit
subZoneText: Temple of the White Tiger
IsFlyableArea(): true

--- Debugging Output ---

Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
PreClick handler called on LM_B1
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 6 rules for button 1
 - no rules matched
Dispatching flow control action IF [noclass:DRUID]
 - IF test is true
Dispatching rule  Limit {CLASS}
 - new filter: PALADIN
Dispatching flow control action ELSE
 - ELSE test is false
Dispatching flow control action END IF
Dispatching flow control action IF [faction:Alliance]
 - IF test is true
Dispatching rule  Limit +Alliance
 - new filter: PALADIN +Alliance
Dispatching flow control action ELSEIF [faction:Horde]
 - ELSEIF test is false
Dispatching flow control action END IF
PostClick handler called on LM_B1
 - setting action to in-combat action
PreClick handler called on LM_B1
Dispatching rule LeaveVehicle
Dispatching rule Dismount
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 6 rules for button 1
 - no rules matched
Dispatching flow control action IF [noclass:DRUID]
 - IF test is true
Dispatching rule  Limit {CLASS}
 - new filter: PALADIN
Dispatching flow control action ELSE
 - ELSE test is false
Dispatching flow control action END IF
Dispatching flow control action IF [faction:Alliance]
 - IF test is true
Dispatching rule  Limit +Alliance
 - new filter: PALADIN +Alliance
Dispatching flow control action ELSEIF [faction:Horde]
 - ELSEIF test is false
Dispatching flow control action END IF
PostClick handler called on LM_B1

--- Options DB ---

T33wZXnYXA(J58GpNWZ4bafUk)YHu3VqkTI9mkSNqiiaBqYEfy3Cr3T0qV7YF7BE5lRcD3GJLCy9WgXe
ocpqfQkRSYkVw1hAwhxpR(SlUUzG)VhD1QLD99n3F(pE)5pF5QB6g6UQzj)QTR7(5LnFUzrFtBF3jnxm
SQ(yAKRwE5IR(LUH1lwTS(0mQJl3TtN9t0qV)8FDttF3YnpY9tjF84TdlxS8Q7p)9BxF9F9jD3SA5IlU
)8hVy4I(UhD)5Z667UD1WM6n1N9476V9AHFoz1QLdBxUSB4Fl8Z6B7U4rX)K7haJL8tXFuBmj0uYhF3Q
V0nC)5Fy1WCIZo76fD9Z)R)6)9T9n31n8X3095fBA20XC6BA2o01pbRUhp54o)csmZ09F7RRh3S5(ZF2
QHB4z59xttZDFh2np72HflL9N3SO)6UF77Wc5FvfM)EZWI5Fx0GvLJGgtgXzFyOzXgs)8dn9FIySMnx)
NwF)5hn)ZnlVq0kEx3WMTdTDZ)oWrVOByflhEtxZT8CDCFZ6Bx0C9ntmxtPeE22((feN(Dy3BFw7Pddx
F3MRVzXxVy4FIEbBVoLX50mzZ006HTJ7w8DqQCC)ILFINJNm0D3Mvl)gegR7E8QBAB28TpPbpc0ycK4S
F6IM10B(1flNVA1W6Fy9xwCZnKv2h)1vB3in9rYYAO5ZStnE8)1qN)4oK9bfVwV999VoMEIk4Q(UUHMR
)gKeFfRYV29)DCw()yB3W2(vBx)1ZlF17b)R574Kfdn9B3(DGFoI5hATV6Y7pFZ1SK46UUnnxlMQRVzk
D)9ODc3132UEZILDB209DWy55xVI1p)WQ(lvNB39Btjj(Np4VfozA9K9yLNp0SCsE5RFE(9Dp8Uv9lBg
6U8YVdI1qO7FH8wU57Wm8RFl64VA7Y7Ufzc9VxP5EBApR5UP83(vqoz0KmB1Q)X3NC2(9SgN1SC1W3J0
zEYIptMUK(WMUU5sM2nuNwT(BWv8x9C97TaFDF3nFlPf8vpPbf9)oruA7B5I5)Z9R50CiBP)9xzNNT9Q
Vb2)by23VQV)BXJ0FVJuMFw)IRUwwHNsZ76VhoHrzsF8zCqBj77xU8YUHLn9SMZWIpjgXFGcQp03D3)Y
mq(dVs3xpLMUBhwD5I(Ux3D3AEkE4T3ZEs3LnB738aLrgE901UfE)0LRfE)0fAnI(twLu49tx0s49pyv
eHU8Gj)h6YdLVFOhtPlVVu6WmJd94bYRD8cDklRW7FWKWcD5bYkk0HPsGj82hoNLXYYdZ1i82jd)pAV6
HcEh6YKrEdV(bIjg6WuXYgTj0W5XFHQo(SMH1KD6CsQpMapy4Sr6ctg5zKj1deVi0JPDThE)dDCtJ0yF
GYdgTz)qfwg6Y0ohdV)H8E57b1NR6x120priaYZ1ILR3WPZWoJonMw2n9lUz(QH6tJi(JkYI8xE)5VMk
TA(QBwtPo7IOx8(U502YvkFv9B3sP)rDvZT2LNsYFoq5jnFP(0YCIQNSQFJ40Fyffv70QkAMN1nm0CrN
gy9PlN33TEnc8DffDYrcWRBMV6lx2WhEYR76ULyWSuMTiXutp5oHSyBU5ln3rZAsublS63Cn5nA1sorT
30Sq1qEXQJicFr3s(vuaJ8iWGpD9fn3s)3lhwrEEEY2HLxVQFENSikjUMMKHMF73yd6Jhw9jwH7LR7Bw
oNeeLfevEh9mr0gAeP8YU6VeZIInB6X66OH5Dl)shriQlXPep(Yl6OaeFzjFcqBAMZoU)pl)lX)x0Ilp
VI0RgUAlr(uhV3UOxo5OhZBYlfPFrmplrJPm9(vFMwCl56bxqr34apdB58hdl6QIu24A4t3SIDX9ms2q
RZ400snaXL0)2Zs8lKDXMLnShxYM(QEU7fz0I(O)b5j9M7y6tsdwALuuY6eetmFOJZyEKW2rJ4TB3Wsn
IaXvu46xoWSWtwDXNwZnfNZ(EB6wYADXzX0k)fn99JY465BBgMVGSloTkRc6f)47yo7KvlfDuwfi1vXQ
93F(BPbrBvNrooiH7ocQMBUTzXvl)VKvyUkrUURzGwlZUEXfFQBdtOIeAs(0DSYazKWR5z0MC)o5asuc
67rs8Rl(0aTGOLv3TBUMwxz8M9JxTON1F5J5Jh2z90o59N)UoEZmlJKfhT9IR5tAy7s5qGyfEwZT9oo)
VRfroBj01moduIB2EZNPqjB4nL80eo2ePj23qsWcMHoPPRNCDYQ1)DYpfVhLKaTEDwGAmnAI(VElT4Mr
eKBPkHKJ8cSLLI8K(cwcX7LjSdIHM)X18Erww((8pT539jsiW7FS6AufjeElfoOHDoq94KUlUU5kwUfh
7OHF2IURGPYBhUAyXn3WlHKKsIfExFZvBjVy9S(ywucVBrRqEB)NxsXeA50wycXsON9b2oFG3XFEZWWI
1Sk2B6KZRXX7szPST1u2m0s92n8snzhdgskoYJmtHCoUXAX2(uQyqsLy8akyPZSv9SdGHg2EpLzSzRgU
6AAu0)MnVjHHEAW(ntwfKujwnqvEsABr0y(5(5Bz5qCue7gA1vB)tRVMx3)c7sNfSX5jbs)d0ENEyIJi
6nl7edoXG5KFHCyq5pXE6FabusASoX3qlLKiomlLVKQKKKeNnLkH4D99D3YotMZdlZuXO8O6UyL4IX5I
)NZbjuht4zv8ZUu9SWkJfXKe40M)X)ZMnIMHJDEtrTUu8qmYpd7y8usiEnLpnB1MYw3uqdYi(gEfqIH3
OcPrgRNDR4gKOAYUU7p0JAyQszA9eXF5j0(HqCQLFzbhuvLo)T1Dd7OCeNxLUV(uUdUY)XD9M)JI8zEN
MLeLuzNeo7XRwsu9ZnBwXE7sJQcHvFmlPhxDHuAHLba94nK95M3rCYWInl0y9jvzUYcoMpfRTk3Lipgt
2jKeNFmPSSGI2kTsQYz4Xih7dxESiRicTw6IJvILxvMyJkYHUYKkpmE9XKSsseWpLvwv6aRKKwQd3vvg
LeAe8xkfOx7Ac55fSQtCyin6QkkSPViMc6jVpQOYwGjK)r9rY)RlwBKm0CvEofR)8IeJu5vvzjycIZkX
SMMNLPtajRsRuc4YizH(yAsrbwQ5jrjyfMxG5NNk0rxvIk9IDLyWKMFE8OrRtumTsuEknLcvgwO5gFKf
5cJh7VzjuV1oKuLIwPPh7PYOWEAuCIjQJllCfHoOZqwvLnxzvjXUahueMwDfKhXU4nbrryPyCvrm2FjN
p(DAkmU1iwPSgvE41P(5jbR)QyxmAnTm1ypQVf2tGMzvfLzHHpAoHiPicZP0i0dCvrXbzk2gRklmYtsu
q)8COpKvuggG1KkvYG6n5ylgZvefbp2pTzJuubv4ThO(vuLLxfgMXxroSesYOueJdtoegfLLqVG1FrFJ
lRQcZBQxdiB0Urgia7TipqwVke2oyPDggKZu1PD1syRZB2ApZlCqRippozKCfsB6XuBhKuL8mQz(rQFf
Hjc(CIjTsTNS)lWNKam2VBskg6JPfLqTJN)ep3x675y6RZFAzvwqTZz(xQmNkYOWS6smpHPeB53uIknd
Giqkxc5EvLzS7ly0KuLKgz6Trvyu5Kdsq(k)RzIATwMdx1cvXGkmMI07RGKoLYV2f4uOkrmI52GCWufi
QU(RkYk1NYItJhTMXMFsKTtYYuZuKSQSijXLLfbIc3VGKIifeIyuSoiJFNFpjpcJHLtrXbIoItnVg5oy
cl0nZ3xR18i4FtMmWcPuvQqugrsv0kTbBbyi13GQQl3)ENz0e5CENzvjbQACyEAHsvwP1cGw68lbMSqT
jk2iarwVp(QSSazrewwfiliKCMDtu5iVKoSjKuywBmZ6d3MaRnxAkCXxqcg0tAVY8sMr1bfBuQQkT2lc
0hjDe8E2lQ1ZQuexL0RWsLIVNyoHtZ8wLMJ3msbwNsorIuFhHMQJIedgMCZa)dsOAOcLtoJlc9Ti0xld
ND8pzdlPaB1SpnLQXvUOiJuK7XqylBwJmVJ0uI9u2vKPE48ETYJTmHQYTefKCgq6roipPeoY8gvucoM7
no9vHML5LjgF6SSxivABX7kmo27q3LXgf6JvwQjKFDVZxMpXJzz2Ipn1b3yzKahECkQYriPkNfiK9DA5
ELyHHtITKa5GVbNqkTDu(awsErrX49mdHXK6YGxgYnGnL8SpsYdlBk0FoEKscaAoSkMNLjrgMvNLeBsE
Uz3qz7KdhceduzQJ0UTfyJc4yXalInLaQMZ4SqF96Z5iLfYHfgpRJnQNMSil3wvu(IM)AKKK0rZjFAcu
9zvuBZJcSLh6k8CXZe2DI85grXqG8HYwlZyKy)AYLKnMQ6SsdbHdeVSL2Ypl3sySkQ0Cr4FICWa9ixAz
CEsGQMlkAhqBTilZsmGZ2WNoseCJhtBRjMOmc5lht(nItdu1y70eWwz(CJesfSSl8SAm4VIm4SKRYWRi
J8IYRmRvUntpMcg7D1MBAV06a(hPLFMNqzJ8WG5uY8flKcoJoWY5wHvLuIbqpI4ztMrBvHeATOGmv9zj
gdhgKnJvzgVOSieLrGz50rSGnPMJtMvXK6injW1uoiqPGePOgio(b2rs91TeBzRsMS5iuf1p(a0KhjRB
t5N28ZnVdeLqjcUsFcK0owvORzbYA(TPSWT8HtQ8zHq9WsX0zraPkpI97(bHEEI3DlykkbV0rX1H2BuH
5WKl8P0Yrk4Ipnjl8AV)w8AYEeBiX5wixYvUzMYsuiOQYlGkvEPpucRXzzfsrp9LAg7cDagKzE9uILST
js6dnU88Yqrbrr(HBrKZmNWSlCWNu0rOpMNxHHqgt2whZNwYPvoiKOKtXUj5SawquPXwSRuRAdEdOYVC
Scs5IRG)3ilFBwb1S5TmxLoIh5y86JS00YHNAmn0vlluAZojieaZtsjm9KUCQL5xPP)twcw1mzPolFJq
QsKy3Y8oIugbttbXndusb0o6bsb1s4Km2mFAXXgPO0US0YQmVxK3ptKsrhrJPKrTotKBNyZ(VkQQW7El
ZmLP1FyJO0yF7CxibEKr0elhFHrnlj7GvO40vOUvPWclsdjuHLghFqEkvo5ESotnVhfvwwtUsihzwcmc
L1wH5jL8tAjXKAbNjd(0X1sIDVux04ThDyPwavYZUl4iXYeL4P4KarnxMSBD9rAISK5j(YI5rP0yj3e7
9us6KWYG0tDbIgYcWC0fzb0irQ5hIsA1FSx5XEhjw9VufZg7tE2TaQ86eUkCw9huf3fWpj1rl3bUNGLP
De8yfzGh7FFEi3leYsKuk9lCMvkRLI2qiEAJZoriwdFKDvQXBy9sEEq4aYVPL(iPwJ1BkvUlMzIfh5cD
K)klUHpwhVYZ88rzy5QtuCL3doPwNeIku6F0N)rCrvQ3FSvWlfR1SLLUcfpobnOosP1A1(rMv(8gindl
VrsjYB3B1tX6tWLplsR8K1F6QuoaWgMQy3otcMuXH(ghil0uIsJhVYukWMHzbU1sO0ohMKc(asQnHi2O
jlslhZQu4eGu9SY3ZO0QqoK0gSTvBgbubtwTZf(zmpp1NvAfofgA6mdFMI5bU0S2JIkdlO8qubyH7YnZ
YCKPeXUwkFuEGL(d(k1N)qMpemRXg2sXco18osAPAlK(pkdPScXhjd(S4GKepXvUuew3W5MZSqylEtz3
z(qt9sAhNVxmys)XFY0083KygqSRtBolJWMIy8AHVj)vM00vIhZO6qJdDvFKfMqYerXBGN7u7u8y6BNt
ftuBV0Au0uXwaRPyTwyhemhUsPpvRqSV2EBPie12cTOaSi10FSux4dHeBwSeflz(ChHUDAKflvAn3ZOM
tmNfmItisFQI2KSDrVRewxi3hl3cgYLnHtkMnOa5Z8Nhg5vY0KjwgZeLlILfvwMvEPCGT6W92GUOu)rP
KKyxYbn9wUOKHI)owOg95F4pTPexAWnsEivcN3pDAWlID0LoFKH8qiYmRsz(mw8NQuUP6W3ruitml9ck
cTpZr4rv6PFhZkAIuxTdhGjQ2vwII5KunTSZOUAL)xWw1bQ6J6wgox6QiFo22Ter7(wWEsJoEux9eiXo
dCMSfHjZo8LS8WbsxM4dIxcxYSy10PP8PnphLMRdXqWNcvsWqXoXhYHHDeiehuoA5gYsQ08SrEcSA88E
ne(cXTsT6nLgHtBs0w65vupsvLxXJsyinmtwENf(IWQOKrd(YtgXvqyuuLmUVvHwr4AsAyP0r(NSu6ip
mHI4D(d8XoQ9QctZKslWI1WL2MfYRioWSw5roRceHzTmAjTei5RISit8j5AwK8HQQdJCgfoBPu)P8ufp
sABh2pLBVDWCCFv(MQdgtaLh9OSCSIp4kESnzQKNOav1vd5ToO8vzz6tkjMYjPgv5z1IWySmVOumgXQ(
YmSIBsOipMZbQOEiSy5AiZKelzqRIfwZjpqulbXeVnptvezW59ZqLl6Z)L2mY8lk7C0stnTCHSw5zrwT
cKV)Sr8AH)XOGpn8uU)w64qlJKQMIJphjo2cS9OTvOyMh7Ig5ukCqjwg6KkK5GkkXQhws1iyBzmGlpCX
YMkMDy1sHeH1KvMlLQrWNzMpCF4UOS4Dv(ZyKtwyuPLily(A7dlElhvxSVEZyZuqYYcAxKbQLxh5YnlW
P6sMpx5WgPnOy7K34mDG1dPMBtug0Tj1jltesWxfc1NfwWOrYLcy5SSy)zExzh8BvHv7d9FTngMMwkRf
2PFtCPpQD(ik5Sa452DlYc0r5xQdIlnkbR8QWvhzXA8NRctqS0ipFPEdi7okPK1TGQI00sZlF0bqvcny
)5JXe1x8tijmtPUSO0F8Jo)944SkLfkI1Bm1bm7uWclsBQVaVIi)5vt7hbZFBfNXMkbQoQVMBhkre0QJ
dPvBsuVLQvrLKUmCMsfeff0MSl2LlVZhMXBav4VLJkYTMYxJoZ5uxID(huW1rBukdW3Tpm)CMrpFxTim
oPdIKZO6vcLI7X9aF4nHiF(htn5hvQfsSxiQzxMu4ZSo2N0tP)gIKRFiqvym5QIg1vZxaF9e1MqfZpFQ
cqJLYEXsKm3eKY8dDHkQ54avXQMks08au4VOe(ofmRWypewyEnibSLfFHXMeWzL2qLm7hVDo78Hknkt1
QarThjDDmkgdcvbQIoW39vuyDzjOwe7t03zIy(UX05IVpTyBwthTfhfiAINO(J9o2o3wPVXEM1Of3xFg
KP2gdZbwk(oZBV03quYrHwTlri3FYKKUUPTxM78NZBI3LpFlUJiRpxWmZ9o5nZmK5(c9CVNl2pHD6tKQ
VjWZk9M0mzdMSqGhtbySDe(22vPGGqaWn8TwN6zxSpW3vk8KLAfcq7hi4nLHAsqnWYQlRWkgMjzEGK6C
sfXKKmsL1mKTZhNCU594qmAM96sFgbEy14lKxUKqt1Okd7M5z2Dt78liglpvEhE2T4qI3rcN80art9mQ
)CmtSJ8K1SGhZk)rKWI)Iq9AwEiCxTC09sIypQPC(J(LbD1iuXbD0ISen7Wn1NnST3aZp()yu)pFbdax
dK)30C7JKAHsQpB922B6gUQBE9zRUT(SJo9jmvAUqqZ)zNWahK(Ndx5h7MhX6WmAdPH)qupwCMrK)Y(7
4VkkIDRp7)1Lx8OSC(Qh)6NkY7KmvUjNk7Rx4rms((6jAASs00jjA3VTzO5rmK7yXFcADp50PVDgppFv
t5I5pIVfqzkZEyrMSBosK91r83VD9M2v9ByG4UEX6nRg0jk)3xGjFpatmbeRmS5Wz5jN8mHSB8cK)qV6
p0R(3PE1MP(6K6(Tl63oVB(z32XFqbbyl3wFkGQCBTHu5wZrj)sfMY8tkkL5NuqktpPyuMBsHOCRHqzB
KYtk(KBn4jluqGFdMOePjfqYC3v8ilDJdhZnPOrwMibmYkZMcotHICRHezUjfiYTgoK5(RWqMFPIc5wn
2uzPNAYauWgldqWAmZKcuJBnKg3wdGgZ0sWzSiEeygBJlT(4AaY4JRbgJn2phtiJneBKf6kxavCRHPyR
B6QuruSS4eaf3AGiUvdNf78ZqHNUcVPaigRn5DkMHBRbKHBRX9lRTOcDfUWGqjk7RieMFsbiSidturHc
p4wdDW2avbNaiyr4iiRs6UahyRBYtkyGb)jTiibUvbcS1v0GS0yua3AGaU1aNrlukGwKG6xEkvq)k0ra
6RrrDHOy7TT2GUBRLvS1npRjCGca32AKWSqbbZTT1aOTGnuotrjRkNs8lgh0QfiWYpPWEL7MI1v(jfvR
mn4t4x6LGEvRxOnb7QcJXNbNrmD9kOr16LSIuSO2AqrfCOAAjq9HFqbCQnUepxRDtrzQ8KKxS1p)UQlZ
OsfS8IGkScu0wRiU2Au4UjmGkVGgu9LvHbIvIafuBMeUuH8j3KI4tLAzy3xsTMFqX1PnYs)uPg7Y9n2A
W3u4Ab9MTQbQ6wrbFP09cS2eSv2wB4P84A7igS2seFckSjBvPSm3kuhfE1b1gfDJTarJsF4I6HykZ3zy
VXalST2WvyRbRqzTMOCGIFWwd(GcbIH3Bf23CtsrfkL4BZrAsoqdUnfSF8tkw)u2s5pfPGQyix1jua71
AG0dRyLukYj4URGTJFsryxRbWoLNZWaum11AqQtycb7CT1a6CwV0zsH7h)sf8P8tkS44NuaWzJOYgHY4
zENek43ugjfb8qyoaJnWKqwRGuZEkXehX(UbtebGyTgOWARbsWARbqWeki4aJFsHbg)KcpCvwfR6Tazy
TamwICrGAvBnqALkQI1W5k6QAb4QeA6GRvfpvmZiyOcR6sJf0fMI1P2AdGtC3f8nHXPcPsv3fqs6yvkO
Idbgs270Nuqi1AyqI7LINBRBwahNABaOSkmFHgxcvJAutxz6NtYX1apukthNBcPc48wodmEcuyhPtadz
E2awRs0gGmufZrYYmg(gfCdlduaIMe5Vc6qPwMuOoxUnfRrIGvGIBBnWch)s9teRTgansiRaJWJRnygX
9xa)JirlHxkfufTgAHmzMNxl9CH5zifYy5SbpUgW9tLIqBcaPq6VaSq5TPWraWve3McRi5jhCnIZKuLq
qLsbvKWUYnSdgjoXtoWacipvHvUL6GNiERq98quchfHSvsZDEQPBzPw2AkqIARboIu2fwjkkIARbiIKh
Qa3QWFeZJU21JOxENaFiDEcPxzw9PrWPwcsnvVsEU7oeWwHGUs9yymjygQvHmKmjckwARX3GITKvfk9e
QAn4c1wd0cjCGCqwYtccSBRbSVBRbsHmAb1BSfOiEt6T8rbWZJE0K8t6PK2wBqeQT2oKvzMIHlrGpOwd
EqT12je3A3(p3FfAqhxdWVzKag(52(IcZTwd(m8lvibbbwLrSurDwHKCRDXigvZ89YBxAH1kXUSIqkzT
NNbZsbsoSmtWaKqcbcqQyuJTQykRTg43OTgO)H7Tc(Nw7IHKExOusr(JiBeah2cfhD5l4(P1auMrkzG6
1jXKkdzab8K1wd8(WDsG7dtk9RsG7L(bLz9xTi0VGa2RNc2hiBGSxrIP9KQ9iy9P1G6tlq6dptkqFaJv
6jFbtEfqnqAbZf4Xqr4tlCDGG7zyxeOj1OL4qur3d)sfexT12v0HULfPDRagRkSUaJf6vSfNqxSkME4U
lq6HBsHPtlOLU2Yrc6aopgXKGoa0GYqLZUV1WYtB9PaVZg1Gzg8OR3kQiequxGZQJRbiE43vzciN8n7Y
pi3Ma4l13HGEhLfGXKIi22AdWT8l1BrclsNpzmTgof2oGTGbJCX)YYqU1Jw1om2snjY8lkq2rNHCSLl3
JI8YelYQE3XYqf46iRCbTo6QdwIoKamqQJeDwqQwBnUEAHScmDAHAGkoSqokgD43P4E3iM45rVm8wqvS
ue85OtUMwME55cjKVYariiyZXwjjMqRWKgiRffxokXsTjhzPdm5iRC44a3ZfpNMPQIgNJTBIvhxsKfnh
hyGIdh5LX2oMIzaL8iRTmZdAKLKO(btEm2mZ9edo8L7QfmwI5CSY8MwHjWzBM6nEY9xrDtRDdXTgKBmA
5TllngtfakmRK1Ma3Mwvb1uFlqnCaRnhdQHLzLvLKc0gRFilkbAlm36DQjy9qevccBKzqaytBnWxtRbE
erA4Y9N9uSkUvS1ySMkwuK1yluSyeyNimKaRgwrwrvJ461oogNz7OiQPT2audwO4Gdu40y9tDPOaNHFR
8H6iYYC7uK0VEJ2AGogWBi9dfgng1G5Ma4g5TzrE7Osiyqr2fX5(Z0Oe58PFDkIyqGpJSeeWyDmKB5w)
sqHxwDWkEFmYPjlLhBLnlWMryib)F8tkaEK2KRxhlbS5QqsXihYQicP)Q4LbVm1Iny7cHdkWYj0zfyeR
iLrwccqzONsrMekizy3kcgz4(OOjG7JGzBv8zNgLL6oahJSmrmyfl4TqKHzXYdxzxbimgDS9uKjIcig9
bejwGdtRDt)sVHsKIegJsWfJdkragmcNiFxvmNiGGPTgFPukxIWJkOjmIHC)sITJ2fwgk6xeYNfJWa5O
efG9fvuHZUvHUc3Ff4l2a8oZKvTI6L2Aa6fJVkH4YzATihWutMlGDXEvIjTu1dfSO8t6hvxRH0fEK633
btkLpbmx0NYInwiwddgBjGhRiCHFs)AKT5wzERU)k7O6vqjPD3oQybBlgTcArEnlZpFckyhaiGFsbUeV
kfyTi0ncbsIvqTWcm57FI7V(Tk1wBFktTQ(LfbcHzfSSWJZC8dOFYDsXXIXzwsZQOgNhPIFfHxsqXdAf
QY4fWROCqvyxuDplOiS1WJi)of3kYAq1fvq51AqLujPT)OawrEkv7U(f8yuY7Xxx663NDBTHuL26tbqv
4fJ8bjk0Va17auQWpPOmccl9L63BTYgirF9R)cCgOwMDCwaDkC3KVStJ1uNFkczBX2OZZBEN0QJB97hv
Plwc54kcaKuq3vPOcif(L6NWRMNBgoma9ZVOv9uyP4eHDo9RsUTgOUr6vIwXMIZiMckGNeHM8fLlCTar
fHfLqahxJp)62Aavzims87aOn9N9bzKYhVPrTcpNPlQuCQ6k0JmzMgKm10LDi3fG3eJwYa1p1DJn0jsH
AYX1gYzATVdFHFQmpJ(C1kqs8cmDATFgaATVbzUpk2sS1iItNzLLQal5yLVSZvOaoXsXHZGF0eo2avIS
yRGzd(OvSUL7jwS1pNLSFS6EbO0GJZjWjHFP(dJb)KaMew2LR6)oRmr93Ud(b9ZsL7tgoyDNX86V6hI0
sGzvBnWpc3KGIpUf9NPeWuQRx9hzePxWDBLvFnWRK9eOvsIvHb2f1FJwATFxwK3vzNNsc2HvSI0Y336L
9nx94RBwEfamIgpAw9zV4NpD2tFF9z)z(cFX1ooJ)5aCr)k5NNr8g9cvP38HJE)BE7JFnAhh0f1(jV9u
RrvsZTD0ZFQ1r1xa)Bv1tPUUZ0IF(vMX)GJUCZ13nyJrnsP2p7fhDYrNAnR(HOMF6YRwSSRBeFIs1MCA
0AnLxD0Sx86tF5ZFXmJd0lezF5b28FaMw(kNP3Dk)RBm)7Sy3yMi(bgwSGJVdwROA5d4aTGTjjLMzZKR
hu7QUD9(x(w)gSE6Iu7VQ7lD9xm0C5MrcpT4695b(894z59)8lFI1t9KRNElqJMqV79)SSLj38)OvF1K
cn8lvWbSmsnFxTjaWVjPJc1n(v8V(MKw8CJs61umPSePStV7DV)Lp9SzJNh3dppjtop6fhWcG3(8F(PE
rVCAYhS(WpUotqhChVZ2t9xdio7qBuT2VP1h0JyDIbHBsyYDs8lK0uSMMA00Js)kToqlsY4zsUdNcgl8
p6nh9Kx6n0vWECWMIEcwhsQ9v21RRBFgb4YBhQoP9TG5WjML9fga9EhQxTVjUMI0E6fkWlMusQifyYxH
K33FTHtq4GMvCdStZ7WeaPdtov4mVoC5zSXdQZjhX(ElxCzgttnn23b6bih5zh4Aql3BYzxVKGPLD6b3
VpJPaT5GjhFohZMi4eFq97tffcpuRp7n)TXuU6qkRxq)SGFYrHwNyfHBpB20(U1Q4NDObo(zY6H1I2p6
TEM5hWTAgkZ2Zzeo9WDPGIXH97k(LzB2eomvqfnPoHIxQhqXKb20HBy6VJku7V(Ub(xsymjAU5tlh0ke
oqJqoRPz7NZdUOLhyJqrI1b6Q4qkMnoAOwM)SDISP3v9blkCOFZ2ZviUJOjLC6nqDaJaSRTdL2tZ7akj
j6FGCavVSl)JV2Wj2LXx08UQk65ZnLAR(91V)UOECxhkE0J8A2(HCLJi6b2OWf)DGiv)TIJ(N2VHT(Dq
50w3zhexRY0kvksCMDGlAbVa7kgWzcEW6cfSoj9XVHbZMWmllBQnaCwvtQSOhM7Sj97Oh6408GcjQztK
FeUKRhq4d4NSpZJJE(qvn9aHouzwpgPdBxWu0bIt81epBFF543gVPwgAfAtWqcG32rzaOe4G(kuVyAQR
hy(KYw9UxNw1sp7K90Huarn52lZcztVaXhj2KBH6f7oLwbvsz72nBwT8OlgJn4)d(39C(N18N103)dYp
5ZYFV6(HD(lbd9VEE)I5CRpRV527FLG537p)x5FPN5)YUD)5uCf6Tu5Y58)HbVNJFGV2Gc(HC(SiV)vV
PR5ZD)s31lUOV7(x9KfRLF9JV)vpE1T3nRz4QUnRprB5OBVT)U3ZFWe3)Q7FfXNVC5InYp07R7OfD7D3
F(f9nRxteF7s9Vpbpzy7I53)Qx(mIZwUsE7JKIG(irIZFZIBwqd8)9JFZrND2)37F1tFZzpLBpG(zIcC
V5gL)sXiVDZkA9(0tFcXapdCYrZNF)5xQON(hj(qwdRXeJ2FK5mA8C)N9)kBlZ(o9x(bsFNoR)KPp1CF
b(fW(hh64)gCCXg(VFl7WfwpEK6mEh6QnnIf8D27aAN(7BDYH41b3Dm(MNAqWyENrG2MC9Y)Yzt7WS4E
Z1D3CWQn8(hnY2BhYpQ9rtX(JEhpF7m(DEZVdf8Hf3z0(wNC5X)P24h5)EiT4s(pTL7S0439i9NHE8NM
HV0mC5oeFX8hfhLwosqld6f0wGqQMf0WMX)j2z5HJlQy)X5)7nWH9oU6Gz5n8g9LR4psc2aSPBz3IjML
89h3jnx9NUUzG)tlWftSAspO)YFCc4FJ2pO3jLU97TO(1UAy5H9ok6G1WVSI)l80t7NqSgvDqN32Z)nt
ycU4G14hyXYUsX3VDP(NyGpSOF((93(7eXc(VIeR67pKDCL7OanY11RGhRA(Rj5p8Q)hE1)dV6)Hx9)W
R())Ox9)d2F8D)0zFzXnKG8ZDd8FL1iNS6qiFG(plXFaF2GKN63)ZN(tF4O386F4()pp7n)TqV99L6Zp
E2hE5jth1G)c)2UEZQBOibYhaOvdS8fpA1Qj)duEV8SvvM8p2TSrPj9kiKhLcF0ghvBI0aQOuEoudS8p
1thqEmCGdY)u8JQpIJdWyvPso5F4pqaL0HYLaFeQ6sAyCDBkHrXO6cGpZeDGufKZQ34)F1))(d

**Comment by mbattersby** [comment]
Hi, this is an bug in testing for covenants if you don't have one. I will put out a fix shortly, please look for LiteMount 9.1.10.
