### ISSUE TITLE
Litemount

### ISSUE THREAD

**Issue by Ewellenne** [xod-wow/LiteMount#61]
What happens?
(sorry my english is bad) i created the maccro " /litemount macro", i placed the other macro in my spell bar, i used it but nothing happened

What did you expect to happen instead?
i think i have to summon a mount

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
yes it's work in the previous version.  i do the script error maccro and i have this

Message: Interface\AddOns\LiteMount\ActionButton.lua:27: attempt to index field 'Rules' (a nil value)
Time: Tue Jul 27 13:57:40 2021
Count: 1
Stack: Interface\AddOns\LiteMount\ActionButton.lua:27: attempt to index field 'Rules' (a nil value)
[string "@Interface\AddOns\LiteMount\ActionButton.lua"]:27: in function `CompileRules'
[string "@Interface\AddOns\LiteMount\ActionButton.lua"]:101: in function `Create'
[string "@Interface\AddOns\LiteMount\Core.lua"]:56: in function `Initialize'
[string "@Interface\AddOns\LiteMount\Core.lua"]:96: in function `?'
[string "@Interface\AddOns\LiteMount\AutoEventFrame.lua"]:20: in function <Interface\AddOns\LiteMount\AutoEventFrame.lua:18>

Locals: self = LM_B1 {
 0 = <userdata>
 id = 1
 Create = <function> defined @Interface\AddOns\LiteMount\ActionButton.lua:87
 PreClick = <function> defined @Interface\AddOns\LiteMount\ActionButton.lua:34
 HasApplyRules = <function> defined @Interface\AddOns\LiteMount\ActionButton.lua:112
 globalEnv = <table> {
 }
 CalculateAction = <function> defined @Interface\FrameXML\SecureTemplates.lua:584
 CompileRules = <function> defined @Interface\AddOns\LiteMount\ActionButton.lua:25
 PostClick = <function> defined @Interface\AddOns\LiteMount\ActionButton.lua:69
}
actionList = "# Slow Fall, Levitate, Zen Flight, Glide, Flap
Spell [falling] 130, 1706, 125883, 131347, 164862
LeaveVehicle
Dismount
CopyTargetsMount
ApplyRules
Limit [mod:shift,nosubmerged,flyable] RUN/WALK,~FLY
Limit [mod:shift,submerged] -SWIM
SmartMount
Macro
"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "# Slow Fall, Levitate, Zen Flight, Glide, Flap
Spell [falling] 130, 1706, 125883, 131347, 164862
LeaveVehicle
Dismount
CopyTargetsMount
ApplyRules
Limit [mod:shift,nosubmerged,flyable] RUN/WALK,~FLY
Limit [mod:shift,submerged] -SWIM
SmartMount
Macro
"
(*temporary) = "attempt to index field 'Rules' (a nil value)"
LM = <table> {
 TravelForm = <table> {
 }
 Mount = <table> {
 }
 PlayerMounts = <unnamed> {
 }
 PairsByKeys = <function> defined @Interface\AddOns\LiteMount\TableUtil.lua:37
 FLAG = <table> {
 }
 MountList = <table> {
 }
 tUpdate = <function> defined @Interface\AddOns\LiteMount\TableUtil.lua:65
 Warning = <function> defined @Interface\AddOns\LiteMount\Print.lua:84
 CreateAutoEventFrame = <function> defined @Interface\AddOns\LiteMount\AutoEventFrame.lua:24
 tJoin = <function> defined @Interface\AddOns\LiteMount\TableUtil.lua:50
 UIDebug = <function> defined @Interface\AddOns\LiteMount\Print.lua:76
 tMap = <function> defined @Interface\AddOns\LiteMount\TableUtil.lua:15
 WarningAndPrint = <function> defined @Interface\AddOns\LiteMount\Print.lua:88
 UIFilter = <table> {
 }
 ActionButton = <table> {
 }
 Actions = <table> {
 }
 Print = <function> defined @Interface\AddOns\LiteMount\Print.lua:21
 SPELL = <table> {
 }
 Conditions = <table> {
 }
 Vars = <table> {
 }
 SlashCommandFunc = <function> defined @Interface\AddOns\LiteMount\SlashCommand.lua:208
 RunningWild = <table> {
 }
 Nagrand = <table> {
 }
 PrintError = <function> defined @Interface\AddOns\LiteMount\Print.lua:26
 SecureAction = <table> {
 }
 GhostWolf = <table> {
 }
 GetDebugLines = <function> defined @Interface\AddOns\LiteMount\Print.lua:30
 Spell = <table> {
 }
 MOUNT_TYPES = <table> {
 }
 Journal = <table> {
 }
 Environment = <unnamed> {
 }
 tSlice = <function> defined @Interface\AddOns\LiteMount\TableUtil.lua:29
 Options = <table> {
 }
 MOUNTFAMILY = <table> {
 }
 Localize = <table> {
 }
 TableToString = <function> defined @Interface\AddOns\LiteMount\TableUtil.lua:157
 ITEM = <table> {
 }
 tMerge = <function> defined @Interface\AddOns\LiteMount\TableUtil.lua:75
 tCopyShallow = <function> defined @Interface\AddOns\LiteMount\TableUtil.lua:23
 Debug = <function> defined @Interface\AddOns\LiteMount\Print.lua:41
 UnitAura = <function> defined @Interface\AddOns\LiteMount\SpellInfo.lua:83
 ItemSummoned = <table> {
 }
}

Please do not modify anything below this line.

--- General ---

date: Tue Jul 27 14:05:20 2021
version: 9.1.10
locale: frFR
current profile: Default

--- Player ---

name: Naysa-Vol'jin
class: PALADIN
level: 60
race: Human
faction: Alliance
spec: 2 66 Protection

--- Location ---

map: Revendreth (1525)
mapPath: Revendreth (1525) -> Ombreterre (1550) -> Cosmique (946)
instance: Ombreterre (2222)
zoneText: Revendreth
subZoneText: Tombe-Vice
IsFlyableArea(): true

--- Debugging Output ---

VersionUpgrade: 5
 - checking profile: Default
VersionUpgrade: 6

--- Options DB ---

nQ1YoY1rY1pNXg2Aq((H3rtQrWyK6rwnnb8SOGUQ7InlHQRIt1vrj6fc(lWB8QzNHxj61ZxGB4Fe)L4t
K5jYS6hgsTerF77nZiJmIteXjY7DLD1RxD5vVB5G87xV(9RV7N(2p7N(23SF7V573SR9W97E7MBEZ6d3
Tz)UvxexD5PDFyzZ2LVB76VA5Qd7xD5QJRU8Y7)0HLDl)IZgd9Rw2S5xAGjzGVC9URpS(xJi)8Fy92TR
39RzOVCz7MRU)t)skqBSxS8X7(LgyttFXTBoU(WYDN(vivm8B2U)7w2(Sc7Yn7U74YURwFhE8foxjdB7
c2CWXCnSfB)F)x)ZF(p((nlh7ti4HF7W9)LDRLNJbD7YH7)eM9f1KrCP3((TYJGMD56dVF9UJD589lxV
wgJB1LF9(dh1HSF76nB)PV9Q9NaOy3rObwziVE)Pd3I5(3cfagKJ4p5Y9QLB3D)NUtu1k0(x(U7)ppUE
bI6ILJV7WMfOIrSf(smRR2ClxM3iR4pILphwD5VB)MdR7k1L7V97oSE7PDRLfoG59pC1AaX(b4zF5MJq
LHU9xv(T2)6MPPkyPTcO9OmbVSHVe(2Dlh2SVlXxdjU(ZEZMRKbe8ygFjmGV40rzjV6()YX7)eK4vl3(
(LB2PAXh3(HLdxVEhwLsgY8Rx2Dne562Me)9F)Ht3Q(JxV5GG6V8QnhFxBnsylv)T2gqq21F3YreTS9X
YwgA21IB((M1e69wUrCv7ZONThuFYou8hFyJaFWFJ58pFhaIRUWMcq6)rrZ3IO7lSotuS17UEn2j059n
7V6DR3j2FbVef75(Dl3D8(F(GoK2E)oGfeWIv27l3DxxeWm0mzyr)dhwUPP5fS7)6d7FRSoNoG5F5YUB
oTzNSaWb5fBJPzBEHyf(H1lBVU9NFrZQ0U8F80617(nyUVC)oSuFy54(dFuME2YPF(CF5(pSE3IaR)DB
2Ti25xD40DhfxY6MzsMPbETVz91h2C9n98j1F89ydGTAlkYfIc0bHDhpDB3S(Q93cX1FC2bt3xIB(Y)N
)9th(SRx)zF9M1ho0WCX0d9iaDF1tJbGHrS(BV)NHb)Si5xChuYEOpCUsO87U)ty2AaH4CVC)P3(2dsk
HMjeg4xS7OS42wW)V)02gkCbwyRrE89)BIv42930Zg9h3Ra7)0P7)VoklVG4GTAJ4NX0IsK2xSDdCSiy
7Q)7)J)oSYY4(8DxTDp(9YPF8N(213D12Lp0CK4Nvx(hKy1J0o4YLNGm)M1FOLa)47GMzf01LF1BGZB7
2nYUP5ZpS5ob4(LyOyB4r2cjG7loS5wX9CC)wa78LE(d4FjO8iYQ10JIy9r01I4wrEiO(h38No1ceJ(z
ElrbSySV6WcW7iCqWd7)4YmoULx9ozGgRve69)8nmB1rnhk(3fBo9VS0GuXGKTB59BAolxFO390ytKH)
gKr(Mgw6XjbAvdEpIx2SD9VF9hV75RcF5Rw)2LtB))Pk78PpTW68zptT05dFUYNNn1NRI58XpTi58zpF
DXXZNB(2oxVnU829N2D8RHH8WMJB61c92yba1lS4sFn5DTlTWrylTlDLsoyWVLSDHicPBdW4T1y)YCmB
4DlERTlmNVMtP(DDgVmwmgrwPUSeb0FUlwqkm5QyPw8usPIRRa(AX4AZ2gCMC)5oK9HkOVvZsxZm1ex2
IYG9TLluc6D9M(omgJEB)Mwd0V2LI6XDDk7urLQ1OJlaSwLM(7dPySlvyHc1Ua8ryb6xgC5m3FjNX1vB
pceDT5llfhOV662mRVWjBZ2K9Szt13KRDDkeSr7CJMu9iA8DRRmF6vJom6(aC1aVlwE6jBZksFI1viaW
wY(8CaDNwSw11kwDw)udYt1UVdsgRpnme55wr1QSTVsW9f4vYLQ7Vw76CQwCP5JdJ1XzN3Lar4Mv1d3v
XHQmBJmnN)zlkTjzdnVTBsGGVA0nQmR(L1swKVRVr63lLiEiMlZXR3QBvIL(cKTflxkuC5STs0n8FoUR
e3dHF5AmrGMhazlxgJpmT)0AHshfd1BJng6YTTeP5sm34ufSPeD7XIDLAa5dXwn0cetzpDUUA0x6cC69
aGirlTaZPpdUunkY56PdA7ccia22pCjHe3qiGvmugg71T54YuxLsjRBkun01e7lEsbET0ztxVxZruBlP
8)s4o1tVRLdZ1uznZs0BkDzjHEeqHPy6ojjfKc8XK6pUQoa8qKUHsVgm5Pmjsb2WGzk0mv)aZGcKfZqH
uGHCzosULTWIOo7mZf1eA3mvZQ3mAdwfmbZKAWd(ux)edkZQjH1u9TfU5J1mvzzGZWcFhxGSczUpaLEp
Di2q067JT4zrJMmptpvlAYZqWMuNJvVBYuodKqpwOKyTauvXWDQCxNwwQAgRWihI49Ptbfa8JSreL2KQ
QHPqMsnMzOSTc(VZWojQbRwWyRmegsDKJg(Fc0KfOVRqUG0eiAl85MIOGma1t)RyxTtDDKqlOEWqqsrd
XLXqPFbjwCJW(aZ8iOUOI6asNllsTuz5YiWveIG6fcURLMlfnDnasYX6fvtsZygALMA7auJOBxaSJZb1
IJAIlunLj0rvrghhcEc2a(TWLugzEos6wKug(HqjUdyvAPcoMSe1nmkbGKr3rjRIaTGaHFumKwx4XRm9
i2h0t6JcUSl0uRsFl3asJ0Lea1b1mxdZc4(UhrsrrxoqjeYG41mZCjY0ouuMxDwvtIS18Q4h95yBOjpe
n1VslgXSLijyF(ryUzCCUMycJQxRKj74rLslnyvLeJK8prXKvTef0vWeEmHWXyZgkwSGpAjAhaenffwC
BxacleToF0hO7gEUctbNKmg6SarqUSEL8PlLumm4RKygbyNjewqONL6IJeOrgV5rzfwRgboXSYJnK0TL
nOagrR6O92qtdBk1kchDIFmY89Trsfq2bv9s7OAI1KMdvttILIsf2f7aMwzUzW4I(upOXL64u4cIQyHD
TYkKOGVAHIOd)U1eeUtAvDKsKuTHpsysi7q4JvJDXYaUMYwy6Di1(ALJrYE3lKly9sHEDFOTK6DqaUmq
sjwK5GySMyRdXslFCqWPLZMWbjuUFtxw6NV7TGcQ7BWbzY2JfpRAGoQcm4YzQd0GlCw2BTvJqo6hmiJm
erWafAHq5hfeI0NgMttWt01JqhwGeyigRdVvMCKIwTTPMuzyccLdA0AkoaHrsbeSx8XbYtBlbWv7uvJQ
bYMy5dpqwuPIAVsbjCVREHr)hwL1PtObqzMBhKwF2(rwjHOqqvFnebPphKWGtJ2eqnsP)4mdUcssxAFm
wnDJivA1ngRgowCvsvXwmrAFqfrIkc(I20fych6XGIBv5HH4jL)qjwuTkpiGuTS4eckcJSU8XiOKkNKO
w3hEnwvCd0qj2mMaQOeplfpBUeb9oTczYoXwHrH9jJOsSm4cRfCAzyz(NOHIcKRzHrqhrtfl1QzXCuJK
GOeQpZqpKiomutgJGSJ6vkPXkOsg0L2ZauyxO)RuvaGSF0(kLwKyWokehM5tP)t42t)JrPcIsXbEPynD
JDwAkZb)oplfl43rIv2)JSD91Pm1j5Ceuj9kREWQx5VA0(NCy6kHO6iVVe9nHNkPtjqKwrJvBqxisZff
5QPDeMrYuq0uAhcOLaUOiIxx1QPMNPVCJ5RahqJux)2RdO9Cbxv1DQYZVPQCaOpJWW1Z6gOFcxhJ0SP9
CsckyqiSfP76Asx8sHFsNdOaADq3sJ0qWHtTdTZOyh0oZGLjEUg9NIAdtbVHHNc5mAPr0Fy0CuYxhBks
9O1lQBkw1vJMrOyrJoKrI41zoZOv9pGVPEPd6IwaiOnpjcLscTZR5unMGYVYOUsyck9sDXYy1l6zwHSl
jVYRXN5PFjCDyIgbiP0caRcAjckqqIyu0L076k1(BN7dYFZNol5CDqjSqCGGt73mx0zu5raGe32bjbJr
TrgdNBbLd7liYBssKIMZWAqBLfJrWsvZDbiAEktI78jnSdb4SwR4SpZAWfYpQk6LMAucvfsSPnu6cY1W
iDS20lQ1w0Jtrgkt7ayHgT5SfnnmSn5Wux1Q1iHqyQbZ4nMXxSO15qjijucJdCZx0KyIO6ZQHm19yy04
o4CxNABEAzQtTLKRYA)UTHY5Bcw9mcGLTovawVV6ZQhgmRimlQHwOFefM5YKgRS6QZqUKrgbunU3Gx2p
iEjYmnv0EQfr8ebig4UZus321EP2irfXcdl865oloAfOKvcOGhJwbweiviOA6LsSyIIkZeWql5X8ajYu
vgaNZdtatewrKeLEn0yF66rvkNwVM9vmMtlSE42apR8CefvHdP08GPuZP4xuxCXKNXbdkF9nITN9Qx2p
wL3qyVqsnmIQndUHqOKixyCwBsXrYUh1RzfRKEewTCF0mNiteyptJY5bT9g0YKL0jZJ4gXjP1B1Y143H
bVuswwG8rfO1S3caklsNQ(OnnVjmiJPhkwgCO0Y2z9qPQqj04uVEarWR7g8wJAdJsNtfDaJGdrr5qLdO
rr3gLwpkMYfqCbdUg1Z2NkQd9cqxm(HhRVK4MqaKMTgvBxy2xVFqv3PmiqXoT1uOQEgikNpllSi5z0GF
dRXKMviLrQIQOLOAs1YjHgK4DrfwwnvowlJI80JnPnuUdfxoT7aUoc6Hy1vaU6bXEdp4m5uqyerwMxFZ
iILBCG8dNnuIVqB0SCqsRs6aI2E2ihZ3z8tPsFKGRucBoDFjBbLLqoOKIJAibAsXKkdrPeK9kwwA4wlx
jppof6GLqvVuuagFHIb6zFMRJxpHBacRzT6FmODo2K6m4Vmu1bZg9iBK2qgLcGwPjeZ6jhIayJwUtKQg
Wu0KJnTIEw5iRitLQr5d4Nvgb0t7fb5xuyUiwQIw9W6fLvjF61InshPXUAj2v7uxJJB6MQkXyGh24vU5
4PtihskDgcUQ72qtSkfgy)1UiLrwhcvpUFqUxBEvglXnGOTcYf4CFTKTIRFGUknn4rR5PmPojk6zYKJv
An3WbevA6MbZKwHi6QZ18zsvJRmz9SVrhlzLFh6UDuXZsoCOSCqd8qDenBT0ZXmeyMrPWx)ztUm0e4cs
MVbCuA)6jHkBS8zWnTykIx1gqmAZci3F8mTL7m)GSlsZPu5rMbV2zCwZ(2u2r4sGozzwQcwTuxts(DEv
inP)RyaK81p0unY3QUOk0pQOOu8OUywrycSu5COhel2r(ju1pBEGlU3nl5ZWp54GIeiKD6HuzqFICNjV
Y9vJ6RejN6hcsBw2a7yZlNcs32jomnRKzEYpn5lBuHl2zWFckbqxptXIgsNHVr15OD24etzI68KowJ7H
gXe1OlypP3i7uMlYrOWK2veD2xh8BTXjrMC2HS2pJ0ePTTndPXc6z(2g58P9ujp4u)FRLKUGkq6ePKr4
k5fPOBrKDmTyR1x)KCKzwgjy1U2AMZkpkDu9EgJsyHE6ynHQSyuyS8AY66EjR9JkCykJTB6SOZrMy)O9
z)4CmKKUKIMpBSkFgu4z2yISLB(DxE0xrvDX(jJMMyjWkIoBO5RQV7LMHM1GhKRqIp9fD0u20yl4D8L4
EwlzTx1HJ(K(wCEU7OvyNzAc8ZcFJVafeZp40OGh5f26uoSmOwoZoDoN9grp7f8xuITz5BwQFM0v1u2e
jTLYH32vkxnPVEt5qn1xxr7LqmflHnjZ4O0lklfe4QVgxtmQPLL21u6cgwTaTQFgfLilwiFFeUPq5E2y
ys7guT7)8TVzY(iTJpefrtN19hDXLDAszXORMnLYjeGEs7Tt9IWgNttCurwrfGuvIUTZVppLQw5Z8GxY
Yz1oNAWiGiQjrrdfXPgOVqi5CL5qJJ32SiwLvRXnpn3swPjiVkt7CS0j4LVDjALWwBw8x53jJ1ph7zrx
r2AjO3PeeDN9PkO2grSf12Q8VAILHCGuIYkZOCSBdvdzgioV3porrK1GtcP1DtBBIvVL3qhrsOcHEo3Y
R80YPvR65zigSWqBPFqE7NDFQyKzHYGw8geuvszIHLjcK3CCDkZ0uM0Yhco9KgfqltQo)YmIvBEQPuQi
KI7perRFFmJ(4LVNI5vCDKD)OZQWi77iZH(sUAsKixPVWUXR9DtqdT85oy4wkPNyPGRyEW64WYeR)Gtw
YOCkLHsdHi2z2fLG3O2uo60qhX6L15h69lE85(a2F72LBE57w2Dt)Z2Jnb96vx(n)txS6Y)MvY3yz)WI
E69Qp8E8Ry7H3RZT)b3JDh9W71XZpvEpAn45f9W52p0JNQFPN5EpAC9p6GhVSs1Shn12z1(WLTxF6r3R
9Pw9yvw(6cF62n)mB3hBM7Vz1hzsBV64hEV(jf8W52R)D(90)B1)3d

**Comment by mbattersby** [comment]
Thank you for your excellent bug report.

I think something has gone wrong with your addon install or upgrade process. It seems like it is missing some files or maybe some files are corrupted.

Can you please try to force re-install or uninstall and re-install LiteMount and see if that fixes the problem?

**Comment by mbattersby** [comment]
Closing.
