### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by psycho1666** [xod-wow/LiteMount#70]
7x LiteMount\Mount-Aufsitzen.lua:40: attempt to index field '?' (a nil value)
[string "@LiteMount\Mount-Aufsitzen.lua"]:40: in function `Get'
[string "@LiteMount\PlayerMounts.lua"]:114: in function `AddJournalMounts'
[string "@LiteMount\PlayerMounts.lua"]:77: in function `Initialize'
[string "@LiteMount\Core.lua"]:46: in function `Initialize'
[string "@LiteMount\Core.lua"]:96: in function `?'
[string "@LiteMount\AutoEventFrame.lua"]:20: in function <LiteMount\AutoEventFrame.lua:18>

Locals:
self = <table> {
 IsCastable = <function> defined @LiteMount\Mount.lua:160
 GetFlags = <function> defined @LiteMount\Mount.lua:49
 MatchesOneFilter = <function> defined @LiteMount\Mount.lua:93
 __index = <table> {
 }
 new = <function> defined @LiteMount\Mount.lua:22
 MountFilterToString = <function> defined @LiteMount\Mount.lua:67
 GetCancelAction = <function> defined @LiteMount\Mount.lua:184
 MatchesFilter = <function> defined @LiteMount\Mount.lua:117
 IsActive = <function> defined @LiteMount\Mount.lua:156
 Dump = <function> defined @LiteMount\Mount.lua:214
 MatchesFilters = <function> defined @LiteMount\Mount.lua:136
 GetGroups = <function> defined @LiteMount\Mount.lua:53
 MawUsable = <function> defined @LiteMount\Mount.lua:202
 FlagsSet = <function> defined @LiteMount\Mount.lua:149
 IsCancelable = <function> defined @LiteMount\Mount.lua:173
 Refresh = <function> defined @LiteMount\Mount.lua:63
 GetCastAction = <function> defined @LiteMount\Mount.lua:179
 Get = <function> defined @LiteMount\Mount.lua:26
}
className = "Journal"
class = <table> {
 GetFlags = <function> defined @LiteMount\LM_Journal.lua:103
 Dump = <function> defined @LiteMount\LM_Journal.lua:151
 GetCastAction = <function> defined @LiteMount\LM_Journal.lua:139
 IsCastable = <function> defined @LiteMount\LM_Journal.lua:128
 Refresh = <function> defined @LiteMount\LM_Journal.lua:120
 __index = <table> {
 }
 Get = <function> defined @LiteMount\LM_Journal.lua:40
}
m = <table> {
 sourceType = 1
 sceneID = 4
 isCollected = false
 modelID = 100108
 isSelfMount = false
 icon = 3852563
 isFavorite = false
 mountID = 803
 isUsable = false
 flags = <table> {
 }
 sourceText = "|cFFFFD200Pakt: |rVenthyr|n|cFFFFD200Beute von:|r Stygischer Steinzermalmer|n|cFFFFD200Zone:|r Korthia|n"
 name = "Meisterhafte Grabschwinge"
 mountType = 248
 family = "Unbekannt"
 isFiltered = false
 description = "Dieser meisterhaft gefertigte Steingeborene wurde von der Steinhauerin persönlich in Handarbeit hergestellt und wird nur jenen anvertraut, die sie als würdig erachtet."
 spellID = 215545
}
(*temporary) = nil
(*temporary) = 215545
(*temporary) = "Mammoth"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
LM = <table> {
 TravelForm = <table> {
 }
 Mount = <table> {
 }
 PlayerMounts = <unnamed> {
 }
 PairsByKeys = <function> defined @LiteMount\TableUtil.lua:37
 FLAG = <table> {
 }
 MountList = <table> {
 }
 tUpdate = <function> defined @LiteMount\TableUtil.lua:65
 Warning = <function> defined @LiteMount\Print.lua:84
 CreateAutoEventFrame = <function> defined @LiteMount\AutoEventFrame.lua:24
 tJoin = <function> defined @LiteMount\TableUtil.lua:50
 UIDebug = <function> defined @LiteMount\Print.lua:76
 tMap = <function> defined @LiteMount\TableUtil.lua:15
 WarningAndPrint = <function> defined @LiteMount\Print.lua:88
 UIFilter = <table> {
 }
 ActionButton = <table> {
 }
 Rules = <table> {
 }
 Actions = <table> {
 }
 Print = <function> defined @LiteMount\Print.lua:21
 SPELL = <table> {
 }
 Conditions = <table> {
 }
 Vars = <table> {
 }
 SlashCommandFunc = <function> defined @LiteMount\SlashCommand.lua:208
 RunningWild = <table> {
 }
 Nagrand = <table> {
 }
 PrintError = <function> defined @LiteMount\Print.lua:26
 SecureAction = <table> {
 }
 GhostWolf = <table> {
 }
 GetDebugLines = <function> defined @LiteMount\Print.lua:30
 Spell = <table> {
 }
 MOUNT_TYPES = <table> {
 }
 Journal = <table> {
 }
 Environment = <unnamed> {
 }
 tSlice = <

**Comment by mbattersby** [comment]
This is already fixed in LiteMount 9.1.12, please update.
