### ISSUE TITLE
Zone-specific mount suggestion (mechagon island)

### ISSUE THREAD

**Issue by Benzoyl** [xod-wow/LiteMount#72]
Hello, since some zone mounts are hard-coded in default setting, I'd like to suggest another for a practical reason.
In Mechagon island, players in flying mounts are attacked by specific enemy unit throughput the map. 
But Blizzard has two specific mounts that are free from these attacks.

Zone: Mechagon Island (1462)
Mounts: Rustbolt Resistor (168829), Aerial Unit R-21/X (168830)

**Comment by Benzoyl** [comment]
Probably that's true that normally players don't meddle with rules much. In my case, I use 'default button' quite often when I want to see a working example usually after I fail to customize command lines. Luckily now with new 9.1.2, I finally managed to add a working rule for mechagon myself and very happy about it. Thank you!

**Comment by mbattersby** [comment]
I'm going to leave this open for a bit, I think I will try to put it into the defaults once I get this beta testing out of the way.

**Comment by mbattersby** [comment]
I think this needs the picker and the rules UI to allow up to 3 mounts. Making a group in the defaults is too annoying with AceDB.

**Comment by mbattersby** [comment]
Looks like there's a heap of mounts that do this now, such that three wouldn't be enough anyway. Sadly this is a niche case and all of the solutions are probably too much work to get right.

Closing. Oh well.
