### ISSUE TITLE
Interference with addon Shadowed Unit Frames inside Torghast

### ISSUE THREAD

**Issue by Horogg** [xod-wow/LiteMount#74]
I have minor problem inside Torghast...
When I have enabled only addons "LiteMount" and "Shadowed Unit Frames", after reload UI parts of Objective Tracker are at wrong position (see screenshots).

SUF + LM after reload UI inside Torghast - with issue
![suf-and-lm_issue](https://user-images.githubusercontent.com/49456814/136673228-33f8661b-ade5-412d-9c61-c5904a611f35.jpg)

Only SUF or only LM after reload UI inside Torghast - w/o issue
![only-suf_no-issue](https://user-images.githubusercontent.com/49456814/136673226-b54a7fc4-d844-4618-baad-40148eed3906.jpg)

**Comment by mbattersby** [comment]
This is a bug in SUF somehow. I have logged my analysis into their issue tracker:

https://www.curseforge.com/wow/addons/shadowed-unit-frames/issues/1711

There's nothing I can do in LiteMount to fix it. I can trigger it in SUF without LiteMount installed.
