### ISSUE TITLE
WowUp/CurseBreaker/etc "updated" LiteMount to a really old version

### ISSUE THREAD

**Issue by gotex007** [xod-wow/LiteMount#76]
It just says "You can't do that right now."

Of course I'd make a new character today to experience this.

Update: Now that I'm in Stormwind and have Apprentice Riding it still says "You can't do that right now." when I press my Litemount keybind.

Update 2: I swapped to my main. The addon simply doesn't work now. It doesn't let me mount using its keybind anymore.

**Comment by mbattersby** [comment]
Looks like CurseForge eventually became aware of this happening across many many addons, and by the look of things have now fixed it.
