### ISSUE TITLE
version 9.1.15 key bind limitation change

### ISSUE THREAD

**Issue by ShakariPsy** [xod-wow/LiteMount#77]
Since the last patch on retail 9.15 the addon no longer allows long combination for a direct key binding is Ctrl+Alt+M in my case, shortens it to Ctrl+M.

Revert to the previous version of the addon and Crtl+Alt+M works fine.

**Comment by mbattersby** [comment]
Any info? Will close this soon unless I hear back. If that happens feel free to re-open it if you still have a problem.

**Comment by ShakariPsy** [comment]
HI sorry for the late reply. Ctrl+Alt+L works for me but Ctrl+Alt+M still doesn't, why I don't know. Have you tried Crtl+Alt+M?
is it a protected short cut?

**Comment by mbattersby** [comment]
![image](https://user-images.githubusercontent.com/1300207/142744738-759288cd-5dbe-4ecb-8407-af155742afc5.png)

I didn't have any trouble with that either. Perhaps it's something in your OS or maybe even your keyboard.

**Comment by mbattersby** [comment]
Closing this off, I'm 99.9% sure it's not a LiteMount issue. Please re-open it if you have more information.
