### ISSUE TITLE
[Feature] Uncheck all mount

### ISSUE THREAD

**Issue by jgauthi** [xod-wow/LiteMount#8]
Hello,
I want to use 3-5 mounts by profil. Can you add a button to uncheck all mount ?

**Comment by mbattersby** [comment]
Use the priority adjust in the header row to set all mounts to priority 0.

https://github.com/xod-wow/LiteMount/wiki/Priorities

**Comment by mbattersby** [comment]
I have added an FAQ for this;

https://github.com/xod-wow/LiteMount/wiki/Disabling-Mounts
