### ISSUE TITLE
Set new mount from major/minor patch to priority "Undefined"

### ISSUE THREAD

**Issue by jgauthi** [xod-wow/LiteMount#82]
Hello,
I use multiple profiles, one per character with different priorities (1, 2, 3). But with the new patches, the new mounts are added automatically on priority 1.

Can you set a new priority for mounts in future patches to "Undefined" instead (equivalent to disable) ?

**Comment by mbattersby** [comment]
There is a setting for this on the General tab, "Automatically disable newly added mounts."

If you tick that box new mounts Blizzard add to the game will have priority 0 instead of 1.

**Comment by jgauthi** [comment]
Thank you.
