### ISSUE TITLE
Package release on git?

### ISSUE THREAD

**Issue by l3uGsY** [xod-wow/LiteMount#85]
Can you please consider adding a package release to your github repo.  Overwolf/Curse is blocked here due to privacy and data vulnerability concerns.

**Comment by l3uGsY** [comment]
I can manually do it by downloading from Curse, I just can't install Overwolf on this PC.  I do use Curse Breaker and add each github.  I've noticed many authors taking this approach over the years, even before Curse was acquired by Overwolf. 

So please forgive my ignorance but all this time I just assumed it was no different and authors were just benefiting from both.  Like you mentioned, there is a clear benefit to the community Curse has built in which Overwolf has bought.  << see there it is. :P  

But all jokes aside, I was just curious on it's addition to simplify updates and all.  I appreciate the work you've put in over the years. many many years.  Especially your handling of Druid forms.

**Comment by mbattersby** [comment]
Thank you! And thanks for the information.

I admit I'm not really familiar with Cursebreaker, the only other addon updater I tried was Wowup which also seems to be going down a bad path.

If you have a moment, I wonder if you could tell me how you put a github repo into Cursebreaker (or a screenshot) and also give me an example of another addon repo you have added that way that's working? I'd like to have a look at their repo to see what they have done.

I wish Overwolf hadn't bought Curseforge too. I'm fairly sure, based on their developers discord and everything else I see that they don't really care about WoW addons anyway, and they bought Curseforge mostly for Minecraft. Hopefully someday someone will make an alternative with all the features. I don't think it would be that hard to do, but it would be quite costly to pay for all the hosting.

Happy adventuring, X.

**Comment by l3uGsY** [comment]
As it sits now, Curse Breaker is being retired but should work for git unless they do what Overwolf did and block 3rd party programs.
![image](https://user-images.githubusercontent.com/35513633/155925998-447ac124-24c9-4fac-86dd-a39a479a4166.png)

CB> install gh:xod-wow/LiteMount

It will install the latest release and use the version to check and update if necessary. Simple like the old old wowace updater.
Another package I install via Git is Ice-Hud. https://github.com/parnic/ice-hud and it follows a the same format 
CB> install gh:parnic/ice-hud
Among others like [Skillet](https://github.com/b-morgan/Skillet) and for my terrible spelling, [Misspelled ;P](https://github.com/nrpieper/wow-misspelled).
All of which update on both, git and curse.

I also noticed the community of [wago.io](https://wago.io/) growing.  It's at the point where they have their own app, with a database at [addons.wago.io](https://addons.wago.io/)  As you mentioned about bad actors earlier, I did notice a report option.

**Comment by mbattersby** [comment]
Thanks for that, again.

Without understanding **at all** what I'm doing, I followed the instructions for using the bigwigs packager and a 9.2.2 release seems to have appeared on github.

Can you try your cursebreaker actions again and see if anything good happened?

**Comment by mbattersby** [comment]
p.s. FWIW, I will _never_ host on wago.io, owned by Method, the people that perpetrated and covered up sexual abuse and assault within the WoW community. CurseForge is the diet coke of evil compared to those people.

**Comment by l3uGsY** [comment]
![image](https://user-images.githubusercontent.com/35513633/156022300-6da249f4-f0c2-43dc-a578-faf3a1d2bf04.png)

Worked like a charm.  Thank you for taking the time to toss this up.

As for wago.io, I didn't know that but I do recall the incident.  Eeesh, what good is a report feature if it doesn't even work on your own employees.

**Comment by l3uGsY** [comment]
On another note, in terms of updaters besides Curse Breaker, most supports VCS through services like Github/Bitbucket/Gitlab and not git/hg/svn etc directly.  You can find a detailed break down here.  This might come in handy is more people look for delivery methods besides wago and overwolf.

https://ogri-la.github.io/wow-addon-managers/

**Comment by mbattersby** [comment]
Thanks for testing, glad it's worked. I'll keep an eye on it when I do new releases.

I've used wowup before, but they've (recently partnered)[https://mailcoach.method.gg/webview/7e52f06b-1a71-4307-aef1-712b3a16a378] or merged with wago.io/Method so that's problematic.

Based on your table, and my recollection, they used to support addons from github, but I can't see anything like that in the options and I wonder if they took it out after the merger to force people into wago.io and their ads.

Everything is awful!

**Comment by mbattersby** [comment]
I think this probably also means that their wowuphub, which I had hoped my be a viable curseforge replacement, is dead.

**Comment by l3uGsY** [comment]
Man did the add-on landscape get mucky.  Crosses fingers for Tukui.org  Probably the last place with a large enough community for localization and error reporting.  Maybe wowinterface.com will pick up some new traffic that might allow them to improve the backend for systems similar to curseforge.

Regardless of where it all ends up, it nice to see authors putting values first.  Thank you.
