### ISSUE TITLE
Chauffeurs & Running Wild

### ISSUE THREAD

**Issue by Sluimerstand** [xod-wow/LiteMount#89]
The SmartMount feature generally understands when to use a Chauffer Mount and when not to, however when I add a Worgen's Running Wild ability to the mix, it always tries to use that ability. Even when no riding skill is learned. I couldn't find a conditional to check whether a spell is learned to manually circumvent this.

**Comment by mbattersby** [comment]
Running Wild is full mount speed, whereas chauffeurs are slower. So LiteMount will always prefer Running Wild if it is available.

Are you saying there is a case where LiteMount is trying to cast Running WIld but it is not usable? Can you give some details about what the case is?

**Comment by Sluimerstand** [comment]
I am in the Worgen starting zone, and I do learn Running Wild from levelling up - but it requires the apprentice riding skill to use. So LM is trying to use Running Wild, but the spell cannot be cast without that requirement being met.

**Comment by mbattersby** [comment]
Oh that's interesting, must be something Blizzard broke with the level squish for shadowlands. There's a few things like that around still, spells you learn before you can use, or talents that affects spells you can't learn yet.

If I make a fresh level 1 worgen will I see the error? If I can reproduce it I should be able to fix it pretty quickly (hopefully).

**Comment by mbattersby** [comment]
Put in a fix, thanks for the report. Should be in 9.2.11 out soon, but I expect you've leveled past the problem anyway.

**Comment by Sluimerstand** [comment]
I did actually hold off on learning the riding skill so I could test your fix, although I don't expect any issues there. Thanks for the quick fix, I absolutely love using your addon. :D
