### ISSUE TITLE
Please don't show unusable mounts on Mounts page by default

### ISSUE THREAD

**Issue by MarshallBuhl** [xod-wow/LiteMount#92]
Hi,

I really love LiteMount, but it gets annoying to have to uncheck Not Collected, Unusable, and Hidden every time I want to look over my collection.  Would it be possible to have those disabled by default?

**Comment by mbattersby** [comment]
It's not every time, it's only once per UI reload.

Let me think about it. It has to default one way or the other, and I think how it is now is how I prefer it, but maybe I'm wrong.

**Comment by MarshallBuhl** [comment]
The reason I want it is that when I bring up my mounts list to see which ones I want to enable/disable, I don't want a LONG list of mounts that includes ones I can't use.  I have NEVER wanted to see mounts I can't use.  The only reason I can think of to see uncollected mounts would be to find some I might want to get.  That's not something I ever do.

**Comment by mbattersby** [comment]
LiteMount 9.2.23 now defaults to not showing "hidden" and "unusable" mounts, same as the mount journal. It still shows uncollected mounts greyed out at the bottom, same as the mount journal. I know it wasn't everything you wanted, but I do appreciate that you took time to log the suggestion and to answer my questions.
Happy adventuring, X.

**Comment by MarshallBuhl** [comment]
Thanks so much.  I don't mind at all that uncollected mounts show up at the end.  

My hero!
