### ISSUE TITLE
Translation not works

### ISSUE THREAD

**Issue by Unplayed** [xod-wow/LiteMount#93]
Localization.lua ruRU.

L["LM_FLYABLE_AREA"] = "Область полета"

But in game I see untranslated text.

And correct translation, used in aviation: "Летная зона".

Also something strange in 1654 line:

    L["LM_HERB"] = [=[Трава
    ]=]

Maybe it should be like others:
    L["LM_HERB"] = "Трава"

![WoWScrnShot_070222_124323_cr](https://user-images.githubusercontent.com/43932588/176988385-58d4ac09-a69e-45c1-a776-7175797cd66d.jpg)

**Comment by mbattersby** [comment]
Thanks, the Flyable Area on is my bug, the other one looks like something strange with the CurseForge export. Fix incoming.

Again thanks for all your translation help.

**Comment by mbattersby** [comment]
Please try LiteMount 9.2.15. Thanks!
