### ISSUE TITLE
PreCast Crusader Aura & what not seems to no longer be working

### ISSUE THREAD

**Issue by Jaladhjin** [xod-wow/LiteMount#98]
I'm totally on the enUS client & I put in https://github.com/xod-wow/LiteMount/wiki/Crusader-Aura's instructions right after Dismount.

So mine reads as I believe it always has:

```
LeaveVehicle
Dismount [nofalling]
CopyTargetsMount
ApplyRules
Limit [mod:shift,nosubmerged,flyable] RUN,~FLY
Limit [mod:shift,submerged] -SWIM
SmartMount
IF [falling]
  # Slow Fall, Levitate, Zen Flight, Glide, Flap
  Spell 130, 1706, 125883, 131347, 164862
  # Hearty Dragon Plume, Rocfeather Skyhorn Kite
  Use 182729, 131811
  # Last resort dismount even if falling
  Dismount
PreCast Crusader Aura, Path of Frost, Slow Fall, Water Walking
END
Macro
```

Any idea why it's no longer working?

I've also generated a new /litemount macro no change

**Comment by mbattersby** [comment]
I think the instructions need an update (which I will do). You should put the line after the

`Dismount [nofalling]`

near the top, not at the end.

**Comment by mbattersby** [comment]
I've updated the documentation to say to put the line before `CopyTargetsMouint`

Please let me know (or close this) if you get it working again.

Happy adventuring, X.

**Comment by Jaladhjin** [comment]
Huzah it worked thanks very much!
