### ISSUE TITLE
Not choosing flying mounts in flyable areas of Shadowlands

### ISSUE THREAD

**Issue by Starlynk1** [xod-wow/LiteMount#99]
What happens?
Flying mount is not summoned in Shadowlands even though I have it unlocked on the account.

What did you expect to happen instead?
Expected LiteMount to use a flying mount in flyable areas of Shadowlands.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
I'm not sure what previous version it had worked, but it had worked correctly previously.

Please do not modify anything below this line.

--- General ---

date: Thu Aug 25 22:10:20 2022
version: 9.2.22
locale: enUS
current profile: Default

--- Player ---

name: Nobledeath-Skywall
class: DEATHKNIGHT
level: 50
race: Tauren
faction: Horde
spec: 2 251 Frost

--- Location ---

map: Bastion (1533)
mapPath: Bastion (1533) -> The Shadowlands (1550) -> Cosmic (946)
instance: The Shadowlands (2222)
zoneText: Bastion
subZoneText: Aspirant's Crucible
IsFlyableArea(): true

--- Debugging Output ---

Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 120 mounts
 - trying Ground Mount
 - found 63 mounts.
 - PriorityRandom n=63, t=0.979, c=0.368
 - setting action to mount Swift Purple Hawkstrider
PreClick ok time 22.735499978065
PostClick handler called on LM_B1
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 120 mounts
 - trying Ground Mount
 - found 63 mounts.
 - PriorityRandom n=63, t=0.979, c=0.436
 - setting action to mount Armored Brown Bear
PreClick ok time 18.024300038815
PostClick handler called on LM_B1
 - setting action to in-combat action
PreClick handler called on LM_B1
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.10319995880127
PostClick handler called on LM_B1
 - setting action to in-combat action
PreClick handler called on LM_B1
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 120 mounts
 - trying Ground Mount
 - found 63 mounts.
 - PriorityRandom n=63, t=0.984, c=0.562
 - setting action to mount Great Black Dragon Turtle
PreClick ok time 15.243400037289
PostClick handler called on LM_B1
 - setting action to in-combat action
PreClick handler called on LM_B1
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.10240000486374
PostClick handler called on LM_B1
 - setting action to in-combat action
PreClick handler called on LM_B1
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 120 mounts
 - trying Ground Mount
 - found 63 mounts.
 - PriorityRandom n=63, t=0.984, c=0.895
 - setting action to mount Dreamlight Runestag
PreClick ok time 13.212399959564
PostClick handler called on LM_B1
 - setting action to in-combat action
PreClick handler called on LM_B1
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.15880000591278
PostClick handler called on LM_B1

--- Options DB ---

nQ12UrYro2VODrC)YJ(YAp76DAya1Wpmpi01yvDRcwQkpLKwJ(f)9m)hZp2EyK8qMEB5fYUb6SZIjdgm
ip8qM5TXBF)T38Z3F4Q83V7YF)HJ3D8WZ3)7F4F73)Wn)YN)Tdp8WsIlN)4Pp9thV(0PlNV9DZBF(2B(
2JxVE48BrY)JxUE58NF8Ylp9wK(MNpC9HpF(xElY(9NV84bygVfzF)9hF8WNo(weLMW9hp8WBrEO67U(
YP7ElY(vxF((lF6W13KW)0Lt3D)lNF(F9pV(we)7pD(FC6nTd)UJNV7WlV1n3VE90XNE(Ti8nxo)PNE5
njP4JV8woLHWF6Hl)9dRF)PxE8XlN)MlWP8e(3VlLtP4TVd)bxusRRIJzUvU9DDCZqTo17wR9IiNiAlp
dRllJEFS98L4qv1C0t4HXZLMHyoV98PsRo3E(AEuBR7UeOOlqUmMRhd2cx1upnRRl71wSOlvklpeuf(5
EpSD3Aqw11dL6bXQevv7r93dPyjRR6mw3wQuDM1finllbK7osTrs3SPC1UAY9sjm0hcBgSxAIQQT522Q
fcP6stT4uVxDO2H4PXTQRDFoTPNyp2InxLB7KXyko6IOCCwarhYzwED(i6CwBD93XI77JzFTan882Iwt
ljZ15q3M5qFM32MLc8)(zwADjmQrvdpWjHE8flPHCOlIxhJsv3aLQEqgYr1uYWp12uvd(F9mRL7HUP1w
CzwYwz4262tL6ZIgPGt8CDlOibFvz7Ul1QRvyeu3wQTmkiYm0KGs5GOPMxlePJgAmQNYXAqJUWEkK0OV
yiO7)4elvEB)hXcPUce7iBv5SmeIDgPwLZC53tT6wGYZVsU5nNo)0Zho)ZhxPIXBV5ho8WPhV7Y1BFxa
W(hE65JxrfIF405pD3LhFsmyCUFZ8Fp(7F4Rp88ZpaSQlF83)WxD9UJN)na2EhSKEuQebuYRaJc72cwN
3F9KGelY(894H(MRV80H7oEvmWq92B(6ho8Z)Y1l)mGt(oanC31pJhSgELh8(dp(RlRpg7nGcD)H7U8B
pE5cmZV(LnH)(RIkEAP7bavVE6XRhoHF4Bp(RxEwEs4(V5BVE44zzN2eH(PtxE4iqi)lxK9qCTnF)HZh
KcK)xVC(tpCuc774U)TJxpkfy)RylEswejr(MB(R)eCdp8WjXBctaf1o9Kyu)3h)FoILEfQgWJ)JRQZ2
(5hHX9Ysl4u8M)ZRYJ8TWpi3QHKKB(bbK)9NUEq8(4)w45aXDTVF4W2(SbGZB(B4FC4bWeyH4(RxV8Xt
pC8ho(5N()HAaib8rug51zd4)4FcbaxGxTMV)ZVAzE)NFTk7FPU)II5)bf8L1V9F(1lz7)(Fwv6DBGVS
WS)JVwT4)GT9kLF3T9(YkU)F27x(tCR(P86iM3gx(OuEfHwxUE65tBj3aFzuumV8SLv8LCfvn3qDgJEz
RabQUuR6Loukax6b9UJms)2ES8S32qZkTfQVScZ(uHsTQFLwl9hRyTwPal(jlVc0Q1h2qIlA5DquOSHe
c8XwM3tXEB5rrRnNL6SRlRJ5q1ZCeCnQ1bt5ylART(0BLgPRr3yXA01JXrzm1hoN16EaIx9vLuOR2ykh
uxCCRyQONcRlk(VoD7DudB7UOQgD7J8qxPATM3myPUGsfavviPGWSnT9J61AbTQdixXQxnWzHhVXQs6k
NWXVsFPnNQSXsL8NssiePAHn6olvlXxrybnQPgFua9iTyxlfsQBS1v3OyPBpc2fK9uEOQzhNKi2iw4bn
0Lk9IMnnstoVU18OnANvneyPvnqTcIurQaYKqWz5DfUmKkuNjfOOUEqUu72tr6vWNMgS89ON7UGkpS5K
gf42gZUPs2JGD4oszQlfKI0Wr4s3T)5obEf9Ke5CBxHAV6p3QKWItZw896ti3uTdeyg1BwYnn7Ac6OUK
Qh35BiMPMZfJGs1oEMmFaGp6Eg3vnzHg22QwN9b9995S4AvdzfuMURv9ePhy(uvAjyD5eNsrxscEiCkD
TQIU1MGCZesZywuFWOpsOu8OBpIrIR29tOeVL9CQFtmWnBb8yvCW6WTonjdE3GULt9CGGfiWA73H3zQl
pawu)uh0v18UaQ)ZnxixiWCQgzI5K81t9brcLJ)OEtK5QocaTQXZlG0SBRm7lzrnIA5D7XiTqn5tcUze
zhSGdMKkn4EwdOxu7D8xfUX5yJCKy1Hq1qc8F5UBPQ9l1RuTg6mMqCRwtyDBRi(n1QBrlslPLPWAI)SD
5KaBsvOGT77AAosyzbvTjv5p5u0GzGS62cTrn6Ua6AjGVmbym55wR114NsjR6cDuPUISHdwYSCcWoB0a
JgIsdrKB75zpxvjNWRwCdXdvime6nBNsJ6ZBXVIKBwcaxY6(iiXL3sxQgZjqBBxnIdDZlz8SBluTrxsC
MZMXfFQ(8EtQOguzx0NAkl1UZu1GwDibuVQzHUS0BcI)j(ZdUSLrJyVbCsPlqHyMc8KUuos4YwvGouxo
ZcQ2meeLs7Rv6BkD3OnWoSfC8enSUeIZVSnqWEQ6HQeba7kcq3AKEtGCIwkLrnnwWAzRkUs18ABnmhLM
iNAmR0FrY3kjpbOr4ZEsrOsicPrbIK7OugL8vaw3MPaEySZzj8Nul68qRyC)wJbGhLLkNOaIByMCkRu5
WYOKulkKbGjgCUnICK5RHUTBCasOQAhiLxx8MfgOZ1iUX1vjLnBQPTQNTjPp0Lik9mzelco10WgjnToA
2UjQazvbIeVEMysUarn5VNc2L5GveV0iVGqLEwwcUTn9RLDesEErYs8lQXRtIHghRqxPY7tgSIaaw4jW
JnevsVTOsJOEHKFiKwg8yuktOOrHOBXHxsoXFEQU9yT3zi)iv3Tl4dbYYmMOg18BjNLJ2PKzRnGcUXHD
ByBRLkPhcs0PJkL2r0rdlWMJ5CLs1ycvAShjOtncuMxv1fLEcoVPLBwpeBa2E4IsCZzupCKiuTueGT1O
GLOQU0zJfxoDYPjJwd2maq4KHgGyBZPuhT6trnGtcSTJVKrp0OsmMbT9kDixBBfYIg94e1KTLsjAVnfn
DkvYnLUq0aGmtQLgstm0UuiwnWmS5KbTQ(c88QFVA8IGTgkCKBbMLivOyYoQGqxvoBongkAZLfeAdKvc
8K6ZiJXt1EJ08WPdnz0HKMVjh)d39K8fs9odXsxxw6(TSETISdkK4g9iQHvfGu3TSEHVUQq0tQUB1znU
SIIIwIaJy2tRJ8UiCYs77ww2qnyucJnTfTMkLMfCNGHfum2KfFMXtD5BHc5iGqas2epcJ7sOxQSBPQJV
5tYOqgOcdF1Og25gy9Om4qzpdsD3e79jYlNMo6kdlqtBSAFHeBYXMFipIKTyIVMaKjwCb5gjZeuXJs)e
SF1rmy3T1kTtbsL4ln27N4rzH8uqVjGp5gQnBSedupl1nAmuRlt1y7Uvd9ntYrasjROJn0HRTKvoLfyM
A9pN8NnjdKguzXZbHRKouTavsYe7h26HoRF5Fj(DI4wyz6q3iwyVjNeECVSetz0xEcf14ZL1YVYubmcP
eUc9mBt6Aqk6zbevnKjRFUwunFxgGgVPfSHQ327VkulEypturiwNWr2Baay0ond1MbXCZNINrtakMtfy
itMkpdtsYhDyZBALTxovRXF(YHYKTh2OKz)YsvJQUd6RBtOqGt5JbVQQlbPA7kKU5njrYreSDXX2OefD
M3gDYWG00GnXije7YEBLxP1MPcSMG1gCDO85LUqy1GmVu2veBwgGyY1kjynJeHBcE0kyyavwuwQLUrZN
VlLvhPmcdXQzxRAIsMDHj0UuWQkZearqM6IY68Lwki6e2zABLsM4oOg3qbO7f71xMaDcsWJrcsuDXlms
AFGJbNpBjAoOc7NC5Q42Rg1Nscv3UzNZsfh5vtogOl91QdXqURkaaQ5RVRWb4atkWk0cza1oWcQz)sGA
3vQrKvrIfpkJ4q54TFTkv320zalj7fQqcOsCCANSm8Bwmyz2T7U3J8suntxMrIgtMSq5jiD3CrvCF9Td
tlOzwqFNARUSeQaK93rcBNEBMj4jRwdtWBTBJ5oU6WfL9AuAfxun(Eg5WLYSte4Rg7wEgkzVGxj8wPcK
TIuqs25z1AcfvnTGsaA5gQYay3RSE5wzwFiSZauynbaq5MJyqh0rTPQvKtYy1auzirQ3dCAO7fzVkVGo
2Z7m6nJsIvj8HXZcPjSqbcWyE0Gzush46gvkeOwxM9Ylj)BROu50uEHuf29bji2z1vQbPYejruUOJaBw
aIwjPlhYxKvfOo3pTavz6NjafDAIQofOjVvVIX2LjQIGrxNQ3vyc6LC3jk52g60NJ6SgKuM9ajNKKoda
n88pcjL5WmwJvWVKV8DKsPqYITQOx5m7WbjIe7FWjySwEfjZ)IuKLxdofE)wlCwN07EJ)YiASQJK)aWE
TwPl88zn6wDtLmg)cbyspjXbNIYdnBCIBVP)LUaveROoHpqeMUOWv1CeqLjqwAsw3HcMZ2AjdIyt)nVM
PizJR0yxLw2eT85HqsnTzYOyxcgV)AYfv9aHuMd0fHajVwT1LikWzS9dCQjzz(F3sFePJl6vxxKdu2jl
BOiW6jGHktTk8nJSK0E(eF5GIwT2HSP)B82wUdsgimsE8kr(dHMDY7VovWHQ5ALvUNCgqOjeFOinR)Er
2nJbDmzTcmi2e)EM22n01xrf3SBSBpLKhomB1op5WBKMtAoq0GNxDo)WKmiNHR1UllDmZ0EzjOvKDoi2
Dpy3LjnaPM9LhB8vRky6B)Ua)OGQa)XPKg5xst2YoeJ1op98KrYOxyFEnZahY36ZWsVmBDFitUMGoto4
C(fBPQntkJLI1w50m7cF)DYKbmOSOnHSah12UpzmrPr93hm0BPugoGUMOcQ2CpCkRYLd)spbM4UYBEWa
lZCMcWhU7vqAFvCOWJhDVzxsu0oTAuv4R(zPvJJxIm4rHHUHbYjPkeViz)wLCHbaHvckydKY(AOwmKux
S9T4LQ2XvRP1Drb8DdhCWzZV7JMtQw0Cz3SQMGYBBvnnjaUYQ9jFcdjZujCEfLZ4cGge0JtWrnSZTY4T
chovQvCAF5KBR0boT3oxMdFFzQ6tn57MA1IilbmjW9s0Dhwdx2KlRgVxT34G9XucEr(GHtCGIslW7cx3
eym6233aR72bZEwxRYOw5ZoqHlgaqJhvJ98)ifQwSrizJVKmHff(gohL0k(BEMikLTi05hkHm1QTllnp
4FyL65S7H)KNYPeZ5LzPw0nj)0nGZyQgeN6YsJnvUmxzzi(rDpohjVpeTeMmGMDgz2fT4AvJgaolpcLr
sTD3rNT(IkZCoxG7r0pIumz(ktKjBWotazcgb2drRBeo(O1R0rtHACoVj4M45YUjlkA1dMzk8mBSKHOk
EyPz0Ct8fnVmulwTXgQKPOq)dPUMMn(Ad93ZeiCM44MaHQDJAT4gaN5wmN5qX1piuXSAAntzWv6Mw)yG
xUI8C61u583aHo7MSjI9FnOYl1wxuuCKf1LSf9URxlHRw1TjVb)MlRMfjahdxVQ12Y2CbtDdeCyVwciO
HY3d70kJbaGPUBKOvpiGj8JO9D(iwRtbW(OCBwhoYmNuaf77tzedg1OuJF)X2NXm6ZpYowLIEoNrkQOu
w)lyVyr9tboQWdntwJXL(9xF72qzAUERMtGZOw0BY0lhm(e(XOlB0CcKOMiRvwQqyzXgYUElUSzx2Dzy
mTPzZYnZ(KwIYoAsCmHlr9ib9md1RRMat7Z0sKLEA7t6E3xVnkJvSxZawSDMB3Sb((S0p644kUHFJnlM
(6wtEZkEhmSfUSmKFQSK9wQtCcVGWktUfVRvuZF1U(eg2bPu4NPXkY1PbB8yT3F7YcuKgGKPMvPZpiNS
pcGy2k7OFy6uRQf4Bl0x2KzHqtvxRjFvJUAlMXQfnQronsjatXpNwTu5qW(01M1Qh3YmErRoutVBlljK
knxtpxImB610gfLN1))2)3p

**Comment by mbattersby** [comment]
I don't suppose this fixed itself up when you logged out and in again?

I don't know why that would happen. There is a weird (Blizzard) bug when  you come out of one of the scenarios for the Kyrian campaign and you have to relog for it to remember you can fly. Everything looks ok with your debug output, so LiteMount must have _thought_ one of these was true:

1. You didn't know how to fly at all (learning flying skill from the flight trainer).
2. You hadn't unlocked Shadowlands flying by completing Memories of Sunless Skies (quest 63893)

If it's not fixed can you send me the outputs from:

  /dump C_QuestLog.IsQuestFlaggedCompleted(63893)

and

  /dump LiteMount.LM.Environment:KnowsFlyingSkill()

**Comment by Starlynk1** [comment]
[21:36] [21:36:54] Dump: value=C_QuestLog.IsQuestFlaggedCompleted(63893) 
 [21:36] [21:36:54] [1]=false 
 [21:37] [21:37:10] Dump: value=LiteMount.LM.Environment:KnowsFlyingSkill() 
 [21:37] [21:37:10] [1]=true

**Comment by Starlynk1** [comment]
It's only in the main SL zones that I am not getting LiteMount to use a flying mount. In ZM, it works fine.

I can manually choose a flying mount, so even though the quest is flagged as not completed, I can still fly from other toons completing it. That is a guess though... I don't know much about how the flying works across toons.

**Comment by mbattersby** [comment]
> [21:36:54] Dump: value=C_QuestLog.IsQuestFlaggedCompleted(63893) = false

This is definitely the problem, this is the main check for if you can fly in Shadowlands ("instance" 2222).

It's a hidden quest that completes account-wide when you use the Memories of Sunless Skies item ([itemid 185965](https://www.wowhead.com/item=185965/memories-of-sunless-skies)) to cast Shadowlands Flying (spell [352177](https://www.wowhead.com/spell=352177/shadowlands-flying)).

Is there some other way to unlock flying in Shadowlands now? Can you fly in Shadowlands merely by completing the ZM flying unlock and never doing the Shadowlands flying unlock questline?

**Comment by Starlynk1** [comment]
They may have done that with ZM and catch up mechanics. I played SL from launch until just before Domination. I switched to Classic Era during that time and came back to retail for ZM. So I did the ZM storyline and then got flying in ZM. It also gave me flying in SL areas.

Not sure how to verify that I have flying for both from the ZM method.

**Comment by mbattersby** [comment]
That's almost certainly it then, ZM flying must also give you SL flying. I'm not sure how to test it because my account already has everything unlocked and I don't have access to any other account Especially not one that has ZM completed but didn't do the rest of the SL flying unlocks.

I'm nervous about putting a change in for this without being able to test it for sure, but I can't think of anything else to do.

**Comment by mbattersby** [comment]
Can you confirm for me that this returns "true":

/dump IsSpellKnown(366736)

**Comment by Starlynk1** [comment]
I checked on 4 of my toons and all came up false

**Comment by Starlynk1** [comment]
I checked for the ZM achievement Unlocking the Secrets and that shows completed.

**Comment by mbattersby** [comment]
Hmm that is frustrating. How about

/dump GetAchievementInfo(15514)

hopefully the 4th field is "true".

**Comment by mbattersby** [comment]
Can you also check

/dump C_QuestLog.IsQuestFlaggedCompleted(65539)

**Comment by Starlynk1** [comment]
[17:18] [17:18:00] [1]=15514, 
 [17:18] [17:18:00] [2]="Unlocking the Secrets", 
 [17:18] [17:18:00] [3]=15, 
 [17:18] [17:18:00] [4]=true, 
 [17:18] [17:18:00] [5]=8, 
 [17:18] [17:18:00] [6]=4, 
 [17:18] [17:18:00] [7]=22, 
 [17:18] [17:18:00] [8]="Complete the Zereth Mortis achievements listed below.", 
 [17:18] [17:18:00] [9]=393216, 
 [17:18] [17:18:00] [10]=237388, 
 [17:18] [17:18:00] [11]="Reward: Zereth Mortis Flying", 
 [17:18] [17:18:00] [12]=false, 
 [17:18] [17:18:00] [13]=true, 
 [17:18] [17:18:00] [14]="", 
 [17:18] [17:18:00] [15]=false

**Comment by Starlynk1** [comment]
[17:18] [17:18:37] Dump: value=C_QuestLog.IsQuestFlaggedCompleted(65539) 
 [17:18] [17:18:37] [1]=true

**Comment by Starlynk1** [comment]
Not sure what the 4th field is, but it is true. :)

**Comment by mbattersby** [comment]
I've had a go at fixing this in LiteMount 9.2.23. Please test it a let me know if it helped.

**Comment by Starlynk1** [comment]
that appears to have made it work. Thank you!

**Comment by mbattersby** [comment]
Terrific!

Thanks for all your help with this, greatly appreciated.
